/**
 * The served step-kind catalog, translated into a node library (WFA-004).
 *
 * WF-002 argued at length that step kinds structurally cannot enter
 * `node-catalog.json` — it is generated by *running* the two node registers and
 * `catalog:check` deletes anything hand-written — and that argument stands. It
 * never blocked a canvas, because the editor does not read `node-catalog.json`
 * at all: **it learns node types from connected clients**
 * (`NodeLibraryImporter.onClientImport`), which is how WFA-001 delivered the
 * cloud types. This module is the same door, with the library built from a
 * running backend's `GET /admin/workflow-step-kinds` rather than from a file.
 *
 * That is the point of the README's "served, not generated" decision: the
 * palette comes from the backend the workflow will actually run on, so it
 * cannot describe a kind that backend is unable to execute.
 *
 * WHAT MAPS ONTO WHAT
 *
 *   step kind          → node type (`workflow.<kind>`), one per kind
 *   param              → input port, control chosen from the param's `type`
 *   `ref`              → input port (a step field, but it edits like a param)
 *   incoming edge      → the single `in` signal input
 *   `next`             → signal output
 *   `routes.<name>`    → one signal output per route (dynamic ones come later,
 *                        per node, from `cases`)
 *   `onError`          → signal output of the error wire type
 *
 * @module models/workflow/workflowNodeLibrary
 */

import type { NodeLibraryData, NodeLibraryDataNodeType } from '@noodl-models/nodelibrary/NodeLibraryData';

import { WIRE_TYPE_ERROR } from '../../views/nodegrapheditor/canvas/CanvasTheme';
import type { StepKindCatalog, StepKindSpec, StepParamSpec } from './types';

/** Node type names are namespaced so nothing can collide with a runtime node. */
export const WORKFLOW_TYPE_PREFIX = 'workflow.';

/** The one input every step has: "an edge reached me". */
export const PORT_IN = 'in';
/** The unconditional success edge. */
export const PORT_NEXT = 'next';
/** The failure edge. */
export const PORT_ON_ERROR = 'onError';
/** Route output ports are `route:<name>`, so a route can be called `next` safely. */
export const ROUTE_PORT_PREFIX = 'route:';

/** The port group every route output lands in, so they sort together. */
const GROUP_ROUTES = 'Routes';
const GROUP_PARAMS = 'Params';

export function routePortName(route: string): string {
  return ROUTE_PORT_PREFIX + route;
}

export function isRoutePort(portName: string): boolean {
  return portName.startsWith(ROUTE_PORT_PREFIX);
}

export function routeNameFromPort(portName: string): string {
  return portName.slice(ROUTE_PORT_PREFIX.length);
}

export function typeNameForKind(kind: string): string {
  return WORKFLOW_TYPE_PREFIX + kind;
}

export function kindFromTypeName(typeName: string): string | undefined {
  return typeName.startsWith(WORKFLOW_TYPE_PREFIX) ? typeName.slice(WORKFLOW_TYPE_PREFIX.length) : undefined;
}

/**
 * Category → the canvas colour taxonomy.
 *
 * Deliberately onto the *existing* five-key taxonomy plus `logic` (a UIX-001
 * token that had no referent until now — see CanvasTheme). No new colour is
 * introduced, and red stays reserved for the error edge under phase 23's law.
 */
const CATEGORY_COLOR: Record<string, string> = {
  Workflow: 'component', // it schedules a function — a component, one tier down
  'Workflow Logic': 'logic',
  'Workflow Timing': 'logic',
  'Workflow Error Handling': 'default' // quiet on purpose: these are exception paths
};

function colorForCategory(category: string): string {
  return CATEGORY_COLOR[category] || 'default';
}

/**
 * A param's declared type → an editor port type.
 *
 * `condition` and `path` get their own port types so `Ports.viewClassForPort`
 * can dispatch to the controls WFA-004 adds; the rest reuse the port types the
 * property editor has always understood.
 */
export const PORT_TYPE_CONDITION = 'workflow-condition';
export const PORT_TYPE_PATH = 'workflow-path';
/** A param that accepts anything, including a `{"$path": …}` reference. */
export const PORT_TYPE_VALUE = 'workflow-value';

function portTypeForParam(param: StepParamSpec, catalog?: StepKindCatalog): unknown {
  switch (param.type) {
    case 'enum':
      return { name: 'enum', enums: param.enums || [] };
    case 'condition':
      // The operator set and the scope roots ride ON the port type, the way
      // `enum` already carries its values — so the control reads them off the
      // port it is rendering and never holds its own copy of a served contract.
      return { name: PORT_TYPE_CONDITION, ops: conditionOps(catalog), scope: scopeRoots(catalog) };
    case 'path':
      return { name: PORT_TYPE_PATH, scope: scopeRoots(catalog) };
    case 'boolean':
      return 'boolean';
    case 'number':
      return 'number';
    case 'string':
      return 'string';
    case 'array':
      return 'array';
    case 'object':
      return 'object';
    case 'any':
    default:
      // `any` params take a literal OR a `{"$path": …}` reference (WFA-003), so
      // they need the value control rather than a bare text field.
      return { name: PORT_TYPE_VALUE, scope: scopeRoots(catalog) };
  }
}

/**
 * The operator set the backend will actually evaluate.
 *
 * Empty when a pre-1.2.0 backend served no `conditionLanguage`. The control
 * says so rather than falling back to a guessed list: an operator that backend
 * cannot evaluate is a run that fails loudly at 3am, which is worse than a
 * control that admits it does not know.
 */
function conditionOps(catalog?: StepKindCatalog) {
  return catalog?.conditionLanguage?.ops || [];
}

/** The root names a `$path` may start from, from the served value language. */
function scopeRoots(catalog?: StepKindCatalog): { name: string; description: string }[] {
  const scope = catalog?.valueLanguage?.scope;
  if (!Array.isArray(scope)) return [];
  return scope
    .filter((s) => s && typeof (s as { name?: unknown }).name === 'string')
    .map((s) => s as { name: string; description: string });
}

/**
 * `cases` is an array, but it is a `raw` DSL structure whose labels *become
 * ports*. It gets the condition-family editor rather than a JSON textarea; the
 * spec is explicit that a JSON textarea here fails the task.
 */
function portTypeForRawParam(param: StepParamSpec, catalog?: StepKindCatalog): unknown {
  if (param.type === 'condition') {
    return { name: PORT_TYPE_CONDITION, ops: conditionOps(catalog), scope: scopeRoots(catalog) };
  }
  if (param.name === 'cases') {
    return { name: PORT_TYPE_CASES, ops: conditionOps(catalog), scope: scopeRoots(catalog) };
  }
  return portTypeForParam(param, catalog);
}

export const PORT_TYPE_CASES = 'workflow-cases';

/** A signal output that paints its name on the wire. */
function routePort(route: string, index: number, description: string) {
  return {
    name: routePortName(route),
    displayName: route,
    editorName: route,
    type: { name: 'signal', connectionLabel: true },
    plug: 'output',
    group: GROUP_ROUTES,
    index,
    tooltip: description
  };
}

function portsForKind(spec: StepKindSpec, catalog?: StepKindCatalog) {
  const ports: Record<string, unknown>[] = [];

  ports.push({
    name: PORT_IN,
    displayName: 'in',
    type: 'signal',
    plug: 'input',
    index: 0
  });

  let index = 1;

  // `ref` is a step field rather than a param, but it edits exactly like one and
  // it is the single most useful thing on the card, so it goes first.
  if (spec.invokesFunction) {
    ports.push({
      name: 'ref',
      displayName: 'Function',
      type: { name: 'string', allowEditOnly: true },
      plug: 'input',
      group: GROUP_PARAMS,
      index: index++,
      tooltip: 'The cloud function this step invokes.'
    });
  }

  for (const param of spec.params) {
    // The catalog lists `ref` as a param for the kinds that need it; it is
    // already above, as a step field.
    if (param.name === 'ref') continue;

    ports.push({
      name: param.name,
      displayName: param.name,
      type: param.raw ? portTypeForRawParam(param, catalog) : portTypeForParam(param, catalog),
      plug: 'input',
      group: GROUP_PARAMS,
      index: index++,
      default: param.default,
      tooltip: param.description
    });
  }

  // `next` is the plain edge and is not labelled on the wire — an unnamed
  // default output is the canvas's existing idiom, and labelling every edge
  // would drown the ones that carry meaning.
  ports.push({
    name: PORT_NEXT,
    displayName: 'next',
    type: 'signal',
    plug: 'output',
    group: GROUP_ROUTES,
    index: index++,
    tooltip: 'Taken when this step succeeds, whatever it decided.'
  });

  for (const route of spec.routes) {
    // A dynamic route name is a placeholder in the catalog (`<case label>`) —
    // the real ports come per node from its own params.
    if (route.dynamic) continue;
    ports.push(routePort(route.name, index++, route.description));
  }

  ports.push({
    name: PORT_ON_ERROR,
    displayName: 'onError',
    editorName: 'onError',
    type: { name: WIRE_TYPE_ERROR, connectionLabel: true },
    plug: 'output',
    group: GROUP_ROUTES,
    index: index++,
    tooltip: 'Taken when this step fails. With no error edge, a failure halts the workflow.'
  });

  return ports;
}

function nodeTypeForKind(spec: StepKindSpec, catalog?: StepKindCatalog): NodeLibraryDataNodeType {
  return {
    name: typeNameForKind(spec.kind),
    displayNodeName: spec.displayName,
    category: spec.category,
    color: colorForCategory(spec.category),
    shortDesc: spec.summary,
    docs: '',
    allowAsChild: false,
    allowAsExportRoot: false,
    haveComponentChildren: undefined,
    ports: portsForKind(spec, catalog),
    dynamicports: [],
    searchTags: ['workflow', spec.kind, spec.category],
    // Everything the property editor and the picker preview want to say about
    // a kind, kept on the type so nothing has to re-fetch the catalog.
    workflowSpec: spec
  } as unknown as NodeLibraryDataNodeType;
}

/**
 * Build the library the importer merges. Categories in `nodeIndex.coreNodes`
 * are what the picker's rail renders, so they come from the served spec's own
 * `category` strings rather than a list written here.
 */
export function buildWorkflowNodeLibrary(catalog: StepKindCatalog): NodeLibraryData {
  const nodetypes = catalog.kinds.map((spec) => nodeTypeForKind(spec, catalog));

  const byCategory = new Map<string, string[]>();
  for (const spec of catalog.kinds) {
    const list = byCategory.get(spec.category) || [];
    list.push(typeNameForKind(spec.kind));
    byCategory.set(spec.category, list);
  }

  const coreNodes = [...byCategory.entries()].map(([name, items]) => ({
    name,
    description: `Workflow steps — ${name}`,
    type: 'Workflow',
    subCategories: [{ name: '', items }],
    items: []
  }));

  return {
    // The workflow runtime has no project settings, no typecasts of its own and
    // no colour blob — the canvas reads colours from CanvasTheme (UIX-005).
    projectsettings: undefined,
    typecasts: [],
    dynamicports: [],
    colors: undefined,
    nodetypes,
    nodeIndex: { coreNodes, moduleNodes: [] }
  } as unknown as NodeLibraryData;
}
