// @ts-check

/**
 * One autogenerated sidebar, driven by folder structure and each folder's
 * `_category_.json` — deliberately not hand-maintained. §3's generator writes
 * `docs/nodes/**` on every run; a hand-edited sidebar would silently drift the
 * moment a node's category changed, which is exactly the failure mode ALPHA-006
 * §3 exists to prevent.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ]
};

module.exports = sidebars;
