/**
 * The WF-002 step-kind catalog — the machine-readable description of every
 * workflow step kind, plus the write-time validation derived from it.
 *
 * WHY THIS FILE EXISTS AND WHY IT IS SHAPED LIKE A CATALOG
 * --------------------------------------------------------
 * SUB-004's node catalog (`packages/noodl-types/src/node-catalog.json`) is
 * generated by *running the two runtime node registers* — browser
 * (`noodl-viewer-react`) and cloud (`noodl-viewer-cloud`) — and serialising
 * what registered. A workflow step kind is not registered in either: it is not
 * a graph node with ports, it is a `kind` field in a `*.workflow-def.json`
 * step DAG, executed by the WF-001 engine. It therefore cannot enter that
 * artifact, and `catalog:check` (which regenerates from the registers and
 * fails on drift) would not accept a hand-written entry — the same reason
 * library **module** nodes are documented as out of catalog scope.
 *
 * What the catalog requirement actually buys is *discoverability by the
 * semantic validator and the AI authoring loop*. That is delivered here in the
 * form that fits the artifact: a versioned, machine-readable spec table with
 * params, routes, output shape and prose, which is
 *   - served at `GET /admin/workflow-step-kinds` (so a running backend
 *     describes its own step vocabulary),
 *   - surfaced to agents through the MCP `list_backend_step_kinds` tool and the
 *     `create_backend_workflow` schema,
 *   - the single source of truth for write-time validation, so an unknown kind
 *     or a missing required param is REJECTED at `POST /admin/workflow-defs`
 *     and refuses to load from disk, and
 *   - coverage-gated by `tests/workflow-steps-catalog.test.ts`, which fails if
 *     a kind is implemented without a spec entry, or specced without author
 *     documentation in `docs/runtime/WORKFLOW-NODES.md`.
 *
 * That last point is the local equivalent of `catalog:merge:check
 * --require-coverage`: a step kind cannot ship undocumented and invisible.
 * The full argument, and why this is NOT the WF-005 "no catalog at all"
 * exemption, is in WF-002-NOTES.md.
 *
 * This module holds NO runtime dependencies (no engine, no runner) so that
 * `validateWorkflowDefinition` can consult it from the registry's load path.
 *
 * @module nodegx-backend/workflow/steps/kinds
 */

import type { StepKind, WorkflowStep } from '../types';
import { CONDITION_LANGUAGE, validateCondition } from './conditions';
import type { ConditionLanguageSpec } from './conditions';
import type { ValueLanguageSpec } from './values';
import { MIGRATED_STEP_KINDS } from './migrate';
import {
  CONTROL_TRANSFORM_OUTPUT,
  TRANSFORM_LANGUAGE,
  TRANSFORM_OP_NAMES,
  validateTransformOutput
} from './transform';
import type { TransformLanguageSpec } from './transform';
import { CONTROL_VALIDATE_RULES, VALIDATE_LANGUAGE, VALIDATE_TYPE_NAMES, validateValidateRules } from './validate';
import type { ValidateLanguageSpec } from './validate';
import { DEFAULT_MAX_BATCHES } from './data';
import { isPlainObject, VALUE_LANGUAGE } from './values';

/**
 * Bumped when the spec table's SHAPE changes (not when a kind is added).
 *
 * 1.1.0 — WFA-003 added `valueLanguage` (so a client can render the right
 * control for a param and know what a `$path` may address) and `raw` on a param.
 * 1.2.0 — WFA-004 added `conditionLanguage`. The workflow canvas renders a
 * condition as three controls, and the operator list it offers has to come from
 * the backend that will evaluate it — a bundled copy could offer an operator
 * this backend does not implement, which is the drift the served registry
 * exists to prevent.
 * 1.3.0 — CWF-001 added `paramMapping` on a KIND. It describes something the
 * engine has done since WFA-003 and nothing declared: a step's params are merged
 * into its input by name, so a `call-function` step can hand a function a value
 * under a name the author chose. It went unauthorable because the editor builds
 * one row per DECLARED param and there were none to declare.
 *
 * Degradation, both ways: an editor talking to a pre-1.3.0 backend is served no
 * `paramMapping`, so it shows no mapping row — and definitions already carrying a
 * mapping still run, because the engine never needed the declaration. A pre-1.3.0
 * editor talking to a 1.3.0 backend ignores fields it does not know and renders
 * exactly what it rendered before.
 * 1.4.0 — CWF-005 added `displayName` and `control` on a param. Two of retry's
 * seven knobs lied in the only place people read — the field NAME — and neither
 * could be renamed without migrating every definition that uses it, because the
 * name is the wire contract. `displayName` separates the two jobs. `control`
 * names a bespoke editor control, and an editor that does not recognise the name
 * falls back to the control for the param's `type`, which is the whole reason it
 * is a served string rather than an enum.
 * 1.5.0 — CWF-005 folded `retry` into `call-function` as a policy group, added
 * `group` on a param, and added `migratedKinds` to the served catalog. A client
 * that refuses a kind this backend does not serve needs to tell "cannot run it"
 * from "accepts it and converts it", and only the backend knows which.
 * 1.6.0 — CWF-004 added `transformLanguage`: the closed operation vocabulary the
 * `transform` step's `output` may use. Served for the same reason
 * `conditionLanguage` is — an editor holding its own copy could offer an
 * operation this backend cannot perform, and an agent working from memory will
 * simply invent one. Removing an op from the backend removes it from the
 * editor's picker with no editor change.
 *
 * Degradation: a pre-1.6.0 backend serves neither the `transform` kind nor the
 * vocabulary, so a newer editor draws no Transform card for it and the picker
 * offers nothing; an older editor talking to a 1.6.0 backend gets the kind, and
 * its `output` param falls back to the control for its declared `object` type
 * (that is exactly what `control` being a served STRING rather than an enum is
 * for).
 * 1.7.0 — CWF-004 slice 2 added `validateLanguage`: the closed type vocabulary a
 * `validate` step's path rules may assert. Served for the third time now for the
 * same reason as the first two — an editor holding its own copy of the list could
 * offer `"type": "email"`, which this backend does not check, and an agent
 * working from memory would simply invent it.
 *
 * The four other kinds slice 2 added (`filter`, `sort`, `deduplicate`, `split`)
 * needed NO new served language, which is the point: `filter` and `sort` reuse
 * the condition language and its ordering whole, and the other two need no
 * vocabulary at all. A shape bump is for a shape change, and four kinds is not
 * one.
 *
 * Degradation: an older editor talking to a 1.7.0 backend gets the five kinds
 * and renders every param from its declared `type` — `rules` falls back to the
 * `array` control, which is a JSON list rather than a rules editor, but is not
 * broken. A newer editor talking to a pre-1.7.0 backend is served none of the
 * kinds, so there is no card whose rules editor would have nothing to offer.
 */
export const STEP_KIND_CATALOG_VERSION = '1.7.0';

export interface StepParamSpec {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'enum' | 'array' | 'object' | 'condition' | 'path' | 'any';
  required?: boolean;
  default?: unknown;
  enums?: string[];
  description: string;
  /**
   * The label a property editor puts on the row. Defaults to `name`.
   *
   * CWF-005: `maxAttempts` is the case this exists for. The number means "how
   * many calls in total", the name reads as "how many retries", and the
   * description saying so was losing — a description is read once, a field name
   * is read every time. The NAME cannot change: it is the wire contract, and
   * renaming it would mean migrating every definition that sets it.
   */
  displayName?: string;
  /**
   * The name of a bespoke control a client's property editor should use for this
   * param, when the control for its `type` will not do (CWF-005).
   *
   * Served rather than inferred, so the backend stays the authority on its own
   * param vocabulary — and safe to add, because a client that does not recognise
   * the name falls back to the control for `type`. That is the degradation story
   * for an editor older than the backend it is talking to.
   */
  control?: string;
  /**
   * The property-panel section this param belongs in. Defaults to the kind's one
   * Params group.
   *
   * CWF-005: `call-function` carries a six-knob retry policy that is off for most
   * steps, and six ungrouped number fields between the function name and the
   * routes is exactly the shape the fold exists to avoid.
   */
  group?: string;
  /**
   * WFA-003: this param is a DSL STRUCTURE — a condition, a filter, a switch's
   * cases — not a value. Its operands use the value language, but the executor
   * evaluates them when the step runs, so the engine does not resolve the param
   * itself. Every other param IS value-resolved before the step runs.
   *
   * A property editor should render a `raw` param with its own editor (three
   * dropdowns for a condition) rather than a value/binding control.
   */
  raw?: boolean;
}

export interface StepRouteSpec {
  name: string;
  description: string;
  /** True when the route names are derived from params (switch cases). */
  dynamic?: boolean;
}

/**
 * CWF-001 — a kind that takes params the AUTHOR names, beyond the declared ones.
 *
 * ⚠️ Read this before you "add param mapping": the engine has merged a step's
 * params into its input by name since WFA-003, so
 * `{"kind":"call-function","ref":"charge","params":{"amount":{"$path":"previous.result.total"}}}`
 * already delivers `body.amount` to the function, and
 * `tests/workflow-data-mapping.test.ts` has proved it end-to-end all along. What
 * did not exist was a *declaration*: the editor builds one row per DECLARED
 * param, so a kind whose only declared param was `ref` had nowhere to author a
 * mapping and the `$path` picker was reachable by no route in the product.
 *
 * This is that declaration, and it deliberately adds no second on-disk form.
 * There is exactly one way to write a mapping and it is the way that already
 * worked.
 */
export interface StepParamMappingSpec {
  /** The row label a property editor puts on the mapping. */
  displayName: string;
  description: string;
  /**
   * Names a mapping may not use — the backend refuses these. Served rather than
   * bundled so an editor's error and the backend's 400 cannot drift apart.
   */
  reserved: string[];
  /**
   * Names a mapping MAY use but which replace part of the run payload for the
   * called function. Legal; worth saying out loud in a property editor.
   */
  shadows: string[];
}

export interface StepKindSpec {
  kind: StepKind;
  displayName: string;
  category: string;
  /** The phase-11 spec this implements, for traceability. */
  source: string;
  summary: string;
  whenToUse: string;
  /** True when the step invokes a cloud function (and so needs `ref`). */
  invokesFunction: boolean;
  params: StepParamSpec[];
  /** CWF-001: present when the kind also takes author-named params. */
  paramMapping?: StepParamMappingSpec;
  routes: StepRouteSpec[];
  /** Prose description of the step's output object (what `previous` becomes). */
  output: string;
  /** The client-runtime node this mirrors, and how it differs. */
  clientEquivalent?: string;
  notes?: string[];
}

// ---------------------------------------------------------------------------
// The catalog
// ---------------------------------------------------------------------------

/** The property-panel section the folded retry knobs live in (CWF-005). */
const RETRY_GROUP = 'Retry policy';

const REF_PARAM: StepParamSpec = {
  name: 'ref',
  type: 'string',
  required: true,
  description: 'The cloud function to invoke (a step field, not a param).'
};

/**
 * The array param the four CWF-004 slice-2 array kinds share.
 *
 * One declaration rather than four, so `filter`, `sort`, `deduplicate` and
 * `split` cannot drift into describing the same thing differently — and so the
 * default (`previous.items`) is written once beside the one the executors
 * supply. `for-each`'s `items` is deliberately NOT this constant: its
 * description carries its own iteration warning, and merging them would make one
 * of the two say something untrue about itself.
 */
const ITEMS_PARAM: StepParamSpec = {
  name: 'items',
  type: 'any',
  default: { $path: 'previous.items' },
  description:
    'The array to work on — usually `{"$path": "previous.items"}`, but any path or literal array. A value that ' +
    'is not an array is a step FAILURE and not an empty list: an absent list and an empty one are different bugs.'
};

/**
 * Names a param mapping may NOT use (CWF-001 S2). Exactly one, and the reason is
 * specific: `WorkflowEngine` builds a step's input as
 * `{ ...payload, ...params, previous }`, so a param called `previous` is
 * overwritten by the engine and the author is left debugging a value that never
 * arrived. Refused at write time, where renaming costs nothing.
 *
 * ⚠️ The list was drafted longer — the whole canonical payload — and that was
 * WRONG, caught by `workflow-data-mapping.test.ts`, which has passed
 * `{ body: {"$path":"body"} }` since WFA-003. A payload root in a mapping is not
 * lossy: the params merge AFTER the payload, so the author's value wins. That is
 * an override, and an explicit identity mapping is a legitimate way to say what a
 * step passes. See `SHADOWED_STEP_INPUT_KEYS` for what an editor should still
 * mention.
 */
export const RESERVED_STEP_INPUT_KEYS: ReadonlySet<string> = new Set(['previous']);

/**
 * Names a mapping may use but which REPLACE part of the run payload for the
 * function being called (CWF-001).
 *
 * Legal, occasionally intended, and worth a word in a property editor — a
 * function that stops seeing `body` because a step remapped it is a confusing
 * thing to debug, and a confusing thing is not the same as an illegal one.
 */
export const SHADOWED_STEP_INPUT_KEYS: readonly string[] = ['body', 'trigger', 'triggerType', 'headers', 'query'];

/**
 * CWF-001 — what a Call Function step hands the function it calls.
 *
 * Without it a function could only read data by the name and shape its CALLER
 * happened to produce — `previous.result.total`, wherever `previous` came from —
 * which welds a reusable unit of work to one position in one graph. With it, a
 * function declares `amount` and each step says where `amount` comes from.
 */
const CALL_FUNCTION_MAPPING: StepParamMappingSpec = {
  displayName: 'Params',
  description:
    'What this step passes the function, as `{ "<name>": <value> }`. Each value is a literal or a reference — ' +
    '`{"$path": "previous.result.total"}` — and the names arrive at the top level of the request body, so the ' +
    'function reads `amount`. A name cannot reference another name of the same step: params resolve against the ' +
    'run, before they are merged into anything.',
  reserved: [...RESERVED_STEP_INPUT_KEYS],
  shadows: [...SHADOWED_STEP_INPUT_KEYS]
};

export const STEP_KIND_SPECS: Record<StepKind, StepKindSpec> = {
  'call-function': {
    kind: 'call-function',
    displayName: 'Call Function',
    category: 'Workflow',
    source: 'WF-001',
    summary: 'Invokes an existing cloud function and uses its response as the step output.',
    whenToUse:
      'The workhorse step: any real work — reading or writing records, calling an external API, sending email — ' +
      'is a cloud function graph, and this step schedules it. Prefer it over inventing new step kinds.',
    invokesFunction: true,
    params: [
      REF_PARAM,
      {
        name: 'maxAttempts',
        group: RETRY_GROUP,
        displayName: 'Total attempts (incl. the first)',
        // CWF-005: this row also draws the backoff preview, because the delay
        // sequence is the thing seven separate number fields cannot show you.
        control: 'retry-backoff',
        type: 'number',
        default: 3,
        description: 'How many times the function is called IN TOTAL. 1 means no retry at all. Min 1.'
      },
      {
        name: 'delayMs',
        group: RETRY_GROUP,
        displayName: 'First delay (ms)',
        type: 'number',
        default: 1000,
        description: 'How long to wait before the SECOND attempt. Later delays multiply from this.'
      },
      {
        name: 'backoffMultiplier',
        group: RETRY_GROUP,
        displayName: 'Delay multiplier',
        type: 'number',
        default: 2,
        description: 'Each subsequent delay is multiplied by this. 1 = a fixed delay every time.'
      },
      {
        name: 'maxDelayMs',
        group: RETRY_GROUP,
        displayName: 'Longest single delay (ms)',
        type: 'number',
        default: 60000,
        description: 'Ceiling on any one backoff delay, however far the multiplier has taken it.'
      },
      {
        name: 'jitter',
        group: RETRY_GROUP,
        displayName: 'Spread delays randomly',
        type: 'boolean',
        default: false,
        description: 'Randomise each delay across [50%, 100%] of its computed length, to avoid retry storms.'
      },
      {
        name: 'retryOnStatus',
        group: RETRY_GROUP,
        displayName: 'Retry ONLY these statuses',
        type: 'array',
        description:
          'Leave empty to retry any failure. Set it and the meaning INVERTS: only these HTTP statuses are ' +
          'retried and every other failure fails immediately — which is usually what you want (a 400 will not ' +
          'get better on the third attempt), and is never what adding one helpful code to the list looks like.'
      }
    ],
    paramMapping: CALL_FUNCTION_MAPPING,
    routes: [],
    output:
      "The function's parsed 2xx response body. A non-2xx response or a missing function is a step FAILURE. " +
      'With the retry policy ON, the output also carries `attempts` and `retried`.',
    notes: [
      'Runs through the unlogged WorkflowRunner.invokeFunction, so the engine writes the only execution record.',
      "The request body is the run payload, then this step's params, then `previous` — in that order, so a mapped " +
        'name overrides a payload key of the same name and `previous` cannot be overridden at all.',
      'CWF-005: the retry policy is OFF unless `maxAttempts` is greater than 1, and a step without it is invoked ' +
        'exactly once through exactly the path it always used. The standalone `retry` kind was folded in here — it ' +
        'took its own `ref` and invoked a function directly, so it was never a wrapper — and a definition still ' +
        'saying `kind: "retry"` is migrated on read, forever.',
      'Backoff waits are cancellable: cancelling the run or tripping the workflow timeout aborts the wait ' +
        'immediately rather than sleeping out the delay.'
    ]
  },

  branch: {
    kind: 'branch',
    displayName: 'Branch (IF)',
    category: 'Workflow Logic',
    source: 'CF11-001',
    summary: 'Evaluates a declarative condition and takes the `ontrue` or `onfalse` route.',
    whenToUse:
      'Route a run down one of two paths on a value — "was the order over £100", "did the upstream step return an ' +
      'error". This is the server-side equivalent of the client Condition node.',
    invokesFunction: false,
    params: [
      {
        name: 'condition',
        type: 'condition',
        required: true,
        raw: true,
        description:
          'A declarative condition (see the condition language). Paths resolve against the run scope, so ' +
          '`{"$path":"previous.total"}` reads the upstream step output and `{"$path":"upstream.save.id"}` reads a ' +
          'named earlier step.'
      }
    ],
    routes: [
      { name: 'ontrue', description: 'Taken when the condition evaluates true.' },
      { name: 'onfalse', description: 'Taken when the condition evaluates false.' }
    ],
    output: '`{ result: boolean, isfalse: boolean }` — mirrors the client Condition node output port names.',
    clientEquivalent:
      'Condition (`ontrue`/`onfalse`/`result`/`isfalse`). Port names match. Differences: the condition is a ' +
      'declarative object rather than a JavaScript expression (no eval on the server), and there is no `eval` ' +
      'signal input — a step runs when its incoming edge is taken.',
    notes: [
      'A condition that cannot be evaluated (incomparable operands, bad regex) is a LOUD step failure, not a ' +
        'silent false.'
    ]
  },

  switch: {
    kind: 'switch',
    displayName: 'Switch',
    category: 'Workflow Logic',
    source: 'CF11-001',
    summary: 'Matches a value against labelled cases and takes that case route, or `default`.',
    whenToUse:
      'Multi-way routing on one value — an order status, a webhook event type, a country code. Use `branch` for ' +
      'a two-way yes/no.',
    invokesFunction: false,
    params: [
      {
        name: 'value',
        type: 'any',
        description: 'The value to switch on — a literal or `{"$path": "..."}` into the step input.'
      },
      {
        name: 'cases',
        type: 'array',
        required: true,
        raw: true,
        description:
          'Ordered `[{ label, equals }]` or `[{ label, when: <condition> }]`. The FIRST match wins. Each label ' +
          'names a route in `routes`; `default` is reserved.'
      }
    ],
    routes: [
      { name: '<case label>', description: 'Taken when that case matches.', dynamic: true },
      { name: 'default', description: 'Taken when no case matches.' }
    ],
    output: '`{ matched: string | null, value: unknown }`.',
    clientEquivalent:
      'None. The client `Switch` node is a two-state on/off toggle, NOT multi-way routing — the shared name is a ' +
      'collision, not an equivalence. Closest client analogue is `String Selector`.',
    notes: ['`cases` may not be empty and case labels must be unique and non-`default`.']
  },

  'for-each': {
    kind: 'for-each',
    displayName: 'For Each',
    category: 'Workflow Logic',
    source: 'CF11-001',
    summary: 'Invokes a cloud function once per item of an array and collects the results.',
    whenToUse:
      'Fan a list out over a per-item function — charge every line of an order, notify every subscriber. The ' +
      'per-item unit is a function (a real node graph), which keeps the "a workflow node is a node" rule intact.',
    invokesFunction: true,
    params: [
      REF_PARAM,
      {
        name: 'items',
        type: 'any',
        default: { $path: 'previous.items' },
        description: 'The array to iterate — usually `{"$path": "previous.items"}`. Must resolve to an array.'
      },
      { name: 'itemKey', type: 'string', default: 'item', description: 'Key the item is passed under.' },
      { name: 'indexKey', type: 'string', default: 'index', description: 'Key the zero-based index is passed under.' },
      {
        name: 'maxIterations',
        type: 'number',
        default: 1000,
        description:
          'Hard cap. Exceeding it is a step FAILURE, not a truncation — a runaway list on a metered platform must ' +
          'be loud. Raise deliberately.'
      },
      {
        name: 'concurrency',
        type: 'number',
        default: 1,
        description: 'Items processed at once. 1 (default) preserves result order deterministically.'
      },
      {
        name: 'continueOnError',
        type: 'boolean',
        default: false,
        description:
          'False (default): the first failing item fails the whole step. True: failures are collected into ' +
          '`errors` and the step succeeds — every failure is still recorded in the output, never swallowed.'
      },
      {
        name: 'filter',
        type: 'condition',
        raw: true,
        description: 'Optional condition; items that do not match are skipped (counted in `skipped`).'
      }
    ],
    routes: [
      { name: 'empty', description: 'Taken when the resolved array had no items to process.' },
      { name: 'nonempty', description: 'Taken when at least one item was processed.' }
    ],
    output: '`{ results: unknown[], count, skipped, errors: [{index,message}], failed: number }`.',
    clientEquivalent:
      'Repeater / For Each in the browser renders a component per item. This runs a FUNCTION per item and ' +
      'collects return values; there is nothing to render server-side.',
    notes: [
      'CF11-001 sketched a `triggerOutputAndWait` sub-graph per item. WF-001 has no signal ports and no nested ' +
        'scheduler, so the per-item unit is a function invocation. Iterating an arbitrary SUB-DAG is deferred.'
    ]
  },

  merge: {
    kind: 'merge',
    displayName: 'Merge',
    category: 'Workflow Logic',
    source: 'CF11-001',
    summary: 'Combines the outputs of the upstream steps that reached it into one object or array.',
    whenToUse:
      'Converge branches — after a `branch` or `switch` fanned out, collect whatever ran into a single payload for ' +
      'the next step.',
    invokesFunction: false,
    params: [
      {
        name: 'mode',
        type: 'enum',
        enums: ['all', 'any'],
        default: 'all',
        description:
          '`all`: every declared source must have reached this step, else the step FAILS loudly (a half-merge ' +
          'silently passed downstream is the bug this prevents). `any`: merge whatever arrived.'
      },
      {
        name: 'sources',
        type: 'array',
        description:
          'Step ids expected to feed this merge. Defaults to every step with an edge into it (derived from the ' +
          'definition, so it stays correct as the graph is edited).'
      },
      {
        name: 'strategy',
        type: 'enum',
        enums: ['object', 'array', 'shallow'],
        default: 'object',
        description:
          '`object`: `{ [stepId]: output }` (lossless). `array`: outputs in definition order. `shallow`: one ' +
          'flat object, later sources winning — convenient, lossy, and it can silently drop a key, so it is not ' +
          'the default.'
      }
    ],
    routes: [],
    output: '`{ merged, sources: string[], missing: string[] }`.',
    clientEquivalent:
      'None. The browser has no merge because per-frame propagation makes convergence implicit; server-side the ' +
      'DAG is explicit, so convergence is an explicit step.',
    notes: [
      'No waiting is involved: topological order guarantees every predecessor has already finished when a merge ' +
        'step runs. CF11-001 described branch-arrival tracking, which only made sense in a signal runtime.'
    ]
  },

  transform: {
    kind: 'transform',
    displayName: 'Transform',
    category: 'Workflow Data',
    source: 'CWF-004',
    summary: 'Builds a new object out of the run\'s data — renaming, flattening and defaulting, with no code.',
    whenToUse:
      "Reshape an awkward payload before handing it on. A supplier's webhook arrives nested and verbose; a " +
      'function should not have to know that. Reshape here and the function keeps a stable input contract, so it ' +
      'stays callable from your app and from three other workflows.',
    invokesFunction: false,
    params: [
      {
        name: 'output',
        type: 'object',
        required: true,
        raw: true,
        control: CONTROL_TRANSFORM_OUTPUT,
        displayName: 'Fields',
        description:
          'The object this step produces, as `{ "<field>": <value> }`. Each value is a literal, a ' +
          '`{"$path": "previous.user.order.payment"}` reference, or one of the operations in `transformLanguage` ' +
          `(${TRANSFORM_OP_NAMES.join(', ')}) applied to values. A field cannot read another field of the same ` +
          'transform — every field resolves against the run, in one pass.'
      }
    ],
    routes: [],
    output: 'The object you described, and nothing else — so the next step reads it as `previous.<field>`.',
    clientEquivalent:
      'Nothing exact. In the browser you would wire an Object node, or compute in a Function. Server-side there ' +
      'is no code here on purpose: a workflow definition is deployable, agent-authored JSON running with admin ' +
      'authority, so it references and reshapes, and it never evaluates.',
    notes: [
      'The vocabulary is CLOSED and served. An unknown `$operation` is refused when the definition is saved, ' +
        'never passed through as data — which is what stops a typo becoming a literal object inside a function.',
      'There is no arithmetic in it. That was proposed and deliberately left out of the first cut: the value ' +
        'language already tells every client "no arithmetic — compute in a cloud function", and shipping `$add` ' +
        'would have falsified a served sentence. Adding an op later is additive; removing one is not.',
      'Wildcard paths (`lines.*.amount`) are NOT in v1. They would be a change to the `$path` walker that ' +
        'conditions share, and a second walker for transforms is the one thing CWF-004 rules out by name.',
      'Chain two transform steps where one field genuinely depends on another. One pass, one scope, no order to ' +
        'depend on — which is also what makes a transform diffable and safe for an agent to write.'
    ]
  },

  validate: {
    kind: 'validate',
    displayName: 'Validate',
    category: 'Workflow Data',
    source: 'CWF-004',
    summary: "Checks that the run's data is the shape you expect, and fails the step loudly when it is not.",
    whenToUse:
      'Guard the top of a workflow that a third party can start. A webhook from someone else\'s system is exactly ' +
      'where a silent `undefined` ruins an afternoon three weeks later — this turns it into one loud failure, at ' +
      'the step whose job was to notice, with the path named.',
    invokesFunction: false,
    params: [
      {
        name: 'rules',
        type: 'array',
        required: true,
        raw: true,
        control: CONTROL_VALIDATE_RULES,
        displayName: 'Rules',
        description:
          'What must be true. Each rule has EXACTLY ONE of `path` (assert a path is present, and optionally that ' +
          `it is one of ${VALIDATE_TYPE_NAMES.join(', ')}) or \`when\` (assert any condition the branch language ` +
          'can express). `required` defaults to TRUE on a path rule; set it false for "optional, but this type ' +
          'when present". A `message` replaces the generated one.'
      },
      {
        name: 'mode',
        type: 'enum',
        enums: ['all', 'first'],
        default: 'all',
        description:
          '`all` (default): check every rule and report every broken one in a single failure — usually what you ' +
          'want, because fixing one supplier field at a time is four deploys. `first`: stop at the first.'
      }
    ],
    routes: [],
    output: '`{ ok: true, checked: number }` when every rule held. A broken rule is a step FAILURE, not an output.',
    clientEquivalent:
      'None. In the browser you would wire Conditions and an Expression; here the rules are declarative data, ' +
      'because a workflow definition is deployable, agent-authored JSON running with admin authority.',
    notes: [
      'There is no `invalid` route, deliberately: a failure routes down `onError`, and error edges already ARE ' +
        'try/catch. A second way to express "the data was bad" would be one way too many.',
      'A condition rule that cannot be EVALUATED is reported as a broken rule rather than as a different kind of ' +
        'failure, so `mode: "all"` still tells you about the other four rules.',
      'The type vocabulary is CLOSED and served as `validateLanguage`. Anything richer than a JSON type — an ' +
        'email shape, a range, one of three values — is a `when` rule, using the operator set that is already ' +
        'served and already implemented.',
      'A rule with `"required": false` and no `type` asserts nothing, and is refused at write time rather than ' +
        'passing silently.'
    ]
  },

  filter: {
    kind: 'filter',
    displayName: 'Filter',
    category: 'Workflow Data',
    source: 'CWF-004',
    summary: 'Keeps only the array items that match a declarative condition.',
    whenToUse:
      'Narrow a list before doing anything expensive with it — only the unpaid invoices, only the EU customers. ' +
      'Reach for it before a For Each, so the per-item function is called for the items that matter and the ' +
      'filtered list is visible in the execution record.',
    invokesFunction: false,
    params: [
      ITEMS_PARAM,
      {
        name: 'condition',
        type: 'condition',
        required: true,
        raw: true,
        description:
          'Kept when this is true. The item is in scope under `itemKey` and its position under `indexKey`, so ' +
          '`{"$path": "item.status"}` reads the item — the same condition that works in a For Each filter.'
      },
      { name: 'itemKey', type: 'string', default: 'item', description: 'Key the item is in scope under.' },
      {
        name: 'indexKey',
        type: 'string',
        default: 'index',
        description: 'Key the zero-based position is in scope under.'
      }
    ],
    routes: [
      { name: 'empty', description: 'Taken when nothing matched.' },
      { name: 'nonempty', description: 'Taken when at least one item matched.' }
    ],
    output: '`{ items: unknown[], count, dropped, total }` — `items` is the kept list, in its original order.',
    clientEquivalent:
      'Array Filter, which runs a JavaScript predicate per item. Here the predicate is a declarative condition ' +
      'for the reason nothing on this tier evaluates a string.',
    notes: [
      'This is the ONE array step with routes, because it is the one that can change whether the list is empty. ' +
        'Sorting, de-duplicating and splitting cannot, so ports for it there would answer a question the ' +
        'previous step already knew.',
      '`for-each` has had a `filter` param since WF-002 and still does. As a STEP the filtered list is an ' +
        'output — recorded, readable downstream, and usable for something other than a per-item call.',
      'A condition that cannot be evaluated on an item is a LOUD step failure naming the index, not a silent drop.'
    ]
  },

  sort: {
    kind: 'sort',
    displayName: 'Sort',
    category: 'Workflow Data',
    source: 'CWF-004',
    summary: "Orders an array by a path inside each item, using the condition language's own ordering.",
    whenToUse:
      'Put a list in a deliberate order before it is written, sent or batched — oldest first, largest last. ' +
      'Cheap, declarative, and it makes the next step reproducible instead of dependent on whatever order a ' +
      'supplier happened to send.',
    invokesFunction: false,
    params: [
      ITEMS_PARAM,
      {
        name: 'by',
        type: 'string',
        displayName: 'Sort by (a path inside each item)',
        description:
          'A dotted path INTO each item — `payment.total`, `createdAt`. Leave it empty to order the items ' +
          'themselves, which is what you want for a list of strings or numbers.'
      },
      {
        name: 'order',
        type: 'enum',
        enums: ['ascending', 'descending'],
        default: 'ascending',
        description: 'Which end the smallest value goes. Items with no sort key stay last either way.'
      }
    ],
    routes: [],
    output: '`{ items: unknown[], count }` — a new array; the input is never reordered in place.',
    clientEquivalent:
      'Array Sort in the browser takes a JavaScript comparator. This takes a path, and the order is the one ' +
      '`gt` / `lt` already use, so a sort and a condition can never disagree about which value is larger.',
    notes: [
      'Numbers order numerically, numeric strings order numerically (so `"10"` is after `"9"`), ISO dates order ' +
        'as instants, and two plain strings order lexicographically — the condition language\'s rules exactly.',
      'The sort is STABLE: equal keys keep the order they arrived in.',
      'An item whose key is missing or null sorts LAST in BOTH directions. Absence is not a value, so reversing ' +
        'the order must not move it.',
      'Two items that cannot be ordered — a number against an object — FAIL the step. Inventing an order there ' +
        'is how a report comes out wrong rather than missing.'
    ]
  },

  deduplicate: {
    kind: 'deduplicate',
    displayName: 'Deduplicate',
    category: 'Workflow Data',
    source: 'CWF-004',
    summary: 'Drops repeated array items, compared by a path inside each item.',
    whenToUse:
      'A supplier that re-sends, a join that fanned out, a webhook delivered twice. Collapse the repeats before ' +
      'the list reaches anything that charges a card or sends an email.',
    invokesFunction: false,
    params: [
      ITEMS_PARAM,
      {
        name: 'by',
        type: 'string',
        displayName: 'Same when (a path inside each item)',
        description:
          'A dotted path INTO each item — `id`, `customer.email`. Leave it empty to compare whole items by value.'
      },
      {
        name: 'keep',
        type: 'enum',
        enums: ['first', 'last'],
        default: 'first',
        description:
          'Which of a repeated pair survives. Either way the surviving item holds its FIRST position, so the ' +
          'list order does not shuffle under you.'
      }
    ],
    routes: [],
    output: '`{ items: unknown[], count, removed, keyless }` — `keyless` counts the items that had no key at all.',
    clientEquivalent: 'None. In the browser this is a Function node over an array.',
    notes: [
      'Keys are compared BY VALUE, with object keys sorted first — so `{a:1,b:2}` and `{b:2,a:1}` are one value ' +
        'and not two, which is what "the same data" means to an author.',
      '⚠️ An item whose key is MISSING is always kept. Absence is not a value anywhere in this language, so it ' +
        'cannot be a duplicate — and bucketing every key-less item together would silently delete every row the ' +
        'supplier forgot an id for, which is the data you most want when you go looking for what went wrong. ' +
        '`keyless` in the output says how many there were.'
    ]
  },

  split: {
    kind: 'split',
    displayName: 'Split into Batches',
    category: 'Workflow Data',
    source: 'CWF-004',
    summary: 'Chunks an array into batches of a fixed size, for a rate-limited downstream.',
    whenToUse:
      'An API that accepts 50 records per call, or a For Each you want to run in waves rather than all at once. ' +
      'Split first, then For Each over `previous.batches` with a function that takes a batch.',
    invokesFunction: false,
    params: [
      ITEMS_PARAM,
      {
        name: 'size',
        type: 'number',
        required: true,
        displayName: 'Items per batch',
        description: 'How many items go in each batch. A whole number of 1 or more. The last batch may be shorter.'
      },
      {
        name: 'maxBatches',
        type: 'number',
        default: DEFAULT_MAX_BATCHES,
        description:
          'Hard cap on how many batches this may produce. Exceeding it is a step FAILURE, not a truncation — ' +
          'silently producing the first thousand batches of a hundred thousand is data loss that looks like ' +
          'success. Raise it deliberately.'
      }
    ],
    routes: [],
    output: '`{ batches: unknown[][], count, size, total }` — `count` is how many batches, `total` how many items.',
    clientEquivalent: 'None.',
    notes: [
      'An empty list produces zero batches and succeeds. There are no `empty` / `nonempty` routes here because a ' +
        'For Each over `previous.batches` already has that pair, and the answer is the same one.',
      'Batches hold the items in their original order, so a Sort before a Split is a Sort that survives it.'
    ]
  },

  stop: {
    kind: 'stop',
    displayName: 'Stop / Error',
    category: 'Workflow Error Handling',
    source: 'CF11-002',
    summary: 'Ends this path deliberately — either failing the run with a message, or stopping quietly.',
    whenToUse:
      'Terminate a branch on purpose: a validation guard that should fail the run loudly (`isError: true`), or a ' +
      'no-op path that simply has nothing more to do (`isError: false`).',
    invokesFunction: false,
    params: [
      {
        name: 'message',
        type: 'string',
        default: 'Workflow stopped',
        description: 'Recorded as the step error message and surfaced in the History Panel.'
      },
      {
        name: 'isError',
        type: 'boolean',
        default: true,
        description:
          'True (default): fails the step, so `onError` routing or the unrouted-halt rule applies. False: the ' +
          'step succeeds but takes NO outgoing edges — this path simply ends.'
      }
    ],
    routes: [],
    output: '`{ stopped: true, message }` when `isError` is false. Throws otherwise.',
    clientEquivalent: 'None.',
    notes: [
      'A non-error stop takes no edges at all — not even `next`. Everything downstream of it is recorded skipped, ' +
        'which is visible in the execution record rather than inferred.'
    ]
  },

  return: {
    kind: 'return',
    displayName: 'Return',
    category: 'Workflow Result',
    source: 'CWF-002',
    summary: 'Ends this path and sets the value the run answers with.',
    whenToUse:
      'Say explicitly what a caller gets back — a webhook in sync mode, or anything reading the run result. ' +
      'Without one, the run answers with whichever step finished last, which a branching canvas cannot show you.',
    invokesFunction: false,
    params: [
      {
        name: 'value',
        type: 'any',
        description:
          'What the run returns: a literal, or `{"$path": "previous.result.total"}` into any predecessor. ' +
          'Omitted, the upstream step\'s output is returned (and `null` on the entry step).'
      }
    ],
    routes: [],
    output: '`{ returned: true, value }` as the STEP output; the run\'s own `output` becomes `value` itself.',
    clientEquivalent:
      'The cloud function Response node — same idea one tier up. Response answers an HTTP request it was ' +
      'handed; Return sets the run result, which reaches a caller only when there is one (a sync webhook, or ' +
      'the admin run route). A scheduled run with a Return step is not an error; nobody is listening, is all.',
    notes: [
      'Takes NO outgoing edges, like a non-error stop — everything downstream is recorded skipped. A `return` ' +
        'with a `next` edge is refused at write time.',
      'Two Return steps on two branches (success path, error path) is legal and normal. If two both RUN, the ' +
        'FIRST wins and the execution record carries `returnConflict` naming both — the ambiguity is recorded, ' +
        'never silently resolved.',
      'A `return` value is not validated against a schema: the workflow layer references and reshapes data, it ' +
        'does not compute it.'
    ]
  },

  wait: {
    kind: 'wait',
    displayName: 'Wait',
    category: 'Workflow Timing',
    source: 'CF11-003',
    summary: 'Pauses the run for a fixed duration, cancellably.',
    whenToUse:
      'Rate-limit a downstream API, or let an external system settle before the next step. For "run this later ' +
      'on a clock", use a WF-005 schedule trigger instead — that costs nothing while it waits.',
    invokesFunction: false,
    params: [
      { name: 'duration', type: 'number', required: true, description: 'How long to wait, in `unit`s. Must be > 0.' },
      {
        name: 'unit',
        type: 'enum',
        enums: ['milliseconds', 'seconds', 'minutes', 'hours'],
        default: 'milliseconds',
        description: 'Unit for `duration`.'
      }
    ],
    routes: [],
    output: '`{ waitedMs: number }`.',
    clientEquivalent:
      'Timer (displayName "Delay"), whose `duration` input this matches. Differences: browser timers are ' +
      'frame-scheduled and free; this holds a real server process and a concurrency slot for the whole duration.',
    notes: [
      'COST AND OCCUPANCY (read this): a waiting run occupies one of the workflow\'s `concurrency` slots and keeps ' +
        'the service process alive. There are no frames server-side and nothing is swapped out. A long wait is a ' +
        'long-running server task, with the cost that implies on a metered host.',
      'Capped at 24 hours; a longer wait is rejected at write time. Per-step and per-workflow timeouts still apply ' +
        'and will interrupt a wait.',
      'Cancelling the run aborts the wait immediately (it does not sleep out the remainder).'
    ]
  },

  'wait-until': {
    kind: 'wait-until',
    displayName: 'Wait Until',
    category: 'Workflow Timing',
    source: 'CF11-003',
    summary: 'Waits until a target instant, or takes the `skipped` route if it has already passed.',
    whenToUse:
      'Hold a run until an embargo time computed earlier in the workflow. Same cost warning as `wait`; for ' +
      'anything more than minutes away, a schedule trigger is the right tool.',
    invokesFunction: false,
    params: [
      {
        name: 'target',
        type: 'any',
        required: true,
        description:
          'An ISO-8601 string, epoch milliseconds, or `{"$path": "..."}` resolving to either. An unparseable ' +
          'target is a step FAILURE, not a zero wait.'
      }
    ],
    routes: [
      { name: 'done', description: 'Taken after waiting until the target.' },
      { name: 'skipped', description: 'Taken immediately when the target is already in the past.' }
    ],
    output: '`{ waitedMs: number, skipped: boolean, target: string }`.',
    clientEquivalent: 'None.',
    notes: ['Subject to the same 24-hour cap and the same cancellation behaviour as `wait`.']
  }
};

/** Every implemented kind, in catalog order. */
export const STEP_KINDS = Object.keys(STEP_KIND_SPECS) as StepKind[];

export function isStepKind(v: unknown): v is StepKind {
  return typeof v === 'string' && Object.prototype.hasOwnProperty.call(STEP_KIND_SPECS, v);
}

/**
 * The params of a kind that are DSL structures rather than values, and so are
 * NOT resolved by the engine before the step runs (WFA-003). The engine asks
 * this; nothing else needs to know which they are.
 */
export function rawParamNames(kind: StepKind): ReadonlySet<string> {
  const spec = STEP_KIND_SPECS[kind];
  if (!spec) return EMPTY_RAW_PARAMS;
  const cached = RAW_PARAM_CACHE.get(kind);
  if (cached) return cached;
  const names = new Set(spec.params.filter((p) => p.raw).map((p) => p.name));
  RAW_PARAM_CACHE.set(kind, names);
  return names;
}

const EMPTY_RAW_PARAMS: ReadonlySet<string> = new Set();
const RAW_PARAM_CACHE = new Map<StepKind, ReadonlySet<string>>();

/** The wire form served by `GET /admin/workflow-step-kinds` and MCP. */
export interface StepKindCatalog {
  version: string;
  source: string;
  docs: string;
  kinds: StepKindSpec[];
  /**
   * WFA-003: how a param value may reference the run's data. Served alongside
   * the kinds because a client rendering a param editor needs both, and a
   * bundled copy of either could disagree with the backend that will execute it.
   */
  valueLanguage: ValueLanguageSpec;
  /**
   * WFA-004: the closed operator set, with a label per operator and which ones
   * are unary — everything a three-control condition editor needs in order not
   * to hold its own copy of the list.
   */
  conditionLanguage: ConditionLanguageSpec;
  /**
   * CWF-004: the closed operation vocabulary a `transform` step's `output` may
   * use, with each operation's arity and operand labels — everything a rows-plus-
   * op-picker editor needs in order not to hold its own copy of the list, and
   * everything an authoring agent needs in order not to invent one.
   */
  transformLanguage: TransformLanguageSpec;
  /**
   * CWF-004 slice 2: the closed type vocabulary a `validate` step's path rules
   * may assert, and the two rule forms. Served for the reason the other three
   * languages are — a rules editor holding its own list could offer a check this
   * backend does not perform, and an agent will invent `"type": "email"` unless
   * something tells it what the types are.
   */
  validateLanguage: ValidateLanguageSpec;
  /**
   * CWF-005: step kinds this backend no longer SERVES but still reads and
   * converts, as `{ oldKind: newKind }`.
   *
   * A client that refuses a kind the backend does not serve — MCP's
   * `refuseUnservedKinds`, WFA-007's proposal check — has to tell "this backend
   * cannot run that" from "this backend accepts that and will convert it", and
   * only the backend knows which. Served rather than bundled for the same reason
   * everything else here is.
   */
  migratedKinds: Record<string, string>;
}

export function stepKindCatalog(): StepKindCatalog {
  return {
    version: STEP_KIND_CATALOG_VERSION,
    source: 'nodegx-backend/workflow/steps/kinds.ts (WF-002, WFA-003, WFA-004)',
    docs: 'docs/runtime/WORKFLOW-NODES.md',
    kinds: STEP_KINDS.map((k) => STEP_KIND_SPECS[k]),
    valueLanguage: VALUE_LANGUAGE,
    conditionLanguage: CONDITION_LANGUAGE,
    transformLanguage: TRANSFORM_LANGUAGE,
    validateLanguage: VALIDATE_LANGUAGE,
    migratedKinds: { ...MIGRATED_STEP_KINDS }
  };
}

// ---------------------------------------------------------------------------
// Write-time validation
// ---------------------------------------------------------------------------

/** Hard ceiling on any single wait, in ms (24h). See the `wait` spec notes. */
export const MAX_WAIT_MS = 24 * 60 * 60 * 1000;

export const WAIT_UNIT_MS: Record<string, number> = {
  milliseconds: 1,
  seconds: 1000,
  minutes: 60 * 1000,
  hours: 60 * 60 * 1000
};

function params(step: WorkflowStep): Record<string, unknown> {
  return (step.params || {}) as Record<string, unknown>;
}

/** True for `{"$path": …}` / `{"$literal": …}` — a value that is not known yet. */
function isValueSpec(v: unknown): boolean {
  return isPlainObject(v) && (typeof v.$path === 'string' || '$literal' in v);
}

/**
 * CWF-001: the names a kind's param mapping may use.
 *
 * Checked for the kinds that DECLARE a mapping, and only for the params that are
 * not declared by the kind itself — the declared ones are the kind's own
 * vocabulary and are not the author's to collide with. What is deliberately NOT
 * checked is whether a `$path` resolves to anything: a function's output shape is
 * the function's business, which is the same line `validateValueReferences`
 * already draws.
 */
function validateParamMapping(spec: StepKindSpec, p: Record<string, unknown>, at: string): string[] {
  if (!spec.paramMapping) return [];
  const declared = new Set(spec.params.map((param) => param.name));
  const errors: string[] = [];

  for (const key of Object.keys(p)) {
    if (declared.has(key)) continue;
    if (!key.trim()) {
      errors.push(`${at}: a param needs a name — it is what the function reads the value as`);
    } else if (RESERVED_STEP_INPUT_KEYS.has(key)) {
      errors.push(
        `${at}.params.${key}: the engine writes "${key}" into the step input AFTER the params, so this value ` +
          'would be silently discarded. Give it another name.'
      );
    }
  }
  return errors;
}

function requirePositiveNumber(v: unknown, where: string, errors: string[], min = 1): void {
  if (v === undefined) return;
  if (typeof v !== 'number' || !Number.isFinite(v) || v < min) {
    errors.push(`${where} must be a number >= ${min}`);
  }
}

/**
 * Per-kind shape validation, consulted by `validateWorkflowDefinition`. Returns
 * error strings prefixed with the step id; empty means valid.
 *
 * Everything checkable without running is checked HERE, at write time, so a
 * definition that could not possibly work is rejected with a 400 and never
 * persisted — the same doctrine as the graph-level acyclicity check.
 */
export function validateStepShape(step: WorkflowStep): string[] {
  const errors: string[] = [];
  const at = `step "${step.id}"`;
  const spec = STEP_KIND_SPECS[step.kind];
  if (!spec) {
    errors.push(`${at}: unknown kind "${String(step.kind)}" (known: ${STEP_KINDS.join(', ')})`);
    return errors;
  }

  if (spec.invokesFunction && (typeof step.ref !== 'string' || !step.ref)) {
    errors.push(`${at}: kind "${step.kind}" needs a ref (the cloud function name)`);
  }
  if (!spec.invokesFunction && step.ref) {
    errors.push(`${at}: kind "${step.kind}" does not invoke a function — remove "ref"`);
  }

  // WFA-004: the editor's canvas position. Optional and engine-invisible, but
  // checked so a malformed one is a 400 at write time rather than something a
  // canvas has to defend against on every open.
  if (step.ui !== undefined) {
    const ui = step.ui as unknown;
    if (
      !isPlainObject(ui) ||
      typeof ui.x !== 'number' ||
      typeof ui.y !== 'number' ||
      !Number.isFinite(ui.x) ||
      !Number.isFinite(ui.y)
    ) {
      errors.push(`${at}: ui must be { x: number, y: number } (the editor's canvas position)`);
    }
  }

  const p = params(step);
  const routeNames = Object.keys(step.routes || {});

  switch (step.kind) {
    case 'branch': {
      if (p.condition === undefined) errors.push(`${at}: branch needs a "condition" param`);
      else errors.push(...validateCondition(p.condition, `${at}.params.condition`));
      if (routeNames.length === 0) {
        errors.push(`${at}: branch needs at least one of the routes "ontrue" / "onfalse"`);
      }
      for (const r of routeNames) {
        if (r !== 'ontrue' && r !== 'onfalse') errors.push(`${at}: branch route "${r}" must be "ontrue" or "onfalse"`);
      }
      break;
    }

    case 'switch': {
      const cases = p.cases;
      if (!Array.isArray(cases) || cases.length === 0) {
        errors.push(`${at}: switch needs a non-empty "cases" array`);
        break;
      }
      const labels = new Set<string>();
      cases.forEach((c, i) => {
        const where = `${at}.params.cases[${i}]`;
        if (typeof c !== 'object' || c === null) {
          errors.push(`${where}: must be an object`);
          return;
        }
        const label = (c as { label?: unknown }).label;
        if (typeof label !== 'string' || !label) errors.push(`${where}: needs a non-empty string label`);
        else if (label === 'default') errors.push(`${where}: "default" is reserved — it is the no-match route`);
        else if (labels.has(label)) errors.push(`${where}: duplicate case label "${label}"`);
        else labels.add(label);

        const hasEquals = 'equals' in (c as object);
        const hasWhen = 'when' in (c as object);
        if (hasEquals === hasWhen) errors.push(`${where}: needs exactly one of "equals" or "when"`);
        if (hasWhen) errors.push(...validateCondition((c as { when: unknown }).when, `${where}.when`));
      });
      for (const r of routeNames) {
        if (r !== 'default' && !labels.has(r)) {
          errors.push(`${at}: route "${r}" matches no case label (labels: ${[...labels].join(', ') || 'none'})`);
        }
      }
      break;
    }

    case 'for-each': {
      requirePositiveNumber(p.maxIterations, `${at}.params.maxIterations`, errors);
      requirePositiveNumber(p.concurrency, `${at}.params.concurrency`, errors);
      if (p.filter !== undefined) errors.push(...validateCondition(p.filter, `${at}.params.filter`));
      if (p.itemKey !== undefined && typeof p.itemKey !== 'string') errors.push(`${at}.params.itemKey must be a string`);
      if (p.indexKey !== undefined && typeof p.indexKey !== 'string') {
        errors.push(`${at}.params.indexKey must be a string`);
      }
      for (const r of routeNames) {
        if (r !== 'empty' && r !== 'nonempty') errors.push(`${at}: for-each route "${r}" must be "empty" or "nonempty"`);
      }
      break;
    }

    case 'merge': {
      if (p.mode !== undefined && p.mode !== 'all' && p.mode !== 'any') {
        errors.push(`${at}.params.mode must be "all" or "any"`);
      }
      if (p.strategy !== undefined && !['object', 'array', 'shallow'].includes(String(p.strategy))) {
        errors.push(`${at}.params.strategy must be "object", "array" or "shallow"`);
      }
      if (p.sources !== undefined && (!Array.isArray(p.sources) || p.sources.some((s) => typeof s !== 'string'))) {
        errors.push(`${at}.params.sources must be an array of step ids`);
      }
      break;
    }

    case 'stop': {
      if (p.message !== undefined && typeof p.message !== 'string') errors.push(`${at}.params.message must be a string`);
      if (p.isError !== undefined && typeof p.isError !== 'boolean') {
        errors.push(`${at}.params.isError must be a boolean`);
      }
      if ((step.next || []).length > 0 && p.isError !== false) {
        errors.push(`${at}: a stop step with isError true can never take "next" — remove the edge or set isError false`);
      }
      break;
    }

    case 'return': {
      // A `return` ends its path, so an outgoing edge is dead wiring — the same
      // class of mistake the `stop`/`isError` rule above catches, and refused
      // for the same reason: it would never be taken and nothing would say so.
      if ((step.next || []).length > 0) {
        errors.push(`${at}: a return step ends its path and can never take "next" — remove the edge`);
      }
      // `value` is deliberately optional and deliberately unconstrained: any
      // JSON, or a `{"$path"}` reference, is a legal thing to hand a caller.
      // The only structural rule is depth, which the generic value walk in
      // validateWorkflowDefinition already enforces.
      break;
    }

    case 'wait': {
      const unit = p.unit === undefined ? 'milliseconds' : String(p.unit);
      if (!WAIT_UNIT_MS[unit]) {
        errors.push(`${at}.params.unit must be one of ${Object.keys(WAIT_UNIT_MS).join(', ')}`);
      }
      // A duration written as a reference cannot be range-checked here — the
      // value does not exist yet. The executor already resolves it and already
      // fails loudly on a non-number and on the 24h cap, so this defers to it
      // rather than rejecting a legal definition. (`WaitStepExecutor` has
      // resolved `duration` since WF-002; write-time validation refused it,
      // which made the feature unreachable.)
      if (isValueSpec(p.duration)) break;
      if (typeof p.duration !== 'number' || !Number.isFinite(p.duration) || p.duration <= 0) {
        errors.push(`${at}.params.duration must be a number > 0`);
      } else if (WAIT_UNIT_MS[unit] && p.duration * WAIT_UNIT_MS[unit] > MAX_WAIT_MS) {
        errors.push(
          `${at}: wait of ${p.duration} ${unit} exceeds the ${MAX_WAIT_MS}ms (24h) cap — use a schedule trigger`
        );
      }
      break;
    }

    case 'transform': {
      // CWF-004: `output` is REQUIRED here rather than defaulted, and the
      // executor has no fallback either. A declared default never runs a setter
      // in this codebase, and CWF-005 found that an executor's fallback is what
      // ever actually applies — so a transform with nothing to produce is
      // refused at the one place a refusal costs nothing.
      errors.push(...validateTransformOutput(p.output, at));
      break;
    }

    case 'validate': {
      // Same doctrine as `transform`'s `output`: the thing the step exists to
      // do is REQUIRED at write time, with no declared default and no executor
      // fallback, because a validate step with no rules asserts nothing while
      // looking exactly like a guard.
      errors.push(...validateValidateRules(p.rules, at));
      if (p.mode !== undefined && p.mode !== 'all' && p.mode !== 'first') {
        errors.push(`${at}.params.mode must be "all" or "first"`);
      }
      break;
    }

    case 'filter': {
      if (p.condition === undefined) errors.push(`${at}: filter needs a "condition" param — it would keep everything`);
      else errors.push(...validateCondition(p.condition, `${at}.params.condition`));
      if (p.itemKey !== undefined && typeof p.itemKey !== 'string') errors.push(`${at}.params.itemKey must be a string`);
      if (p.indexKey !== undefined && typeof p.indexKey !== 'string') {
        errors.push(`${at}.params.indexKey must be a string`);
      }
      for (const r of routeNames) {
        if (r !== 'empty' && r !== 'nonempty') errors.push(`${at}: filter route "${r}" must be "empty" or "nonempty"`);
      }
      break;
    }

    case 'sort': {
      if (p.by !== undefined && typeof p.by !== 'string') {
        errors.push(`${at}.params.by must be a dotted path string into each item`);
      }
      if (p.order !== undefined && p.order !== 'ascending' && p.order !== 'descending') {
        errors.push(`${at}.params.order must be "ascending" or "descending"`);
      }
      break;
    }

    case 'deduplicate': {
      if (p.by !== undefined && typeof p.by !== 'string') {
        errors.push(`${at}.params.by must be a dotted path string into each item`);
      }
      if (p.keep !== undefined && p.keep !== 'first' && p.keep !== 'last') {
        errors.push(`${at}.params.keep must be "first" or "last"`);
      }
      break;
    }

    case 'split': {
      requirePositiveNumber(p.maxBatches, `${at}.params.maxBatches`, errors);
      // A size written as a reference cannot be range-checked here — the value
      // does not exist yet. `wait.duration` set this precedent and for the same
      // reason: refusing it at write time made a legal definition unwritable,
      // and the executor already fails loudly on a bad one.
      if (isValueSpec(p.size)) break;
      if (p.size === undefined) {
        errors.push(`${at}: split needs a "size" param — how many items go in each batch`);
      } else if (typeof p.size !== 'number' || !Number.isInteger(p.size) || p.size < 1) {
        errors.push(`${at}.params.size must be a whole number of 1 or more`);
      }
      break;
    }

    case 'wait-until': {
      if (p.target === undefined) errors.push(`${at}: wait-until needs a "target" param`);
      for (const r of routeNames) {
        if (r !== 'done' && r !== 'skipped') errors.push(`${at}: wait-until route "${r}" must be "done" or "skipped"`);
      }
      break;
    }

    case 'call-function': {
      // CWF-001: until this case existed, `call-function` fell through to
      // `default: break` and any params object at all was legal — which was
      // tolerable while no UI could author one, and is not now that the mapping
      // is a declared, documented feature with a row of its own.
      errors.push(...validateParamMapping(spec, p, at));

      // CWF-005: this WAS `case 'retry'`, moved here by the fold. Unchanged, so
      // a definition that migrated is checked by exactly the rules it was
      // checked by before.
      requirePositiveNumber(p.maxAttempts, `${at}.params.maxAttempts`, errors);
      requirePositiveNumber(p.delayMs, `${at}.params.delayMs`, errors, 0);
      requirePositiveNumber(p.maxDelayMs, `${at}.params.maxDelayMs`, errors, 0);
      if (p.backoffMultiplier !== undefined && (typeof p.backoffMultiplier !== 'number' || p.backoffMultiplier < 1)) {
        errors.push(`${at}.params.backoffMultiplier must be a number >= 1`);
      }
      if (p.retryOnStatus !== undefined) {
        if (!Array.isArray(p.retryOnStatus) || p.retryOnStatus.some((s) => typeof s !== 'number')) {
          errors.push(`${at}.params.retryOnStatus must be an array of HTTP status numbers`);
        }
      }
      break;
    }

    default:
      break;
  }

  // A kind with no routes in its spec must not carry a `routes` object: it
  // would be silently dead wiring (the executor never selects anything), which
  // is exactly the class of mistake SUB-005's enrichment pass exists to catch.
  if (spec.routes.length === 0 && routeNames.length > 0) {
    errors.push(`${at}: kind "${step.kind}" has no routes — use "next" / "onError" edges instead of "routes"`);
  }

  return errors;
}
