/**
 * The WF-002 step-kind catalog — the machine-readable description of every
 * workflow step kind, plus the write-time validation derived from it.
 *
 * WHY THIS FILE EXISTS AND WHY IT IS SHAPED LIKE A CATALOG
 * --------------------------------------------------------
 * SUB-004's node catalog (`packages/noodl-types/src/node-catalog.json`) is
 * generated by *running the two runtime node registers* — browser
 * (`noodl-viewer-react`) and cloud (`noodl-viewer-cloud`) — and serialising
 * what registered. A workflow step kind is not registered in either: it is not
 * a graph node with ports, it is a `kind` field in a `*.workflow-def.json`
 * step DAG, executed by the WF-001 engine. It therefore cannot enter that
 * artifact, and `catalog:check` (which regenerates from the registers and
 * fails on drift) would not accept a hand-written entry — the same reason
 * library **module** nodes are documented as out of catalog scope.
 *
 * What the catalog requirement actually buys is *discoverability by the
 * semantic validator and the AI authoring loop*. That is delivered here in the
 * form that fits the artifact: a versioned, machine-readable spec table with
 * params, routes, output shape and prose, which is
 *   - served at `GET /admin/workflow-step-kinds` (so a running backend
 *     describes its own step vocabulary),
 *   - surfaced to agents through the MCP `list_backend_step_kinds` tool and the
 *     `create_backend_workflow` schema,
 *   - the single source of truth for write-time validation, so an unknown kind
 *     or a missing required param is REJECTED at `POST /admin/workflow-defs`
 *     and refuses to load from disk, and
 *   - coverage-gated by `tests/workflow-steps-catalog.test.ts`, which fails if
 *     a kind is implemented without a spec entry, or specced without author
 *     documentation in `docs/runtime/WORKFLOW-NODES.md`.
 *
 * That last point is the local equivalent of `catalog:merge:check
 * --require-coverage`: a step kind cannot ship undocumented and invisible.
 * The full argument, and why this is NOT the WF-005 "no catalog at all"
 * exemption, is in WF-002-NOTES.md.
 *
 * This module holds NO runtime dependencies (no engine, no runner) so that
 * `validateWorkflowDefinition` can consult it from the registry's load path.
 *
 * @module nodegx-backend/workflow/steps/kinds
 */

import type { StepKind, WorkflowStep } from '../types';
import { CONDITION_LANGUAGE, validateCondition } from './conditions';
import type { ConditionLanguageSpec } from './conditions';
import type { ValueLanguageSpec } from './values';
import { isPlainObject, VALUE_LANGUAGE } from './values';

/**
 * Bumped when the spec table's SHAPE changes (not when a kind is added).
 *
 * 1.1.0 — WFA-003 added `valueLanguage` (so a client can render the right
 * control for a param and know what a `$path` may address) and `raw` on a param.
 * 1.2.0 — WFA-004 added `conditionLanguage`. The workflow canvas renders a
 * condition as three controls, and the operator list it offers has to come from
 * the backend that will evaluate it — a bundled copy could offer an operator
 * this backend does not implement, which is the drift the served registry
 * exists to prevent.
 * 1.3.0 — CWF-001 added `paramMapping` on a KIND. It describes something the
 * engine has done since WFA-003 and nothing declared: a step's params are merged
 * into its input by name, so a `call-function` step can hand a function a value
 * under a name the author chose. It went unauthorable because the editor builds
 * one row per DECLARED param and there were none to declare.
 *
 * Degradation, both ways: an editor talking to a pre-1.3.0 backend is served no
 * `paramMapping`, so it shows no mapping row — and definitions already carrying a
 * mapping still run, because the engine never needed the declaration. A pre-1.3.0
 * editor talking to a 1.3.0 backend ignores fields it does not know and renders
 * exactly what it rendered before.
 * 1.4.0 — CWF-005 added `displayName` and `control` on a param. Two of retry's
 * seven knobs lied in the only place people read — the field NAME — and neither
 * could be renamed without migrating every definition that uses it, because the
 * name is the wire contract. `displayName` separates the two jobs. `control`
 * names a bespoke editor control, and an editor that does not recognise the name
 * falls back to the control for the param's `type`, which is the whole reason it
 * is a served string rather than an enum.
 */
export const STEP_KIND_CATALOG_VERSION = '1.4.0';

export interface StepParamSpec {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'enum' | 'array' | 'object' | 'condition' | 'path' | 'any';
  required?: boolean;
  default?: unknown;
  enums?: string[];
  description: string;
  /**
   * The label a property editor puts on the row. Defaults to `name`.
   *
   * CWF-005: `maxAttempts` is the case this exists for. The number means "how
   * many calls in total", the name reads as "how many retries", and the
   * description saying so was losing — a description is read once, a field name
   * is read every time. The NAME cannot change: it is the wire contract, and
   * renaming it would mean migrating every definition that sets it.
   */
  displayName?: string;
  /**
   * The name of a bespoke control a client's property editor should use for this
   * param, when the control for its `type` will not do (CWF-005).
   *
   * Served rather than inferred, so the backend stays the authority on its own
   * param vocabulary — and safe to add, because a client that does not recognise
   * the name falls back to the control for `type`. That is the degradation story
   * for an editor older than the backend it is talking to.
   */
  control?: string;
  /**
   * WFA-003: this param is a DSL STRUCTURE — a condition, a filter, a switch's
   * cases — not a value. Its operands use the value language, but the executor
   * evaluates them when the step runs, so the engine does not resolve the param
   * itself. Every other param IS value-resolved before the step runs.
   *
   * A property editor should render a `raw` param with its own editor (three
   * dropdowns for a condition) rather than a value/binding control.
   */
  raw?: boolean;
}

export interface StepRouteSpec {
  name: string;
  description: string;
  /** True when the route names are derived from params (switch cases). */
  dynamic?: boolean;
}

/**
 * CWF-001 — a kind that takes params the AUTHOR names, beyond the declared ones.
 *
 * ⚠️ Read this before you "add param mapping": the engine has merged a step's
 * params into its input by name since WFA-003, so
 * `{"kind":"call-function","ref":"charge","params":{"amount":{"$path":"previous.result.total"}}}`
 * already delivers `body.amount` to the function, and
 * `tests/workflow-data-mapping.test.ts` has proved it end-to-end all along. What
 * did not exist was a *declaration*: the editor builds one row per DECLARED
 * param, so a kind whose only declared param was `ref` had nowhere to author a
 * mapping and the `$path` picker was reachable by no route in the product.
 *
 * This is that declaration, and it deliberately adds no second on-disk form.
 * There is exactly one way to write a mapping and it is the way that already
 * worked.
 */
export interface StepParamMappingSpec {
  /** The row label a property editor puts on the mapping. */
  displayName: string;
  description: string;
  /**
   * Names a mapping may not use — the backend refuses these. Served rather than
   * bundled so an editor's error and the backend's 400 cannot drift apart.
   */
  reserved: string[];
  /**
   * Names a mapping MAY use but which replace part of the run payload for the
   * called function. Legal; worth saying out loud in a property editor.
   */
  shadows: string[];
}

export interface StepKindSpec {
  kind: StepKind;
  displayName: string;
  category: string;
  /** The phase-11 spec this implements, for traceability. */
  source: string;
  summary: string;
  whenToUse: string;
  /** True when the step invokes a cloud function (and so needs `ref`). */
  invokesFunction: boolean;
  params: StepParamSpec[];
  /** CWF-001: present when the kind also takes author-named params. */
  paramMapping?: StepParamMappingSpec;
  routes: StepRouteSpec[];
  /** Prose description of the step's output object (what `previous` becomes). */
  output: string;
  /** The client-runtime node this mirrors, and how it differs. */
  clientEquivalent?: string;
  notes?: string[];
}

// ---------------------------------------------------------------------------
// The catalog
// ---------------------------------------------------------------------------

const REF_PARAM: StepParamSpec = {
  name: 'ref',
  type: 'string',
  required: true,
  description: 'The cloud function to invoke (a step field, not a param).'
};

/**
 * Names a param mapping may NOT use (CWF-001 S2). Exactly one, and the reason is
 * specific: `WorkflowEngine` builds a step's input as
 * `{ ...payload, ...params, previous }`, so a param called `previous` is
 * overwritten by the engine and the author is left debugging a value that never
 * arrived. Refused at write time, where renaming costs nothing.
 *
 * ⚠️ The list was drafted longer — the whole canonical payload — and that was
 * WRONG, caught by `workflow-data-mapping.test.ts`, which has passed
 * `{ body: {"$path":"body"} }` since WFA-003. A payload root in a mapping is not
 * lossy: the params merge AFTER the payload, so the author's value wins. That is
 * an override, and an explicit identity mapping is a legitimate way to say what a
 * step passes. See `SHADOWED_STEP_INPUT_KEYS` for what an editor should still
 * mention.
 */
export const RESERVED_STEP_INPUT_KEYS: ReadonlySet<string> = new Set(['previous']);

/**
 * Names a mapping may use but which REPLACE part of the run payload for the
 * function being called (CWF-001).
 *
 * Legal, occasionally intended, and worth a word in a property editor — a
 * function that stops seeing `body` because a step remapped it is a confusing
 * thing to debug, and a confusing thing is not the same as an illegal one.
 */
export const SHADOWED_STEP_INPUT_KEYS: readonly string[] = ['body', 'trigger', 'triggerType', 'headers', 'query'];

/**
 * CWF-001 — what a Call Function step hands the function it calls.
 *
 * Without it a function could only read data by the name and shape its CALLER
 * happened to produce — `previous.result.total`, wherever `previous` came from —
 * which welds a reusable unit of work to one position in one graph. With it, a
 * function declares `amount` and each step says where `amount` comes from.
 */
const CALL_FUNCTION_MAPPING: StepParamMappingSpec = {
  displayName: 'Params',
  description:
    'What this step passes the function, as `{ "<name>": <value> }`. Each value is a literal or a reference — ' +
    '`{"$path": "previous.result.total"}` — and the names arrive at the top level of the request body, so the ' +
    'function reads `amount`. A name cannot reference another name of the same step: params resolve against the ' +
    'run, before they are merged into anything.',
  reserved: [...RESERVED_STEP_INPUT_KEYS],
  shadows: [...SHADOWED_STEP_INPUT_KEYS]
};

export const STEP_KIND_SPECS: Record<StepKind, StepKindSpec> = {
  'call-function': {
    kind: 'call-function',
    displayName: 'Call Function',
    category: 'Workflow',
    source: 'WF-001',
    summary: 'Invokes an existing cloud function and uses its response as the step output.',
    whenToUse:
      'The workhorse step: any real work — reading or writing records, calling an external API, sending email — ' +
      'is a cloud function graph, and this step schedules it. Prefer it over inventing new step kinds.',
    invokesFunction: true,
    params: [REF_PARAM],
    paramMapping: CALL_FUNCTION_MAPPING,
    routes: [],
    output: "The function's parsed 2xx response body. A non-2xx response or a missing function is a step FAILURE.",
    notes: [
      'Runs through the unlogged WorkflowRunner.invokeFunction, so the engine writes the only execution record.',
      "The request body is the run payload, then this step's params, then `previous` — in that order, so a mapped " +
        'name overrides a payload key of the same name and `previous` cannot be overridden at all.'
    ]
  },

  branch: {
    kind: 'branch',
    displayName: 'Branch (IF)',
    category: 'Workflow Logic',
    source: 'CF11-001',
    summary: 'Evaluates a declarative condition and takes the `ontrue` or `onfalse` route.',
    whenToUse:
      'Route a run down one of two paths on a value — "was the order over £100", "did the upstream step return an ' +
      'error". This is the server-side equivalent of the client Condition node.',
    invokesFunction: false,
    params: [
      {
        name: 'condition',
        type: 'condition',
        required: true,
        raw: true,
        description:
          'A declarative condition (see the condition language). Paths resolve against the run scope, so ' +
          '`{"$path":"previous.total"}` reads the upstream step output and `{"$path":"upstream.save.id"}` reads a ' +
          'named earlier step.'
      }
    ],
    routes: [
      { name: 'ontrue', description: 'Taken when the condition evaluates true.' },
      { name: 'onfalse', description: 'Taken when the condition evaluates false.' }
    ],
    output: '`{ result: boolean, isfalse: boolean }` — mirrors the client Condition node output port names.',
    clientEquivalent:
      'Condition (`ontrue`/`onfalse`/`result`/`isfalse`). Port names match. Differences: the condition is a ' +
      'declarative object rather than a JavaScript expression (no eval on the server), and there is no `eval` ' +
      'signal input — a step runs when its incoming edge is taken.',
    notes: [
      'A condition that cannot be evaluated (incomparable operands, bad regex) is a LOUD step failure, not a ' +
        'silent false.'
    ]
  },

  switch: {
    kind: 'switch',
    displayName: 'Switch',
    category: 'Workflow Logic',
    source: 'CF11-001',
    summary: 'Matches a value against labelled cases and takes that case route, or `default`.',
    whenToUse:
      'Multi-way routing on one value — an order status, a webhook event type, a country code. Use `branch` for ' +
      'a two-way yes/no.',
    invokesFunction: false,
    params: [
      {
        name: 'value',
        type: 'any',
        description: 'The value to switch on — a literal or `{"$path": "..."}` into the step input.'
      },
      {
        name: 'cases',
        type: 'array',
        required: true,
        raw: true,
        description:
          'Ordered `[{ label, equals }]` or `[{ label, when: <condition> }]`. The FIRST match wins. Each label ' +
          'names a route in `routes`; `default` is reserved.'
      }
    ],
    routes: [
      { name: '<case label>', description: 'Taken when that case matches.', dynamic: true },
      { name: 'default', description: 'Taken when no case matches.' }
    ],
    output: '`{ matched: string | null, value: unknown }`.',
    clientEquivalent:
      'None. The client `Switch` node is a two-state on/off toggle, NOT multi-way routing — the shared name is a ' +
      'collision, not an equivalence. Closest client analogue is `String Selector`.',
    notes: ['`cases` may not be empty and case labels must be unique and non-`default`.']
  },

  'for-each': {
    kind: 'for-each',
    displayName: 'For Each',
    category: 'Workflow Logic',
    source: 'CF11-001',
    summary: 'Invokes a cloud function once per item of an array and collects the results.',
    whenToUse:
      'Fan a list out over a per-item function — charge every line of an order, notify every subscriber. The ' +
      'per-item unit is a function (a real node graph), which keeps the "a workflow node is a node" rule intact.',
    invokesFunction: true,
    params: [
      REF_PARAM,
      {
        name: 'items',
        type: 'any',
        default: { $path: 'previous.items' },
        description: 'The array to iterate — usually `{"$path": "previous.items"}`. Must resolve to an array.'
      },
      { name: 'itemKey', type: 'string', default: 'item', description: 'Key the item is passed under.' },
      { name: 'indexKey', type: 'string', default: 'index', description: 'Key the zero-based index is passed under.' },
      {
        name: 'maxIterations',
        type: 'number',
        default: 1000,
        description:
          'Hard cap. Exceeding it is a step FAILURE, not a truncation — a runaway list on a metered platform must ' +
          'be loud. Raise deliberately.'
      },
      {
        name: 'concurrency',
        type: 'number',
        default: 1,
        description: 'Items processed at once. 1 (default) preserves result order deterministically.'
      },
      {
        name: 'continueOnError',
        type: 'boolean',
        default: false,
        description:
          'False (default): the first failing item fails the whole step. True: failures are collected into ' +
          '`errors` and the step succeeds — every failure is still recorded in the output, never swallowed.'
      },
      {
        name: 'filter',
        type: 'condition',
        raw: true,
        description: 'Optional condition; items that do not match are skipped (counted in `skipped`).'
      }
    ],
    routes: [
      { name: 'empty', description: 'Taken when the resolved array had no items to process.' },
      { name: 'nonempty', description: 'Taken when at least one item was processed.' }
    ],
    output: '`{ results: unknown[], count, skipped, errors: [{index,message}], failed: number }`.',
    clientEquivalent:
      'Repeater / For Each in the browser renders a component per item. This runs a FUNCTION per item and ' +
      'collects return values; there is nothing to render server-side.',
    notes: [
      'CF11-001 sketched a `triggerOutputAndWait` sub-graph per item. WF-001 has no signal ports and no nested ' +
        'scheduler, so the per-item unit is a function invocation. Iterating an arbitrary SUB-DAG is deferred.'
    ]
  },

  merge: {
    kind: 'merge',
    displayName: 'Merge',
    category: 'Workflow Logic',
    source: 'CF11-001',
    summary: 'Combines the outputs of the upstream steps that reached it into one object or array.',
    whenToUse:
      'Converge branches — after a `branch` or `switch` fanned out, collect whatever ran into a single payload for ' +
      'the next step.',
    invokesFunction: false,
    params: [
      {
        name: 'mode',
        type: 'enum',
        enums: ['all', 'any'],
        default: 'all',
        description:
          '`all`: every declared source must have reached this step, else the step FAILS loudly (a half-merge ' +
          'silently passed downstream is the bug this prevents). `any`: merge whatever arrived.'
      },
      {
        name: 'sources',
        type: 'array',
        description:
          'Step ids expected to feed this merge. Defaults to every step with an edge into it (derived from the ' +
          'definition, so it stays correct as the graph is edited).'
      },
      {
        name: 'strategy',
        type: 'enum',
        enums: ['object', 'array', 'shallow'],
        default: 'object',
        description:
          '`object`: `{ [stepId]: output }` (lossless). `array`: outputs in definition order. `shallow`: one ' +
          'flat object, later sources winning — convenient, lossy, and it can silently drop a key, so it is not ' +
          'the default.'
      }
    ],
    routes: [],
    output: '`{ merged, sources: string[], missing: string[] }`.',
    clientEquivalent:
      'None. The browser has no merge because per-frame propagation makes convergence implicit; server-side the ' +
      'DAG is explicit, so convergence is an explicit step.',
    notes: [
      'No waiting is involved: topological order guarantees every predecessor has already finished when a merge ' +
        'step runs. CF11-001 described branch-arrival tracking, which only made sense in a signal runtime.'
    ]
  },

  retry: {
    kind: 'retry',
    displayName: 'Retry',
    category: 'Workflow Error Handling',
    source: 'CF11-002',
    summary: 'Invokes a cloud function repeatedly with exponential backoff until it succeeds or attempts run out.',
    whenToUse:
      'Wrap a call that fails transiently — a flaky third-party API, a rate-limited endpoint. Use `onError` edges ' +
      'for failures that need a different path rather than another attempt.',
    invokesFunction: true,
    params: [
      REF_PARAM,
      {
        name: 'maxAttempts',
        displayName: 'Total attempts (incl. the first)',
        // CWF-005: this row also draws the backoff preview, because the delay
        // sequence is the thing seven separate number fields cannot show you.
        control: 'retry-backoff',
        type: 'number',
        default: 3,
        description: 'How many times the function is called IN TOTAL. 1 means no retry at all. Min 1.'
      },
      {
        name: 'delayMs',
        displayName: 'First delay (ms)',
        type: 'number',
        default: 1000,
        description: 'How long to wait before the SECOND attempt. Later delays multiply from this.'
      },
      {
        name: 'backoffMultiplier',
        displayName: 'Delay multiplier',
        type: 'number',
        default: 2,
        description: 'Each subsequent delay is multiplied by this. 1 = a fixed delay every time.'
      },
      {
        name: 'maxDelayMs',
        displayName: 'Longest single delay (ms)',
        type: 'number',
        default: 60000,
        description: 'Ceiling on any one backoff delay, however far the multiplier has taken it.'
      },
      {
        name: 'jitter',
        displayName: 'Spread delays randomly',
        type: 'boolean',
        default: false,
        description: 'Randomise each delay across [50%, 100%] of its computed length, to avoid retry storms.'
      },
      {
        name: 'retryOnStatus',
        displayName: 'Retry ONLY these statuses',
        type: 'array',
        description:
          'Leave empty to retry any failure. Set it and the meaning INVERTS: only these HTTP statuses are ' +
          'retried and every other failure fails immediately — which is usually what you want (a 400 will not ' +
          'get better on the third attempt), and is never what adding one helpful code to the list looks like.'
      }
    ],
    routes: [],
    output: "The successful attempt's function output, plus `attempts` and `retried`.",
    clientEquivalent: 'None.',
    notes: [
      'Backoff waits are cancellable: cancelling the run or tripping the workflow timeout aborts the wait ' +
        'immediately rather than sleeping out the delay.',
      'Exhausting all attempts is a normal step FAILURE, so `onError` routing (or the halt rule) applies. The ' +
        'last error message names the attempt count.'
    ]
  },

  stop: {
    kind: 'stop',
    displayName: 'Stop / Error',
    category: 'Workflow Error Handling',
    source: 'CF11-002',
    summary: 'Ends this path deliberately — either failing the run with a message, or stopping quietly.',
    whenToUse:
      'Terminate a branch on purpose: a validation guard that should fail the run loudly (`isError: true`), or a ' +
      'no-op path that simply has nothing more to do (`isError: false`).',
    invokesFunction: false,
    params: [
      {
        name: 'message',
        type: 'string',
        default: 'Workflow stopped',
        description: 'Recorded as the step error message and surfaced in the History Panel.'
      },
      {
        name: 'isError',
        type: 'boolean',
        default: true,
        description:
          'True (default): fails the step, so `onError` routing or the unrouted-halt rule applies. False: the ' +
          'step succeeds but takes NO outgoing edges — this path simply ends.'
      }
    ],
    routes: [],
    output: '`{ stopped: true, message }` when `isError` is false. Throws otherwise.',
    clientEquivalent: 'None.',
    notes: [
      'A non-error stop takes no edges at all — not even `next`. Everything downstream of it is recorded skipped, ' +
        'which is visible in the execution record rather than inferred.'
    ]
  },

  return: {
    kind: 'return',
    displayName: 'Return',
    category: 'Workflow Result',
    source: 'CWF-002',
    summary: 'Ends this path and sets the value the run answers with.',
    whenToUse:
      'Say explicitly what a caller gets back — a webhook in sync mode, or anything reading the run result. ' +
      'Without one, the run answers with whichever step finished last, which a branching canvas cannot show you.',
    invokesFunction: false,
    params: [
      {
        name: 'value',
        type: 'any',
        description:
          'What the run returns: a literal, or `{"$path": "previous.result.total"}` into any predecessor. ' +
          'Omitted, the upstream step\'s output is returned (and `null` on the entry step).'
      }
    ],
    routes: [],
    output: '`{ returned: true, value }` as the STEP output; the run\'s own `output` becomes `value` itself.',
    clientEquivalent:
      'The cloud function Response node — same idea one tier up. Response answers an HTTP request it was ' +
      'handed; Return sets the run result, which reaches a caller only when there is one (a sync webhook, or ' +
      'the admin run route). A scheduled run with a Return step is not an error; nobody is listening, is all.',
    notes: [
      'Takes NO outgoing edges, like a non-error stop — everything downstream is recorded skipped. A `return` ' +
        'with a `next` edge is refused at write time.',
      'Two Return steps on two branches (success path, error path) is legal and normal. If two both RUN, the ' +
        'FIRST wins and the execution record carries `returnConflict` naming both — the ambiguity is recorded, ' +
        'never silently resolved.',
      'A `return` value is not validated against a schema: the workflow layer references and reshapes data, it ' +
        'does not compute it.'
    ]
  },

  wait: {
    kind: 'wait',
    displayName: 'Wait',
    category: 'Workflow Timing',
    source: 'CF11-003',
    summary: 'Pauses the run for a fixed duration, cancellably.',
    whenToUse:
      'Rate-limit a downstream API, or let an external system settle before the next step. For "run this later ' +
      'on a clock", use a WF-005 schedule trigger instead — that costs nothing while it waits.',
    invokesFunction: false,
    params: [
      { name: 'duration', type: 'number', required: true, description: 'How long to wait, in `unit`s. Must be > 0.' },
      {
        name: 'unit',
        type: 'enum',
        enums: ['milliseconds', 'seconds', 'minutes', 'hours'],
        default: 'milliseconds',
        description: 'Unit for `duration`.'
      }
    ],
    routes: [],
    output: '`{ waitedMs: number }`.',
    clientEquivalent:
      'Timer (displayName "Delay"), whose `duration` input this matches. Differences: browser timers are ' +
      'frame-scheduled and free; this holds a real server process and a concurrency slot for the whole duration.',
    notes: [
      'COST AND OCCUPANCY (read this): a waiting run occupies one of the workflow\'s `concurrency` slots and keeps ' +
        'the service process alive. There are no frames server-side and nothing is swapped out. A long wait is a ' +
        'long-running server task, with the cost that implies on a metered host.',
      'Capped at 24 hours; a longer wait is rejected at write time. Per-step and per-workflow timeouts still apply ' +
        'and will interrupt a wait.',
      'Cancelling the run aborts the wait immediately (it does not sleep out the remainder).'
    ]
  },

  'wait-until': {
    kind: 'wait-until',
    displayName: 'Wait Until',
    category: 'Workflow Timing',
    source: 'CF11-003',
    summary: 'Waits until a target instant, or takes the `skipped` route if it has already passed.',
    whenToUse:
      'Hold a run until an embargo time computed earlier in the workflow. Same cost warning as `wait`; for ' +
      'anything more than minutes away, a schedule trigger is the right tool.',
    invokesFunction: false,
    params: [
      {
        name: 'target',
        type: 'any',
        required: true,
        description:
          'An ISO-8601 string, epoch milliseconds, or `{"$path": "..."}` resolving to either. An unparseable ' +
          'target is a step FAILURE, not a zero wait.'
      }
    ],
    routes: [
      { name: 'done', description: 'Taken after waiting until the target.' },
      { name: 'skipped', description: 'Taken immediately when the target is already in the past.' }
    ],
    output: '`{ waitedMs: number, skipped: boolean, target: string }`.',
    clientEquivalent: 'None.',
    notes: ['Subject to the same 24-hour cap and the same cancellation behaviour as `wait`.']
  }
};

/** Every implemented kind, in catalog order. */
export const STEP_KINDS = Object.keys(STEP_KIND_SPECS) as StepKind[];

export function isStepKind(v: unknown): v is StepKind {
  return typeof v === 'string' && Object.prototype.hasOwnProperty.call(STEP_KIND_SPECS, v);
}

/**
 * The params of a kind that are DSL structures rather than values, and so are
 * NOT resolved by the engine before the step runs (WFA-003). The engine asks
 * this; nothing else needs to know which they are.
 */
export function rawParamNames(kind: StepKind): ReadonlySet<string> {
  const spec = STEP_KIND_SPECS[kind];
  if (!spec) return EMPTY_RAW_PARAMS;
  const cached = RAW_PARAM_CACHE.get(kind);
  if (cached) return cached;
  const names = new Set(spec.params.filter((p) => p.raw).map((p) => p.name));
  RAW_PARAM_CACHE.set(kind, names);
  return names;
}

const EMPTY_RAW_PARAMS: ReadonlySet<string> = new Set();
const RAW_PARAM_CACHE = new Map<StepKind, ReadonlySet<string>>();

/** The wire form served by `GET /admin/workflow-step-kinds` and MCP. */
export interface StepKindCatalog {
  version: string;
  source: string;
  docs: string;
  kinds: StepKindSpec[];
  /**
   * WFA-003: how a param value may reference the run's data. Served alongside
   * the kinds because a client rendering a param editor needs both, and a
   * bundled copy of either could disagree with the backend that will execute it.
   */
  valueLanguage: ValueLanguageSpec;
  /**
   * WFA-004: the closed operator set, with a label per operator and which ones
   * are unary — everything a three-control condition editor needs in order not
   * to hold its own copy of the list.
   */
  conditionLanguage: ConditionLanguageSpec;
}

export function stepKindCatalog(): StepKindCatalog {
  return {
    version: STEP_KIND_CATALOG_VERSION,
    source: 'nodegx-backend/workflow/steps/kinds.ts (WF-002, WFA-003, WFA-004)',
    docs: 'docs/runtime/WORKFLOW-NODES.md',
    kinds: STEP_KINDS.map((k) => STEP_KIND_SPECS[k]),
    valueLanguage: VALUE_LANGUAGE,
    conditionLanguage: CONDITION_LANGUAGE
  };
}

// ---------------------------------------------------------------------------
// Write-time validation
// ---------------------------------------------------------------------------

/** Hard ceiling on any single wait, in ms (24h). See the `wait` spec notes. */
export const MAX_WAIT_MS = 24 * 60 * 60 * 1000;

export const WAIT_UNIT_MS: Record<string, number> = {
  milliseconds: 1,
  seconds: 1000,
  minutes: 60 * 1000,
  hours: 60 * 60 * 1000
};

function params(step: WorkflowStep): Record<string, unknown> {
  return (step.params || {}) as Record<string, unknown>;
}

/** True for `{"$path": …}` / `{"$literal": …}` — a value that is not known yet. */
function isValueSpec(v: unknown): boolean {
  return isPlainObject(v) && (typeof v.$path === 'string' || '$literal' in v);
}

/**
 * CWF-001: the names a kind's param mapping may use.
 *
 * Checked for the kinds that DECLARE a mapping, and only for the params that are
 * not declared by the kind itself — the declared ones are the kind's own
 * vocabulary and are not the author's to collide with. What is deliberately NOT
 * checked is whether a `$path` resolves to anything: a function's output shape is
 * the function's business, which is the same line `validateValueReferences`
 * already draws.
 */
function validateParamMapping(spec: StepKindSpec, p: Record<string, unknown>, at: string): string[] {
  if (!spec.paramMapping) return [];
  const declared = new Set(spec.params.map((param) => param.name));
  const errors: string[] = [];

  for (const key of Object.keys(p)) {
    if (declared.has(key)) continue;
    if (!key.trim()) {
      errors.push(`${at}: a param needs a name — it is what the function reads the value as`);
    } else if (RESERVED_STEP_INPUT_KEYS.has(key)) {
      errors.push(
        `${at}.params.${key}: the engine writes "${key}" into the step input AFTER the params, so this value ` +
          'would be silently discarded. Give it another name.'
      );
    }
  }
  return errors;
}

function requirePositiveNumber(v: unknown, where: string, errors: string[], min = 1): void {
  if (v === undefined) return;
  if (typeof v !== 'number' || !Number.isFinite(v) || v < min) {
    errors.push(`${where} must be a number >= ${min}`);
  }
}

/**
 * Per-kind shape validation, consulted by `validateWorkflowDefinition`. Returns
 * error strings prefixed with the step id; empty means valid.
 *
 * Everything checkable without running is checked HERE, at write time, so a
 * definition that could not possibly work is rejected with a 400 and never
 * persisted — the same doctrine as the graph-level acyclicity check.
 */
export function validateStepShape(step: WorkflowStep): string[] {
  const errors: string[] = [];
  const at = `step "${step.id}"`;
  const spec = STEP_KIND_SPECS[step.kind];
  if (!spec) {
    errors.push(`${at}: unknown kind "${String(step.kind)}" (known: ${STEP_KINDS.join(', ')})`);
    return errors;
  }

  if (spec.invokesFunction && (typeof step.ref !== 'string' || !step.ref)) {
    errors.push(`${at}: kind "${step.kind}" needs a ref (the cloud function name)`);
  }
  if (!spec.invokesFunction && step.ref) {
    errors.push(`${at}: kind "${step.kind}" does not invoke a function — remove "ref"`);
  }

  // WFA-004: the editor's canvas position. Optional and engine-invisible, but
  // checked so a malformed one is a 400 at write time rather than something a
  // canvas has to defend against on every open.
  if (step.ui !== undefined) {
    const ui = step.ui as unknown;
    if (
      !isPlainObject(ui) ||
      typeof ui.x !== 'number' ||
      typeof ui.y !== 'number' ||
      !Number.isFinite(ui.x) ||
      !Number.isFinite(ui.y)
    ) {
      errors.push(`${at}: ui must be { x: number, y: number } (the editor's canvas position)`);
    }
  }

  const p = params(step);
  const routeNames = Object.keys(step.routes || {});

  switch (step.kind) {
    case 'branch': {
      if (p.condition === undefined) errors.push(`${at}: branch needs a "condition" param`);
      else errors.push(...validateCondition(p.condition, `${at}.params.condition`));
      if (routeNames.length === 0) {
        errors.push(`${at}: branch needs at least one of the routes "ontrue" / "onfalse"`);
      }
      for (const r of routeNames) {
        if (r !== 'ontrue' && r !== 'onfalse') errors.push(`${at}: branch route "${r}" must be "ontrue" or "onfalse"`);
      }
      break;
    }

    case 'switch': {
      const cases = p.cases;
      if (!Array.isArray(cases) || cases.length === 0) {
        errors.push(`${at}: switch needs a non-empty "cases" array`);
        break;
      }
      const labels = new Set<string>();
      cases.forEach((c, i) => {
        const where = `${at}.params.cases[${i}]`;
        if (typeof c !== 'object' || c === null) {
          errors.push(`${where}: must be an object`);
          return;
        }
        const label = (c as { label?: unknown }).label;
        if (typeof label !== 'string' || !label) errors.push(`${where}: needs a non-empty string label`);
        else if (label === 'default') errors.push(`${where}: "default" is reserved — it is the no-match route`);
        else if (labels.has(label)) errors.push(`${where}: duplicate case label "${label}"`);
        else labels.add(label);

        const hasEquals = 'equals' in (c as object);
        const hasWhen = 'when' in (c as object);
        if (hasEquals === hasWhen) errors.push(`${where}: needs exactly one of "equals" or "when"`);
        if (hasWhen) errors.push(...validateCondition((c as { when: unknown }).when, `${where}.when`));
      });
      for (const r of routeNames) {
        if (r !== 'default' && !labels.has(r)) {
          errors.push(`${at}: route "${r}" matches no case label (labels: ${[...labels].join(', ') || 'none'})`);
        }
      }
      break;
    }

    case 'for-each': {
      requirePositiveNumber(p.maxIterations, `${at}.params.maxIterations`, errors);
      requirePositiveNumber(p.concurrency, `${at}.params.concurrency`, errors);
      if (p.filter !== undefined) errors.push(...validateCondition(p.filter, `${at}.params.filter`));
      if (p.itemKey !== undefined && typeof p.itemKey !== 'string') errors.push(`${at}.params.itemKey must be a string`);
      if (p.indexKey !== undefined && typeof p.indexKey !== 'string') {
        errors.push(`${at}.params.indexKey must be a string`);
      }
      for (const r of routeNames) {
        if (r !== 'empty' && r !== 'nonempty') errors.push(`${at}: for-each route "${r}" must be "empty" or "nonempty"`);
      }
      break;
    }

    case 'merge': {
      if (p.mode !== undefined && p.mode !== 'all' && p.mode !== 'any') {
        errors.push(`${at}.params.mode must be "all" or "any"`);
      }
      if (p.strategy !== undefined && !['object', 'array', 'shallow'].includes(String(p.strategy))) {
        errors.push(`${at}.params.strategy must be "object", "array" or "shallow"`);
      }
      if (p.sources !== undefined && (!Array.isArray(p.sources) || p.sources.some((s) => typeof s !== 'string'))) {
        errors.push(`${at}.params.sources must be an array of step ids`);
      }
      break;
    }

    case 'retry': {
      requirePositiveNumber(p.maxAttempts, `${at}.params.maxAttempts`, errors);
      requirePositiveNumber(p.delayMs, `${at}.params.delayMs`, errors, 0);
      requirePositiveNumber(p.maxDelayMs, `${at}.params.maxDelayMs`, errors, 0);
      if (p.backoffMultiplier !== undefined && (typeof p.backoffMultiplier !== 'number' || p.backoffMultiplier < 1)) {
        errors.push(`${at}.params.backoffMultiplier must be a number >= 1`);
      }
      if (p.retryOnStatus !== undefined) {
        if (!Array.isArray(p.retryOnStatus) || p.retryOnStatus.some((s) => typeof s !== 'number')) {
          errors.push(`${at}.params.retryOnStatus must be an array of HTTP status numbers`);
        }
      }
      break;
    }

    case 'stop': {
      if (p.message !== undefined && typeof p.message !== 'string') errors.push(`${at}.params.message must be a string`);
      if (p.isError !== undefined && typeof p.isError !== 'boolean') {
        errors.push(`${at}.params.isError must be a boolean`);
      }
      if ((step.next || []).length > 0 && p.isError !== false) {
        errors.push(`${at}: a stop step with isError true can never take "next" — remove the edge or set isError false`);
      }
      break;
    }

    case 'return': {
      // A `return` ends its path, so an outgoing edge is dead wiring — the same
      // class of mistake the `stop`/`isError` rule above catches, and refused
      // for the same reason: it would never be taken and nothing would say so.
      if ((step.next || []).length > 0) {
        errors.push(`${at}: a return step ends its path and can never take "next" — remove the edge`);
      }
      // `value` is deliberately optional and deliberately unconstrained: any
      // JSON, or a `{"$path"}` reference, is a legal thing to hand a caller.
      // The only structural rule is depth, which the generic value walk in
      // validateWorkflowDefinition already enforces.
      break;
    }

    case 'wait': {
      const unit = p.unit === undefined ? 'milliseconds' : String(p.unit);
      if (!WAIT_UNIT_MS[unit]) {
        errors.push(`${at}.params.unit must be one of ${Object.keys(WAIT_UNIT_MS).join(', ')}`);
      }
      // A duration written as a reference cannot be range-checked here — the
      // value does not exist yet. The executor already resolves it and already
      // fails loudly on a non-number and on the 24h cap, so this defers to it
      // rather than rejecting a legal definition. (`WaitStepExecutor` has
      // resolved `duration` since WF-002; write-time validation refused it,
      // which made the feature unreachable.)
      if (isValueSpec(p.duration)) break;
      if (typeof p.duration !== 'number' || !Number.isFinite(p.duration) || p.duration <= 0) {
        errors.push(`${at}.params.duration must be a number > 0`);
      } else if (WAIT_UNIT_MS[unit] && p.duration * WAIT_UNIT_MS[unit] > MAX_WAIT_MS) {
        errors.push(
          `${at}: wait of ${p.duration} ${unit} exceeds the ${MAX_WAIT_MS}ms (24h) cap — use a schedule trigger`
        );
      }
      break;
    }

    case 'wait-until': {
      if (p.target === undefined) errors.push(`${at}: wait-until needs a "target" param`);
      for (const r of routeNames) {
        if (r !== 'done' && r !== 'skipped') errors.push(`${at}: wait-until route "${r}" must be "done" or "skipped"`);
      }
      break;
    }

    case 'call-function': {
      // CWF-001: until this case existed, `call-function` fell through to
      // `default: break` and any params object at all was legal — which was
      // tolerable while no UI could author one, and is not now that the mapping
      // is a declared, documented feature with a row of its own.
      errors.push(...validateParamMapping(spec, p, at));
      break;
    }

    default:
      break;
  }

  // A kind with no routes in its spec must not carry a `routes` object: it
  // would be silently dead wiring (the executor never selects anything), which
  // is exactly the class of mistake SUB-005's enrichment pass exists to catch.
  if (spec.routes.length === 0 && routeNames.length > 0) {
    errors.push(`${at}: kind "${step.kind}" has no routes — use "next" / "onError" edges instead of "routes"`);
  }

  return errors;
}
