import React from 'react';

import type { PreflightSummary } from '@nodegx/export';

/**
 * EXP-012 — the pre-flight, shown before the author picks a folder.
 *
 * Everything here is read off `PreflightSummary`, which is itself read off the export that has
 * already been generated in memory — the numbers are exact, not estimated (P18 §21.2), and this
 * is the same set of facts `EXPORT-REPORT.md` will print once the files are written. The modal
 * decides nothing of its own: it does not re-count, re-classify or re-word the exporter's verdict.
 *
 * Markup and classes follow `ConfirmModal` so the popup layer's existing styles apply.
 */
export interface CodeExportModalProps {
  summary: PreflightSummary;
  onConfirm: () => void;
  onCancel: () => void;
}

function plural(n: number, one: string, many = one + 's'): string {
  return `${n} ${n === 1 ? one : many}`;
}

function backendLine(summary: PreflightSummary): string {
  switch (summary.backend) {
    case 'connected':
      return `Talks to the project's backend at ${summary.backendEndpoint} — its database, cloud functions and sign-in.`;
    case 'stubbed':
      return 'Uses a backend, but none is deployed for this project yet — the data calls are generated against a placeholder address you set in one place.';
    default:
      return 'Uses no backend.';
  }
}

export function CodeExportModal({ summary, onConfirm, onCancel }: CodeExportModalProps) {
  const attention = summary.attention;
  const deferred = summary.noFile.filter((c) => c.kind === 'deferred');

  return (
    <div className="popup confirm-modal" style={{ minWidth: 520, maxWidth: 640 }}>
      <label>Export {summary.projectName} as React code</label>

      <p>
        <strong>Nothing has been written yet.</strong> This is what the export will produce.
      </p>

      <p>
        <strong>{plural(summary.generatedFiles, 'file')}</strong> — {plural(summary.pages, 'page')},{' '}
        {plural(summary.components, 'component')}, plus the app shell, styles and build config
        {summary.copiedAssets > 0 ? `, and ${plural(summary.copiedAssets, 'asset')} copied as-is` : ''}.
        <br />
        {backendLine(summary)}
      </p>

      {summary.refusals === 0 ? (
        <p>
          <strong>Everything translates.</strong> No node, wire or parameter is left out.
        </p>
      ) : (
        <>
          <p>
            <strong>{plural(summary.refusals, 'thing')} will not translate.</strong> Each is a node, wire, parameter
            — or a whole component — the export has no rule for. It is <em>left out</em>, never translated wrongly,
            and the reason for every one is written into the app as <code>EXPORT-REPORT.md</code>.
          </p>
          {(attention.length > 0 || deferred.length > 0) && (
            <p style={{ maxHeight: 160, overflowY: 'auto' }}>
              {attention.map((c) => (
                <span key={c.path} style={{ display: 'block' }}>
                  <code>{c.path}</code> — {plural(c.refusals, 'refusal')}
                  {c.unreachable ? ' (no route reaches it)' : ''}
                </span>
              ))}
              {deferred.map((c) => (
                <span key={c.path} style={{ display: 'block' }}>
                  <code>{c.path}</code> — no file: {c.reason}
                </span>
              ))}
            </p>
          )}
        </>
      )}

      <p>
        Every line is generated by rule and <strong>nothing is run</strong>. The export is one-way: the code will not
        sync back, and exporting again overwrites what you changed.
      </p>

      <div className="confirm-buttons">
        <button
          className="confirm-button"
          data-test="code-export-choose-folder"
          onFocus={(e) => e.currentTarget.blur()}
          onClick={(e) => {
            onConfirm();
            e.stopPropagation();
          }}
        >
          Choose folder and export…
        </button>
        <button
          className="cancel-button"
          onFocus={(e) => e.currentTarget.blur()}
          onClick={(e) => {
            onCancel();
            e.stopPropagation();
          }}
        >
          Cancel
        </button>
      </div>
    </div>
  );
}
