/**
 * SB-017 acceptance 1, the backend-side half — `authored-bundle.ts` loses nothing.
 *
 * The editor's deploy path dropped 51 of 100 cloud connections and shipped a
 * template where every endpoint timed out, while this package's 29-spec
 * publication suite stayed green on the same seven components — because it
 * builds its bundle with `tests/helpers/authored-bundle.ts` rather than the
 * editor's deploy path. Two paths, same graphs, opposite outcomes, and nothing
 * compared them (SB-017 §4).
 *
 * s17 wrote the editor's half (`noodl-editor/tests/cloud/sb017-deploy-connection-parity.test.ts`)
 * and left this one owed, so "editor == helper" was asserted of one side only.
 * This is the other side.
 *
 * ## Both halves compare to the same third thing, and that is not a compromise
 *
 * The two converters **cannot run in one process**. The editor's
 * `exportComponent` reads `node.type.allowAsChild` and `graph.getConnectionHealth`
 * off a live `NodeLibrary`, which is exactly why this helper exists
 * (`authored-bundle.ts`'s own header). So neither can be diffed against the
 * other directly.
 *
 * What they can both be measured against is the **shipped template** —
 * `site-builder.content.json`, generated by `npm run template:site-builder` from
 * the same `SB004_COMPONENTS` this suite authors through the MCP door (SB-007).
 * The editor's half says *the deploy path emits every connection the template
 * holds*; this half says *the helper emits every connection the template holds*.
 * Together they close the claim from both ends, and a failure says which end
 * moved rather than that they disagree.
 *
 * ## 🔴 Counts are not enough, and the editor's half learned that first
 *
 * A converter that reached the right total by re-pointing a wire would satisfy
 * every count and still be wrong. So the comparison is a **multiset of
 * type-qualified wires** — `SourceType.port -> TargetType.port` — for the same
 * two reasons the editor's half gives: ids differ between the two artefacts (a
 * project made from a template gets fresh ones, SB-007 F9), and `claimSite`
 * holds two `Response` nodes, so de-duplicating would forgive a lost wire.
 *
 * ⚠️ **This asserts about connections, which is acceptance 1's subject.** The
 * helper differs from the editor's exporter in three further ways it states in
 * its own header — `roots` is empty, component ports are derived from the
 * interface nodes with the plug inverted, and unhealthy wires are not dropped.
 * The last of those is the *point*: the helper is lossless because it does not
 * filter, and the editor's half is what says the editor no longer needs to.
 */
import { SB004_COMPONENTS } from '../../noodl-mcp/tests/sb004Components';

import { bundleAuthoredComponents } from './helpers/authored-bundle';
import { authorSiteTemplate } from './helpers/site-drive';

/* eslint-disable @typescript-eslint/no-var-requires */
const siteBuilderTemplate = require('../../noodl-editor/src/editor/src/models/template/templates/site-builder.content.json') as {
  components: Array<{
    name: string;
    graph: {
      roots: TemplateNode[];
      connections: Array<{ fromId: string; fromProperty: string; toId: string; toProperty: string }>;
    };
  }>;
};
/* eslint-enable @typescript-eslint/no-var-requires */

interface TemplateNode {
  id: string;
  type: string;
  children?: TemplateNode[];
}

/** Every node in a graph — `children` is a tree. */
function flatten(roots: TemplateNode[], out: TemplateNode[] = []): TemplateNode[] {
  for (const node of roots || []) {
    out.push(node);
    flatten(node.children, out);
  }
  return out;
}

/**
 * A component's connections as a multiset of type-qualified wires.
 *
 * The same identity the editor's half uses, deliberately: two files asserting
 * the same claim about two converters should be comparing the same thing, or a
 * disagreement between them is about the instruments and not the paths.
 */
function wireCounts(
  nodes: TemplateNode[],
  connections: Array<{ source: string; sourcePort: string; target: string; targetPort: string }>
): Record<string, number> {
  const typeOf: Record<string, string> = {};
  flatten(nodes).forEach((node) => (typeOf[node.id] = node.type));

  const counts: Record<string, number> = {};
  for (const c of connections) {
    const key = `${typeOf[c.source]}.${c.sourcePort} -> ${typeOf[c.target]}.${c.targetPort}`;
    counts[key] = (counts[key] ?? 0) + 1;
  }
  return counts;
}

/** The wires `have` is missing relative to `want`, as a flat list. */
function shortfall(want: Record<string, number>, have: Record<string, number>): string[] {
  const missing: string[] = [];
  for (const [wire, n] of Object.entries(want)) {
    for (let i = 0; i < n - (have[wire] ?? 0); i++) missing.push(wire);
  }
  return missing;
}

describe('SB-017 acceptance 1 (backend half): the authored-bundle helper is lossless on connections', () => {
  let bundle: ReturnType<typeof bundleAuthoredComponents>;

  /** The seven cloud components as the shipped template carries them. */
  const templateCloudComponents = siteBuilderTemplate.components.filter((c) => c.name.startsWith('/#__cloud__/'));

  beforeAll(async () => {
    const projectDir = await authorSiteTemplate('sb017-lossless');
    bundle = bundleAuthoredComponents(
      projectDir,
      SB004_COMPONENTS.map((c) => c.key)
    );
  }, 120_000);

  it('measures the same seven components the editor half does', () => {
    // The population control. Both halves have to be about the same graphs, or
    // "editor == helper" is closed over two different sets. Seven is also what
    // SB-017 §10.3's table has a row per.
    expect(templateCloudComponents.map((c) => c.name).sort()).toEqual(
      SB004_COMPONENTS.map((c) => c.legacyName).sort()
    );
    expect(bundle.components.map((c) => c.name).sort()).toEqual(SB004_COMPONENTS.map((c) => c.legacyName).sort());
  });

  it('emits the same number of connections each component holds — per component', () => {
    // Per component and not as a total: a total can be right while two
    // components are wrong in opposite directions.
    const fromTemplate: Record<string, number> = {};
    for (const component of templateCloudComponents) {
      fromTemplate[component.name] = component.graph.connections.length;
    }

    const fromHelper: Record<string, number> = {};
    for (const component of bundle.components) {
      fromHelper[component.name] = component.connections.length;
    }

    expect(fromHelper).toEqual(fromTemplate);

    // And it is the same total the editor's half reaches, so the two ends meet on
    // a number rather than only on a shape.
    //
    // ⚠️ **101 and not s18's 100, and the difference is a template edit, not
    // drift in this converter.** SB-018 (5) replaced `compose.out-built ->
    // res.pm-received` (a signal cast into a value parameter, which answered
    // `{"received": false}` about a stored message) with a `stored` node between
    // `save.done` and `mail.send`: one wire out, three in, net +1 on
    // `submitContactForm`. That component's own count is asserted above, so a
    // future change landing here has to say which component moved.
    //
    // ⚠️ SBR-002's +2 on `Pages/Site` does NOT land here — this population is
    // the seven `/#__cloud__/` components only (the control above pins it), so
    // a browser-side template edit leaves this total alone by design.
    // ⚠️ **118 and not 101, and again it is a template edit rather than converter
    // drift.** SBR-015 gave every cloud endpoint the failure edges it never had —
    // each failure-capable node's `failure` into a `status: 'failure'` Response,
    // plus each Run Tasks' `unchanged`. All four movers, named:
    //
    //   publishPage       +6  (16 → 22) — had NO failure wire at all
    //   duplicatePage     +9  (22 → 31) — had NO failure wire at all
    //   submitContactForm +1  (20 → 21) — `stored` throwing hung the one PUBLIC endpoint
    //   claimSite         +1  (20 → 21) — `gate`'s two custom signals only look exhaustive
    //
    // Before it, publish and duplicate had exactly one way out — the happy path —
    // so any error was a thirty-second timeout with no status and no node named,
    // while claimSite answered in 29ms and was the control that made the
    // difference diagnosable. The three worker components are untouched: they
    // have no Response node and answer through the Run Tasks contract instead.
    expect(fromHelper['/#__cloud__/publishPage']).toBe(22);
    // ⚠️ **32 and not s18's 31 — D24, and again a template edit.** `duplicatePage`
    // ran its `newProps` code node four times per request and wrote a Page row on
    // each, because the write hung off `Record.Fetched` (which fires from the `Id`
    // setter, before any read) and off every value arrival. The repair moved the
    // trigger to the fetch's `Done` outcome and added ONE wire — `source.id ->
    // newProps.in-sourceId`, the readiness value the guard tests. The three
    // `runOnChange-in-*` parameters that came with it are parameters, not wires,
    // so they do not land here.
    expect(fromHelper['/#__cloud__/duplicatePage']).toBe(32);
    expect(fromHelper['/#__cloud__/submitContactForm']).toBe(21);
    expect(fromHelper['/#__cloud__/claimSite']).toBe(21);
    // SBR-007 AC2 adds two components and 24 wires: `reorderSection` (19) and
    // its worker `site/SetSectionOrder` (5). The endpoint is born with its
    // failure edges rather than acquiring them later — SBR-015's rule is a gate
    // now, so the +6/+9 story above is history rather than a pattern to repeat.
    expect(fromHelper['/#__cloud__/reorderSection']).toBe(19);
    expect(fromHelper['/#__cloud__/site/SetSectionOrder']).toBe(5);
    expect(Object.values(fromHelper).reduce((total, n) => total + n, 0)).toBe(143);
  });

  it('loses no wire, and re-points none — asserted as a multiset, not a count', () => {
    // 🔴 The assertion a count cannot make. Shortfall in **both** directions:
    // a wire the template has and the bundle does not is a loss, and a wire the
    // bundle has that the template does not is a wire this converter invented.
    for (const component of templateCloudComponents) {
      const built = bundle.components.find((c) => c.name === component.name);
      expect(built).toBeDefined();

      const inTemplate = wireCounts(
        component.graph.roots,
        component.graph.connections.map((c) => ({
          source: c.fromId,
          sourcePort: c.fromProperty,
          target: c.toId,
          targetPort: c.toProperty
        }))
      );
      const inBundle = wireCounts(
        built!.nodes as TemplateNode[],
        built!.connections.map((c) => ({
          source: c.sourceId,
          sourcePort: c.sourcePort,
          target: c.targetId,
          targetPort: c.targetPort
        }))
      );

      expect({ [component.name]: shortfall(inTemplate, inBundle) }).toEqual({ [component.name]: [] });
      expect({ [component.name]: shortfall(inBundle, inTemplate) }).toEqual({ [component.name]: [] });
    }
  });

  it('carries `claimSite`s starting wire — the one a script-only fix would still lose', () => {
    // SB-017 §6.4's line, asserted on this side too. It is not a duplicate of
    // the editor half's identical case: that one says the *editor* keeps it, and
    // if this helper had ever lacked it, the 29-spec publication suite would have
    // been green on a `claimSite` that could not start either.
    const claimSite = bundle.components.find((c) => c.name === '/#__cloud__/claimSite');
    expect(
      claimSite!.connections.some((c) => c.sourcePort === 'done' && c.targetPort === 'storageFetch')
    ).toBe(true);
  });

  it('🔴 the comparison can fail — a dropped wire is seen', () => {
    // The known-firing control, and this file needs one badly: every assertion
    // above is an equality between two lists, and two lists built by a broken
    // reader agree perfectly when both are empty. Removing one real wire from
    // one component has to be visible, and it has to be visible *as that wire*.
    const claimSite = bundle.components.find((c) => c.name === '/#__cloud__/claimSite')!;
    const template = templateCloudComponents.find((c) => c.name === '/#__cloud__/claimSite')!;

    const inTemplate = wireCounts(
      template.graph.roots,
      template.graph.connections.map((c) => ({
        source: c.fromId,
        sourcePort: c.fromProperty,
        target: c.toId,
        targetPort: c.toProperty
      }))
    );
    const lessOne = wireCounts(
      claimSite.nodes as TemplateNode[],
      claimSite.connections.slice(1).map((c) => ({
        source: c.sourceId,
        sourcePort: c.sourcePort,
        target: c.targetId,
        targetPort: c.targetPort
      }))
    );

    expect(shortfall(inTemplate, lessOne)).toHaveLength(1);
  });
});
