/**
 * POL-006 — **the list**, with nothing else in it.
 *
 * Split out of `starterAssets.ts` by VIB-003 (phase 81) for one reason: this is the only
 * description in the repository of *what a real project has in it that a template directory does
 * not*, and until now the only way to read it was to import a module that reaches
 * `@noodl/platform`. So anything outside Electron — the phase-81 Judge, a script, a spec in
 * another package — had to write the list out again.
 *
 * 🔴 **A second copy of this list is the defect this file exists to prevent.** The copy would be
 * right on the day it was written and wrong the first time a starter module is added, and its
 * failure mode is silent: a harness that installs four of the five things a real project has
 * photographs a project nobody owns and reports nothing. `shareAsTemplate.ts` already derives
 * `SHARED_BY_INSTALLER` from this constant rather than restating it, with the rule written out
 * there; this file is that same argument applied one package wider.
 *
 * Deliberately **import-free**. That is the whole property: a consumer needs no platform, no
 * filesystem and no bundler alias to read it, and can do the copying whichever way suits it.
 * `installStarterAssets` (next door) is the Electron-side one; it is not the only legitimate one.
 *
 * @module noodl-editor/models/template/starterAssetList
 */

/** One file to place, resolved against the app directory and the project directory respectively. */
export interface StarterAsset {
  /** Path under the installed app, e.g. `src/assets/starter-project/...`. */
  from: string;
  /** Project-relative destination, e.g. `noodl_modules/inter/styles.css`. */
  to: string;
}

/** Where the starter tree lives inside the app. `src/assets` is inside electron-builder's allow-list. */
const STARTER_ROOT = 'src/assets/starter-project/';

/**
 * The four Inter weights the shipped element defaults reference, copied from the editor's own
 * bundled Inter rather than duplicated into the starter tree — they are the same files, and two
 * copies in one repo is two copies to keep in step.
 */
const INTER_WEIGHTS = ['Regular', 'Medium', 'SemiBold', 'Bold'];

export const STARTER_ASSETS: readonly StarterAsset[] = [
  // ── Inter ──────────────────────────────────────────────────────────────────
  { from: `${STARTER_ROOT}noodl_modules/inter/manifest.json`, to: 'noodl_modules/inter/manifest.json' },
  { from: `${STARTER_ROOT}noodl_modules/inter/styles.css`, to: 'noodl_modules/inter/styles.css' },
  { from: 'src/assets/Inter/LICENSE.txt', to: 'noodl_modules/inter/LICENSE.txt' },
  ...INTER_WEIGHTS.map((weight) => ({
    from: `src/assets/Inter/Inter-${weight}.ttf`,
    to: `noodl_modules/inter/Inter-${weight}.ttf`
  })),

  // ── Lucide ─────────────────────────────────────────────────────────────────
  // Generated by `scripts/library/make-starter-iconset.js` from the library module. The stylesheet
  // carries a rule for all 1998 glyphs while the manifest lists a curated 212, which is what makes
  // "add any other Lucide icon" one line in the manifest and no new files.
  { from: `${STARTER_ROOT}noodl_modules/lucide-icons/manifest.json`, to: 'noodl_modules/lucide-icons/manifest.json' },
  { from: `${STARTER_ROOT}noodl_modules/lucide-icons/styles.css`, to: 'noodl_modules/lucide-icons/styles.css' },
  { from: `${STARTER_ROOT}noodl_modules/lucide-icons/lucide.woff2`, to: 'noodl_modules/lucide-icons/lucide.woff2' },

  // ── Starter imagery (VIB-003) ──────────────────────────────────────────────
  // The third thing a page needs to stop looking empty, after a typeface and a glyph set.
  // Generated by `scripts/library/make-starter-imagery.js`, which argues the two decisions:
  // abstract because a shipped photograph carries a licence claim this repo cannot check for a
  // reader, and hue-neutral because an `<img src>` SVG is a separate document that cannot read
  // `var(--primary)` — so its colours are frozen at generation time and a branded one would clash
  // the first time somebody switched preset. `backgroundGradient` is the token that re-themes; this
  // is what it paints over. Six files, ~6 KB total.
  //
  // 🔴 A `noodl_modules/` directory rather than loose files under `assets/`, and not for tidiness:
  // that prefix is what `RESTORED_ON_INSTALL` (`shareAsTemplate.ts`) filters on, so putting them
  // anywhere else would have made six pictures travel inside every shared template while the
  // installer put its own copies beside them.
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/manifest.json`, to: 'noodl_modules/starter-imagery/manifest.json' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/ground-aurora.svg`, to: 'noodl_modules/starter-imagery/ground-aurora.svg' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/ground-ridge.svg`, to: 'noodl_modules/starter-imagery/ground-ridge.svg' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/tile-1.svg`, to: 'noodl_modules/starter-imagery/tile-1.svg' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/tile-2.svg`, to: 'noodl_modules/starter-imagery/tile-2.svg' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/tile-3.svg`, to: 'noodl_modules/starter-imagery/tile-3.svg' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/portrait.svg`, to: 'noodl_modules/starter-imagery/portrait.svg' }
];
