/**
 * POL-006 — **the list**, with nothing else in it.
 *
 * Split out of `starterAssets.ts` by VIB-003 (phase 81) for one reason: this is the only
 * description in the repository of *what a real project has in it that a template directory does
 * not*, and until now the only way to read it was to import a module that reaches
 * `@noodl/platform`. So anything outside Electron — the phase-81 Judge, a script, a spec in
 * another package — had to write the list out again.
 *
 * 🔴 **A second copy of this list is the defect this file exists to prevent.** The copy would be
 * right on the day it was written and wrong the first time a starter module is added, and its
 * failure mode is silent: a harness that installs four of the five things a real project has
 * photographs a project nobody owns and reports nothing. `shareAsTemplate.ts` already derives
 * `SHARED_BY_INSTALLER` from this constant rather than restating it, with the rule written out
 * there; this file is that same argument applied one package wider.
 *
 * Deliberately **import-free**. That is the whole property: a consumer needs no platform, no
 * filesystem and no bundler alias to read it, and can do the copying whichever way suits it.
 * `installStarterAssets` (next door) is the Electron-side one; it is not the only legitimate one.
 *
 * @module noodl-editor/models/template/starterAssetList
 */

/** One file to place, resolved against the app directory and the project directory respectively. */
export interface StarterAsset {
  /** Path under the installed app, e.g. `src/assets/starter-project/...`. */
  from: string;
  /** Project-relative destination, e.g. `noodl_modules/inter/styles.css`. */
  to: string;
}

/** Where the starter tree lives inside the app. `src/assets` is inside electron-builder's allow-list. */
const STARTER_ROOT = 'src/assets/starter-project/';

/**
 * The four Inter weights the shipped element defaults reference, copied from the editor's own
 * bundled Inter rather than duplicated into the starter tree — they are the same files, and two
 * copies in one repo is two copies to keep in step.
 */
const INTER_WEIGHTS = ['Regular', 'Medium', 'SemiBold', 'Bold'];

export const STARTER_ASSETS: readonly StarterAsset[] = [
  // ── Inter ──────────────────────────────────────────────────────────────────
  { from: `${STARTER_ROOT}noodl_modules/inter/manifest.json`, to: 'noodl_modules/inter/manifest.json' },
  { from: `${STARTER_ROOT}noodl_modules/inter/styles.css`, to: 'noodl_modules/inter/styles.css' },
  { from: 'src/assets/Inter/LICENSE.txt', to: 'noodl_modules/inter/LICENSE.txt' },
  ...INTER_WEIGHTS.map((weight) => ({
    from: `src/assets/Inter/Inter-${weight}.ttf`,
    to: `noodl_modules/inter/Inter-${weight}.ttf`
  })),

  // ── Lucide ─────────────────────────────────────────────────────────────────
  // Generated by `scripts/library/make-starter-iconset.js` from the library module. The stylesheet
  // carries a rule for all 1998 glyphs while the manifest lists a curated 212, which is what makes
  // "add any other Lucide icon" one line in the manifest and no new files.
  { from: `${STARTER_ROOT}noodl_modules/lucide-icons/manifest.json`, to: 'noodl_modules/lucide-icons/manifest.json' },
  { from: `${STARTER_ROOT}noodl_modules/lucide-icons/styles.css`, to: 'noodl_modules/lucide-icons/styles.css' },
  { from: `${STARTER_ROOT}noodl_modules/lucide-icons/lucide.woff2`, to: 'noodl_modules/lucide-icons/lucide.woff2' },

  // ── Starter imagery (VIB-003) ──────────────────────────────────────────────
  // The third thing a page needs to stop looking empty, after a typeface and a glyph set.
  // Generated by `scripts/library/make-starter-imagery.js`, which argues the two decisions:
  // abstract because a shipped photograph carries a licence claim this repo cannot check for a
  // reader, and hue-neutral because an `<img src>` SVG is a separate document that cannot read
  // `var(--primary)` — so its colours are frozen at generation time and a branded one would clash
  // the first time somebody switched preset. `backgroundGradient` is the token that re-themes; this
  // is what it paints over. Six files, ~6 KB total.
  //
  // 🔴 A `noodl_modules/` directory rather than loose files under `assets/`, and not for tidiness:
  // that prefix is what `RESTORED_ON_INSTALL` (`shareAsTemplate.ts`) filters on, so putting them
  // anywhere else would have made six pictures travel inside every shared template while the
  // installer put its own copies beside them.
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/manifest.json`, to: 'noodl_modules/starter-imagery/manifest.json' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/ground-aurora.svg`, to: 'noodl_modules/starter-imagery/ground-aurora.svg' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/ground-ridge.svg`, to: 'noodl_modules/starter-imagery/ground-ridge.svg' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/tile-1.svg`, to: 'noodl_modules/starter-imagery/tile-1.svg' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/tile-2.svg`, to: 'noodl_modules/starter-imagery/tile-2.svg' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/tile-3.svg`, to: 'noodl_modules/starter-imagery/tile-3.svg' },
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/portrait.svg`, to: 'noodl_modules/starter-imagery/portrait.svg' },

  // ── The stock photograph library (VIB-011) ─────────────────────────────────
  // 44 CC0/public-domain photographs, ~3.4 MB, from `Category:Images from Unsplash` and
  // `Category:Images from Pixabay` on Wikimedia Commons. Built by
  // `scripts/library/make-stock-library.js` from candidates gathered and licence-checked by
  // `scripts/library/fetch-stock-imagery.js`.
  //
  // 🔴 **This supersedes the abstract-SVG decision, not the SVGs.** VIB-003 shipped generated art on
  // a licence argument — *a photograph carries a provenance this repo cannot check on a reader's
  // behalf* — and the argument was right about the risk and wrong about the conclusion: the risk is
  // checkable, per file, and `LICENCES.json` beside these files is that check. The six SVGs stay,
  // because shipped recipes point at them and because an abstract ground is still the honest answer
  // when no photograph would be true about the subject.
  //
  // 🔴 **Free to use is not free to bundle**, which is why the licence class is narrow. This library
  // is redistributed twice — inside the editor, and inside every app a user deploys — and CC0/PD is
  // the only class with no downstream obligation and no restriction on redistributing the images as
  // a collection. `LICENCES.json` is listed first so the record travels with the pictures.
  { from: `${STARTER_ROOT}noodl_modules/starter-imagery/LICENCES.json`, to: 'noodl_modules/starter-imagery/LICENCES.json' },
  // Band grounds and hero media, 1600x900, chosen dark or deep enough to carry display type.
  ...["ground-canyon.webp", "ground-city-dusk.webp", "ground-coast.webp", "ground-dune.webp", "ground-forest-fog.webp", "ground-red-rock.webp", "ground-shore.webp", "ground-skyline.webp"].map((file) => ({
    from: `${STARTER_ROOT}noodl_modules/starter-imagery/${file}`,
    to: `noodl_modules/starter-imagery/${file}`
  })),
  // Surfaces rather than subjects, 1200x675 and deliberately softer — see `ROLES` in the build script.
  ...["texture-brick.webp", "texture-coffee.webp", "texture-earth.webp", "texture-pebbles.webp", "texture-snow.webp", "texture-soil.webp"].map((file) => ({
    from: `${STARTER_ROOT}noodl_modules/starter-imagery/${file}`,
    to: `noodl_modules/starter-imagery/${file}`
  })),
  // Somebody making something. The category that stops a feature row looking like a theme demo.
  ...["work-baker.webp", "work-carpenter.webp", "work-chef.webp", "work-hands-clay.webp", "work-leather-bench.webp", "work-machine-shop.webp", "work-potter.webp", "work-welder.webp"].map((file) => ({
    from: `${STARTER_ROOT}noodl_modules/starter-imagery/${file}`,
    to: `noodl_modules/starter-imagery/${file}`
  })),
  // People at work and in places, 900x675.
  ...["people-cafe.webp", "people-coffee-shop.webp", "people-desk.webp", "people-market.webp", "people-meeting.webp"].map((file) => ({
    from: `${STARTER_ROOT}noodl_modules/starter-imagery/${file}`,
    to: `noodl_modules/starter-imagery/${file}`
  })),
  // Produce, plates and markets, 900x675.
  ...["food-bakery.webp", "food-board.webp", "food-bread.webp", "food-carrots.webp", "food-grocer.webp", "food-market.webp", "food-plate.webp"].map((file) => ({
    from: `${STARTER_ROOT}noodl_modules/starter-imagery/${file}`,
    to: `noodl_modules/starter-imagery/${file}`
  })),
  // Animals, 900x675.
  ...["animal-cat.webp", "animal-dog.webp", "animal-horse.webp", "animal-sheep.webp"].map((file) => ({
    from: `${STARTER_ROOT}noodl_modules/starter-imagery/${file}`,
    to: `noodl_modules/starter-imagery/${file}`
  })),
  // 256px squares framed on the face, for testimonial and comment rows.
  ...["avatar-1.webp", "avatar-2.webp", "avatar-3.webp", "avatar-4.webp", "avatar-5.webp", "avatar-6.webp"].map((file) => ({
    from: `${STARTER_ROOT}noodl_modules/starter-imagery/${file}`,
    to: `noodl_modules/starter-imagery/${file}`
  })),
];
