/**
 * BLD-008 — the interview, on disk.
 *
 * `<project>/.nodegx/review/interview.json`. One per project, beside the
 * conversation `ThreadSidecar` writes to `.nodegx/threads/` and the unapplied
 * build `PlanSessionSidecar` writes to `.nodegx/plan/`, and sharing their rules:
 * created on first write, gitignored on first write, excluded from the deploy
 * walk, never inside the project's own files.
 *
 * ## Why this one is worth a disk at all
 *
 * The store alone already satisfies the written acceptance criterion — it is a
 * singleton, so leaving the panel and coming back resumes at the same question
 * with the answers intact. What it does not survive is ⌘Q, and what is in it is
 * **six paragraphs a person typed about their own project**, which is the single
 * most expensive thing this panel ever holds and the one thing that cannot be
 * regenerated by running something again.
 *
 * ⚠️ This project has lost that exact bet twice: the one-second quit that cost a
 * project save, and `PlanSessionSidecar.flush()` — written for the quit path in
 * AIB-003, never called by anything until BLD-006 found it. So this rides the
 * same `flushAiSidecars` handshake from the start rather than being wired
 * "later", and there is a spec for the flush rather than only for the write.
 *
 * ## JSON, not JSONL
 *
 * The thread is append-only and streams, so a line-per-turn format is right for
 * it. An interview is one small object that is *rewritten* as answers change and
 * re-opened questions delete their answers — an append log of that would need a
 * replay to read, for a file of six answers.
 *
 * @module AiAssistant/review/InterviewSidecar
 */

import { filesystem } from '@noodl/platform';

import { ensureSidecarDirectory, sidecarPath } from '../../../utils/nodegxSidecar';
import type { InterviewAnswer, InterviewQuestion, InterviewState, ProposedDoc } from './interviewState';

const REVIEW_DIR = 'review';
const FILE = 'interview.json';

/** Long enough to coalesce typing, short enough to be there after a crash. */
const WRITE_DEBOUNCE_MS = 750;

/** Bumped when the shape changes in a way an older file cannot be read as. */
export const INTERVIEW_FILE_VERSION = 1;

interface InterviewFile {
  version: number;
  /** Written so a stale file from another project is visible rather than silently adopted. */
  projectId?: string;
  savedAt: string;
  interview: InterviewState;
}

/**
 * Read one back, or nothing.
 *
 * ⚠️ Every failure is `undefined`, never a throw. This file sits in a directory
 * a person can open, and the cost of an unreadable one must be *this interview*,
 * never the panel — the same rule `parseThreadFile` follows one directory over.
 */
export function parseInterviewFile(text: string, projectId?: string): InterviewState | undefined {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return undefined;
  }
  if (!parsed || typeof parsed !== 'object') return undefined;
  const file = parsed as Partial<InterviewFile>;
  if (file.version !== INTERVIEW_FILE_VERSION) return undefined;
  // A saved interview belongs to the project it was about. The id is checked
  // rather than trusted because `.nodegx/` travels with a copied folder.
  if (projectId && file.projectId && file.projectId !== projectId) return undefined;

  const interview = file.interview;
  if (!interview || typeof interview !== 'object') return undefined;
  const questions = Array.isArray(interview.questions) ? interview.questions : [];
  if (questions.length === 0) return undefined;

  const clean: InterviewQuestion[] = [];
  for (const raw of questions) {
    if (!raw || typeof raw !== 'object') continue;
    const question = raw as Partial<InterviewQuestion>;
    if (typeof question.id !== 'string' || typeof question.question !== 'string') continue;
    if (question.docKind !== 'brief' && question.docKind !== 'architecture' && question.docKind !== 'conventions') {
      continue;
    }
    clean.push({
      id: question.id,
      docKind: question.docKind,
      heading: typeof question.heading === 'string' ? question.heading : '',
      question: question.question,
      why: typeof question.why === 'string' ? question.why : '',
      guess: typeof question.guess === 'string' ? question.guess : ''
    });
  }
  if (clean.length === 0) return undefined;

  const answers: Record<string, InterviewAnswer> = {};
  const raw = interview.answers;
  if (raw && typeof raw === 'object') {
    for (const [id, value] of Object.entries(raw as Record<string, unknown>)) {
      if (!value || typeof value !== 'object') continue;
      const answer = value as Partial<InterviewAnswer>;
      if (answer.status === 'answered' && typeof answer.text === 'string' && answer.text.trim()) {
        answers[id] = { status: 'answered', text: answer.text };
      } else if (answer.status === 'skipped') {
        answers[id] = { status: 'skipped' };
      }
      // `pending` is the absence of an entry, so a corrupt one degrades to
      // "not answered yet" — the state that asks again rather than the state
      // that silently drops a question out of the interview.
    }
  }

  return {
    questions: clean,
    answers,
    ...(isProposedDoc(interview.proposedDoc) ? { proposedDoc: interview.proposedDoc } : {}),
    ...(typeof interview.proposalAccepted === 'boolean' ? { proposalAccepted: interview.proposalAccepted } : {})
  };
}

function isProposedDoc(value: unknown): value is ProposedDoc {
  if (!value || typeof value !== 'object') return false;
  const doc = value as Partial<ProposedDoc>;
  return (
    typeof doc.path === 'string' &&
    doc.path.startsWith('docs/') &&
    typeof doc.title === 'string' &&
    typeof doc.purpose === 'string' &&
    (doc.inject === 'always' || doc.inject === 'pull')
  );
}

export function serialiseInterview(interview: InterviewState, projectId: string | undefined, savedAt: string): string {
  const file: InterviewFile = {
    version: INTERVIEW_FILE_VERSION,
    ...(projectId ? { projectId } : {}),
    savedAt,
    interview
  };
  return `${JSON.stringify(file, null, 2)}\n`;
}

export class InterviewSidecar {
  static instance = new InterviewSidecar();

  private pending:
    | { projectDirectory: string; projectId: string | undefined; interview: InterviewState }
    | undefined;
  private timer: ReturnType<typeof setTimeout> | undefined;
  private queue: Promise<unknown> = Promise.resolve();

  async read(projectDirectory: string, projectId?: string): Promise<InterviewState | undefined> {
    const path = this.path(projectDirectory);
    if (!filesystem.exists(path)) return undefined;
    try {
      return parseInterviewFile(await filesystem.readFile(path), projectId);
    } catch (error) {
      console.warn('Could not read the saved docs interview, starting fresh:', error);
      return undefined;
    }
  }

  write(projectDirectory: string, interview: InterviewState, projectId?: string): void {
    this.pending = { projectDirectory, projectId, interview };
    this.schedule();
  }

  /** Remove it — the interview finished, or the user started another. */
  async remove(projectDirectory: string): Promise<void> {
    this.pending = undefined;
    const path = this.path(projectDirectory);
    if (!filesystem.exists(path)) return;
    try {
      await filesystem.removeFile(path);
    } catch (error) {
      console.warn('Could not remove the saved docs interview:', error);
    }
  }

  /** Write anything outstanding now. For the quit path, and for tests. */
  async flush(): Promise<void> {
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = undefined;
    }
    this.drain();
    await this.queue;
  }

  private schedule(): void {
    if (this.timer) return;
    this.timer = setTimeout(() => {
      this.timer = undefined;
      this.drain();
    }, WRITE_DEBOUNCE_MS);
  }

  private drain(): void {
    const pending = this.pending;
    if (!pending) return;
    this.pending = undefined;
    this.enqueue(() => this.persist(pending.projectDirectory, pending.projectId, pending.interview));
  }

  private enqueue(work: () => Promise<void>): void {
    this.queue = this.queue.then(work, work).catch(() => undefined);
  }

  private async persist(
    projectDirectory: string,
    projectId: string | undefined,
    interview: InterviewState
  ): Promise<void> {
    try {
      const directory = await ensureSidecarDirectory(projectDirectory, REVIEW_DIR);
      if (!directory) return;
      await filesystem.writeFileOverride(
        this.path(projectDirectory),
        serialiseInterview(interview, projectId, new Date().toISOString())
      );
    } catch (error) {
      // Losing this loses a restart's worth of answers; throwing here would
      // reach a React state update in the panel.
      console.warn('Could not save the docs interview:', error);
    }
  }

  private path(projectDirectory: string): string {
    return sidecarPath(projectDirectory, REVIEW_DIR, FILE);
  }
}
