/**
 * `src/lib/animate.ts` — the animation pair's frame engine, emitted into the app (EXP-011 §49).
 *
 * The same shape as {@link ./timerLib.ts}: constant text, shipped only where a component calls into
 * it, a fifth module rather than a section of `timer.ts` because an app with a countdown should
 * not ship a tween engine. `states.ts` ({@link ./statesLib.ts}) imports this one.
 *
 * It is a transcription of four things the interpreter runs:
 *
 * - `noodl-runtime/src/timerscheduler.ts` — one timer with repeat count 1: `start()` queues it, it
 *   **joins at the end of the next frame** with `_start = frameTime + delay` (a zero delay plays
 *   `onStart` + `onRunning(0)` in that frame), each later frame at or after `_start` computes
 *   `t = (now − _start) / duration` (`1` when the duration is 0), calls `onRunning(min(t, 1))`, and
 *   at `t ≥ 1` calls `onFinish`. `stop()` fires nothing; `start()` on a running timer stops it first.
 * - `noodl-viewer-react/src/easecurves.ts` — start/end baked into every curve, so callers pass the
 *   endpoints. The four names the picker offers, with `easeIn`/`easeOut`/`easeInOut` aliased onto
 *   the cubic variants exactly as that file does.
 * - `bezier-easing` 1.1.1 — the solver behind a States transition's `curve: [x1, y1, x2, y2]`,
 *   transcribed with its constants (four Newton iterations, the eleven-sample table, the
 *   subdivision fallback) so the two worlds put the same value on the same frame.
 * - `noodl-viewer-react/src/nodes/std-library/animate-to-value.ts` — the first target is adopted
 *   outright, a target equal to the current end is ignored, anything else tweens from wherever the
 *   value is; booleans are 1/0 and a NaN is ignored; `At Target Value` fires on finish only.
 *
 * ⚠️ **One liberty, recorded.** The frame clock is `requestAnimationFrame`'s timestamp here and the
 * viewer's frame callback there; both are monotonic milliseconds advanced by the host once per
 * frame, and nothing an author can wire observes which.
 */

/** Where the module lands in the exported app. */
export const ANIMATE_LIB_PATH = 'src/lib/animate.ts';

/** The exported helpers a component imports. Sorted — the import list is sorted too. */
export const ANIMATE_HELPERS = ['useAnimatedValue'] as const;

/** The easing names the node's enum offers — `easecurves.ts`'s aliases, in the picker's order. */
export const ANIMATE_EASE_NAMES = ['easeOut', 'easeIn', 'linear', 'easeInOut'] as const;
export type AnimateEaseName = (typeof ANIMATE_EASE_NAMES)[number];

/**
 * The module's source.
 *
 * ⚠️ A plain string rather than a template literal, for `dateLib.ts`'s stated reason: the emitted
 * body needs no interpolation, and keeping it out of an interpolation context means a future edit
 * cannot accidentally interpolate the generator's own scope into the exported app.
 */
export function animateLibSource(): string {
  return [
    '//',
    "// The animation pair's frame engine, transcribed from the interpreter it has to agree with:",
    '// noodl-runtime/src/timerscheduler.ts (one timer, repeat count 1), noodl-viewer-react/src/easecurves.ts,',
    "// bezier-easing 1.1.1 (a States transition's curve) and",
    '// noodl-viewer-react/src/nodes/std-library/animate-to-value.ts.',
    '//',
    '// A run joins on the frame after it starts, with its start instant that frame plus the delay (a zero',
    '// delay plays the first frame at once); every later frame at or after the start computes t over the',
    '// duration, publishes the eased position, and finishes at t = 1. A stopped run publishes nothing more.',
    '//',
    '',
    "import { useEffect, useRef, useState } from 'react';",
    '',
    '// ---- easecurves.ts — start and end baked into the curve, so callers pass the endpoints ----------',
    '',
    'export type Ease = (start: number, end: number, t: number) => number;',
    "export type EaseName = 'linear' | 'easeIn' | 'easeOut' | 'easeInOut';",
    '',
    'export const eases: Record<EaseName, Ease> = {',
    '  linear: (start, end, t) => start + (end - start) * t,',
    '  // easeInCubic',
    '  easeIn: (start, end, t) => (end - start) * (t * t * t) + start,',
    '  // easeOutCubic',
    '  easeOut: (start, end, t) => {',
    '    t--;',
    '    return (end - start) * (t * t * t + 1.0) + start;',
    '  },',
    '  // easeInOutCubic',
    '  easeInOut: (start, end, t) => {',
    '    t *= 2.0;',
    '    if (t < 1.0) return ((end - start) / 2.0) * t * t * t + start;',
    '    t -= 2.0;',
    '    return ((end - start) / 2.0) * (t * t * t + 2.0) + start;',
    '  }',
    '};',
    '',
    '// ---- bezier-easing 1.1.1 — `BezierEasing(points).get(x)`, with its constants ----------------------',
    '',
    'const NEWTON_ITERATIONS = 4;',
    'const NEWTON_MIN_SLOPE = 0.001;',
    'const SUBDIVISION_PRECISION = 0.0000001;',
    'const SUBDIVISION_MAX_ITERATIONS = 10;',
    'const SPLINE_TABLE_SIZE = 11;',
    'const SAMPLE_STEP_SIZE = 1.0 / (SPLINE_TABLE_SIZE - 1.0);',
    '',
    'const A = (a1: number, a2: number): number => 1.0 - 3.0 * a2 + 3.0 * a1;',
    'const B = (a1: number, a2: number): number => 3.0 * a2 - 6.0 * a1;',
    'const C = (a1: number): number => 3.0 * a1;',
    'const calcBezier = (t: number, a1: number, a2: number): number => ((A(a1, a2) * t + B(a1, a2)) * t + C(a1)) * t;',
    'const getSlope = (t: number, a1: number, a2: number): number => 3.0 * A(a1, a2) * t * t + 2.0 * B(a1, a2) * t + C(a1);',
    '',
    'function binarySubdivide(aX: number, aA: number, aB: number, mX1: number, mX2: number): number {',
    '  let currentX: number;',
    '  let currentT: number;',
    '  let i = 0;',
    '  do {',
    '    currentT = aA + (aB - aA) / 2.0;',
    '    currentX = calcBezier(currentT, mX1, mX2) - aX;',
    '    if (currentX > 0.0) aB = currentT;',
    '    else aA = currentT;',
    '  } while (Math.abs(currentX) > SUBDIVISION_PRECISION && ++i < SUBDIVISION_MAX_ITERATIONS);',
    '  return currentT;',
    '}',
    '',
    'function newtonRaphsonIterate(aX: number, aGuessT: number, mX1: number, mX2: number): number {',
    '  for (let i = 0; i < NEWTON_ITERATIONS; ++i) {',
    '    const currentSlope = getSlope(aGuessT, mX1, mX2);',
    '    if (currentSlope === 0.0) return aGuessT;',
    '    const currentX = calcBezier(aGuessT, mX1, mX2) - aX;',
    '    aGuessT -= currentX / currentSlope;',
    '  }',
    '  return aGuessT;',
    '}',
    '',
    '/** The curve `[x1, y1, x2, y2]` as the function `x → y` the interpreter calls `.get(x)` on. */',
    'export function cubicBezier(points: readonly number[]): (x: number) => number {',
    '  const [mX1, mY1, mX2, mY2] = points;',
    '  const samples = new Float32Array(SPLINE_TABLE_SIZE);',
    '  const linear = mX1 === mY1 && mX2 === mY2;',
    '  if (!linear) for (let i = 0; i < SPLINE_TABLE_SIZE; ++i) samples[i] = calcBezier(i * SAMPLE_STEP_SIZE, mX1, mX2);',
    '  const getTForX = (aX: number): number => {',
    '    let intervalStart = 0.0;',
    '    let currentSample = 1;',
    '    const lastSample = SPLINE_TABLE_SIZE - 1;',
    '    for (; currentSample !== lastSample && samples[currentSample] <= aX; ++currentSample) intervalStart += SAMPLE_STEP_SIZE;',
    '    --currentSample;',
    '    const dist = (aX - samples[currentSample]) / (samples[currentSample + 1] - samples[currentSample]);',
    '    const guessForT = intervalStart + dist * SAMPLE_STEP_SIZE;',
    '    const initialSlope = getSlope(guessForT, mX1, mX2);',
    '    if (initialSlope >= NEWTON_MIN_SLOPE) return newtonRaphsonIterate(aX, guessForT, mX1, mX2);',
    '    if (initialSlope === 0.0) return guessForT;',
    '    return binarySubdivide(aX, intervalStart, intervalStart + SAMPLE_STEP_SIZE, mX1, mX2);',
    '  };',
    '  return (x: number): number => {',
    '    if (linear) return x;',
    '    // Because JavaScript numbers are imprecise, the extremes are guaranteed.',
    '    if (x === 0) return 0;',
    '    if (x === 1) return 1;',
    '    return calcBezier(getTForX(x), mY1, mY2);',
    '  };',
    '}',
    '',
    '// ---- timerscheduler.ts — one timer, repeat count 1 ---------------------------------------------',
    '',
    '/** A frame-driven run: the scheduler\'s timer, with its bookkeeping (`_start`, `_isRunning`, `_hasCalledOnStart`). */',
    'export interface Run {',
    '  duration: number;',
    '  delay: number;',
    '  onStart?: () => void;',
    '  onRunning?: (t: number) => void;',
    '  onFinish?: () => void;',
    '  startAt: number | null;',
    '  running: boolean;',
    '  started: boolean;',
    '  /** Queued by `start`, joining on the next frame — `newTimers` in the scheduler. */',
    '  queued: boolean;',
    '  frame: number | null;',
    '}',
    '',
    'export function createRun(duration: number, delay: number): Run {',
    '  return { duration, delay, startAt: null, running: false, started: false, queued: false, frame: null };',
    '}',
    '',
    "const requestFrame = (callback: (now: number) => void): number =>",
    "  typeof requestAnimationFrame === 'function'",
    '    ? requestAnimationFrame(callback)',
    '    : (setTimeout(() => callback(Date.now()), 16) as unknown as number);',
    'const cancelFrame = (frame: number): void => {',
    "  if (typeof cancelAnimationFrame === 'function') cancelAnimationFrame(frame);",
    '  else clearTimeout(frame as unknown as ReturnType<typeof setTimeout>);',
    '};',
    '',
    '/** `Timer.start`: a running run is stopped first; the run then joins on the next frame (`scheduleTimer`). */',
    'export function startRun(run: Run): void {',
    '  if (run.queued) return;',
    '  if (run.running) stopRun(run);',
    '  run.queued = true;',
    '  run.frame = requestFrame((now) => runFrame(run, now));',
    '}',
    '',
    '/** `Timer.stop`: nothing fires for a stopped run — not `onFinish`, not another frame. */',
    'export function stopRun(run: Run): void {',
    '  if (run.frame !== null) cancelFrame(run.frame);',
    '  run.frame = null;',
    '  run.queued = false;',
    '  run.running = false;',
    '  run.started = false;',
    '}',
    '',
    '/**',
    ' * One scheduler frame for this run at instant `now` — `runTimers`, for a single timer. Exported so a',
    ' * test can drive it at chosen instants; the app drives it from the frame callback.',
    ' */',
    'export function runFrame(run: Run, now: number): void {',
    '  run.frame = null;',
    '  if (run.queued) {',
    '    // Joins at the end of the frame it was queued for: `_start = currentTime + delay`, and a zero',
    '    // delay plays the first frame directly "to keep everything nicely synched".',
    '    run.queued = false;',
    '    run.running = true;',
    '    run.startAt = now + run.delay;',
    '    if (run.delay === 0) {',
    '      run.onStart?.();',
    '      run.started = true;',
    '      run.onRunning?.(0);',
    '    }',
    '    run.frame = requestFrame((next) => runFrame(run, next));',
    '    return;',
    '  }',
    '  if (!run.running || run.startAt === null) return;',
    '  if (now >= run.startAt) {',
    '    if (!run.started) {',
    '      run.onStart?.();',
    '      run.started = true;',
    '    }',
    '    const t = run.duration > 0 ? (now - run.startAt) / run.duration : 1.0;',
    '    run.onRunning?.(t >= 1.0 ? 1.0 : t);',
    '    if (t >= 1.0) {',
    '      run.running = false;',
    '      run.started = false;',
    '      run.onFinish?.();',
    '      return;',
    '    }',
    '  }',
    '  run.frame = requestFrame((next) => runFrame(run, next));',
    '}',
    '',
    '// ---- animate-to-value.ts ---------------------------------------------------------------------------',
    '',
    '/** The node\'s `_internal`: the current number, whether a first target has arrived, the tween\'s endpoints. */',
    'export interface AnimatedValue {',
    '  run: Run;',
    '  current: number;',
    '  initialized: boolean;',
    '  start: number;',
    '  end: number;',
    '  ease: Ease;',
    '}',
    '',
    '/** `targetValue.set`\'s coercion: booleans are 1/0, anything else goes through `Number`, a NaN is ignored. */',
    'function numericTarget(target: unknown): number {',
    '  if (target === true) return 1;',
    '  if (target === false) return 0;',
    '  return Number(target);',
    '}',
    '',
    '/** `initialize` plus the first arrival: a numeric first target is adopted outright; anything else leaves 0. */',
    'export function createAnimatedValue(target: unknown, duration = 300, delay = 0, ease: Ease = eases.easeOut): AnimatedValue {',
    '  const anim: AnimatedValue = { run: createRun(duration, delay), current: 0, initialized: false, start: 0, end: 0, ease };',
    '  const numeric = numericTarget(target);',
    '  if (!Number.isNaN(numeric)) {',
    '    anim.current = numeric;',
    '    anim.initialized = true;',
    '    anim.end = numeric;',
    '  }',
    '  return anim;',
    '}',
    '',
    '/**',
    ' * `targetValue.set`: the first target is adopted outright and published; a target equal to the current',
    ' * end is ignored; anything else tweens from wherever the value is. `publish` is called every frame with',
    ' * the eased value and `onArrive` when the tween settles — never when a new target interrupted it.',
    ' */',
    'export function animateTo(anim: AnimatedValue, target: unknown, publish: (value: number) => void, onArrive?: () => void): void {',
    '  const numeric = numericTarget(target);',
    '  if (Number.isNaN(numeric)) return;',
    '  if (!anim.initialized) {',
    '    anim.current = numeric;',
    '    anim.initialized = true;',
    '    anim.end = numeric;',
    '    publish(numeric);',
    '    return;',
    '  }',
    '  if (numeric === anim.end) return;',
    '  anim.start = anim.current;',
    '  anim.end = numeric;',
    '  anim.run.onRunning = (t) => {',
    '    anim.current = anim.ease(anim.start, anim.end, t);',
    '    publish(anim.current);',
    '  };',
    '  anim.run.onFinish = () => onArrive?.();',
    '  startRun(anim.run);',
    '}',
    '',
    '/**',
    ' * An `Animate To Value` node: the number it publishes, moving towards `target` over `duration` after',
    ' * `delay` along `ease`, with `onArrive` as its At Target Value. The engine lives in a ref and dies',
    ' * with the component (`addDeleteListener` in the node).',
    ' */',
    'export function useAnimatedValue(',
    '  target: unknown,',
    '  options: { duration: number; delay: number; ease: EaseName },',
    '  onArrive?: () => void',
    '): number {',
    '  const animRef = useRef<AnimatedValue | null>(null);',
    '  if (animRef.current === null) animRef.current = createAnimatedValue(target, options.duration, options.delay, eases[options.ease]);',
    '  const anim = animRef.current;',
    '  const [value, setValue] = useState<number>(anim.current);',
    '  const arrive = useRef(onArrive);',
    '  arrive.current = onArrive;',
    '  useEffect(() => {',
    '    // The three parameters are input setters on the node: whatever they hold when a target arrives is what the tween uses.',
    '    anim.run.duration = options.duration;',
    '    anim.run.delay = options.delay;',
    '    anim.ease = eases[options.ease];',
    '    animateTo(anim, target, setValue, () => arrive.current?.());',
    '  }, [anim, target, options.duration, options.delay, options.ease]);',
    '  useEffect(() => () => stopRun(anim.run), [anim]);',
    '  return value;',
    '}',
    ''
  ].join('\n');
}
