/**
 * `src/lib/date.ts` — the date family's arithmetic, emitted into the app (EXP-011 Tier 1.3).
 *
 * Unlike `src/api/http.ts`, which is generated per node from a configuration, this module is the
 * **same text in every project**: the five pure date nodes are one function each, and what varies
 * between two projects using them is only the arguments at the call site. So it is a constant
 * here rather than a builder, and it ships only where something calls into it.
 *
 * It is a transcription of two runtime files, and the transcription is the whole job:
 *
 * - `noodl-runtime/src/nodes/std-library/date/datemath.ts` — `toDate`, `addToDate`,
 *   `differenceBetween`, `truncateTo`, `isoWeek`. The clamping rule and the whole-calendar-step
 *   rule live there and are reproduced exactly, comments included, because both are answers the
 *   author has already seen in the interpreter.
 * - `noodl-runtime/src/nodes/std-library/datetostring.ts` — `_format` and `fieldsInZone`.
 *
 * 🔴 **`Date To String` reads its input differently from the other four, and that is faithful.**
 * It predates `datemath.ts` (its own module comment calls itself "the whole date vocabulary
 * before this task") and its setter is `typeof value === 'string' ? new Date(value) : value` —
 * so a millisecond **number** is passed through unconverted, `getDate()` throws on it, and the
 * node's own catch turns that into a blank. The other four go through `toDate`, which reads a
 * number as epoch milliseconds. Normalising the two would "fix" a blank an author has already
 * worked around.
 *
 * ⚠️ **These functions are pure; the nodes are not.** A node holds its last answer, and when its
 * Date input goes from a value to *unset* the interpreter abstains (`_recompute` returns early on
 * `inputSupplied === false`) and keeps the previous answer, where this returns `undefined`. The
 * divergence is one transition wide, it only exists for a wired input that can deliver empty, and
 * the planner reports it where the wire can actually do that. Note that the interpreter is
 * already inconsistent with itself here: an *invalid* date clears the answer, an *absent* one
 * does not — and the pure form matches the invalid-date branch.
 */

/** Where the module lands in the exported app. */
export const DATE_LIB_PATH = 'src/lib/date.ts';

/** The exported helpers, one per translated date node. Sorted — the import list is sorted too. */
export const DATE_HELPERS = ['dateAdd', 'dateCompare', 'dateDifference', 'datePart', 'dateToString'] as const;

export type DateHelper = (typeof DATE_HELPERS)[number];

/**
 * The module's source.
 *
 * ⚠️ Written as a plain string rather than a template literal: the emitted body contains `${`
 * nowhere by design (the runtime's one template literal is a `throw` this transcription does not
 * reproduce — see `addToDate` below), and keeping it out of an interpolation context means a
 * future edit cannot accidentally interpolate the generator's own scope into the exported app.
 */
export function dateLibSource(): string {
  return [
    '//',
    '// The date vocabulary, transcribed from the interpreter it has to agree with:',
    '// noodl-runtime/src/nodes/std-library/date/datemath.ts and .../datetostring.ts.',
    '//',
    '// Every rule below is one an author has already seen answered in the editor. The two worth',
    '// reading before changing anything are the CLAMP in addToDate and the whole-calendar-step',
    '// trim in differenceBetween.',
    '//',
    '',
    "/** The units the date nodes offer. Fixed-length ones are exact; months and years are calendar steps. */",
    "export type DateUnit = 'milliseconds' | 'seconds' | 'minutes' | 'hours' | 'days' | 'weeks' | 'months' | 'years';",
    '',
    "/** Granularities Date Compare truncates to before comparing. */",
    "export type CompareGranularity = 'millisecond' | 'second' | 'minute' | 'hour' | 'day' | 'month' | 'year';",
    '',
    "/** The fields Date Parts reads off an instant. */",
    'export type DatePartName =',
    "  | 'year'",
    "  | 'month'",
    "  | 'date'",
    "  | 'hours'",
    "  | 'minutes'",
    "  | 'seconds'",
    "  | 'milliseconds'",
    "  | 'dayOfWeek'",
    "  | 'dayName'",
    "  | 'isoWeek'",
    "  | 'timestamp';",
    '',
    '/** Fixed-length units, in milliseconds. `months` and `years` are deliberately absent. */',
    'const FIXED_MS: Partial<Record<DateUnit, number>> = {',
    '  milliseconds: 1,',
    '  seconds: 1000,',
    '  minutes: 60 * 1000,',
    '  hours: 60 * 60 * 1000,',
    '  days: 24 * 60 * 60 * 1000,',
    '  weeks: 7 * 24 * 60 * 60 * 1000',
    '};',
    '',
    "const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];",
    '',
    '/**',
    ' * Read anything a port might carry as a Date, or undefined when it cannot be read.',
    ' *',
    ' * A string is parsed, and a number is epoch milliseconds — because a JSON round trip through a',
    ' * request turns a Date into a string and a timestamp column turns it into a number, and a date',
    ' * family that only worked while the value never left the graph would be half a family.',
    ' */',
    'export function toDate(value: unknown): Date | undefined {',
    "  if (value === undefined || value === null || value === '') return undefined;",
    '  if (value instanceof Date) return Number.isNaN(value.getTime()) ? undefined : value;',
    "  if (typeof value === 'number') {",
    '    if (!Number.isFinite(value)) return undefined;',
    '    const fromNumber = new Date(value);',
    '    return Number.isNaN(fromNumber.getTime()) ? undefined : fromNumber;',
    '  }',
    "  if (typeof value === 'string') {",
    '    const parsed = new Date(value);',
    '    return Number.isNaN(parsed.getTime()) ? undefined : parsed;',
    '  }',
    '  return undefined;',
    '}',
    '',
    '/**',
    ' * `date` plus `amount` of `unit`.',
    ' *',
    ' * 🔴 MONTHS AND YEARS CLAMP. THEY DO NOT OVERFLOW. "Add 1 month to 31 January" is 28 February',
    ' * (29 in a leap year), not 2 or 3 March. Both answers are defensible and the classic date bug is',
    ' * not knowing which one you have, so it is written here as well as on the node.',
    ' *',
    ' * (The interpreter throws on a unit it does not know; this returns undefined instead, which',
    ' * lands in the same place every other unreadable input does. The enum makes it unreachable.)',
    ' */',
    'export function addToDate(date: Date, amount: number, unit: DateUnit): Date | undefined {',
    '  const fixed = FIXED_MS[unit];',
    '  if (fixed !== undefined) return new Date(date.getTime() + amount * fixed);',
    '',
    '  const whole = Math.trunc(amount);',
    '  const result = new Date(date.getTime());',
    '  const dayOfMonth = result.getDate();',
    '',
    '  // Move to the 1st before shifting the month, so the shift itself can never roll over: setting',
    '  // month 0 (January) on the 31st would otherwise land in March all by itself.',
    '  result.setDate(1);',
    "  if (unit === 'months') result.setMonth(result.getMonth() + whole);",
    "  else if (unit === 'years') result.setFullYear(result.getFullYear() + whole);",
    '  else return undefined;',
    '',
    '  const lastDayOfTargetMonth = new Date(result.getFullYear(), result.getMonth() + 1, 0).getDate();',
    '  result.setDate(Math.min(dayOfMonth, lastDayOfTargetMonth));',
    '  return result;',
    '}',
    '',
    '/**',
    ' * How much of `unit` separates `from` and `to` — positive when `to` is later.',
    ' *',
    ' * Fixed units divide exactly and are returned UNROUNDED, so 36 hours is 1.5 days. Months and',
    ' * years are counted in whole calendar steps, because "2.4 months" is not a quantity anyone can',
    ' * check: the answer is the number of whole months you could add without overshooting.',
    ' */',
    'export function differenceBetween(from: Date, to: Date, unit: DateUnit): number {',
    '  const fixed = FIXED_MS[unit];',
    '  if (fixed !== undefined) return (to.getTime() - from.getTime()) / fixed;',
    '',
    '  const sign = to.getTime() >= from.getTime() ? 1 : -1;',
    '  const monthsApart = (to.getFullYear() - from.getFullYear()) * 12 + (to.getMonth() - from.getMonth());',
    '',
    '  // Trim the last step when it overshoots. The invariant this keeps is the one that matters:',
    '  // addToDate(from, differenceBetween(from, to, unit), unit) never lands past `to`. So',
    '  // 31 Jan -> 28 Feb is 1 month (clamping puts Add(31 Jan, 1 month) exactly on 28 Feb), and',
    '  // 31 Jan -> 27 Feb is 0 (it would overshoot).',
    '  let whole = monthsApart;',
    "  const stepped = (n: number) => addToDate(from, n, 'months');",
    '  const over = stepped(whole);',
    '  if (sign > 0 && over !== undefined && over.getTime() > to.getTime()) whole -= 1;',
    '  if (sign < 0 && over !== undefined && over.getTime() < to.getTime()) whole += 1;',
    '',
    "  return unit === 'months' ? whole : Math.trunc(whole / 12);",
    '}',
    '',
    '/**',
    " * Truncate a date to a granularity, in the HOST'S LOCAL ZONE.",
    ' *',
    ' * Local rather than UTC because "the same day" is a question about a calendar somebody is',
    ' * looking at. On a server that calendar is whatever the container says its zone is.',
    ' */',
    'export function truncateTo(date: Date, granularity: CompareGranularity): number {',
    '  const d = new Date(date.getTime());',
    '  switch (granularity) {',
    "    case 'year':",
    '      d.setMonth(0);',
    '    // falls through',
    "    case 'month':",
    '      d.setDate(1);',
    '    // falls through',
    "    case 'day':",
    '      d.setHours(0);',
    '    // falls through',
    "    case 'hour':",
    '      d.setMinutes(0);',
    '    // falls through',
    "    case 'minute':",
    '      d.setSeconds(0);',
    '    // falls through',
    "    case 'second':",
    '      d.setMilliseconds(0);',
    '      break;',
    "    case 'millisecond':",
    '      break;',
    '  }',
    '  return d.getTime();',
    '}',
    '',
    '/** ISO week number (1-53), ISO-8601: weeks start Monday and week 1 holds the first Thursday. */',
    'export function isoWeek(date: Date): number {',
    '  const d = new Date(date.getFullYear(), date.getMonth(), date.getDate());',
    '  // Thursday of this ISO week decides which year the week belongs to.',
    '  d.setDate(d.getDate() + 3 - ((d.getDay() + 6) % 7));',
    '  const firstThursday = new Date(d.getFullYear(), 0, 4);',
    '  firstThursday.setDate(firstThursday.getDate() + 3 - ((firstThursday.getDay() + 6) % 7));',
    '  return 1 + Math.round((d.getTime() - firstThursday.getTime()) / (7 * 24 * 60 * 60 * 1000));',
    '}',
    '',
    '// ---- the five nodes ---------------------------------------------------------------------',
    '',
    '//',
    '// ⚠️ Every VALUE parameter below is `unknown`, and the coercion inside each one is the',
    '// interpreter\'s own setter. Two reasons, and both are load-bearing: a wired input can carry',
    '// any type, so a narrower parameter would make the exported app fail to build on a graph the',
    '// editor allows; and the coercions are behaviour (Number(amount), !!absolute, a format that is',
    '// not a string throwing into the catch), not tidying. The CONFIG parameters — unit,',
    '// granularity, part, answer — stay narrow, because the planner emits them as literals only.',
    '//',
    '',
    '/** Date Add — a date shifted by an amount of a unit. Undefined where the date could not be read. */',
    'export function dateAdd(value: unknown, amount: unknown, unit: DateUnit): Date | undefined {',
    '  const input = toDate(value);',
    '  if (input === undefined) return undefined;',
    '  // The setter is `Number(value)`, and `_recompute` reads a non-finite Amount as 0 rather',
    '  // than letting NaN through into the arithmetic.',
    '  const n = Number(amount);',
    '  return addToDate(input, Number.isFinite(n) ? n : 0, unit);',
    '}',
    '',
    '/** Date Difference — To minus From, counted in Unit, signed unless Absolute. */',
    'export function dateDifference(',
    '  fromValue: unknown,',
    '  toValue: unknown,',
    '  unit: DateUnit,',
    '  absolute: unknown',
    '): number | undefined {',
    '  const from = toDate(fromValue);',
    '  const to = toDate(toValue);',
    '  if (from === undefined || to === undefined) return undefined;',
    '  const difference = differenceBetween(from, to, unit);',
    "  // The setter is `!!value`, so this is truthiness and not a boolean test.",
    '  return absolute ? Math.abs(difference) : difference;',
    '}',
    '',
    '/**',
    ' * Date Compare — one of the node\'s three boolean answers, at a granularity.',
    ' *',
    ' * One call per answer rather than one object with three keys: the calls are pure and the',
    ' * duplication is the compiler\'s to remove, whereas an object read would need a member access',
    ' * the expression vocabulary does not have.',
    ' */',
    'export function dateCompare(',
    '  aValue: unknown,',
    '  bValue: unknown,',
    '  granularity: CompareGranularity,',
    "  answer: 'before' | 'after' | 'same'",
    '): boolean | undefined {',
    '  const a = toDate(aValue);',
    '  const b = toDate(bValue);',
    '  if (a === undefined || b === undefined) return undefined;',
    '  const left = truncateTo(a, granularity);',
    '  const right = truncateTo(b, granularity);',
    "  if (answer === 'before') return left < right;",
    "  if (answer === 'after') return left > right;",
    '  return left === right;',
    '}',
    '',
    '/**',
    ' * Date Parts — one field of an instant, in the local zone.',
    ' *',
    ' * Month is 1-12, not JavaScript\'s 0-11: nobody reading a node called "Month" expects January',
    ' * to be 0.',
    ' */',
    'export function datePart(value: unknown, part: DatePartName): number | string | undefined {',
    '  const input = toDate(value);',
    '  if (input === undefined) return undefined;',
    '  switch (part) {',
    "    case 'year':",
    '      return input.getFullYear();',
    "    case 'month':",
    '      return input.getMonth() + 1;',
    "    case 'date':",
    '      return input.getDate();',
    "    case 'hours':",
    '      return input.getHours();',
    "    case 'minutes':",
    '      return input.getMinutes();',
    "    case 'seconds':",
    '      return input.getSeconds();',
    "    case 'milliseconds':",
    '      return input.getMilliseconds();',
    "    case 'dayOfWeek':",
    '      return input.getDay();',
    "    case 'dayName':",
    '      return DAY_NAMES[input.getDay()];',
    "    case 'isoWeek':",
    '      return isoWeek(input);',
    "    case 'timestamp':",
    '      return input.getTime();',
    '  }',
    '}',
    '',
    '/** CMP-005. English suffixes, in every locale — Intl gives the category, not the string. */',
    'function ordinalSuffix(day: number): string {',
    "  if (day >= 11 && day <= 13) return 'th';",
    '  switch (day % 10) {',
    '    case 1:',
    "      return 'st';",
    '    case 2:',
    "      return 'nd';",
    '    case 3:',
    "      return 'rd';",
    '    default:',
    "      return 'th';",
    '  }',
    '}',
    '',
    '/** The fields the formatter needs, read in a named IANA zone. */',
    'function fieldsInZone(t: unknown, timeZone: string) {',
    "  const parts = new Intl.DateTimeFormat('en-US', {",
    '    timeZone,',
    "    year: 'numeric',",
    "    month: '2-digit',",
    "    day: '2-digit',",
    "    hour: '2-digit',",
    "    minute: '2-digit',",
    "    second: '2-digit',",
    '    hour12: false',
    '  }).formatToParts(t as Date);',
    '  const read = (type: string) => {',
    '    const part = parts.find((p) => p.type === type);',
    '    return part ? parseInt(part.value, 10) : NaN;',
    '  };',
    '  // hour12:false renders midnight as 24 in some ICU versions; % 24 is the documented fix.',
    '  return {',
    "    date: read('day'),",
    "    month: read('month'),",
    "    year: read('year'),",
    "    hours: read('hour') % 24,",
    "    minutes: read('minute'),",
    "    seconds: read('second')",
    '  };',
    '}',
    '',
    '/**',
    ' * Date To String — an instant rendered through a format template.',
    ' *',
    ' * 🔴 THE INPUT IS READ DIFFERENTLY FROM THE OTHER FOUR, ON PURPOSE. This node predates the',
    ' * shared date math, and its own setter is `typeof value === \'string\' ? new Date(value) : value`',
    ' * — so a millisecond NUMBER arrives unconverted and getDate() throws on it, which the catch',
    ' * below turns into a blank. Routing it through toDate() would "fix" a blank the author has',
    ' * already seen and worked around.',
    ' *',
    ' * Undefined before anything has arrived (the node never formats until its setter runs); the',
    " * empty string for a date it could not read, which is the node's own catch.",
    ' */',
    'export function dateToString(value: unknown, format: unknown, timeZone: unknown, locale?: unknown): string | undefined {',
    "  if (value === undefined || value === null || value === '') return undefined;",
    '  // The cast is the node\'s own read, lie included: a number reaches getDate() and throws.',
    "  const t = (typeof value === 'string' ? new Date(value) : value) as Date;",
    "  // The Timezone setter is `value || ''`, so a blank, a null and an unset input are one case.",
    "  const zone = (timeZone || '') as string;",
    '  // CMP-005. The Locale port reads the same way, and an empty one is the en-US that used to',
    '  // be written into the Intl call below.',
    "  const lang = (locale || 'en-US') as string;",
    '  try {',
    '    const fields = zone',
    '      ? fieldsInZone(t, zone)',
    '      : {',
    '          date: t.getDate(),',
    '          month: t.getMonth() + 1,',
    '          year: t.getFullYear(),',
    '          hours: t.getHours(),',
    '          minutes: t.getMinutes(),',
    '          seconds: t.getSeconds()',
    '        };',
    "    if (Number.isNaN(fields.year)) throw new RangeError('Invalid date');",
    '',
    "    const date = ('0' + fields.date).slice(-2);",
    "    const month = ('0' + fields.month).slice(-2);",
    "    const monthShort = new Intl.DateTimeFormat(lang, zone ? { month: 'short', timeZone: zone } : { month: 'short' }).format(t);",
    '    const year = fields.year;',
    '    const yearShort = year.toString().substring(2);',
    "    const hours = ('0' + fields.hours).slice(-2);",
    "    const minutes = ('0' + fields.minutes).slice(-2);",
    "    const seconds = ('0' + fields.seconds).slice(-2);",
    '',
    '    // A Format that is not a string has no `.replace` and throws into the catch below, which',
    '    // is exactly what the interpreter does with one.',
    '    let rendered = (format as string)',
    '      .replace(/\\{date\\}/g, date)',
    '      .replace(/\\{month\\}/g, month)',
    '      .replace(/\\{monthShort\\}/g, monthShort)',
    '      .replace(/\\{year\\}/g, String(year))',
    '      .replace(/\\{yearShort\\}/g, yearShort)',
    '      .replace(/\\{hours\\}/g, hours)',
    '      .replace(/\\{minutes\\}/g, minutes)',
    '      .replace(/\\{seconds\\}/g, seconds);',
    '',
    '    // CMP-005 tokens, rendered lazily: a format that never mentions {dayName} never builds',
    '    // the Intl formatter that would produce it. The order of the two passes is not',
    '    // load-bearing — no rendered value contains a brace — the chain above is simply kept',
    '    // verbatim so it is reviewable as unchanged.',
    '    const substitute = (token: string, render: () => string) => {',
    "      const needle = '{' + token + '}';",
    '      if (rendered.indexOf(needle) === -1) return;',
    '      rendered = rendered.split(needle).join(render());',
    '    };',
    '    const named = (options: Intl.DateTimeFormatOptions) =>',
    '      new Intl.DateTimeFormat(lang, zone ? { ...options, timeZone: zone } : options).format(t as Date);',
    '    // 0 is midnight and prints as 12; 13 prints as 1.',
    '    const hours12 = ((fields.hours + 11) % 12) + 1;',
    "    const meridiem = fields.hours < 12 ? 'am' : 'pm';",
    "    substitute('dayName', () => named({ weekday: 'long' }));",
    "    substitute('dayShort', () => named({ weekday: 'short' }));",
    "    substitute('monthName', () => named({ month: 'long' }));",
    "    substitute('hours12', () => ('0' + hours12).slice(-2));",
    "    substitute('h12', () => String(hours12));",
    "    substitute('ampm', () => meridiem);",
    "    substitute('AMPM', () => meridiem.toUpperCase());",
    "    substitute('ordinal', () => String(fields.date) + ordinalSuffix(fields.date));",
    "    substitute('d', () => String(fields.date));",
    "    substitute('m', () => String(fields.month));",
    "    substitute('h', () => String(fields.hours));",
    "    substitute('min', () => String(fields.minutes));",
    "    substitute('s', () => String(fields.seconds));",
    '    return rendered;',
    '  } catch {',
    "    // The node blanks the output rather than leaving the last answer up: 'makes it easier to",
    "    // handle', in its own words.",
    "    return '';",
    '  }',
    '}',
    ''
  ].join('\n');
}
