/**
 * `src/lib/drag.ts` — `Drag` as a hook, emitted into the app (EXP-011 §63, Tier 2.8 row 13).
 *
 * A transcription of three sources the running app composes: `noodl-viewer-react/src/nodes/visual/drag.ts` (the ports,
 * the snap registers and their setters' abstain / NaN rules, the outcome reports), `src/components/visual/Drag/Drag.tsx`
 * (the state, the outputs' order, the per-axis commit on stop, the snap tween, the timer cleanup) and `react-draggable`
 * 4.5.0 (`DraggableCore`: mouse + touch, the document listeners for one drag, the user-select hack; `Draggable`: the
 * controlled position, the axis flush rule, `bounds: 'parent'` with slack; `positionFns` / `domFns`: the coordinate
 * math). Everything the two class components kept on `this` lives in one ref here; the snap tween runs on
 * `src/lib/animate.ts`'s scheduler transcription (`createRun / startRun / stopRun / eases.easeOut` — the same
 * `TimerScheduler` and the same `EaseCurves.easeOut` the interpreter uses), and the one error the node raises rides
 * `src/lib/errors.ts`, so `emitApp` ships both wherever it ships this module.
 *
 * ⚠️ **Recorded divergences.** The interpreter drags the CHILD's root element (`Drag.tsx` renders no element of its own
 * and clones the first child with the transform and the handlers); the export drags a wrapper `<div>` that takes the
 * child's place in the parent's flex flow. The library's three marker classes (`react-draggable`, `-dragging`,
 * `-dragged`) are not emitted — no CSS ships with them. A snap Value that arrives NaN twice in a row raises once (the
 * arrival is an effect keyed on the value; the setter raises per delivery).
 *
 * 🔴 The handle's `x / y / deltaX / deltaY` are GETTERS over the live values: `Drag.tsx` writes the outputs and THEN
 * pulses, so a Drag Moved chain must read this frame's value — a closure over a plain render value would read the
 * previous render's (§58's "live getters on the handle" rule, for the same reason).
 */

/** Where the module lands in the exported app. */
export const DRAG_LIB_PATH = 'src/lib/drag.ts';

/**
 * The module's source.
 *
 * ⚠️ A plain string array rather than a template literal, for `dateLib.ts`'s stated reason.
 */
export function dragLibSource(): string {
  return [
    '//',
    '// Drag, transcribed from the interpreter it has to agree with:',
    '// noodl-viewer-react/src/nodes/visual/drag.ts and src/components/visual/Drag/Drag.tsx, and react-draggable 4.5.0',
    '// (DraggableCore, Draggable, utils/positionFns, utils/domFns), which Drag.tsx wraps around its first child.',
    '//',
    '// useDrag(source, options, listeners): a handle for the wrapper element that drags — its ref, its transform and the',
    '// three handlers the library puts on the dragged element (mouse and touch, not pointer events); Drag X/Y and Delta X/Y',
    "// as live getters; snapTo('x' | 'y') runs the same easeOut tween the interpreter's TimerScheduler runs (./animate).",
    '//',
    '',
    "import { useEffect, useRef, useState, type CSSProperties, type MouseEvent as ReactMouseEvent, type RefObject, type TouchEvent as ReactTouchEvent } from 'react';",
    '',
    "import { createRun, eases, startRun, stopRun, type Run } from './animate';",
    "import { raiseAppError } from './errors';",
    '',
    '/** Where the node sits, for the one error it raises (`drag/snap-position-not-a-number`). */',
    'export interface DragSource {',
    "  /** The authored label, or the node's display name. */",
    '  label: string;',
    "  /** The node's graph id. */",
    '  nodeId: string;',
    "  /** The component it sits in \u2014 '/Pages/Home'. */",
    '  componentName: string;',
    '}',
    '',
    '/**',
    " * The node's inputs, typed as the ports take them \u2014 a wire delivers whatever it delivers, and each is consumed here",
    " * exactly as Drag.tsx consumes the prop. A key that is absent takes the port's declared default; a key present with",
    ' * `undefined` is a wire that delivered nothing, which is not the same thing (`registerInput` applies a default only to',
    ' * a port nothing set).',
    ' */',
    'export interface DragOptions {',
    "  /** Axis: 'x', 'y' or 'both' \u2014 the node's default is 'x'. Anything else drags on neither axis (canDragX / canDragY). */",
    '  axis?: unknown;',
    '  /** Enabled: only an explicit `false` disables (`disabled={props.enabled === false}`). */',
    '  enabled?: unknown;',
    "  /** Constrain to parent: truthy is `bounds: 'parent'`; absent is the declared default, true. */",
    '  useParentBounds?: unknown;',
    '  /** Scale: pointer deltas are divided by `props.scale || 1`. */',
    '  scale?: unknown;',
    '  /** Start Drag X: `inputPositionX ? inputPositionX : 0` at mount; a later change is adopted raw and reported with its delta. */',
    '  startX?: unknown;',
    '  /** Start Drag Y, the same. */',
    '  startY?: unknown;',
    '  /** Snap To Position X — Value: read on arrival; empty abstains, a non-number raises and abstains; the default is 0. */',
    '  snapX?: unknown;',
    '  /** Snap To Position X — Duration: stored raw; unset is 300; anything not above 0 jumps in one frame. */',
    '  snapXDuration?: unknown;',
    '  /** Snap To Position Y — Value, the same. */',
    '  snapY?: unknown;',
    '  /** Snap To Position Y — Duration, the same. */',
    '  snapYDuration?: unknown;',
    '}',
    '',
    "/** The three pulses and the snaps' Done, called after the outputs are written \u2014 a chain reads this frame's values. */",
    'export interface DragListeners {',
    '  /** Drag Started. */',
    '  onStart?: () => void;',
    '  /** Drag Moved — every frame the pointer moves while dragging. */',
    '  onMove?: () => void;',
    '  /** Drag Ended — the release, including a pointer that leaves the window. */',
    '  onEnd?: () => void;',
    '  /** Done — after every snap call, a no-op included (outcomeOnInnerComponent reports done unless the method returns a string). */',
    '  done?: () => void;',
    '}',
    '',
    "export type DragAxis = 'x' | 'y';",
    '',
    '/** What a Drag node hands the page. */',
    'export interface DragHandle {',
    '  /** The wrapper element the hook drags. */',
    '  ref: RefObject<HTMLDivElement | null>;',
    '  /**',
    '   * `transform: translate(x px, y px)` — the live position on the axes that drag, the committed one on the others — and',
    '   * `width`/`height: fit-content`, so the wrapper is the child\'s box: an unstyled flex item would STRETCH across the parent\'s',
    '   * cross axis (a 320 px wrapper around an 80 px card), and `bounds: \'parent\'` would measure the stretched box and pin the',
    '   * axis at one value. The interpreter drags the child\'s own element, which never stretches on its behalf.',
    '   */',
    '  style: CSSProperties;',
    '  /** The three handlers react-draggable puts on the dragged element; `touchstart` is attached natively (passive: false). */',
    '  handlers: {',
    '    onMouseDown: (event: ReactMouseEvent<HTMLElement>) => void;',
    '    onMouseUp: (event: ReactMouseEvent<HTMLElement>) => void;',
    '    onTouchEnd: (event: ReactTouchEvent<HTMLElement>) => void;',
    '  };',
    '  /** Drag X — where the element is, relative to where it started. Live: a listener reads the value the pulse just wrote. */',
    '  readonly x: number;',
    '  /** Drag Y. */',
    '  readonly y: number;',
    '  /** Delta X — how far it moved since the last Drag Moved. */',
    '  readonly deltaX: number;',
    '  /** Delta Y. */',
    '  readonly deltaY: number;',
    '  /** Snap To Position X / Y — Do. */',
    '  snapTo(axis: DragAxis): void;',
    '}',
    '',
    'interface Pos {',
    '  x: number;',
    '  y: number;',
    '}',
    '',
    "const MOUSE = { move: 'mousemove', stop: 'mouseup' } as const;",
    "const TOUCH = { move: 'touchmove', stop: 'touchend' } as const;",
    '',
    "/** Everything the class components kept on `this` \u2014 Drag.tsx's state, Draggable's state, DraggableCore's fields. */",
    'interface DragState {',
    '  source: DragSource;',
    '  ref: RefObject<HTMLDivElement | null>;',
    '  latest: { options: DragOptions; listeners: DragListeners };',
    '  /** Drag.tsx `state` — the position the node has committed to. */',
    '  committed: Pos;',
    '  /** Draggable `state.x/y` — where the pointer has taken the element during a drag. */',
    '  live: Pos;',
    '  /** Draggable `slackX/slackY` — the overshoot kept while a bound is holding the element. */',
    '  slack: Pos;',
    '  /** Draggable `state.dragging`. */',
    '  draggableDragging: boolean;',
    '  /** The four outputs, as `setDragValues` last wrote them. */',
    '  values: { x: number; y: number; deltaX: number; deltaY: number };',
    '  /** DraggableCore `dragging`, `lastX`, `lastY`, `touchIdentifier`, and which pair of document events this drag listens to. */',
    '  coreDragging: boolean;',
    '  lastX: number;',
    '  lastY: number;',
    '  touchIdentifier: number | null;',
    '  dragEvents: typeof MOUSE | typeof TOUCH;',
    '  /** drag.ts `_internal` — the snap registers the setters fill. */',
    '  snapTarget: Pos;',
    '  snapDuration: { x: unknown; y: unknown };',
    '  /** Drag.tsx `snapToPositionXTimer` / `snapToPositionYTimer`. */',
    '  snapRuns: { x: Run | null; y: Run | null };',
    '  rerender: () => void;',
    '  onDocMove: (event: Event) => void;',
    '  onDocStop: (event: Event) => void;',
    '  onTouchStart: (event: Event) => void;',
    '}',
    '',
    '// ---- utils/shims.js, utils/domFns.js -------------------------------------------------------------------',
    '',
    'const int = (value: string): number => parseInt(value, 10) || 0;',
    '',
    'function outerHeight(node: HTMLElement): number {',
    '  let height = node.clientHeight;',
    '  const computedStyle = node.ownerDocument.defaultView!.getComputedStyle(node);',
    '  height += int(computedStyle.borderTopWidth);',
    '  height += int(computedStyle.borderBottomWidth);',
    '  return height;',
    '}',
    '',
    'function outerWidth(node: HTMLElement): number {',
    '  let width = node.clientWidth;',
    '  const computedStyle = node.ownerDocument.defaultView!.getComputedStyle(node);',
    '  width += int(computedStyle.borderLeftWidth);',
    '  width += int(computedStyle.borderRightWidth);',
    '  return width;',
    '}',
    '',
    'function innerHeight(node: HTMLElement): number {',
    '  let height = node.clientHeight;',
    '  const computedStyle = node.ownerDocument.defaultView!.getComputedStyle(node);',
    '  height -= int(computedStyle.paddingTop);',
    '  height -= int(computedStyle.paddingBottom);',
    '  return height;',
    '}',
    '',
    'function innerWidth(node: HTMLElement): number {',
    '  let width = node.clientWidth;',
    '  const computedStyle = node.ownerDocument.defaultView!.getComputedStyle(node);',
    '  width -= int(computedStyle.paddingLeft);',
    '  width -= int(computedStyle.paddingRight);',
    '  return width;',
    '}',
    '',
    "/** The pointer in the offsetParent's coordinates. The core's scale is 1 \u2014 Draggable strips `scale` before passing props down. */",
    'function offsetXYFromParent(evt: { clientX: number; clientY: number }, offsetParent: HTMLElement): Pos {',
    '  const isBody = offsetParent === offsetParent.ownerDocument.body;',
    '  const offsetParentRect = isBody ? { left: 0, top: 0 } : offsetParent.getBoundingClientRect();',
    '  const x = evt.clientX + offsetParent.scrollLeft - offsetParentRect.left;',
    '  const y = evt.clientY + offsetParent.scrollTop - offsetParentRect.top;',
    '  return { x, y };',
    '}',
    '',
    'function findTouch(list: TouchList | undefined, identifier: number): Touch | undefined {',
    '  if (list === undefined) return undefined;',
    '  for (let i = 0; i < list.length; i++) if (list[i].identifier === identifier) return list[i];',
    '  return undefined;',
    '}',
    '',
    'function getTouch(e: TouchEvent, identifier: number): Touch | undefined {',
    '  return findTouch(e.targetTouches, identifier) || findTouch(e.changedTouches, identifier);',
    '}',
    '',
    'function getTouchIdentifier(e: Event): number | undefined {',
    '  const touches = e as TouchEvent;',
    '  if (touches.targetTouches && touches.targetTouches[0]) return touches.targetTouches[0].identifier;',
    '  if (touches.changedTouches && touches.changedTouches[0]) return touches.changedTouches[0].identifier;',
    '  return undefined;',
    '}',
    '',
    "/** The library's hack against text selection during a drag, verbatim: a style element and a class on the body. */",
    'function addUserSelectStyles(doc: Document): void {',
    "  let styleEl = doc.getElementById('react-draggable-style-el') as HTMLStyleElement | null;",
    '  if (!styleEl) {',
    "    styleEl = doc.createElement('style');",
    "    styleEl.id = 'react-draggable-style-el';",
    "    styleEl.innerHTML = '.react-draggable-transparent-selection *::-moz-selection {all: inherit;}\\n';",
    "    styleEl.innerHTML += '.react-draggable-transparent-selection *::selection {all: inherit;}\\n';",
    "    doc.getElementsByTagName('head')[0].appendChild(styleEl);",
    '  }',
    "  if (doc.body) doc.body.classList.add('react-draggable-transparent-selection');",
    '}',
    '',
    'function removeUserSelectStyles(doc: Document): void {',
    '  try {',
    "    if (doc.body) doc.body.classList.remove('react-draggable-transparent-selection');",
    '    const selection = (doc.defaultView || window).getSelection();',
    "    if (selection && selection.type !== 'Caret') selection.removeAllRanges();",
    '  } catch {',
    '    // probably IE',
    '  }',
    '}',
    '',
    'function scheduleRemoveUserSelectStyles(doc: Document): void {',
    "  if (typeof requestAnimationFrame === 'function') {",
    '    requestAnimationFrame(() => {',
    '      removeUserSelectStyles(doc);',
    '    });',
    '  } else {',
    '    removeUserSelectStyles(doc);',
    '  }',
    '}',
    '',
    "// ---- utils/positionFns.js, for `bounds: 'parent'` -------------------------------------------------------",
    '',
    'function getBoundPosition(node: HTMLElement, x: number, y: number): Pos {',
    '  const ownerWindow = node.ownerDocument.defaultView!;',
    '  const boundNode = node.parentNode;',
    '  if (!(boundNode instanceof ownerWindow.HTMLElement)) {',
    '    throw new Error(\'Bounds selector "parent" could not find an element.\');',
    '  }',
    '  const nodeStyle = ownerWindow.getComputedStyle(node);',
    '  const boundNodeStyle = ownerWindow.getComputedStyle(boundNode);',
    '  const bounds = {',
    '    left: -node.offsetLeft + int(boundNodeStyle.paddingLeft) + int(nodeStyle.marginLeft),',
    '    top: -node.offsetTop + int(boundNodeStyle.paddingTop) + int(nodeStyle.marginTop),',
    '    right: innerWidth(boundNode) - outerWidth(node) - node.offsetLeft + int(boundNodeStyle.paddingRight) - int(nodeStyle.marginRight),',
    '    bottom: innerHeight(boundNode) - outerHeight(node) - node.offsetTop + int(boundNodeStyle.paddingBottom) - int(nodeStyle.marginBottom)',
    '  };',
    '  x = Math.min(x, bounds.right);',
    '  y = Math.min(y, bounds.bottom);',
    '  x = Math.max(x, bounds.left);',
    '  y = Math.max(y, bounds.top);',
    '  return { x, y };',
    '}',
    '',
    '// ---- the props, as Drag.tsx reads them ------------------------------------------------------------------',
    '',
    'const canDragX = (options: DragOptions): boolean => {',
    "  const axis = 'axis' in options ? options.axis : 'x';",
    "  return axis === 'both' || axis === 'x';",
    '};',
    'const canDragY = (options: DragOptions): boolean => {',
    "  const axis = 'axis' in options ? options.axis : 'x';",
    "  return axis === 'both' || axis === 'y';",
    '};',
    "/** `bounds = props.useParentBounds ? 'parent' : undefined`, with the declared default for a port nothing set. */",
    "const boundsOn = (options: DragOptions): boolean => ('useParentBounds' in options ? Boolean(options.useParentBounds) : true);",
    '/** `scale={props.scale || 1}` — a 0 would make every delta Infinity (NDA-012). Coerced the way the division coerces it. */',
    'const scaleOf = (options: DragOptions): number => Number(options.scale) || 1;',
    '/** `componentDidMount`: `props.inputPositionX ? props.inputPositionX : 0`. */',
    'const startOf = (value: unknown): number => (value ? (value as number) : 0);',
    '',
    '/**',
    " * drag.ts `readSnapCoordinate` \u2014 a position has no representable empty state: `undefined`, `null` and `''` abstain",
    ' * and leave the current target alone; anything else is `Number()`ed, and a non-finite answer is reported.',
    ' */',
    'function readSnapCoordinate(value: unknown): number | undefined {',
    "  if (value === undefined || value === null || value === '') return undefined;",
    '  const asNumber = Number(value);',
    '  return Number.isFinite(asNumber) ? asNumber : Number.NaN;',
    '}',
    '',
    '// ---- the machine ----------------------------------------------------------------------------------------',
    '',
    '/** `setDragValues` — positionX, positionY, deltaX, deltaY, in that order. */',
    'function setDragValues(s: DragState, data: { x: number; y: number; deltaX: number; deltaY: number }): void {',
    '  s.values.x = data.x;',
    '  s.values.y = data.y;',
    '  s.values.deltaX = data.deltaX;',
    '  s.values.deltaY = data.deltaY;',
    '}',
    '',
    '/** `getControlPosition` — the right touch, or the mouse; null when this event is not our finger. */',
    'function getControlPosition(s: DragState, e: Event): Pos | null {',
    "  const touchObj = typeof s.touchIdentifier === 'number' ? getTouch(e as TouchEvent, s.touchIdentifier) : null;",
    "  if (typeof s.touchIdentifier === 'number' && !touchObj) return null;",
    '  const node = s.ref.current;',
    "  if (node === null) throw new Error('<DraggableCore>: Unmounted during event!');",
    '  const offsetParent = (node.offsetParent as HTMLElement | null) || node.ownerDocument.body;',
    '  return offsetXYFromParent(touchObj || (e as MouseEvent), offsetParent);',
    '}',
    '',
    '/** Drag.tsx `stopSnapTimers` — both timers, from unmount and from every Drag Started. */',
    'function stopSnapTimers(s: DragState): void {',
    '  if (s.snapRuns.x !== null) stopRun(s.snapRuns.x);',
    '  if (s.snapRuns.y !== null) stopRun(s.snapRuns.y);',
    '  s.snapRuns.x = null;',
    '  s.snapRuns.y = null;',
    '}',
    '',
    '/** DraggableCore `handleDragStart` → Draggable `onDragStart` → Drag.tsx `onStart`. */',
    'function handleDragStart(s: DragState, e: Event): void {',
    '  // allowAnyClick is false: the primary button only.',
    '  const button = (e as MouseEvent).button;',
    "  if (typeof button === 'number' && button !== 0) return;",
    '  const node = s.ref.current;',
    '  if (node === null || !node.ownerDocument || !node.ownerDocument.body) {',
    "    throw new Error('<DraggableCore> not mounted on DragStart!');",
    '  }',
    '  const { ownerDocument } = node;',
    '  const options = s.latest.options;',
    '  if (options.enabled === false || !(e.target instanceof ownerDocument.defaultView!.Node)) return;',
    '  // allowMobileScroll is false: a touch that starts a drag does not scroll.',
    "  if (e.type === 'touchstart') e.preventDefault();",
    '  const touchIdentifier = getTouchIdentifier(e);',
    '  s.touchIdentifier = touchIdentifier === undefined ? null : touchIdentifier;',
    '  const position = getControlPosition(s, e);',
    '  if (position === null) return;',
    '  const { x, y } = position;',
    '  // createCoreData at a start: deltas of 0; createDraggableData: the live position plus nothing.',
    '  setDragValues(s, { x: s.live.x, y: s.live.y, deltaX: 0, deltaY: 0 });',
    '  s.latest.listeners.onStart?.();',
    '  stopSnapTimers(s);',
    '  s.draggableDragging = true;',
    '  addUserSelectStyles(ownerDocument);',
    '  s.coreDragging = true;',
    '  s.lastX = x;',
    '  s.lastY = y;',
    '  ownerDocument.addEventListener(s.dragEvents.move, s.onDocMove);',
    '  ownerDocument.addEventListener(s.dragEvents.stop, s.onDocStop);',
    '  s.rerender();',
    '}',
    '',
    '/** DraggableCore `handleDrag` → Draggable `onDrag` (the bounds and the slack) → Drag.tsx `onDrag`. */',
    'function handleDrag(s: DragState, e: Event): void {',
    '  const position = getControlPosition(s, e);',
    '  if (position === null) return;',
    '  const { x, y } = position;',
    '  const coreDeltaX = x - s.lastX;',
    '  const coreDeltaY = y - s.lastY;',
    '  if (!s.draggableDragging) return;',
    '  const options = s.latest.options;',
    '  const scale = scaleOf(options);',
    '  const uiData = { x: s.live.x + coreDeltaX / scale, y: s.live.y + coreDeltaY / scale, deltaX: coreDeltaX / scale, deltaY: coreDeltaY / scale };',
    '  const newState = { x: uiData.x, y: uiData.y, slackX: 0, slackY: 0 };',
    '  if (boundsOn(options)) {',
    '    const node = s.ref.current;',
    "    if (node === null) throw new Error('<DraggableCore>: Unmounted during event!');",
    '    const unslackedX = newState.x;',
    '    const unslackedY = newState.y;',
    '    newState.x += s.slack.x;',
    '    newState.y += s.slack.y;',
    '    const bound = getBoundPosition(node, newState.x, newState.y);',
    '    newState.x = bound.x;',
    '    newState.y = bound.y;',
    '    newState.slackX = s.slack.x + (unslackedX - newState.x);',
    '    newState.slackY = s.slack.y + (unslackedY - newState.y);',
    '    uiData.x = newState.x;',
    '    uiData.y = newState.y;',
    '    uiData.deltaX = newState.x - s.live.x;',
    '    uiData.deltaY = newState.y - s.live.y;',
    '  }',
    '  setDragValues(s, uiData);',
    '  s.latest.listeners.onMove?.();',
    '  s.live.x = newState.x;',
    '  s.live.y = newState.y;',
    '  s.slack.x = newState.slackX;',
    '  s.slack.y = newState.slackY;',
    '  s.lastX = x;',
    '  s.lastY = y;',
    '  s.rerender();',
    '}',
    '',
    '/** DraggableCore `handleDragStop` → Draggable `onDragStop` → Drag.tsx `onStop`: the commit on the enabled axes only. */',
    'function handleDragStop(s: DragState, e: Event): void {',
    '  if (!s.coreDragging) return;',
    '  const position = getControlPosition(s, e);',
    '  if (position === null) return;',
    '  const { x, y } = position;',
    '  const coreDeltaX = x - s.lastX;',
    '  const coreDeltaY = y - s.lastY;',
    '  if (!s.draggableDragging) return;',
    '  const options = s.latest.options;',
    '  const scale = scaleOf(options);',
    '  // createDraggableData on the stop: the live position plus the last delta, NOT re-bounded (Draggable.js onDragStop).',
    '  const data = { x: s.live.x + coreDeltaX / scale, y: s.live.y + coreDeltaY / scale };',
    '  if (canDragX(options)) s.committed.x = data.x;',
    '  if (canDragY(options)) s.committed.y = data.y;',
    '  s.values.x = data.x;',
    '  s.values.y = data.y;',
    '  s.latest.listeners.onEnd?.();',
    '  // Draggable: dragging false, the slack cleared, and — controlled — the live position back to the prop, which the',
    '  // next render syncs to the committed one (getDerivedStateFromProps).',
    '  s.draggableDragging = false;',
    '  s.slack.x = 0;',
    '  s.slack.y = 0;',
    '  s.live.x = s.committed.x;',
    '  s.live.y = s.committed.y;',
    '  const node = s.ref.current;',
    '  if (node !== null) scheduleRemoveUserSelectStyles(node.ownerDocument);',
    '  s.coreDragging = false;',
    '  s.lastX = NaN;',
    '  s.lastY = NaN;',
    '  if (node !== null) {',
    '    node.ownerDocument.removeEventListener(s.dragEvents.move, s.onDocMove);',
    '    node.ownerDocument.removeEventListener(s.dragEvents.stop, s.onDocStop);',
    '  }',
    '  s.rerender();',
    '}',
    '',
    '/**',
    ' * Drag.tsx `snapToPositionX/Y` over `snapToPosition`: nothing when already there; else the running tween on this axis',
    ' * is stopped and a new one runs from the committed position to the target with `EaseCurves.easeOut`, writing the',
    ' * position and the Drag X/Y output every frame (no delta). Then drag.ts reports `done` — a no-op included.',
    ' */',
    'function snapTo(s: DragState, axis: DragAxis): void {',
    '  const endValue = s.snapTarget[axis];',
    '  if (s.committed[axis] !== endValue) {',
    '    const running = s.snapRuns[axis];',
    '    if (running !== null) stopRun(running);',
    '    const rawDuration = s.snapDuration[axis];',
    '    const run = createRun(rawDuration === undefined ? 300 : Number(rawDuration), 0);',
    '    const startValue = s.committed[axis];',
    '    run.onRunning = (t) => {',
    '      const value = eases.easeOut(startValue, endValue, t);',
    '      s.committed[axis] = value;',
    '      s.live[axis] = value;',
    '      s.values[axis] = value;',
    '      s.rerender();',
    '    };',
    '    s.snapRuns[axis] = run;',
    '    startRun(run);',
    '  }',
    '  s.latest.listeners.done?.();',
    '}',
    '',
    '/**',
    ' * A Drag node. The wrapper element this returns a ref for is what the hook drags — where the interpreter drags the',
    " * child's own root element \u2014 and everything the two class components kept on `this` lives in one ref here.",
    ' */',
    'export function useDrag(source: DragSource, options: DragOptions = {}, listeners: DragListeners = {}): DragHandle {',
    '  const ref = useRef<HTMLDivElement | null>(null);',
    '  const [, setTick] = useState(0);',
    '  const stateRef = useRef<DragState | null>(null);',
    '  if (stateRef.current === null) {',
    '    const startX = startOf(options.startX);',
    '    const startY = startOf(options.startY);',
    '    const s: DragState = {',
    '      source,',
    '      ref,',
    '      latest: { options, listeners },',
    '      committed: { x: startX, y: startY },',
    '      live: { x: startX, y: startY },',
    '      slack: { x: 0, y: 0 },',
    '      draggableDragging: false,',
    '      values: { x: startX, y: startY, deltaX: 0, deltaY: 0 },',
    '      coreDragging: false,',
    '      lastX: NaN,',
    '      lastY: NaN,',
    '      touchIdentifier: null,',
    '      dragEvents: MOUSE,',
    '      snapTarget: { x: 0, y: 0 },',
    '      snapDuration: { x: 300, y: 300 },',
    '      snapRuns: { x: null, y: null },',
    '      rerender: () => setTick((tick) => tick + 1),',
    '      onDocMove: (event) => handleDrag(s, event),',
    '      onDocStop: (event) => handleDragStop(s, event),',
    '      onTouchStart: (event) => {',
    '        s.dragEvents = TOUCH;',
    '        handleDragStart(s, event);',
    '      }',
    '    };',
    '    stateRef.current = s;',
    '  }',
    '  const s = stateRef.current;',
    '  s.latest = { options, listeners };',
    '',
    '  // componentDidMount: the native touchstart (passive: false, so the drag can stop the scroll); componentWillUnmount:',
    '  // every listener off, the selection hack undone, both snap timers stopped (NDA-012 H1). StrictMode runs this twice',
    '  // and the cleanup between makes the second attach the only one.',
    '  useEffect(() => {',
    '    const node = ref.current;',
    '    if (node === null) return undefined;',
    "    node.addEventListener('touchstart', s.onTouchStart, { passive: false });",
    '    return () => {',
    '      const { ownerDocument } = node;',
    "      ownerDocument.removeEventListener('mousemove', s.onDocMove);",
    "      ownerDocument.removeEventListener('touchmove', s.onDocMove);",
    "      ownerDocument.removeEventListener('mouseup', s.onDocStop);",
    "      ownerDocument.removeEventListener('touchend', s.onDocStop);",
    "      node.removeEventListener('touchstart', s.onTouchStart);",
    '      scheduleRemoveUserSelectStyles(ownerDocument);',
    '      stopSnapTimers(s);',
    '    };',
    '    // eslint-disable-next-line react-hooks/exhaustive-deps -- the state object is created once',
    '  }, []);',
    '',
    '  // componentDidUpdate: a changed Start Drag X/Y is adopted raw, reported, and its delta is the difference.',
    '  const prevStart = useRef<{ x: unknown; y: unknown } | null>(null);',
    '  useEffect(() => {',
    '    const prev = prevStart.current;',
    '    prevStart.current = { x: options.startX, y: options.startY };',
    '    if (prev === null) return;',
    '    let changed = false;',
    '    if (prev.x !== options.startX) {',
    '      const next = options.startX as number;',
    '      s.committed.x = next;',
    '      s.live.x = next;',
    '      s.values.x = next;',
    '      s.values.deltaX = next - (prev.x as number);',
    '      changed = true;',
    '    }',
    '    if (prev.y !== options.startY) {',
    '      const next = options.startY as number;',
    '      s.committed.y = next;',
    '      s.live.y = next;',
    '      s.values.y = next;',
    '      s.values.deltaY = next - (prev.y as number);',
    '      changed = true;',
    '    }',
    '    if (changed) s.rerender();',
    '    // eslint-disable-next-line react-hooks/exhaustive-deps -- the state object is created once',
    '  }, [options.startX, options.startY]);',
    '',
    '  // The four snap setters, run on arrival: the Value through readSnapCoordinate, the Duration stored raw.',
    '  const arrive = (axis: DragAxis, value: unknown): void => {',
    '    const coordinate = readSnapCoordinate(value);',
    '    if (coordinate === undefined) return;',
    '    if (Number.isNaN(coordinate)) {',
    '      raiseAppError({',
    "        code: 'drag/snap-position-not-a-number',",
    '        message: `Snap To Position ${axis.toUpperCase()} — Value cannot be read as a number (got ${JSON.stringify(value)}), so the snap position is unchanged.`,',
    '        nodeId: source.nodeId,',
    '        componentName: source.componentName,',
    "        nodeType: 'Drag'",
    '      });',
    '      return;',
    '    }',
    '    s.snapTarget[axis] = coordinate;',
    '  };',
    '  // eslint-disable-next-line react-hooks/exhaustive-deps -- arrival, keyed on the value',
    "  useEffect(() => arrive('x', options.snapX), [options.snapX]);",
    '  // eslint-disable-next-line react-hooks/exhaustive-deps -- arrival, keyed on the value',
    "  useEffect(() => arrive('y', options.snapY), [options.snapY]);",
    '  useEffect(() => {',
    "    if ('snapXDuration' in options) s.snapDuration.x = options.snapXDuration;",
    '    // eslint-disable-next-line react-hooks/exhaustive-deps -- arrival, keyed on the value',
    '  }, [options.snapXDuration]);',
    '  useEffect(() => {',
    "    if ('snapYDuration' in options) s.snapDuration.y = options.snapYDuration;",
    '    // eslint-disable-next-line react-hooks/exhaustive-deps -- arrival, keyed on the value',
    '  }, [options.snapYDuration]);',
    '',
    '  // Draggable.render: controlled, so the live position shows only while dragging, and only on the axes that drag.',
    '  const draggable = s.draggableDragging;',
    '  const transformX = canDragX(options) && draggable ? s.live.x : s.committed.x;',
    '  const transformY = canDragY(options) && draggable ? s.live.y : s.committed.y;',
    '',
    '  return {',
    '    ref,',
    '    style: { width: \'fit-content\', height: \'fit-content\', transform: `translate(${transformX}px,${transformY}px)` },',
    '    handlers: {',
    '      onMouseDown: (event) => {',
    '        s.dragEvents = MOUSE;',
    '        handleDragStart(s, event.nativeEvent);',
    '      },',
    '      onMouseUp: (event) => {',
    '        s.dragEvents = MOUSE;',
    '        handleDragStop(s, event.nativeEvent);',
    '      },',
    '      onTouchEnd: (event) => {',
    '        s.dragEvents = TOUCH;',
    '        handleDragStop(s, event.nativeEvent);',
    '      }',
    '    },',
    '    get x() {',
    '      return s.values.x;',
    '    },',
    '    get y() {',
    '      return s.values.y;',
    '    },',
    '    get deltaX() {',
    '      return s.values.deltaX;',
    '    },',
    '    get deltaY() {',
    '      return s.values.deltaY;',
    '    },',
    '    snapTo: (axis) => snapTo(s, axis)',
    '  };',
    '}',
    ''
  ].join('\n');
}
