/**
 * `src/lib/pageStack.ts` — the component-stack trio as a lib, emitted into the app (EXP-011 §61, Tier 2.8 row 11).
 *
 * A transcription of three runtime files: `noodl-viewer-react/src/nodes/navigation/navigation-handler.ts`
 * (the module-level registry — stacks register BY NAME, several may share one, a push with no stack
 * registered is QUEUED and replayed on the next registration, which resets first), `navigation-stack.tsx`
 * (`navigateAsync` / `replaceAsync` / `back` / `resetAsync` — the three failure codes and sentences, the
 * `_isAlreadyShowing` no-op, `from: null` and NO back callback on replace, no callback on reset either)
 * and `navigate-back.ts` (`navigate`: no callback → `pop-component-stack/no-stack-in-scope`).
 *
 * Two things are deliberately NOT transcribed, and the ledger note records both: the transitions (the
 * runtime animates every push — `Push` by default — and keeps both components mounted until the
 * animation ends; the export switches in one render, so the `stack-transitioning` and
 * `transition-in-progress` failures cannot occur) and the url (`_updateUrlWithTopPage` runs only with
 * `useRoutes`, which the plan refuses by name).
 *
 * ⚠️ Why a MODULE-LEVEL registry and not React context: the runtime resolves a pusher to its stack by
 * name through a singleton, and a pusher legitimately sits outside the stack's subtree — a tab bar beside
 * the stack, a button in the page that hosts it. Context reaches descendants only. Why the Pop reaches
 * its stack through a PROP (`pageStackEntry`) and not context: the runtime hands the back callback to the
 * Pop nodes in the pushed component's OWN scope only (`getNodesWithType`, non-recursive) — the prop the
 * stack row passes to the component it shows is exactly that reach, and a component placed elsewhere, or
 * shown by Reset / Replace, gets no prop and answers the runtime's own `no-stack-in-scope` failure.
 */

/** Where the module lands in the exported app. */
export const PAGE_STACK_LIB_PATH = 'src/lib/pageStack.ts';

/**
 * The module's source.
 *
 * ⚠️ A plain string array rather than a template literal, for `dateLib.ts`'s stated reason.
 */
export function pageStackLibSource(): string {
  return [
    '//',
    '// The Component Stack family, transcribed from the interpreter it has to agree with:',
    '// noodl-viewer-react/src/nodes/navigation/navigation-handler.ts, navigation-stack.tsx and navigate-back.ts.',
    '//',
    '// A stack registers BY NAME when it mounts; a pusher anywhere in the app finds it by that name. A push is a',
    '// call and a pop is its return: the pusher hands a callback along, and the Pop inside the pushed component',
    '// hands values and a named action back through it. Both stay faithful to the runtime in everything but the',
    '// animation — the export switches components in one render.',
    '//',
    '',
    "import { useEffect, useState } from 'react';",
    '',
    '/** One row of a Component Stack\'s Components list. */',
    'export interface PageStackPage {',
    '  id: string;',
    '  label: string;',
    '}',
    '',
    '/** The Component Inputs a push sets on the component it shows, by port name. */',
    'export type PageStackParams = Record<string, unknown>;',
    '',
    '/** What a pop did — navigation-stack.tsx `StackBackResult`: an end-stop is Unchanged, not a Failure. */',
    'export type StackBackResult = { ok: true } | { ok: false; unchanged: true } | { ok: false; code: string; message: string };',
    '',
    '/** What the stack hands the component it pushed, as its `pageStackEntry` prop: the way back. */',
    'export interface PageStackEntryHandle {',
    '  back(args: { backAction?: string; results?: PageStackParams }): StackBackResult;',
    '}',
    '',
    '/** navigation-handler.ts `StackNavigateArgs` — what a Push Component To Stack asks of its stack. */',
    'export interface StackNavigateArgs {',
    '  target?: string;',
    '  params?: PageStackParams;',
    '  /** The pusher\'s callback: the Pop\'s results, then the back action it was popped under. */',
    '  backCallback?(action: string | undefined, results: PageStackParams): void;',
    '  hasNavigated?(): void;',
    '  hasUnchanged?(): void;',
    '  hasFailed?(code: string, message: string): void;',
    '}',
    '',
    '/** One entry of a stack: which page, with which params, and — for a pushed entry only — the way back. */',
    'export interface PageStackEntry {',
    '  /** Fresh per push, so React mounts a new instance each time, as the runtime creates a new node. */',
    '  key: number;',
    '  pageId: string;',
    '  label: string;',
    '  params: PageStackParams;',
    '  /** Absent on the start component and on a replaced one: neither receives a back callback (navigation-stack.tsx). */',
    '  handle?: PageStackEntryHandle;',
    '}',
    '',
    'interface StackEntryInternal extends PageStackEntry {',
    '  backCallback?: StackNavigateArgs[\'backCallback\'];',
    '}',
    '',
    'let nextEntryKey = 1;',
    '',
    '/** One Component Stack node — navigation-stack.tsx minus the transition and the url. */',
    'export class PageStackStore {',
    '  readonly name: string;',
    '  readonly pages: PageStackPage[];',
    '  readonly startPageId: string | undefined;',
    '  stack: StackEntryInternal[] = [];',
    '  topPageName = \'\';',
    '  stackDepth = 0;',
    '  private readonly listeners = new Set<() => void>();',
    '',
    '  constructor(config: { name: string; pages: PageStackPage[]; startPage?: string }) {',
    "    this.name = config.name || 'Main';",
    '    this.pages = config.pages;',
    '    this.startPageId = config.startPage;',
    '  }',
    '',
    '  subscribe(listener: () => void): () => void {',
    '    this.listeners.add(listener);',
    '    return () => {',
    '      this.listeners.delete(listener);',
    '    };',
    '  }',
    '',
    '  private notify(): void {',
    '    for (const listener of this.listeners) listener();',
    '  }',
    '',
    '  /** `_findPage`: by id first, then by label. */',
    '  private findPage(pageIdOrLabel: string): PageStackPage | undefined {',
    '    return this.pages.find((p) => p.id === pageIdOrLabel) ?? this.pages.find((p) => p.label === pageIdOrLabel);',
    '  }',
    '',
    '  /** `_isAlreadyShowing` — the same page with shallow-identical params is a no-op (NDA-008 §2). */',
    '  private isAlreadyShowing(page: PageStackPage, params: PageStackParams | undefined): boolean {',
    '    const stack = this.stack;',
    '    if (stack.length === 0) return false;',
    '    const top = stack[stack.length - 1];',
    '    if (top.pageId !== page.id) return false;',
    '    const a = top.params;',
    '    const b = params ?? {};',
    '    const aKeys = Object.keys(a);',
    '    const bKeys = Object.keys(b);',
    '    if (aKeys.length !== bKeys.length) return false;',
    '    for (const key of aKeys) {',
    '      if (!Object.prototype.hasOwnProperty.call(b, key)) return false;',
    '      if (a[key] !== b[key]) return false;',
    '    }',
    '    return true;',
    '  }',
    '',
    '  /** `setPageOutputs`: the two outputs, then the re-render. */',
    '  private setPageOutputs(): void {',
    '    const top = this.stack[this.stack.length - 1];',
    "    this.topPageName = top !== undefined ? top.label : '';",
    '    this.stackDepth = this.stack.length;',
    '    this.notify();',
    '  }',
    '',
    '  /** `resetAsync`: everything torn down, the start component rebuilt. The mount path reports nothing. */',
    '  reset(): void {',
    '    if (this.pages.length === 0) return;',
    '    const startPageId = this.startPageId ?? this.pages[0].id;',
    '    const page = this.findPage(startPageId);',
    '    if (page === undefined) return;',
    '    this.stack = [{ key: nextEntryKey++, pageId: page.id, label: page.label, params: {} }];',
    '    this.setPageOutputs();',
    '  }',
    '',
    '  /** `navigateAsync`: the three refusals in the runtime\'s order, the no-op, then the push. */',
    '  navigate(args: StackNavigateArgs): void {',
    '    if (this.pages.length === 0) {',
    "      args.hasFailed?.('push-component-stack/stack-has-no-components', `The Component Stack \"${this.name}\" has no components to show — its Components list is empty`);",
    '      return;',
    '    }',
    '    const pageId = args.target || this.pages[0].id;',
    '    const page = this.findPage(pageId);',
    '    if (page === undefined) {',
    "      args.hasFailed?.('push-component-stack/component-not-found', `The Component Stack \"${this.name}\" has no component \"${pageId}\" — check the Target Page against its Components list`);",
    '      return;',
    '    }',
    '    if (this.isAlreadyShowing(page, args.params)) {',
    '      if (args.hasUnchanged !== undefined) args.hasUnchanged();',
    '      else args.hasNavigated?.();',
    '      return;',
    '    }',
    '    const entry: StackEntryInternal = {',
    '      key: nextEntryKey++,',
    '      pageId: page.id,',
    '      label: page.label,',
    '      params: args.params ?? {},',
    '      backCallback: args.backCallback,',
    '      handle: { back: (backArgs) => this.back(backArgs) }',
    '    };',
    '    this.stack.push(entry);',
    '    this.setPageOutputs();',
    '    args.hasNavigated?.();',
    '  }',
    '',
    '  /** `replaceAsync`: the same three refusals; the no-op only at depth 1; the stack becomes one entry with no way back. */',
    '  replace(args: StackNavigateArgs): void {',
    '    if (this.pages.length === 0) {',
    "      args.hasFailed?.('push-component-stack/stack-has-no-components', `The Component Stack \"${this.name}\" has no components to show — its Components list is empty`);",
    '      return;',
    '    }',
    '    const pageId = args.target || this.pages[0].id;',
    '    const page = this.findPage(pageId);',
    '    if (page === undefined) {',
    "      args.hasFailed?.('push-component-stack/component-not-found', `The Component Stack \"${this.name}\" has no component \"${pageId}\" — check the Target Page against its Components list`);",
    '      return;',
    '    }',
    '    if (this.stack.length === 1 && this.isAlreadyShowing(page, args.params)) {',
    '      if (args.hasUnchanged !== undefined) args.hasUnchanged();',
    '      else args.hasNavigated?.();',
    '      return;',
    '    }',
    '    this.stack = [{ key: nextEntryKey++, pageId: page.id, label: page.label, params: args.params ?? {} }];',
    '    this.setPageOutputs();',
    '    args.hasNavigated?.();',
    '  }',
    '',
    '  /** `back`: an end-stop at the root; otherwise the pusher\'s callback fires, then the top entry goes. */',
    '  back(args: { backAction?: string; results?: PageStackParams }): StackBackResult {',
    '    if (this.stack.length <= 1) return { ok: false, unchanged: true };',
    '    const top = this.stack[this.stack.length - 1];',
    '    top.backCallback?.(args.backAction, args.results ?? {});',
    '    this.stack.pop();',
    '    this.setPageOutputs();',
    '    return { ok: true };',
    '  }',
    '}',
    '',
    '// ---- navigation-handler.ts: the registry -------------------------------------------------------',
    '',
    'const pageStacks: Record<string, PageStackStore[]> = {};',
    "const navigationQueue: Array<{ name: string; args: StackNavigateArgs; type: 'navigate' | 'replace' }> = [];",
    '',
    "function performNavigation(name: string, args: StackNavigateArgs, type: 'navigate' | 'replace'): void {",
    '  const stacks = pageStacks[name];',
    '  if (stacks !== undefined) {',
    "    for (const stack of stacks) type === 'navigate' ? stack.navigate(args) : stack.replace(args);",
    '  } else {',
    '    navigationQueue.push({ name, args, type });',
    '  }',
    '}',
    '',
    '/**',
    " * navigate.ts `settle`: one press reports at most once. `performNavigation` fans out over every stack",
    ' * registered under the name, so without this two same-named stacks would report one push twice.',
    ' */',
    'function settledOnce(args: StackNavigateArgs): StackNavigateArgs {',
    '  let settled = false;',
    '  const once = <T extends unknown[]>(fn: ((...a: T) => void) | undefined) =>',
    '    fn === undefined',
    '      ? undefined',
    '      : (...a: T) => {',
    '          if (settled) return;',
    '          settled = true;',
    '          fn(...a);',
    '        };',
    '  return { ...args, hasNavigated: once(args.hasNavigated), hasUnchanged: once(args.hasUnchanged), hasFailed: once(args.hasFailed) };',
    '}',
    '',
    '/** A Push Component To Stack in Push mode: every stack under the name, or the queue until one mounts. */',
    'export function pushComponent(name: string, args: StackNavigateArgs): void {',
    "  performNavigation(name || 'Main', settledOnce(args), 'navigate');",
    '}',
    '',
    '/** A Push Component To Stack in Replace mode. */',
    'export function replaceComponent(name: string, args: StackNavigateArgs): void {',
    "  performNavigation(name || 'Main', settledOnce(args), 'replace');",
    '}',
    '',
    'function registerPageStack(name: string, stack: PageStackStore): void {',
    '  if (pageStacks[name] === undefined) pageStacks[name] = [];',
    '  pageStacks[name].push(stack);',
    '  let hasReset = false;',
    '  let hasNavigated = false;',
    '  let i = 0;',
    '  while (i < navigationQueue.length) {',
    '    const queued = navigationQueue[i];',
    '    if (queued.name === name) {',
    "      if (queued.type === 'navigate') {",
    '        if (!hasReset) {',
    '          stack.reset();',
    '          hasReset = true;',
    '        }',
    '        stack.navigate(queued.args);',
    '      } else {',
    '        stack.replace(queued.args);',
    '      }',
    '      hasNavigated = true;',
    '      navigationQueue.splice(i, 1);',
    '    } else {',
    '      i++;',
    '    }',
    '  }',
    '  if (!hasNavigated) stack.reset();',
    '}',
    '',
    'function deregisterPageStack(name: string, stack: PageStackStore): void {',
    '  const stacks = pageStacks[name];',
    '  if (stacks === undefined) return;',
    '  const index = stacks.indexOf(stack);',
    '  if (index === -1) return;',
    '  stacks.splice(index, 1);',
    '  if (stacks.length === 0) delete pageStacks[name];',
    '}',
    '',
    '/** A Pop Component Stack\'s Navigate (navigate-back.ts): no way back → the runtime\'s own failure. */',
    'export function popComponent(',
    '  handle: PageStackEntryHandle | undefined,',
    '  args: { backAction?: string; results?: PageStackParams }',
    '): StackBackResult {',
    '  if (handle === undefined) {',
    '    return {',
    '      ok: false,',
    "      code: 'pop-component-stack/no-stack-in-scope',",
    "      message: 'No Component Stack to pop — this node only works inside a component that a Component Stack pushed'",
    '    };',
    '  }',
    '  return handle.back(args);',
    '}',
    '',
    '/** What a Component Stack row reads: the top entry to render, the two outputs, and Reset. */',
    'export interface PageStackHandle {',
    '  /**',
    '   * Every entry, bottom to top. The row renders each one and hides all but the top, because the runtime keeps',
    '   * every page\'s node alive under the top (navigation-stack.tsx keeps the outgoing page as `top.from` and',
    '   * re-adds it on the way back) — a Text or an input in the pusher\'s own component keeps its state across the',
    '   * push and the pop, and the Back Results it renders arrive in a component that is still mounted.',
    '   */',
    '  entries: PageStackEntry[];',
    '  top: PageStackEntry | undefined;',
    '  topPageName: string;',
    '  stackDepth: number;',
    '  reset(): void;',
    '}',
    '',
    '/**',
    ' * A Component Stack node. The store is created once per mount; registration (the runtime\'s `didMount`)',
    ' * is the effect, and it resets the stack — so the first render shows nothing, as the runtime\'s does',
    ' * until its async queue has built the start component. Deregistration is the cleanup.',
    ' */',
    'export function usePageStack(config: { name: string; pages: PageStackPage[]; startPage?: string }): PageStackHandle {',
    '  const [store] = useState(() => new PageStackStore(config));',
    '  const [, setVersion] = useState(0);',
    '  useEffect(() => {',
    '    const unsubscribe = store.subscribe(() => setVersion((v) => v + 1));',
    '    registerPageStack(store.name, store);',
    '    return () => {',
    '      deregisterPageStack(store.name, store);',
    '      unsubscribe();',
    '    };',
    '  }, [store]);',
    '  return {',
    '    entries: store.stack,',
    '    top: store.stack[store.stack.length - 1],',
    '    topPageName: store.topPageName,',
    '    stackDepth: store.stackDepth,',
    '    reset: () => store.reset()',
    '  };',
    '}',
    ''
  ].join('\n');
}
