/**
 * EXP-011 §66 — `Subscribe To Changes` (`SubscribeToChanges`), Tier 3.11's third transport and the last scheduled node:
 * `src/lib/realtime.ts`, the node and the runtime's realtime layer transcribed from
 * `noodl-runtime/src/nodes/std-library/data/subscribetochanges.ts` and `api/backends/realtime/` — `RealtimeSubscription.ts`
 * (the lifecycle every transport shares: one reconnection funnel, the confirmation deadline, fatal-as-data),
 * `SseTransport.ts` (the NodeGX dialect: GET /realtime, the `connected` hello, POST /realtime/subscriptions read by its
 * body, the `change` and `resync` frames) and `SseConnectionPool.ts` (one stream per backend shared by every subscription
 * on it — D46), with the contract's types and timing from `nodegx-backend-contract/realtime.ts`. One hook,
 * `useSubscribeToChanges(source, options, listeners)`: the Class and Enabled are the options (a change re-runs the
 * runtime's reconfigure), the five signal outputs are listeners, every Realtime output a live getter — the streaming
 * table's shape (§58, §64, §65) with no Actions. The module imports `../api/client` (the endpoint, the session — EXP-009's
 * client, so a subscription rides the same backend and the same sign-in the queries do) and `./errors` (a failure raises
 * under the node's own code, subscribe-to-changes/realtime-failed).
 *
 * Only the NodeGX SSE dialect is here: the export's backend is the built-in one, and the runtime's other four transports
 * belong to backends an export has not got.
 *
 * Kept as a quoted line array like the other libs: the specs pin lines of it, and mutation arms anchor on them.
 * Generated from a plain source (realtime-lib-source.ts + gen-rtlib.py, session 90's scratchpad) — regenerate, never
 * hand-edit the array.
 */

/** Where the module lands in the exported app. */
export const REALTIME_LIB_PATH = 'src/lib/realtime.ts';

export function realtimeLibSource(): string {
  return [
    '//',
    '// Subscribe To Changes, transcribed from the interpreter it has to agree with:',
    '// noodl-runtime/src/nodes/std-library/data/subscribetochanges.ts (the node), api/backends/realtime/RealtimeSubscription.ts',
    '// (the lifecycle every transport shares), SseTransport.ts (the NodeGX dialect over Server-Sent Events) and',
    '// SseConnectionPool.ts (one stream per backend, shared by every subscription on it — D46), with the contract\'s types',
    '// and timing from nodegx-backend-contract/realtime.ts.',
    '//',
    '// useSubscribeToChanges(source, options, listeners): a live subscription to one backend class over the project\'s own',
    '// backend (src/api/client.ts\'s ENDPOINT and session) — the Class and Enabled are the options, read live: a change',
    '// re-runs the runtime\'s reconfigure (teardown, then a fresh subscription where one is still wanted); Record Created /',
    '// Updated / Deleted / Records Changed / Realtime Failure are the listeners; every Realtime output is a live getter on',
    '// the handle. The export\'s backend is the built-in one, so only the NodeGX SSE dialect is here: the runtime\'s other',
    '// four transports (PocketBase, Directus, Parse LiveQuery, the unavailable pair) belong to backends an export has not got.',
    '//',
    '',
    'import { useEffect, useReducer, useRef } from \'react\';',
    '',
    'import { ENDPOINT, readSession } from \'../api/client\';',
    'import { raiseAppError } from \'./errors\';',
    '',
    '// ============================================================================',
    '// nodegx-backend-contract/realtime.ts — what arrives, failure, lifecycle, timing, the seams',
    '// ============================================================================',
    '',
    '/**',
    ' * The five things a subscription can report. `init` and `resync` are not writes and that is exactly why they are in',
    ' * the union: `resync` is our own backend saying "you may have missed something, re-run your query" — it has no replay',
    ' * log. A consumer that models only create/update/delete silently ignores the one frame that tells it its view is stale.',
    ' */',
    'export type RealtimeEventType = \'init\' | \'create\' | \'update\' | \'delete\' | \'resync\';',
    '',
    '/**',
    ' * One change, normalised. `ids` is the guarantee (strings, always present for create/update/delete) and `records` the',
    ' * bonus; `recordsComplete` says whether the records are the whole story — `records.length === 0` cannot tell a key-only',
    ' * delete from an empty frame.',
    ' */',
    'export interface RealtimeChange {',
    '  type: RealtimeEventType;',
    '  collection: string;',
    '  ids: string[];',
    '  records: Record<string, unknown>[];',
    '  recordsComplete: boolean;',
    '}',
    '',
    '/** Whether retrying could ever help: a bad token cannot become good by waiting. */',
    'export type RealtimeFailureKind = \'fatal\' | \'retryable\';',
    '',
    '/** Why a subscription is not delivering. Every code here is one a measured failure produced. */',
    'export type RealtimeErrorCode =',
    '  | \'TRANSPORT_UNAVAILABLE\'',
    '  | \'CONNECT_FAILED\'',
    '  | \'CONNECT_TIMEOUT\'',
    '  | \'AUTH_FAILED\'',
    '  | \'SUBSCRIPTION_REJECTED\'',
    '  | \'HEARTBEAT_MISSED\'',
    '  | \'CAPABILITY_UNAVAILABLE\';',
    '',
    '/** A realtime failure. `kind` is required: a transport that reports a failure without saying whether to retry has handed the decision to whoever is least able to make it. */',
    'export interface RealtimeError {',
    '  message: string;',
    '  code: RealtimeErrorCode;',
    '  kind: RealtimeFailureKind;',
    '}',
    '',
    '/**',
    ' * The one classification, as data. `AUTH_FAILED` and `CAPABILITY_UNAVAILABLE` are the fatal pair; everything else is',
    ' * worth another go — including `SUBSCRIPTION_REJECTED`, because the rejection may be a permission a later login fixes.',
    ' */',
    'export const REALTIME_FAILURE_KINDS: Readonly<Record<RealtimeErrorCode, RealtimeFailureKind>> = Object.freeze({',
    '  TRANSPORT_UNAVAILABLE: \'fatal\',',
    '  CONNECT_FAILED: \'retryable\',',
    '  CONNECT_TIMEOUT: \'retryable\',',
    '  AUTH_FAILED: \'fatal\',',
    '  SUBSCRIPTION_REJECTED: \'retryable\',',
    '  HEARTBEAT_MISSED: \'retryable\',',
    '  CAPABILITY_UNAVAILABLE: \'fatal\'',
    '});',
    '',
    '/**',
    ' * What a subscription is doing right now. Four states, not a boolean: "connecting for the first time" and "dropped and',
    ' * retrying" want different things on screen, and a fatal stop must not read like a slow connect.',
    ' */',
    'export type RealtimeStatus = \'connecting\' | \'subscribed\' | \'interrupted\' | \'stopped\';',
    '',
    '/** Why a connection went down: the `close` path, the `error` path, the deadline, or a missed keepalive. */',
    'export type RealtimeDownReason = \'closed\' | \'errored\' | \'connect-timeout\' | \'heartbeat-missed\';',
    '',
    '/** Timing, in one place, so "1s doubling to 30s" is a fact rather than a habit. */',
    'export interface RealtimeTiming {',
    '  readonly reconnectBaseMs: number;',
    '  readonly reconnectMaxMs: number;',
    '  /** How long a subscription may sit un-confirmed before the deadline fires. */',
    '  readonly connectTimeoutMs: number;',
    '}',
    '',
    '/** The shipped defaults: the backoff pair survived a live backend restart; 15s is comfortably above every measured connect. */',
    'export const REALTIME_TIMING: RealtimeTiming = Object.freeze({',
    '  reconnectBaseMs: 1000,',
    '  reconnectMaxMs: 30000,',
    '  connectTimeoutMs: 15000',
    '});',
    '',
    '/** Exponential backoff: 1s, 2s, 4s … capped at 30s. A subscription that retries every 4ms looks exactly like one that is working, from the outside. */',
    'export function nextReconnectDelay(attempt: number, timing: RealtimeTiming = REALTIME_TIMING): number {',
    '  const n = Number.isFinite(attempt) && attempt > 0 ? Math.floor(attempt) : 0;',
    '  return Math.min(timing.reconnectMaxMs, timing.reconnectBaseMs * Math.pow(2, Math.min(n, 30)));',
    '}',
    '',
    '/** An `EventSource` as a transport uses one. */',
    'export interface RealtimeEventSourceLike {',
    '  addEventListener(type: string, listener: (event: { data: string }) => void): void;',
    '  onerror: ((...args: unknown[]) => void) | null;',
    '  close(): void;',
    '}',
    '',
    '/** `fetch`, as narrowly as a transport uses one. */',
    'export interface RealtimeFetchResponse {',
    '  status?: number;',
    '  ok?: boolean;',
    '  json?(): Promise<unknown>;',
    '  text?(): Promise<string>;',
    '}',
    '',
    'export type RealtimeFetch = (url: string, init?: unknown) => Promise<RealtimeFetchResponse>;',
    '',
    '/**',
    ' * Everything a transport touches that is not its own logic — the runtime\'s own test seam. Every field is optional and',
    ' * falls back to the host global; an explicit `null` means "this host has none" (`\'EventSourceImpl\' in deps`).',
    ' */',
    'export interface RealtimeDeps {',
    '  EventSourceImpl?: (new (url: string) => RealtimeEventSourceLike) | null;',
    '  fetchImpl?: RealtimeFetch;',
    '  setTimeoutImpl?: (fn: () => void, delay: number) => unknown;',
    '  clearTimeoutImpl?: (handle: unknown) => void;',
    '}',
    '',
    '/** A subscription\'s server-side filter, in the backend\'s own `$` dialect. Never applied client-side. */',
    'export type RealtimeFilter = Record<string, unknown>;',
    '',
    'export interface RealtimeCallbacks {',
    '  onEvent?: (change: RealtimeChange) => void;',
    '  onStatus?: (status: RealtimeStatus) => void;',
    '  onError?: (error: RealtimeError) => void;',
    '}',
    '',
    '/** What to watch. */',
    'export interface RealtimeSubscribeOptions extends RealtimeCallbacks {',
    '  collection: string;',
    '  where?: RealtimeFilter;',
    '  deps?: RealtimeDeps;',
    '  timing?: RealtimeTiming;',
    '}',
    '',
    '/** The backend a subscription rides: the project\'s own, as src/api/client.ts reaches it. */',
    'export interface BackendHandle {',
    '  url: string;',
    '  sessionToken?: string;',
    '}',
    '',
    '// ============================================================================',
    '// RealtimeSubscription.ts — the lifecycle every realtime transport shares',
    '// ============================================================================',
    '',
    '/**',
    ' * Everything a subscription is built from. `primaryKey` names the field carrying the record id, for the transports that',
    ' * send whole records; the node layer knows the schema.',
    ' */',
    'export interface RealtimeSubscriptionOptions extends RealtimeSubscribeOptions {',
    '  /** Field name carrying the record id. Defaults to `id`. */',
    '  primaryKey?: string;',
    '}',
    '',
    '/** How long a subscription may sit un-confirmed before the deadline fires, when the caller has not said. */',
    'const DEFAULT_TIMING: RealtimeTiming = REALTIME_TIMING;',
    '',
    '/**',
    ' * The host identity of every caller that named no `RealtimeDeps` of its own — so that "the browser" is one host rather',
    ' * than one per subscription, which is what lets the pool put two production subscriptions on the same stream while',
    ' * keeping two tests with their own doubles apart.',
    ' */',
    'const DEFAULT_HOST: object = {};',
    '',
    '/**',
    ' * One subscription, and the state machine it runs. Subclasses implement two methods — open a connection, close it — and',
    ' * report through `confirmed`, `emitChange`, `fail` and `transportDownFrom`. Everything else (status, backoff, deadlines,',
    ' * dispose idempotence, the once-per-socket guard) is here, once.',
    ' *',
    ' * Three rules the transports do not get to decide: reconnection has ONE entry (`transportDownFrom`, at most once per',
    ' * socket, a straggler from a replaced socket dropped); the deadline is a CONFIRMATION deadline, armed whenever the',
    ' * subscription is not `subscribed` (three of the five backends will hold an open connection that never confirms',
    ' * anything); fatal is data, not judgement (`REALTIME_FAILURE_KINDS`), overridden only where a transport can prove it.',
    ' */',
    'export abstract class RealtimeSubscription {',
    '  readonly collection: string;',
    '  /** Which wire this subclass speaks. */',
    '  abstract readonly transport: string;',
    '',
    '  protected readonly handle: BackendHandle;',
    '  protected readonly where?: RealtimeFilter;',
    '  protected readonly primaryKey: string;',
    '  protected readonly timing: RealtimeTiming;',
    '  private readonly _deps: RealtimeDeps;',
    '  private readonly _hostKey: object;',
    '',
    '  private readonly _onEvent?: (change: RealtimeChange) => void;',
    '  private readonly _onStatus?: (status: RealtimeStatus) => void;',
    '  private readonly _onError?: (error: RealtimeError) => void;',
    '',
    '  private _status: RealtimeStatus = \'connecting\';',
    '  private _attempt = 0;',
    '  /** Which socket is current. Incremented on every `connect`; a report tagged with an older number is a straggler. */',
    '  private _generation = 0;',
    '  private _downGeneration = -1;',
    '  /** The last generation that reached `subscribed`. */',
    '  private _confirmedGeneration = -1;',
    '  /** The last generation a transport reported a reason for, so it is not reported twice. */',
    '  private _reportedGeneration = -1;',
    '  private _reconnectTimer: unknown = null;',
    '  private _deadlineTimer: unknown = null;',
    '  private _disposed = false;',
    '',
    '  constructor(handle: BackendHandle, options: RealtimeSubscriptionOptions) {',
    '    this.handle = handle;',
    '    this.collection = options.collection;',
    '    this.where = options.where;',
    '    this.primaryKey = options.primaryKey || \'id\';',
    '    this.timing = options.timing || DEFAULT_TIMING;',
    '    this._deps = options.deps || {};',
    '    // ⚠️ The object the caller passed, not `this._deps` — the `|| {}` above mints a fresh one per subscription, which',
    '    // as a key would mean nothing ever shares anything.',
    '    this._hostKey = options.deps || DEFAULT_HOST;',
    '    this._onEvent = options.onEvent;',
    '    this._onStatus = options.onStatus;',
    '    this._onError = options.onError;',
    '  }',
    '',
    '  get status(): RealtimeStatus {',
    '    return this._status;',
    '  }',
    '',
    '  // ── the state machine ────────────────────────────────────────────────────',
    '',
    '  connect(): void {',
    '    if (this._disposed || this._status === \'stopped\') return;',
    '',
    '    this._clearTimer(\'_reconnectTimer\');',
    '    const generation = ++this._generation;',
    '    this._setStatus(this._attempt === 0 ? \'connecting\' : \'interrupted\');',
    '    this._armDeadline(generation);',
    '',
    '    try {',
    '      this.openTransport(generation);',
    '    } catch (e) {',
    '      // A constructor that throws (an unparseable URL is the measured case) is not a socket that will ever report',
    '      // anything, so it has to be reported here.',
    '      this.fail(\'CONNECT_FAILED\', \'Could not open a realtime connection: \' + errorMessage(e));',
    '      this.transportDownFrom(generation, \'errored\');',
    '    }',
    '  }',
    '',
    '  /**',
    '   * The server acknowledged the subscription. Not "the socket opened". Resets the backoff counter, which is why a',
    '   * flapping backend does not walk the delay up to 30s and stay there.',
    '   */',
    '  confirmed(): void {',
    '    if (this._disposed || this._status === \'stopped\') return;',
    '    this._clearTimer(\'_deadlineTimer\');',
    '    this._attempt = 0;',
    '    this._confirmedGeneration = this._generation;',
    '    this._setStatus(\'subscribed\');',
    '  }',
    '',
    '  /** The current socket went down. */',
    '  transportDown(reason: RealtimeDownReason): void {',
    '    this.transportDownFrom(this._generation, reason);',
    '  }',
    '',
    '  /**',
    '   * The single funnel, tagged with the socket that is reporting. Drops a report from a superseded socket, and a second',
    '   * report from the current one — the browser fires `error` AND `close` for the same failure.',
    '   */',
    '  protected transportDownFrom(generation: number, reason: RealtimeDownReason): void {',
    '    if (generation !== this._generation) return;',
    '    if (this._downGeneration === generation) return;',
    '    this._downGeneration = generation;',
    '',
    '    this._clearTimer(\'_deadlineTimer\');',
    '    this._safeClose();',
    '',
    '    if (this._disposed || this._status === \'stopped\') return;',
    '',
    '    this._setStatus(\'interrupted\');',
    '    this.onTransportDown(reason);',
    '',
    '    // ⚠️ A connection that goes down having NEVER confirmed is a failure, and it needs a reason. A confirmed connection',
    '    // going down is not: a backend restart is an ordinary event. `connect-timeout` and `heartbeat-missed` are excluded',
    '    // because they have already reported their own.',
    '    if (',
    '      this._confirmedGeneration !== generation &&',
    '      this._reportedGeneration !== generation &&',
    '      (reason === \'errored\' || reason === \'closed\')',
    '    ) {',
    '      const fatal = this.fail(',
    '        \'CONNECT_FAILED\',',
    '        `The realtime connection to "${this.collection}" went down before it was confirmed (${reason}).`',
    '      );',
    '      if (fatal) return;',
    '    }',
    '',
    '    const delay = nextReconnectDelay(this._attempt++, this.timing);',
    '    this._reconnectTimer = this._setTimeout(() => {',
    '      this._reconnectTimer = null;',
    '      this.connect();',
    '    }, delay);',
    '  }',
    '',
    '  /**',
    '   * Report a failure, and stop for good if it is a fatal one. `kind` defaults from the one classification and is only',
    '   * passed explicitly where a transport can prove the general rule wrong (a backend URL that is not http(s)).',
    '   */',
    '  protected fail(code: RealtimeErrorCode, message: string, kind?: RealtimeFailureKind): boolean {',
    '    const error: RealtimeError = { message, code, kind: kind || REALTIME_FAILURE_KINDS[code] };',
    '    this._reportedGeneration = this._generation;',
    '    this._notify(\'onError\', () => this._onError && this._onError(error));',
    '',
    '    if (error.kind !== \'fatal\') return false;',
    '',
    '    this._clearTimer(\'_deadlineTimer\');',
    '    this._clearTimer(\'_reconnectTimer\');',
    '    this._safeClose();',
    '    this._setStatus(\'stopped\');',
    '    return true;',
    '  }',
    '',
    '  /**',
    '   * The connection is in trouble but is recovering itself, so do not tear it down — the `EventSource` case, and only',
    '   * that case: its retry carries `Last-Event-ID`, which is what earns our backend\'s `resync` frame.',
    '   *',
    '   * ⚠️ The deadline is armed at most once per generation. Re-arming on every `error` would let a stream that errors',
    '   * every three seconds postpone the funnel forever.',
    '   */',
    '  protected interrupted(generation: number): void {',
    '    if (generation !== this._generation) return;',
    '    if (this._disposed || this._status === \'stopped\') return;',
    '    this._setStatus(\'interrupted\');',
    '    if (this._deadlineTimer === null) this._armDeadline(generation);',
    '  }',
    '',
    '  protected emitChange(change: RealtimeChange): void {',
    '    if (this._disposed) return;',
    '    this._notify(\'onEvent\', () => this._onEvent && this._onEvent(change));',
    '  }',
    '',
    '  /**',
    '   * Run a consumer callback without letting it take the transport down with it: a realtime callback runs from inside',
    '   * an SSE listener, where a throw would skip the transport\'s own bookkeeping. Reported and contained, not swallowed.',
    '   */',
    '  private _notify(what: string, run: () => void): void {',
    '    try {',
    '      run();',
    '    } catch (e) {',
    '      // eslint-disable-next-line no-console',
    '      console.error(`[realtime] a ${what} handler for "${this.collection}" threw; the subscription is unaffected.`, e);',
    '    }',
    '  }',
    '',
    '  dispose(): void {',
    '    if (this._disposed) return;',
    '    this._disposed = true;',
    '    this._clearTimer(\'_deadlineTimer\');',
    '    this._clearTimer(\'_reconnectTimer\');',
    '    this._safeClose();',
    '    // Deliberately silent: the caller disposing is the caller that would be told.',
    '    this._status = \'stopped\';',
    '  }',
    '',
    '  // ── what subclasses implement ────────────────────────────────────────────',
    '',
    '  /** Open a connection and wire it to report through `transportDownFrom` with `generation`, `confirmed`, `emitChange` and `fail`. */',
    '  protected abstract openTransport(generation: number): void;',
    '',
    '  /** Close whatever `openTransport` opened. Called more than once; must not throw. */',
    '  protected abstract closeTransport(): void;',
    '',
    '  /** A hook for per-transport teardown that is not closing the socket. */',
    '  protected onTransportDown(_reason: RealtimeDownReason): void {',
    '    /* nothing by default */',
    '  }',
    '',
    '  // ── deps, resolved the way the shipped node did ──────────────────────────',
    '',
    '  /** Which host this subscription runs in — the identity a shared connection is keyed on. */',
    '  protected get hostKey(): object {',
    '    return this._hostKey;',
    '  }',
    '',
    '  protected resolveEventSource(): (new (url: string) => RealtimeEventSourceLike) | null {',
    '    if (\'EventSourceImpl\' in this._deps) return this._deps.EventSourceImpl ?? null;',
    '    return typeof EventSource !== \'undefined\' ? (EventSource as unknown as new (url: string) => RealtimeEventSourceLike) : null;',
    '  }',
    '',
    '  protected resolveFetch(): RealtimeFetch | null {',
    '    if (this._deps.fetchImpl) return this._deps.fetchImpl;',
    '    return typeof fetch !== \'undefined\' ? (fetch.bind(globalThis) as RealtimeFetch) : null;',
    '  }',
    '',
    '  protected _setTimeout(fn: () => void, delay: number): unknown {',
    '    const impl = this._deps.setTimeoutImpl || setTimeout.bind(globalThis);',
    '    return impl(fn, delay);',
    '  }',
    '',
    '  protected _clearTimeout(handle: unknown): void {',
    '    // Typed at the seam\'s width: the emitted app\'s tsconfig refuses `clearTimeout(unknown)` where the runtime\'s does not.',
    '    const impl: (handle: unknown) => void = this._deps.clearTimeoutImpl || ((h: unknown) => clearTimeout(h as ReturnType<typeof setTimeout>));',
    '    impl(handle);',
    '  }',
    '',
    '  // ── internals ────────────────────────────────────────────────────────────',
    '',
    '  /**',
    '   * The token a subscription carries: the session\'s, or none. 🔴 SBR-011: on the Parse wire there is no public token —',
    '   * `publicToken` there holds the APPLICATION ID, and handing it to `?token=` was read as a session token and refused',
    '   * (400 `Invalid session token`) before the stream opened. The empty string is the correct token for an anonymous',
    '   * subscriber: the hub accepts it, and delivery is gated per event on the row ACL.',
    '   */',
    '  protected get token(): string {',
    '    return this.handle.sessionToken || \'\';',
    '  }',
    '',
    '  private _armDeadline(generation: number): void {',
    '    this._clearTimer(\'_deadlineTimer\');',
    '    this._deadlineTimer = this._setTimeout(() => {',
    '      this._deadlineTimer = null;',
    '      this.fail(',
    '        \'CONNECT_TIMEOUT\',',
    '        `The realtime subscription to "${this.collection}" was not confirmed within ${this.timing.connectTimeoutMs}ms.`',
    '      );',
    '      this.transportDownFrom(generation, \'connect-timeout\');',
    '    }, this.timing.connectTimeoutMs);',
    '  }',
    '',
    '  private _clearTimer(which: \'_reconnectTimer\' | \'_deadlineTimer\'): void {',
    '    const handle = this[which];',
    '    if (handle === null || handle === undefined) return;',
    '    this[which] = null;',
    '    this._clearTimeout(handle);',
    '  }',
    '',
    '  private _safeClose(): void {',
    '    try {',
    '      this.closeTransport();',
    '    } catch (e) {',
    '      /* already closed, or never finished connecting */',
    '    }',
    '  }',
    '',
    '  private _setStatus(status: RealtimeStatus): void {',
    '    if (this._status === status) return;',
    '    this._status = status;',
    '    this._notify(\'onStatus\', () => this._onStatus && this._onStatus(status));',
    '  }',
    '}',
    '',
    'export function errorMessage(e: unknown): string {',
    '  if (e && typeof e === \'object\' && \'message\' in e) return String((e as { message: unknown }).message);',
    '  return String(e);',
    '}',
    '',
    '/** `http(s)://host/path` with any trailing slashes removed, or `null` if it is not one. */',
    'export function normalizedHttpBase(url: string | undefined): string | null {',
    '  if (!url || typeof url !== \'string\') return null;',
    '  const cleaned = url.trim().replace(/\\/+$/, \'\');',
    '  return /^https?:\\/\\//i.test(cleaned) ? cleaned : null;',
    '}',
    '',
    '// ============================================================================',
    '// SseTransport.ts — the NodeGX dialect: GET /realtime, the `connected` hello, POST /realtime/subscriptions, `change`',
    '// ============================================================================',
    '',
    '/** What the subscription POST said, once the body has been read. */',
    'export interface SseSubscribeVerdict {',
    '  ok: boolean;',
    '  /** Present when `ok` is false and the server said why. */',
    '  reason?: string;',
    '}',
    '',
    '/** One SSE server\'s dialect. Every field is a place the measured servers differ. */',
    'export interface SseDialect {',
    '  readonly name: string;',
    '  /** The stream URL, token included where the server takes one in the query string. */',
    '  streamUrl(base: string, token: string): string;',
    '  /** The event name carrying `{clientId}`. */',
    '  readonly helloEvent: string;',
    '  /** The event names carrying changes. */',
    '  changeEvents(collection: string): string[];',
    '  /** Extra event names to listen for, mapped straight to a `RealtimeChange` type. */',
    '  readonly resyncEvent?: string;',
    '  /**',
    '   * The registration request for EVERY subscription on this stream at once. ⚠️ An array, not one collection, because',
    '   * the POST REPLACES the set for a `clientId`.',
    '   */',
    '  subscribeRequest(base: string, token: string, clientId: string, subscriptions: readonly SseSubscriptionRequest[]): { url: string; init: Record<string, unknown> };',
    '  /** Whether the registration took FOR ONE COLLECTION, from the status and the body — a union POST can be answered with some accepted and some rejected. */',
    '  readVerdict(status: number | undefined, body: unknown, collection: string): SseSubscribeVerdict;',
    '  /** One change frame, normalised. `null` for a frame this dialect ignores. */',
    '  parseChange(collection: string, primaryKey: string, raw: unknown): RealtimeChange | null;',
    '}',
    '',
    '/** `{accepted, rejected}` — the body our own backend answers a subscription POST with. */',
    'interface NodeGXVerdictBody {',
    '  accepted?: unknown[];',
    '  rejected?: { collection?: string; reason?: string }[];',
    '}',
    '',
    '/** Whether an `accepted[]` / `rejected[]` entry is about `collection`. An entry that names nothing is about whatever is asking. */',
    'function entryIsAbout(entry: unknown, collection: string): boolean {',
    '  if (!entry || typeof entry !== \'object\') return true;',
    '  const named = (entry as { collection?: unknown }).collection;',
    '  if (typeof named !== \'string\') return true;',
    '  return named === collection;',
    '}',
    '',
    '/**',
    ' * Our own backend (BAK-001\'s ChangeBus, over SSE), every cell measured: stream `GET /realtime?token=`; hello',
    ' * `event: connected` `{clientId}`; register `POST /realtime/subscriptions {clientId, subscriptions:[{collection, filter?}]}`;',
    ' * confirmed by `200` WITH a non-empty `accepted[]` (the status is 200 for a rejection too); change frame `change`',
    ' * `{action, collection, record}`, a delete carrying the whole pre-delete record; keepalive `: heartbeat` at 25s.',
    ' */',
    'export const NODEGX_SSE: SseDialect = {',
    '  name: \'nodegx\',',
    '  // EventSource cannot set headers, so the token rides in the query string, where the server reads it.',
    '  streamUrl: (base, token) => base + \'/realtime\' + (token ? \'?token=\' + encodeURIComponent(token) : \'\'),',
    '  helloEvent: \'connected\',',
    '  changeEvents: () => [\'change\'],',
    '  resyncEvent: \'resync\',',
    '  subscribeRequest(base, token, clientId, subscriptions) {',
    '    // ⚠️ `where` is the Parse-style `$` grammar; the hub fails CLOSED on an operator it cannot evaluate.',
    '    const body = subscriptions.map((subscription) =>',
    '      subscription.where === undefined ? { collection: subscription.collection } : { collection: subscription.collection, filter: subscription.where }',
    '    );',
    '    const headers: Record<string, string> = { \'content-type\': \'application/json\' };',
    '    if (token) headers[\'authorization\'] = \'Bearer \' + token;',
    '    return {',
    '      url: base + \'/realtime/subscriptions\',',
    '      init: {',
    '        method: \'POST\',',
    '        headers,',
    '        body: JSON.stringify({ clientId, subscriptions: body })',
    '      }',
    '    };',
    '  },',
    '  readVerdict(_status, body, collection) {',
    '    // ⚠️ The status is 200 either way. `accepted[]` is the answer — and on a union POST it is the answer for some',
    '    // collections and not others, so read the entries, not the length.',
    '    const verdict = (body || {}) as NodeGXVerdictBody;',
    '    const accepted = Array.isArray(verdict.accepted) ? verdict.accepted : [];',
    '    if (accepted.some((entry) => entryIsAbout(entry, collection))) return { ok: true };',
    '    const rejected = Array.isArray(verdict.rejected) ? verdict.rejected : [];',
    '    const mine = rejected.filter((entry) => entryIsAbout(entry, collection))[0];',
    '    return { ok: false, reason: (mine && mine.reason) || undefined };',
    '  },',
    '  parseChange(collection, primaryKey, raw) {',
    '    const payload = raw as { action?: string; collection?: string; record?: Record<string, unknown> };',
    '    const action = payload && payload.action;',
    '    if (action !== \'create\' && action !== \'update\' && action !== \'delete\') return null;',
    '    // A shared stream would deliver other collections; the frame carries the name so the check is free.',
    '    if (payload.collection && payload.collection !== collection) return null;',
    '',
    '    const record = payload.record;',
    '    const id = record ? record.objectId ?? record[primaryKey] : undefined;',
    '    return {',
    '      type: action,',
    '      collection,',
    '      ids: id === undefined || id === null ? [] : [String(id)],',
    '      // Measured: a delete carries the whole record as it was immediately before.',
    '      records: record ? [record] : [],',
    '      recordsComplete: !!record',
    '    };',
    '  }',
    '};',
    '',
    '/**',
    ' * One subscription, riding a stream it shares with every other subscription on the same backend. The shared connection',
    ' * owns the socket, the client id and the union registration; this class owns one subscription\'s state machine — its',
    ' * generation, its confirmation deadline, its backoff. A member reports INTO itself through the callbacks below, which',
    ' * is why a rejection takes one subscription down and leaves its neighbours subscribed.',
    ' */',
    'export class SseTransport extends RealtimeSubscription {',
    '  readonly transport = \'sse\';',
    '',
    '  private readonly _dialect: SseDialect;',
    '  private _connection: SharedSseConnection | null = null;',
    '  private _member: SseMember | null = null;',
    '',
    '  constructor(handle: BackendHandle, options: RealtimeSubscriptionOptions, dialect: SseDialect) {',
    '    super(handle, options);',
    '    this._dialect = dialect;',
    '  }',
    '',
    '  /** Which SSE server this is talking to. */',
    '  get dialect(): string {',
    '    return this._dialect.name;',
    '  }',
    '',
    '  protected openTransport(generation: number): void {',
    '    const EventSourceImpl = this.resolveEventSource();',
    '    if (!EventSourceImpl) {',
    '      // Node 22 has `WebSocket` and no `EventSource` (measured) — the node is client-only for this reason too.',
    '      this.fail(\'TRANSPORT_UNAVAILABLE\', \'EventSource is not available in this environment.\');',
    '      return;',
    '    }',
    '',
    '    // ⚠️ Resolved here rather than when the hello frame arrives: a host with an `EventSource` and no `fetch` cannot',
    '    // register anything, so finding out before opening a stream is strictly better than after.',
    '    const fetchImpl = this.resolveFetch();',
    '    if (!fetchImpl) {',
    '      this.fail(\'TRANSPORT_UNAVAILABLE\', \'fetch is not available to register the realtime subscription.\');',
    '      return;',
    '    }',
    '',
    '    const base = normalizedHttpBase(this.handle.url);',
    '    if (!base) {',
    '      this.fail(\'CONNECT_FAILED\', `Backend URL is not a valid http(s) URL: ${this.handle.url}`, \'fatal\');',
    '      return;',
    '    }',
    '',
    '    const connection = connectionFor({',
    '      host: this.hostKey,',
    '      dialect: this._dialect,',
    '      base,',
    '      token: this.token,',
    '      EventSourceImpl,',
    '      fetchImpl,',
    '      where: this.where',
    '    });',
    '    const member = this._buildMember(generation);',
    '    this._connection = connection;',
    '    this._member = member;',
    '    connection.join(member);',
    '  }',
    '',
    '  protected closeTransport(): void {',
    '    const connection = this._connection;',
    '    const member = this._member;',
    '    this._connection = null;',
    '    this._member = null;',
    '    // ⚠️ Leaving is not the same as closing: the stream stays up for whoever else is on it, and the registry re-POSTs',
    '    // the union without this one. It closes only when the last member has gone.',
    '    if (connection && member) connection.leave(member);',
    '  }',
    '',
    '  /** This subscription\'s face to the shared connection — a fresh one per generation, so a late report for a connection this subscription has already left is dropped by the registry. */',
    '  private _buildMember(generation: number): SseMember {',
    '    const dialect = this._dialect;',
    '    return {',
    '      collection: this.collection,',
    '      where: this.where,',
    '',
    '      receiveFrame: (raw: unknown): void => {',
    '        const change = dialect.parseChange(this.collection, this.primaryKey, raw);',
    '        if (change) this.emitChange(change);',
    '      },',
    '',
    '      receiveResync: (): void => {',
    '        // No replay log. `resync` is the frame that says "your view may be stale, re-run your query".',
    '        this.emitChange({',
    '          type: \'resync\',',
    '          collection: this.collection,',
    '          ids: [],',
    '          records: [],',
    '          recordsComplete: false',
    '        });',
    '      },',
    '',
    '      settle: (verdict: SseSubscribeVerdict): void => {',
    '        if (verdict.ok) {',
    '          this.confirmed();',
    '          return;',
    '        }',
    '        this.fail(\'SUBSCRIPTION_REJECTED\', `The subscription to "${this.collection}" was rejected: ${verdict.reason || \'no reason given\'}`);',
    '        // Retryable in the table, so hand it to the one backoff rather than staying on a stream that will never',
    '        // deliver to this member until the deadline notices.',
    '        this.transportDownFrom(generation, \'closed\');',
    '      },',
    '',
    '      interrupt: (): void => {',
    '        // ⚠️ `EventSource` reconnects on its own, and its retry keeps `Last-Event-ID` — which is what earns our',
    '        // backend\'s `resync` frame. So an error is NOT reported down the funnel immediately: the confirmation deadline',
    '        // is re-armed instead, and if the stream has not delivered a fresh hello frame by the time it fires, the funnel',
    '        // runs and our own backoff takes over.',
    '        this.interrupted(generation);',
    '      },',
    '',
    '      abort: (message: string): void => {',
    '        this.fail(\'CONNECT_FAILED\', message);',
    '        this.transportDownFrom(generation, \'closed\');',
    '      }',
    '    };',
    '  }',
    '}',
    '',
    '// ============================================================================',
    '// SseConnectionPool.ts — one SSE connection per backend, shared by every subscription on it (D46)',
    '// ============================================================================',
    '//',
    '// A browser holds six connections per origin. An SSE stream never ends, so six subscriptions hold all six, and every',
    '// OTHER request to that backend — the app\'s queries, its writes, and the registration POSTs those very streams are',
    '// waiting for — sits in the browser\'s queue; measured: the sixth stream\'s POST read `queued 15007ms, waited 5ms`. So',
    '// every UNFILTERED subscription on one backend shares one stream, the union of their collections in one POST. A',
    '// subscription with a `where` gets its own connection (a shared stream delivers the union, and a consumer here filters',
    '// only by collection name). The host is part of the key: production passes no deps and shares one pool; a test passing',
    '// its own doubles is isolated by construction.',
    '',
    '/** One entry in the union a registration POST carries. */',
    'export interface SseSubscriptionRequest {',
    '  collection: string;',
    '  where?: RealtimeFilter;',
    '}',
    '',
    '/** What a shared connection needs of the subscription riding on it — every call a report INTO the member\'s own state machine. */',
    'export interface SseMember {',
    '  readonly collection: string;',
    '  readonly where: RealtimeFilter | undefined;',
    '  /** A change frame arrived on this member\'s collection; `raw` is the parsed payload. */',
    '  receiveFrame(raw: unknown): void;',
    '  /** The server sent the dialect\'s resync frame. */',
    '  receiveResync(): void;',
    '  /** The union POST came back, and this is what it said about THIS member. */',
    '  settle(verdict: SseSubscribeVerdict): void;',
    '  /** The stream errored. `EventSource` retries on its own, so this is not a teardown. */',
    '  interrupt(): void;',
    '  /** The registration could not be made at all. */',
    '  abort(message: string): void;',
    '}',
    '',
    '/** A filter, as a string that is equal exactly when two filters are. Key-order sensitive: that costs an extra connection and never costs correctness. */',
    'export function filterKey(where: RealtimeFilter | undefined): string {',
    '  if (where === undefined || where === null) return \'\';',
    '  try {',
    '    return JSON.stringify(where);',
    '  } catch (e) {',
    '    return \' uncomparable \';',
    '  }',
    '}',
    '',
    '/** The identity of the connection a member belongs on. */',
    'export function connectionKey(dialect: string, base: string, token: string, where: RealtimeFilter | undefined): string {',
    '  const filter = filterKey(where);',
    '  return dialect + \' \' + base + \' \' + token + (filter ? \' #\' + filter : \'\');',
    '}',
    '',
    '/**',
    ' * One `EventSource`, the registry of who is on it, and the union POST.',
    ' *',
    ' * Two things a registry has to get right: the POST REPLACES the set (so every membership change re-POSTs the union, at',
    ' * most one POST is in flight, and a POST that completes against a superseded `clientId` re-posts instead of settling',
    ' * anybody); and a listener per collection, added when the first member of that collection joins, never removed (the',
    ' * re-POST stops the server sending that collection at all, and the listener set dies with the `EventSource`).',
    ' */',
    'export class SharedSseConnection {',
    '  private _es: RealtimeEventSourceLike | null = null;',
    '  private _clientId: string | null = null;',
    '  private readonly _members = new Set<SseMember>();',
    '  /** Collections this stream already has change listeners for. Never shrinks. */',
    '  private readonly _listening = new Set<string>();',
    '  /** Bumped by every membership change; what `_postedRevision` is compared against. */',
    '  private _revision = 0;',
    '  private _postedRevision = -1;',
    '  private _inFlight = false;',
    '',
    '  constructor(',
    '    private readonly _dialect: SseDialect,',
    '    private readonly _base: string,',
    '    private readonly _token: string,',
    '    private readonly _EventSourceImpl: new (url: string) => RealtimeEventSourceLike,',
    '    private readonly _fetchImpl: RealtimeFetch,',
    '    /** Called when the last member leaves, so the pool can drop this entry. */',
    '    private readonly _onEmpty: () => void',
    '  ) {}',
    '',
    '  get size(): number {',
    '    return this._members.size;',
    '  }',
    '',
    '  /** The stream\'s current client id, or `null` while it is waiting for the hello frame. */',
    '  get clientId(): string | null {',
    '    return this._clientId;',
    '  }',
    '',
    '  join(member: SseMember): void {',
    '    if (this._members.has(member)) return;',
    '    this._members.add(member);',
    '    this._revision++;',
    '    if (!this._es) {',
    '      this._open();',
    '      return;',
    '    }',
    '    // Joining a stream that is already up: the registration is owed as soon as there is a client id to register against.',
    '    this._listen(member.collection);',
    '    this._post();',
    '  }',
    '',
    '  leave(member: SseMember): void {',
    '    if (!this._members.delete(member)) return;',
    '    this._revision++;',
    '    if (this._members.size === 0) {',
    '      this._closeStream();',
    '      this._onEmpty();',
    '      return;',
    '    }',
    '    // The POST replaces the set, so a member leaving is a re-POST, not a no-op.',
    '    this._post();',
    '  }',
    '',
    '  // -- the stream -----------------------------------------------------------',
    '',
    '  private _open(): void {',
    '    const dialect = this._dialect;',
    '    const es = new this._EventSourceImpl(dialect.streamUrl(this._base, this._token));',
    '    this._es = es;',
    '    this._clientId = null;',
    '    this._listening.clear();',
    '    for (const member of this._members) this._listen(member.collection);',
    '',
    '    es.addEventListener(dialect.helloEvent, (event) => {',
    '      if (this._es !== es) return;',
    '      let clientId: string | undefined;',
    '      try {',
    '        clientId = (JSON.parse(event.data) as { clientId?: string }).clientId;',
    '      } catch (e) {',
    '        return;',
    '      }',
    '      if (!clientId) return;',
    '      // A fresh id on every connection, including an `EventSource`-initiated reconnect no member ever saw — so',
    '      // registering again is mandatory, not an optimisation.',
    '      this._clientId = clientId;',
    '      this._postedRevision = -1;',
    '      this._post();',
    '    });',
    '',
    '    if (dialect.resyncEvent) {',
    '      es.addEventListener(dialect.resyncEvent, () => {',
    '        if (this._es !== es) return;',
    '        for (const member of [...this._members]) member.receiveResync();',
    '      });',
    '    }',
    '',
    '    es.onerror = () => {',
    '      if (this._es !== es) return;',
    '      for (const member of [...this._members]) member.interrupt();',
    '    };',
    '  }',
    '',
    '  /** Listen for one collection\'s change frames; `parseChange` returns `null` for a frame belonging to a different one, so a member is still delivered to once. */',
    '  private _listen(collection: string): void {',
    '    if (this._listening.has(collection)) return;',
    '    this._listening.add(collection);',
    '    const es = this._es;',
    '    if (!es) return;',
    '    for (const name of this._dialect.changeEvents(collection)) {',
    '      es.addEventListener(name, (event) => {',
    '        if (this._es !== es) return;',
    '        let raw: unknown;',
    '        try {',
    '          raw = JSON.parse(event.data);',
    '        } catch (e) {',
    '          return;',
    '        }',
    '        for (const member of [...this._members]) {',
    '          if (member.collection !== collection) continue;',
    '          member.receiveFrame(raw);',
    '        }',
    '      });',
    '    }',
    '  }',
    '',
    '  private _closeStream(): void {',
    '    const es = this._es;',
    '    this._es = null;',
    '    this._clientId = null;',
    '    this._listening.clear();',
    '    this._postedRevision = -1;',
    '    if (!es) return;',
    '    es.onerror = null;',
    '    es.close();',
    '  }',
    '',
    '  /** Tear the stream down without touching membership — the members\' own funnels do that. */',
    '  close(): void {',
    '    this._closeStream();',
    '  }',
    '',
    '  // -- the registration -----------------------------------------------------',
    '',
    '  /** How a member is matched to the entry it asked for. */',
    '  private static _memberKey(member: SseMember): string {',
    '    return member.collection + \' \' + filterKey(member.where);',
    '  }',
    '',
    '  /** The union, deduplicated: one entry per distinct `(collection, filter)`. */',
    '  private _requested(): { entries: SseSubscriptionRequest[]; keys: Set<string> } {',
    '    const keys = new Set<string>();',
    '    const entries: SseSubscriptionRequest[] = [];',
    '    for (const member of this._members) {',
    '      const key = SharedSseConnection._memberKey(member);',
    '      if (keys.has(key)) continue;',
    '      keys.add(key);',
    '      entries.push(member.where === undefined ? { collection: member.collection } : { collection: member.collection, where: member.where });',
    '    }',
    '    return { entries, keys };',
    '  }',
    '',
    '  /**',
    '   * POST the union, if there is anything new to say and nothing already in flight. At most one POST is outstanding',
    '   * because the server replaces the set: two in flight would land in an order neither end controls.',
    '   */',
    '  private _post(): void {',
    '    const clientId = this._clientId;',
    '    if (!clientId) return;',
    '    if (this._inFlight) return;',
    '    if (this._postedRevision === this._revision) return;',
    '    if (this._members.size === 0) return;',
    '',
    '    const revision = this._revision;',
    '    this._inFlight = true;',
    '',
    '    // 🔴 What was asked for, kept — a verdict is only about the members that were in the request. A member that joined',
    '    // while this POST was in flight is not named in the body, so `accepted[]` will not name it either; settling it from',
    '    // this answer would report SUBSCRIPTION_REJECTED for a subscription nobody had yet asked the server about.',
    '    const { entries, keys } = this._requested();',
    '    const { url, init } = this._dialect.subscribeRequest(this._base, this._token, clientId, entries);',
    '',
    '    this._fetchImpl(url, init)',
    '      .then((response) => {',
    '        const status = response ? response.status : undefined;',
    '        const readBody = response && typeof response.json === \'function\' ? response.json() : Promise.resolve(null);',
    '        // A 204 has no body; a rejected JSON parse must not look like a rejected subscription.',
    '        return readBody.catch(() => null).then((body) => ({ status, body }));',
    '      })',
    '      .then(({ status, body }) => {',
    '        if (this._clientId !== clientId) {',
    '          // A reply for a connection that has already been replaced says nothing about this one — but the new one',
    '          // still owes a registration.',
    '          this._inFlight = false;',
    '          this._post();',
    '          return;',
    '        }',
    '        this._postedRevision = revision;',
    '        // ⚠️ Snapshot: settling a rejection takes that member down, which calls `leave`. `_inFlight` stays true across',
    '        // the loop so those calls do not each fire a POST; the one below sends the accumulated change once.',
    '        for (const member of [...this._members]) {',
    '          if (!keys.has(SharedSseConnection._memberKey(member))) continue;',
    '          member.settle(this._dialect.readVerdict(status, body, member.collection));',
    '        }',
    '        this._inFlight = false;',
    '        this._post();',
    '      })',
    '      .catch((e) => {',
    '        const message = \'Could not register the realtime subscription: \' + errorMessage(e);',
    '        if (this._clientId !== clientId) {',
    '          this._inFlight = false;',
    '          this._post();',
    '          return;',
    '        }',
    '        for (const member of [...this._members]) {',
    '          if (!keys.has(SharedSseConnection._memberKey(member))) continue;',
    '          member.abort(message);',
    '        }',
    '        this._inFlight = false;',
    '        this._post();',
    '      });',
    '  }',
    '}',
    '',
    '/** The connections a given host is holding, keyed by `connectionKey`. A WeakMap on the deps object the caller passed: no `reset()` is exported, a test\'s own doubles are its own pool. */',
    'const POOLS = new WeakMap<object, Map<string, SharedSseConnection>>();',
    '',
    '/** The pool for every caller that named no host of its own. */',
    'const DEFAULT_POOL_HOST: object = {};',
    '',
    'export interface SseConnectionRequest {',
    '  host: object | undefined;',
    '  dialect: SseDialect;',
    '  base: string;',
    '  token: string;',
    '  EventSourceImpl: new (url: string) => RealtimeEventSourceLike;',
    '  fetchImpl: RealtimeFetch;',
    '  where: RealtimeFilter | undefined;',
    '}',
    '',
    '/** The connection a member belongs on, opening one if this host has none yet. Not joined — the caller does that. */',
    'export function connectionFor(request: SseConnectionRequest): SharedSseConnection {',
    '  const host = request.host || DEFAULT_POOL_HOST;',
    '  let pool = POOLS.get(host);',
    '  if (!pool) {',
    '    pool = new Map<string, SharedSseConnection>();',
    '    POOLS.set(host, pool);',
    '  }',
    '  const key = connectionKey(request.dialect.name, request.base, request.token, request.where);',
    '  const existing = pool.get(key);',
    '  if (existing) return existing;',
    '',
    '  const created = new SharedSseConnection(request.dialect, request.base, request.token, request.EventSourceImpl, request.fetchImpl, () => {',
    '    // Only drop the entry if it is still this connection: a member that left and rejoined within the same turn will',
    '    // have installed a new one.',
    '    const current = POOLS.get(host);',
    '    if (current && current.get(key) === created) current.delete(key);',
    '  });',
    '  pool.set(key, created);',
    '  return created;',
    '}',
    '',
    '/** How many connections a host is holding. Exists so a test can count them. */',
    'export function openConnectionCount(host?: object): number {',
    '  const pool = POOLS.get(host || DEFAULT_POOL_HOST);',
    '  return pool ? pool.size : 0;',
    '}',
    '',
    '/**',
    ' * Open one subscription on the project\'s own backend. Always returns a handle, and the handle always reports — a',
    ' * subscription that cannot connect reports a coded error rather than sitting `connecting` forever.',
    ' */',
    'export function createRealtimeSubscription(handle: BackendHandle, options: RealtimeSubscriptionOptions): RealtimeSubscription {',
    '  const subscription = new SseTransport(handle, options, NODEGX_SSE);',
    '  subscription.connect();',
    '  return subscription;',
    '}',
    '',
    '// ============================================================================',
    '// subscribetochanges.ts — the node',
    '// ============================================================================',
    '',
    '/** Its own code, not Query Records\': an `On App Error` graph filtering on `query-records/realtime-failed` must not start receiving this node\'s failures as well. */',
    'export const SUBSCRIBE_ERROR_CODE = \'subscribe-to-changes/realtime-failed\';',
    '',
    '/** Where the node sits, for the error channel. */',
    'export interface SubscribeToChangesSource {',
    '  label: string;',
    '  nodeId: string;',
    '  componentName: string;',
    '}',
    '',
    '/** The node\'s inputs. Every other input the runtime discovers (the Backend picker, the Filter and its `qp-` ports) is refused at export by name. */',
    'export interface SubscribeToChangesOptions {',
    '  /** Class: the collection to watch; a string, else none — and a node with no class never subscribes, as the runtime\'s does not. */',
    '  collection?: unknown;',
    '  /** Enabled: `!!value` when the page passes a defined one; absent OR undefined means untouched (ON) — a declared default never runs the runtime\'s setter, and an undefined never crosses a wire (node.ts sendValue), so this node works untouched. */',
    '  enabled?: unknown;',
    '}',
    '',
    '/** The five signal outputs, called after the outputs are written — a chain reads this frame\'s values. */',
    'export interface SubscribeToChangesListeners {',
    '  /** Realtime Failure — a subscription that cannot connect, is rejected, or has been given up on; Realtime Error carries the code. */',
    '  realtimeFailure?: () => void;',
    '  /** Record Created — another client created a record in this collection. */',
    '  created?: () => void;',
    '  /** Record Updated. */',
    '  updated?: () => void;',
    '  /** Record Deleted. */',
    '  deleted?: () => void;',
    '  /** Records Changed — any of the three, and also the backend saying the view may be stale after a reconnect (`resync`). */',
    '  changed?: () => void;',
    '}',
    '',
    '/** What a Subscribe To Changes node hands the page. */',
    'export interface SubscribeToChangesHandle {',
    '  /** Subscribed: true while the backend has confirmed the subscription and is delivering changes. */',
    '  readonly subscribed: boolean;',
    '  /** Realtime Status: connecting, subscribed, interrupted or stopped; blank while no subscription is open. */',
    '  readonly realtimeStatus: string;',
    '  /** Realtime Error: the last realtime failure, with a code and whether retrying can help; null until one happens, and cleared by the next confirmation. */',
    '  readonly realtimeError: RealtimeError | null;',
    '  /** Change Type: create, update, delete, init or resync. */',
    '  readonly changedEvent: string;',
    '  /** Changed Record: the record the change was about, as the wire sent it; null when the frame carried none. */',
    '  readonly changedRecord: Record<string, unknown> | null;',
    '  /** Changed Records: every record in the change frame. */',
    '  readonly changedRecords: Record<string, unknown>[];',
    '  /** Changed Record Id: always a string. */',
    '  readonly changedRecordId: string;',
    '}',
    '',
    '/** The runtime\'s own test seam: the transport\'s deps (an EventSource constructor, a fetch, timers) and the timing table. The emitted page never passes it. */',
    'export interface SubscribeToChangesSeams {',
    '  deps?: RealtimeDeps;',
    '  timing?: RealtimeTiming;',
    '}',
    '',
    '/** The node\'s `_internal`. */',
    'interface SubscribeInternal {',
    '  /** The Class dropdown. */',
    '  name: string;',
    '  /** The Enabled input AS THE AUTHOR LEFT IT: `undefined` means untouched, which means ON — read it through `isEnabled` and never directly. */',
    '  enabled?: boolean;',
    '  subscription: RealtimeSubscription | null;',
    '  realtimeStatus?: RealtimeStatus;',
    '  realtimeError: RealtimeError | null;',
    '  realtimeEvent: string;',
    '  changedRecord: Record<string, unknown> | null;',
    '  changedRecords: Record<string, unknown>[];',
    '  changedRecordId: string;',
    '}',
    '',
    '/** initialize(). */',
    'function createInternal(): SubscribeInternal {',
    '  return {',
    '    name: \'\',',
    '    subscription: null,',
    '    realtimeError: null,',
    '    realtimeEvent: \'\',',
    '    changedRecord: null,',
    '    changedRecords: [],',
    '    changedRecordId: \'\'',
    '  };',
    '}',
    '',
    '/** Everything the node kept on `this`, in one ref. */',
    'interface SubState {',
    '  source: SubscribeToChangesSource;',
    '  internal: SubscribeInternal;',
    '  env: SubscribeToChangesSeams;',
    '  dead: boolean;',
    '  latest: { options: SubscribeToChangesOptions; listeners: SubscribeToChangesListeners };',
    '  rerender: () => void;',
    '}',
    '',
    '/** EXP-011 §66.5: node.ts sendValue drops an undefined before it crosses a wire (`if (value === undefined) return;`), so a setter never sees one — an option passed as undefined (a Variable nothing has written) is NOT a delivery: the internal keeps what it holds. */',
    'function has(options: object, key: string): boolean {',
    '  return Object.prototype.hasOwnProperty.call(options, key) && (options as Record<string, unknown>)[key] !== undefined;',
    '}',
    '',
    '/** Rule 2 in the node\'s docblock, and the only reader of `enabled`: `default: true` on the port is what the panel shows, not what the runtime was told. */',
    'function isEnabled(internal: SubscribeInternal): boolean {',
    '  return internal.enabled !== false;',
    '}',
    '',
    '/** The setters: the Class stored as is; Enabled `!!value` — each schedules the reconfigure the effect below runs. */',
    'function applyOptions(s: SubState, options: SubscribeToChangesOptions): void {',
    '  s.internal.name = typeof options.collection === \'string\' ? options.collection : \'\';',
    '  if (has(options, \'enabled\')) s.internal.enabled = !!options.enabled;',
    '}',
    '',
    '/** The backend this node subscribes on: the project\'s own, and the session as the client keeps it — a snapshot at reconfigure, as the runtime\'s resolved handle is. */',
    'function resolveBackend(): BackendHandle {',
    '  const session = readSession();',
    '  return { url: ENDPOINT, ...(session?.sessionToken !== undefined ? { sessionToken: session.sessionToken } : {}) };',
    '}',
    '',
    'function teardown(s: SubState): void {',
    '  const internal = s.internal;',
    '  if (internal.subscription) {',
    '    internal.subscription.dispose();',
    '    internal.subscription = null;',
    '  }',
    '  if (internal.realtimeStatus) {',
    '    internal.realtimeStatus = undefined;',
    '    s.rerender();',
    '  }',
    '}',
    '',
    '/**',
    ' * reconfigure: tear down, and open a fresh subscription where the node is enabled and names a class. The runtime\'s two',
    ' * fatal arms — no backend resolved, a backend with no realtime — cannot arise here: the project declared its backend',
    ' * (or the node was refused at export) and the built-in backend\'s realtime is `supported`.',
    ' */',
    'function reconfigure(s: SubState): void {',
    '  teardown(s);',
    '  const internal = s.internal;',
    '',
    '  if (!isEnabled(internal)) return;',
    '  const collection = internal.name;',
    '  if (!collection) return;',
    '',
    '  const target = resolveBackend();',
    '  internal.subscription = createRealtimeSubscription(target, {',
    '    collection,',
    '    // The Parse wire\'s key is `objectId`, and the frame\'s record carries it (`parseChange` reads it first either way).',
    '    primaryKey: \'objectId\',',
    '    onEvent: (change) => handleRealtimeChange(s, change),',
    '    onStatus: (status) => handleRealtimeStatus(s, status),',
    '    onError: (error) => handleRealtimeError(s, error),',
    '    ...(s.env.deps !== undefined ? { deps: s.env.deps } : {}),',
    '    ...(s.env.timing !== undefined ? { timing: s.env.timing } : {})',
    '  });',
    '',
    '  // ⚠️ The subscription notifies on a status CHANGE, and its first status is the one it was constructed with — so',
    '  // `connecting` is never pushed and a graph reading Realtime Status would see an empty string until the backend',
    '  // answers. Read it off the handle instead.',
    '  handleRealtimeStatus(s, internal.subscription.status);',
    '}',
    '',
    'function handleRealtimeChange(s: SubState, change: RealtimeChange): void {',
    '  const internal = s.internal;',
    '  internal.realtimeEvent = change.type;',
    '  // ⚠️ `recordsComplete` is the gate, not `records.length`: a key-only delete and an empty frame must not both publish `{}`.',
    '  internal.changedRecord = change.recordsComplete && change.records.length > 0 ? change.records[0] : null;',
    '  internal.changedRecords = change.recordsComplete ? change.records : [];',
    '  internal.changedRecordId = change.ids.length > 0 ? change.ids[0] : \'\';',
    '  s.rerender();',
    '',
    '  // `init` is the subscription\'s confirmation snapshot, not a change.',
    '  if (change.type === \'init\') return;',
    '',
    '  // `resync` means the server thinks we may have missed something and keeps no replay log. It is not a',
    '  // create/update/delete and must not pretend to be one — but it IS a reason to go and look, which is what `changed` is for.',
    '  const listeners = s.latest.listeners;',
    '  if (change.type === \'create\') listeners.created?.();',
    '  else if (change.type === \'update\') listeners.updated?.();',
    '  else if (change.type === \'delete\') listeners.deleted?.();',
    '  listeners.changed?.();',
    '}',
    '',
    'function handleRealtimeStatus(s: SubState, status: RealtimeStatus): void {',
    '  const internal = s.internal;',
    '  internal.realtimeStatus = status;',
    '  if (status === \'subscribed\' && internal.realtimeError) internal.realtimeError = null;',
    '  s.rerender();',
    '}',
    '',
    '/** A structured code, a signal, and the app\'s error channel — the runtime\'s order: the outputs, the pulse, then the raise. */',
    'function handleRealtimeError(s: SubState, error: RealtimeError): void {',
    '  s.internal.realtimeError = error;',
    '  s.rerender();',
    '  s.latest.listeners.realtimeFailure?.();',
    '  raiseAppError({',
    '    code: SUBSCRIBE_ERROR_CODE,',
    '    message: error.message || \'The realtime subscription failed.\',',
    '    nodeId: s.source.nodeId,',
    '    nodeType: \'SubscribeToChanges\',',
    '    componentName: s.source.componentName,',
    '    detail: error',
    '  });',
    '}',
    '',
    '/**',
    ' * A Subscribe To Changes node. `env` is the runtime\'s own test seam (the transport\'s deps and the timing table) — the',
    ' * emitted page never passes it, so every subscription on the page shares the one pool the browser is.',
    ' */',
    'export function useSubscribeToChanges(',
    '  source: SubscribeToChangesSource,',
    '  options: SubscribeToChangesOptions = {},',
    '  on: SubscribeToChangesListeners = {},',
    '  env: SubscribeToChangesSeams = {}',
    '): SubscribeToChangesHandle {',
    '  const [, publish] = useReducer((n: number) => n + 1, 0);',
    '  const stateRef = useRef<SubState | null>(null);',
    '  const handleRef = useRef<SubscribeToChangesHandle | null>(null);',
    '  if (stateRef.current === null || handleRef.current === null) {',
    '    const s: SubState = {',
    '      source,',
    '      internal: createInternal(),',
    '      env,',
    '      dead: false,',
    '      latest: { options, listeners: on },',
    '      rerender: () => {',
    '        if (!s.dead) publish();',
    '      }',
    '    };',
    '    stateRef.current = s;',
    '    const internal = s.internal;',
    '    handleRef.current = {',
    '      get subscribed() {',
    '        return internal.realtimeStatus === \'subscribed\';',
    '      },',
    '      get realtimeStatus() {',
    '        return internal.realtimeStatus || \'\';',
    '      },',
    '      get realtimeError() {',
    '        return internal.realtimeError || null;',
    '      },',
    '      get changedEvent() {',
    '        return internal.realtimeEvent || \'\';',
    '      },',
    '      get changedRecord() {',
    '        return internal.changedRecord || null;',
    '      },',
    '      get changedRecords() {',
    '        return internal.changedRecords || [];',
    '      },',
    '      get changedRecordId() {',
    '        return internal.changedRecordId || \'\';',
    '      }',
    '    };',
    '  }',
    '  const s = stateRef.current;',
    '  s.latest = { options, listeners: on };',
    '',
    '  const scheduled = useRef<{ collection: unknown; enabled: unknown } | null>(null);',
    '  // _onNodeDeleted: the subscription disposed. StrictMode runs the mount twice in development; the cleanup between',
    '  // tears the first subscription down and the second mount\'s reconfigure opens it again.',
    '  useEffect(() => {',
    '    s.dead = false;',
    '    scheduled.current = null;',
    '    return () => {',
    '      s.dead = true;',
    '      teardown(s);',
    '    };',
    '    // eslint-disable-next-line react-hooks/exhaustive-deps -- the state object is created once',
    '  }, []);',
    '',
    '  // The setters run on every render (a wired input delivers on change), and each schedules ONE reconfigure after the',
    '  // inputs have updated — here, after the render that changed a Class or an Enabled (and once at mount, as the first',
    '  // delivery does): a class and an enabled arriving in one render reconnect once.',
    '  useEffect(() => {',
    '    applyOptions(s, s.latest.options);',
    '    const prev = scheduled.current;',
    '    // The APPLIED values, not the raw options: an undefined passed on a later render (a Variable written back to undefined) ran no',
    '    // setter in the runtime and schedules nothing here either (§66.5).',
    '    const next = { collection: s.internal.name, enabled: s.internal.enabled };',
    '    scheduled.current = next;',
    '    if (prev === null || prev.collection !== next.collection || prev.enabled !== next.enabled) reconfigure(s);',
    '  });',
    '',
    '  return handleRef.current;',
    '}'
  ].join('\n');
}
