/**
 * `src/lib/runTasks.ts` — the `Run Tasks` node's host, emitted into the app (EXP-011 §53).
 *
 * {@link ./scriptLib.ts}'s shape, one module over: a transcription of the runtime the node has to
 * agree with, shipped only when a component keeps a Run Tasks node. It transcribes
 * `noodl-runtime/src/nodes/std-library/runtasks.ts` — the serial state machine (`idle` / `running` /
 * `aborted`), the queue, bounded concurrency, stop-on-failure, abort, the two token counts (the `Do`
 * pulses a run owns, the `Abort` pulses it honours), `aborted` sent before the outcome and `completed`
 * after it — and the two facts of `createTaskComponent` that reach the emitted app: a task's model id
 * is the item's own `id` when it has one (`Model.create` → `Model.get(data.id)`), else a generated one;
 * the template's inputs are fed by name from the item.
 *
 * What the runtime does with a *component instance* the host does with a *React element*: the hook
 * keeps the tasks in flight as `tasks`, the host component renders one template element per entry, the
 * template's start chain runs in its mount effect (that is `startTask`'s pulse of the start input), and
 * the element's `onSuccess` / `onFailure` are the task's `succeed` / `fail` — the same edge
 * `creatorCallbacks.onOutputChanged` watches for. Finishing removes the element, as `deleteNode` does.
 *
 * The diagnostics — `already-running`, `no-items`, `invalid-concurrency`, `task-failed` — are raised on the
 * app's error channel (`src/lib/errors.ts`, EXP-011 §54) with the node's own provenance, exactly where the
 * runtime raises them; a boundary hears them, and the console default prints them.
 *
 * What differs, recorded rather than hidden: a task's failure report (`run-tasks/task-failed`) carries the
 * index but not the template's error output (the runtime reads it off the dying node; the host has no
 * value channel from the element); `run()` runs its checks synchronously at the pulse rather than through
 * the node's operation queue (the queue exists to serialise `createNode`, which is asynchronous there and
 * synchronous here — React mounts the element).
 */

export const RUN_TASKS_LIB_PATH = 'src/lib/runTasks.ts';

export function runTasksLibSource(): string {
  return [
    '//',
    '// The Run Tasks node, hosted. Transcribed from the runtime it has to agree with:',
    '// noodl-runtime/src/nodes/std-library/runtasks.ts (the state machine, the queue, the outcomes) and',
    '// runtasks-template-contract.ts (the four names the host and its template agree on). The host component',
    '// renders one template element per task in flight; the template runs its start chain when it mounts,',
    "// which is the moment startTask pulses the template's start input, and reports back through the",
    "// element's success / failure callbacks, which is the edge creatorCallbacks.onOutputChanged watches for.",
    '//',
    '// run(items): a Do. `null` clears the list (there is nothing to run); any other falsy value leaves the',
    '// previous list in place, as the items setter does. A Do while a run is in progress is Unchanged; no',
    '// list, or a Max Running Tasks below 1, is a Failure; an empty list is a completed run (Done). Otherwise',
    '// up to Max Running Tasks tasks start at once and every finished task starts the next queued one.',
    '// abort(): an Abort. Nothing running is Unchanged (and no Aborted); otherwise the run ends once the tasks',
    '// in flight finish — Aborted first, then Done. Stop On Failure ends the run at the first failed task:',
    '// Aborted, then Failure. Every outcome is followed by Completed, once per Do or Abort that owns it, so an',
    "// honoured abort fires Completed twice (the run's Do and the Abort are two invocations).",
    '//',
    "// The diagnostics — already-running, no-items, invalid-concurrency, task-failed — are raised on the app's error",
    "// channel (./errors) with the node's own provenance, where the runtime raises them.",
    '//',
    '// Recorded divergences: a failed task is reported without the template\'s error output; the checks run at',
    "// the pulse rather than through the node's operation queue.",
    '//',
    '',
    "import { useEffect, useReducer, useRef } from 'react';",
    '',
    "import { raiseAppError } from './errors';",
    '',
    '/** Which node this is — the provenance every raise carries (Node.raiseRuntimeError fills the same three in). */',
    'export interface RunTasksSource {',
    "  /** The authored label, or 'Run Tasks'. */",
    '  label: string;',
    "  /** The node's graph id. */",
    '  nodeId: string;',
    "  /** The component it sits in — '/Pages/Home'. */",
    '  componentName: string;',
    '}',
    '',
    'export interface RunTasksConfig {',
    '  /** How many tasks may run at the same time (default 10); below 1 the run fails rather than starting. */',
    '  maxRunningTasks?: number;',
    '  /** Abandon the remaining items as soon as one task fails (default false). */',
    '  stopOnFailure?: boolean;',
    '}',
    '',
    '/** The five signal outputs, as the listeners the host component passes. */',
    'export interface RunTasksListeners {',
    '  done?: () => void;',
    '  failure?: () => void;',
    '  unchanged?: () => void;',
    '  completed?: () => void;',
    '  aborted?: () => void;',
    '}',
    '',
    '/** One task in flight: the host renders the template once per entry and passes these two callbacks. */',
    'export interface TaskInstance<Item> {',
    '  /** Unique among the tasks of this hook, for the React key. */',
    '  key: string;',
    "  /** The task's model id: the item's own `id` when it has one, else a generated one (Model.create). */",
    '  id: string;',
    '  /** The position in the list the run was started with, for the failure report. */',
    '  index: number;',
    '  item: Item;',
    "  /** The template's success output fired. */",
    '  succeed: () => void;',
    "  /** The template's failure output fired. */",
    '  fail: () => void;',
    '}',
    '',
    'export interface RunTasksHandle<Item> {',
    '  /** Do — start a run over `items`. */',
    '  run: (items: readonly Item[] | null | undefined) => void;',
    '  /** Abort — stop starting tasks and end the run once those in flight finish. */',
    '  abort: () => void;',
    '  /** The tasks in flight, mount order. The host renders one template element per entry. */',
    '  tasks: ReadonlyArray<TaskInstance<Item>>;',
    '}',
    '',
    "type State = 'idle' | 'running' | 'aborted';",
    '',
    'interface Instance<Item> {',
    '  source: RunTasksSource;',
    '  state: State;',
    '  items: readonly Item[] | undefined;',
    '  queue: Array<{ item: Item; index: number }>;',
    '  active: Array<TaskInstance<Item>>;',
    '  numTasks: number;',
    '  completedTasks: number;',
    '  failedTasks: number;',
    '  /** The Do pulses the run in flight owns — each is owed its outcome and a Completed. */',
    '  runTokens: number;',
    '  /** The Abort pulses accepted but not yet honoured. */',
    '  abortTokens: number;',
    '  dead: boolean;',
    '}',
    '',
    'let nextKey = 0;',
    'const generatedId = (): string => `task-${(++nextKey).toString(36)}`;',
    '',
    '/** The item\'s own id, as Model.create reads it (`data.id`), else a generated one. */',
    'function idOf(item: unknown): string {',
    "  const id = item !== null && typeof item === 'object' ? (item as { id?: unknown }).id : undefined;",
    "  return id === undefined || id === null || id === '' ? generatedId() : String(id);",
    '}',
    '',
    'export function useRunTasks<Item = Record<string, any>>(',
    '  source: RunTasksSource,',
    '  config: RunTasksConfig = {},',
    '  on: RunTasksListeners = {}',
    '): RunTasksHandle<Item> {',
    '  const [, publish] = useReducer((n: number) => n + 1, 0);',
    '  const onRef = useRef(on);',
    '  onRef.current = on;',
    '  const configRef = useRef(config);',
    '  configRef.current = config;',
    '  const inst = useRef<Instance<Item> | null>(null);',
    '  const handle = useRef<RunTasksHandle<Item> | null>(null);',
    '  if (inst.current === null || handle.current === null) {',
    '    const self: Instance<Item> = {',
    '      source,',
    "      state: 'idle',",
    '      items: undefined,',
    '      queue: [],',
    '      active: [],',
    '      numTasks: 0,',
    '      completedTasks: 0,',
    '      failedTasks: 0,',
    '      runTokens: 0,',
    '      abortTokens: 0,',
    '      dead: false',
    '    };',
    '    inst.current = self;',
    '    const fire = (name: keyof RunTasksListeners) => {',
    '      onRef.current[name]?.();',
    '    };',
    "    // raiseRuntimeError: the node's own code and message, its graph id, its type, its component.",
    '    const raise = (code: string, message: string, detail?: unknown) => {',
    "      raiseAppError({ code, message, nodeId: self.source.nodeId, nodeType: 'RunTasks', componentName: self.source.componentName, detail });",
    '    };',
    '    // reportOutcomes: the outcome, then Completed, once per token — the run\'s Do pulses first, then',
    "    // the Abort pulses it honoured, which are Done however the run ended (_endRun).",
    "    const endRun = (outcome: 'done' | 'failure') => {",
    '      const runTokens = self.runTokens;',
    '      const abortTokens = self.abortTokens;',
    '      self.runTokens = 0;',
    '      self.abortTokens = 0;',
    '      for (let i = 0; i < runTokens; i++) {',
    '        fire(outcome);',
    "        fire('completed');",
    '      }',
    '      for (let i = 0; i < abortTokens; i++) {',
    "        fire('done');",
    "        fire('completed');",
    '      }',
    '    };',
    '    const republish = () => {',
    '      self.active = [...self.active];',
    '      handle.current!.tasks = self.active;',
    '      if (!self.dead) publish();',
    '    };',
    '    const startTask = (entry: { item: Item; index: number }) => {',
    '      const task: TaskInstance<Item> = {',
    '        key: generatedId(),',
    '        id: idOf(entry.item),',
    '        index: entry.index,',
    '        item: entry.item,',
    "        succeed: () => finish(task, 'success'),",
    "        fail: () => finish(task, 'failure')",
    '      };',
    '      self.active.push(task);',
    '      republish();',
    '    };',
    '    const startNext = () => {',
    '      const entry = self.queue.shift();',
    '      if (entry !== undefined) startTask(entry);',
    '    };',
    '    // itemOutputSignalTriggered + checkDone, verbatim in order: the counts, then the six terminal paths.',
    "    const finish = (task: TaskInstance<Item>, how: 'success' | 'failure') => {",
    "      if (self.dead || self.state === 'idle' || !self.active.includes(task)) return;",
    '      self.active = self.active.filter((t) => t !== task);',
    "      if (how === 'failure') {",
    "        raise('run-tasks/task-failed', `Task ${task.index + 1} of ${self.numTasks} failed`, { itemIndex: task.index });",
    '        self.failedTasks++;',
    '      }',
    '      self.completedTasks++;',
    "      if (self.state === 'aborted') {",
    '        self.queue = [];',
    "        self.state = 'idle';",
    '        republish();',
    "        fire('aborted');",
    "        endRun('done');",
    '        return;',
    '      }',
    '      if (self.completedTasks === self.numTasks) {',
    "        self.state = 'idle';",
    '        republish();',
    "        endRun(self.failedTasks === 0 ? 'done' : 'failure');",
    '        return;',
    '      }',
    '      if (configRef.current.stopOnFailure === true && self.failedTasks > 0) {',
    '        self.queue = [];',
    "        self.state = 'idle';",
    '        republish();',
    "        fire('aborted');",
    "        endRun('failure');",
    '        return;',
    '      }',
    '      republish();',
    '      startNext();',
    '    };',
    '    handle.current = {',
    '      tasks: self.active,',
    '      run: (items) => {',
    '        if (self.dead) return;',
    '        // The items setter: null clears, any other falsy value abstains, a new list replaces.',
    '        if (items === null) self.items = undefined;',
    '        else if (items) self.items = items;',
    "        if (self.state !== 'idle') {",
    "          raise('run-tasks/already-running', 'Do was triggered while a run was still in progress, so it was ignored');",
    "          fire('unchanged');",
    "          fire('completed');",
    '          return;',
    '        }',
    '        if (self.items === undefined) {',
    "          raise('run-tasks/no-items', 'No Items list was provided, so there is nothing to run');",
    "          fire('failure');",
    "          fire('completed');",
    '          return;',
    '        }',
    '        const max = configRef.current.maxRunningTasks ?? 10;',
    '        if (!(max >= 1)) {',
    "          raise('run-tasks/invalid-concurrency', `Max Running Tasks is ${max}, so no task could ever start`);",
    "          fire('failure');",
    "          fire('completed');",
    '          return;',
    '        }',
    '        self.runTokens = 1;',
    "        self.state = 'running';",
    '        self.numTasks = self.items.length;',
    '        self.failedTasks = 0;',
    '        self.completedTasks = 0;',
    '        self.queue = self.items.map((item, index) => ({ item, index }));',
    '        if (self.queue.length === 0) {',
    "          self.state = 'idle';",
    "          endRun('done');",
    '          return;',
    '        }',
    '        const count = Math.min(max, self.queue.length);',
    '        for (let i = 0; i < count; i++) startNext();',
    '      },',
    '      abort: () => {',
    '        if (self.dead) return;',
    "        if (self.state !== 'running') {",
    "          fire('unchanged');",
    "          fire('completed');",
    '          return;',
    '        }',
    "        self.state = 'aborted';",
    '        self.abortTokens++;',
    '        if (self.active.length === 0) {',
    '          self.queue = [];',
    "          self.state = 'idle';",
    "          fire('aborted');",
    "          endRun('done');",
    '        }',
    '      }',
    '    };',
    '  }',
    '  // Unmount: the node is deleted, and every task in flight with it (_deleteAllTasks).',
    '  useEffect(() => {',
    '    const self = inst.current!;',
    '    self.dead = false;',
    '    return () => {',
    '      self.dead = true;',
    '      self.active = [];',
    '      self.queue = [];',
    "      self.state = 'idle';",
    '    };',
    '  }, []);',
    '  return handle.current;',
    '}',
    ''
  ].join('\n');
}
