/**
 * `src/lib/script.ts` — the `Script` node's host, emitted into the app (EXP-011 §52).
 *
 * {@link ./statesLib.ts}'s shape, one module over: a transcription of the runtime the node has to
 * agree with, shipped only when a component keeps a Script node. It transcribes two files:
 *
 * - `noodl-runtime/src/javascriptnodeparser.js` — the three generations of the declaration DSL.
 *   `define({…})` (gen 1: the object is the node; `run` or `change` is the run function; a key
 *   named like a signal input is that signal's function), `script({…})` (gen 2: `setup` installs
 *   `this.inputs`/`this.outputs`/`this.setOutputs` and the `methods`; `change` diffs against the
 *   previous inputs and calls `changed[k](new, old)`; every `signals[k]` becomes a signal input),
 *   and the bare `Node.*` form (gen 3, taken when neither was called: `Node.Inputs`/`Node.Outputs`
 *   are the type maps, `change` calls `Node.Setters[k]` for each changed key then
 *   `Node.OnInputsChanged`, `setup` is `Node.OnInit` and installs `Node.setOutputs`, `destroy` is
 *   `Node.OnDestroy`, every `Node.Signals[k]` function is a signal input).
 * - `noodl-viewer-react/src/nodes/std-library/javascript.ts` — the lifecycle. Output accessors
 *   exist only for the ports on disk (a set publishes, a signal reads as a callable that pulses);
 *   after parsing, `Node.Inputs` becomes the live input values and `Node.Outputs` the accessors;
 *   setup is scheduled, then the run, then the inputs delivered before the parse are replayed
 *   (each marks itself changed); a value input marks itself changed and schedules a run; a signal
 *   input schedules its function, coalesced per name per pass; deletion runs destroy.
 *
 * What differs, recorded rather than hidden: the host delivers an input when its value changes
 * (`!==`), where the runtime delivers on every upstream publish; a signal's function runs in a
 * microtask after the handler that asked (the runtime schedules it after the pass's inputs have
 * updated), so two pulses of one signal inside one handler coalesce into one call, as they do in
 * one runtime pass; a throw is logged to the console (the runtime also raises an editor warning
 * the exported app has no canvas for). `createComponent`/`deleteComponent` throw — the gate refuses
 * any code that names them, so nothing hosted here reaches them.
 */

export const SCRIPT_LIB_PATH = 'src/lib/script.ts';

export function scriptLibSource(): string {
  return [
    '//',
    '// The Script node, hosted. Transcribed from the runtime it has to agree with:',
    '// noodl-runtime/src/javascriptnodeparser.js (the define / script / Node.* declaration forms) and',
    '// noodl-viewer-react/src/nodes/std-library/javascript.ts (the lifecycle). A node\'s own code lives in',
    '// src/scripts/…, verbatim; this module runs it the way the runtime does.',
    '//',
    '// The code runs once, when the component mounts (the runtime: when the node is created). Its setup runs',
    '// with the inputs it was given at boot, then its change function with every one of them marked changed.',
    '// A later input change runs the change function again with the changed names. A signal input is a',
    '// function on the handle: calling it runs the script\'s function for it after the handler that asked has',
    '// finished (a microtask — the runtime schedules it after the pass\'s inputs have updated). A value',
    '// output written by the script re-renders the component and reads live; a signal output calls the',
    '// listener the component passed. Unmount runs destroy.',
    '//',
    '// Recorded divergences: an input is delivered when its value changes (!==), where the runtime delivers',
    '// on every upstream publish; two pulses of one signal inside one handler coalesce into one call, as in',
    '// one runtime pass; a throw is logged to the console (the runtime also raises an editor warning).',
    '//',
    '',
    "import { useEffect, useReducer, useRef } from 'react';",
    '',
    "import { raiseAppError } from './errors';",
    '',
    '// ---- the definition a script file exports ----------------------------------------------------------',
    '',
    "/** A port type as the editor spells it: 'string' | 'number' | 'boolean' | 'color' | 'signal' | 'object' | 'array' | '*' … */",
    'export type PortType = string;',
    '',
    '/** The ports the editor discovered for the node — the set the running app registers. */',
    'export interface ScriptPorts {',
    '  inputs: Record<string, PortType>;',
    '  outputs: Record<string, PortType>;',
    '}',
    '',
    '/** What user code sees as `this` inside setup, change, destroy and every signal function. */',
    'export interface ScriptScope {',
    '  flagOutputDirty(name: string): void;',
    '  sendSignalOnOutput(name: string): void;',
    '  runNextFrame(): void;',
    '  createComponent(componentName: string): never;',
    '  deleteComponent(component: unknown): never;',
    '  [extra: string]: unknown;',
    '}',
    '',
    'export type UserFunction = (',
    '  this: ScriptScope,',
    '  inputs: Record<string, unknown>,',
    '  outputs: Record<string, unknown>,',
    '  changedInputs?: Record<string, boolean>',
    ') => unknown;',
    '',
    '/** The object user code declares with define({…}) or script({…}), as the parser keeps it. */',
    'export interface DefinedObject {',
    '  inputs?: Record<string, unknown>;',
    '  outputs?: Record<string, unknown>;',
    '  setup?: UserFunction;',
    '  change?: UserFunction;',
    '  run?: UserFunction;',
    '  destroy?: UserFunction;',
    '  signals?: Record<string, UserFunction>;',
    '  changed?: Record<string, (value: unknown, previous: unknown) => void>;',
    '  methods?: Record<string, unknown>;',
    '  [signalOrExtra: string]: unknown;',
    '}',
    '',
    '/** The `Node` (alias `Script`) the code declares against, gen 3. */',
    'export interface NodeApi {',
    '  Inputs: Record<string, unknown>;',
    '  Outputs: Record<string, unknown>;',
    '  Signals: Record<string, unknown>;',
    '  Setters: Record<string, unknown>;',
    '  OnInit?: UserFunction;',
    '  OnInputsChanged?: () => void;',
    '  OnDestroy?: UserFunction;',
    '  setOutputs?: (outputs: Record<string, unknown>) => void;',
    '  [extra: string]: unknown;',
    '}',
    '',
    '/** The author\'s code, wrapped exactly as the runtime compiles it: a function of (define, script, Node, Component). */',
    'export type ScriptSource = (',
    '  define: (userObject: DefinedObject) => void,',
    '  script: (userObject: DefinedObject) => void,',
    '  Node: NodeApi,',
    '  Component: Record<string, unknown>',
    ') => void;',
    '',
    'export interface ScriptDefinition<I, O> {',
    '  /** The node\'s label, for the console. */',
    '  name: string;',
    '  ports: ScriptPorts;',
    '  source: ScriptSource;',
    "  /** Where a load failure is raised from — the node's graph id and its component (EXP-011 §54). */",
    '  at?: { nodeId: string; componentName: string };',
    '  /** Carries the two type arguments through inference; never set. */',
    '  readonly __types?: { inputs: I; outputs: O };',
    '}',
    '',
    '/** Identity, typed: `I` is the input record the component passes, `O` the outputs it reads. */',
    'export function defineScript<I, O>(name: string, ports: ScriptPorts, source: ScriptSource, at?: { nodeId: string; componentName: string }): ScriptDefinition<I, O> {',
    '  return { name, ports, source, at };',
    '}',
    '',
    '// ---- the parser: javascriptnodeparser.js, three generations ----------------------------------------',
    '',
    'interface Parsed {',
    '  inputs: Record<string, unknown>;',
    '  outputs: Record<string, unknown>;',
    '  setup?: UserFunction;',
    '  change?: UserFunction;',
    '  destroy?: UserFunction;',
    '  definedObject: DefinedObject;',
    '  node: NodeApi;',
    '  error?: string;',
    '}',
    '',
    '/** The second generation\'s wrapper (`_scriptExtend`), verbatim in behaviour. */',
    'function scriptExtend(userObject: DefinedObject): DefinedObject {',
    '  const extended: DefinedObject = {',
    '    inputs: userObject.inputs || {},',
    '    outputs: userObject.outputs || {},',
    '    setup: function (this: ScriptScope, inputs, outputs) {',
    '      this.inputs = inputs;',
    '      this.outputs = outputs;',
    '      this.setOutputs = (states: Record<string, unknown>) => {',
    '        for (const key in states) {',
    '          outputs[key] = states[key];',
    '          this.flagOutputDirty(key);',
    '        }',
    '      };',
    '      if (userObject.methods) {',
    '        for (const key in userObject.methods) this[key] = userObject.methods[key];',
    '      }',
    '      userObject.setup && userObject.setup.apply(this, [inputs, outputs]);',
    '    },',
    '    destroy: function (this: ScriptScope, inputs, outputs) {',
    '      this.inputs = inputs;',
    '      this.outputs = outputs;',
    '      userObject.destroy && userObject.destroy.apply(this, [inputs, outputs]);',
    '    },',
    '    change: function (this: ScriptScope, inputs, outputs) {',
    '      this.inputs = inputs;',
    '      this.outputs = outputs;',
    '      const old = (this._oldInputs as Record<string, unknown> | undefined) || {};',
    '      if (userObject.changed) {',
    '        for (const key in inputs) {',
    '          if (inputs[key] !== old[key]) {',
    '            const changedFunction = userObject.changed[key];',
    "            if (typeof changedFunction === 'function') changedFunction.apply(this, [inputs[key], old[key]]);",
    '          }',
    '        }',
    '      }',
    '      this._oldInputs = Object.assign({}, inputs);',
    '    }',
    '  };',
    '  if (userObject.signals) {',
    '    for (const key in userObject.signals) {',
    '      extended[key] = userObject.signals[key];',
    "      (extended.inputs as Record<string, unknown>)[key] = 'signal';",
    '    }',
    '  }',
    '  return extended;',
    '}',
    '',
    '/** Runs the code once and reads what it declared — `new JavascriptNodeParser(code)` and `_afterSourced`. */',
    'function parse(def: ScriptDefinition<unknown, unknown>): Parsed {',
    '  const node: NodeApi = { Inputs: {}, Outputs: {}, Signals: {}, Setters: {} };',
    '  let defined: DefinedObject | undefined;',
    '  const define = (userObject: DefinedObject) => {',
    '    defined = { ...userObject, inputs: userObject.inputs || {}, outputs: userObject.outputs || {}, change: userObject.run || userObject.change };',
    '  };',
    '  const script = (userObject: DefinedObject) => {',
    '    defined = scriptExtend(userObject);',
    '  };',
    '  try {',
    '    def.source(define, script, node, {});',
    '  } catch (e) {',
    "    // javascript.ts: raised as script/source-failed on the error channel; the node stays inert.",
    '    raiseAppError({',
    "      code: 'script/source-failed',",
    '      message: `The script could not be loaded: ${e instanceof Error ? e.message : String(e)}`,',
    '      nodeId: def.at?.nodeId ?? def.name,',
    "      nodeType: 'Javascript2',",
    "      componentName: def.at?.componentName ?? '<runtime>',",
    '      detail: { error: String(e) }',
    '    });',
    '    return { inputs: {}, outputs: {}, definedObject: {}, node, error: String(e) };',
    '  }',
    '  if (defined !== undefined) {',
    '    return { inputs: defined.inputs ?? {}, outputs: defined.outputs ?? {}, setup: defined.setup, change: defined.change, destroy: defined.destroy, definedObject: defined, node };',
    '  }',
    '  // The third generation: nothing was called, so the declarations are what the code put on Node.',
    '  const inputs: Record<string, unknown> = Object.assign({}, node.Inputs || {});',
    '  const outputs: Record<string, unknown> = Object.assign({}, node.Outputs || {});',
    '  const setup: UserFunction = function (this: ScriptScope, _inputs, outs) {',
    '    node.setOutputs = (values: Record<string, unknown>) => {',
    '      for (const key in values) {',
    '        outs[key] = values[key];',
    '        this.flagOutputDirty(key);',
    '      }',
    '    };',
    '    node.OnInit && node.OnInit.apply(this, [_inputs, outs]);',
    '  };',
    '  const destroy = node.OnDestroy;',
    '  const change: UserFunction = (ins, _outs, changedInputs) => {',
    '    for (const key in changedInputs) {',
    "      if (typeof node.Setters[key] === 'function') (node.Setters[key] as (value: unknown) => void)(ins[key]);",
    '    }',
    "    if (typeof node.OnInputsChanged === 'function') node.OnInputsChanged();",
    '  };',
    '  const definedObject: DefinedObject = { inputs, outputs, setup, destroy, change };',
    '  if (node.Signals !== undefined) {',
    '    for (const key in node.Signals) {',
    "      if (typeof node.Signals[key] === 'function') {",
    "        inputs[key] = 'signal';",
    '        definedObject[key] = node.Signals[key];',
    '      }',
    '    }',
    '  }',
    '  return { inputs, outputs, setup, change, destroy, definedObject, node };',
    '}',
    '',
    '// ---- the instance: javascript.ts, the lifecycle ----------------------------------------------------',
    '',
    'interface Instance {',
    '  name: string;',
    '  parsed: Parsed;',
    '  /** The live input values — `Node.Inputs` after the parse. */',
    '  inputValues: Record<string, unknown>;',
    '  /** What the script has written. */',
    '  outputValues: Record<string, unknown>;',
    '  /** The accessors user code writes through — `Node.Outputs` after the parse, and the `outputs` argument. */',
    '  outputProperties: Record<string, unknown>;',
    '  changedInputs: Record<string, boolean>;',
    '  signalScheduled: Record<string, boolean>;',
    '  runNextFrameScheduled: boolean;',
    '  killed: boolean;',
    '  scope: ScriptScope;',
    '}',
    '',
    'function logThrow(inst: Instance, phase: string, e: unknown): void {',
    "  console.error(`Script node ${inst.name}: ${phase} threw:`, e);",
    '}',
    '',
    'function callRun(inst: Instance): void {',
    '  if (!inst.parsed.change || inst.killed) return;',
    '  const changed = inst.changedInputs;',
    '  try {',
    '    inst.parsed.change.call(inst.scope, inst.inputValues, inst.outputProperties, changed);',
    '  } catch (e) {',
    "    logThrow(inst, 'run', e);",
    '  }',
    '  inst.changedInputs = {};',
    '}',
    '',
    'function callSetup(inst: Instance): void {',
    '  if (!inst.parsed.setup || inst.killed) return;',
    '  try {',
    '    inst.parsed.setup.call(inst.scope, inst.inputValues, inst.outputProperties);',
    '  } catch (e) {',
    "    logThrow(inst, 'setup', e);",
    '  }',
    '}',
    '',
    'function callDestroy(inst: Instance): void {',
    '  if (!inst.parsed.destroy) return;',
    '  try {',
    '    inst.parsed.destroy.call(inst.scope, inst.inputValues, inst.outputProperties);',
    '  } catch (e) {',
    "    logThrow(inst, 'destroy', e);",
    '  }',
    '}',
    '',
    'function callSignal(inst: Instance, name: string): void {',
    '  if (inst.killed) return;',
    '  const fn = inst.parsed.definedObject[name];',
    "  if (typeof fn !== 'function') return;",
    '  try {',
    '    (fn as UserFunction).call(inst.scope, inst.inputValues, inst.outputProperties);',
    '  } catch (e) {',
    "    logThrow(inst, `signal ${name}`, e);",
    '  }',
    '}',
    '',
    '/** A signal input pulsed: the function runs after the pass, coalesced per name (`scheduleSignal`). */',
    'function scheduleSignal(inst: Instance, name: string): void {',
    '  if (inst.signalScheduled[name] || inst.killed) return;',
    '  inst.signalScheduled[name] = true;',
    '  queueMicrotask(() => {',
    '    inst.signalScheduled[name] = false;',
    '    if (!inst.killed) callSignal(inst, name);',
    '  });',
    '}',
    '',
    'function nextFrame(fn: () => void): void {',
    "  if (typeof requestAnimationFrame === 'function') requestAnimationFrame(fn);",
    '  else setTimeout(fn, 16);',
    '}',
    '',
    '/** Creates the node: runs the code, builds the accessors for the ports on disk, hands Node the live records. */',
    'function instantiate(def: ScriptDefinition<unknown, unknown>, publish: () => void, pulse: (name: string) => void): Instance {',
    '  const parsed = parse(def);',
    '  const inst: Instance = {',
    '    name: def.name,',
    '    parsed,',
    '    inputValues: {},',
    '    outputValues: {},',
    '    outputProperties: {},',
    '    changedInputs: {},',
    '    signalScheduled: {},',
    '    runNextFrameScheduled: false,',
    '    killed: false,',
    '    scope: undefined as unknown as ScriptScope',
    '  };',
    '  inst.scope = {',
    '    flagOutputDirty(name: string) {',
    "      if (!name) throw new Error('Output port name must be specified');",
    '      if (!inst.killed) publish();',
    '    },',
    '    sendSignalOnOutput(name: string) {',
    '      if (!inst.killed && name in def.ports.outputs) pulse(name);',
    '    },',
    '    runNextFrame() {',
    '      if (inst.runNextFrameScheduled) return;',
    '      inst.runNextFrameScheduled = true;',
    '      nextFrame(() => {',
    '        inst.runNextFrameScheduled = false;',
    '        if (!inst.killed) callRun(inst);',
    '      });',
    '    },',
    '    createComponent() {',
    "      throw new Error('createComponent is not available in the exported app');",
    '    },',
    '    deleteComponent() {',
    "      throw new Error('deleteComponent is not available in the exported app');",
    '    }',
    '  };',
    '  // The ports on disk are the ports the node has (javascript.ts registers outputs from model.outputPorts).',
    '  for (const name of Object.keys(def.ports.inputs)) {',
    "    if (def.ports.inputs[name] !== 'signal') inst.inputValues[name] = undefined;",
    '  }',
    '  for (const name of Object.keys(def.ports.outputs)) {',
    "    const isSignal = def.ports.outputs[name] === 'signal';",
    '    Object.defineProperty(inst.outputProperties, name, {',
    '      enumerable: true,',
    '      set(value: unknown) {',
    '        if (isSignal) return; // Cannot set signal functions',
    '        inst.outputValues[name] = value;',
    '        if (!inst.killed) publish();',
    '      },',
    '      get() {',
    '        if (isSignal) {',
    '          return () => {',
    '            if (!inst.killed) pulse(name);',
    '          };',
    '        }',
    '        return inst.outputValues[name];',
    '      }',
    '    });',
    '  }',
    '  // Node API: after the parse the type maps give way to the live records (javascript.ts `_onCodeParsed`).',
    '  parsed.node.Inputs = inst.inputValues;',
    '  parsed.node.Outputs = inst.outputProperties;',
    '  return inst;',
    '}',
    '',
    '// ---- the hook a component calls --------------------------------------------------------------------',
    '',
    'export interface ScriptHandle<I, O> {',
    '  /** The outputs the script has written, read live — undefined until written, as the runtime getter reads. */',
    '  readonly outputs: Readonly<Partial<O>>;',
    '  /** The signal inputs, as functions: calling one runs the script\'s function for it after this pass. */',
    '  readonly signals: { readonly [name: string]: () => void };',
    '  /** Present so `I` takes part in inference; never set. */',
    '  readonly __inputs?: I;',
    '}',
    '',
    '/**',
    ' * Hosts one Script node for the life of the component. `inputs` is the record of value inputs the',
    ' * graph feeds (a key that is absent was never delivered and reads undefined in the code); `on` is',
    ' * the chain wired off each signal output, called synchronously when the code pulses it.',
    ' */',
    'export function useScript<I, O>(',
    '  def: ScriptDefinition<I, O>,',
    '  inputs: Partial<I> = {},',
    '  on: Partial<Record<keyof O | string, () => void>> = {}',
    '): ScriptHandle<I, O> {',
    '  const [, publish] = useReducer((n: number) => n + 1, 0);',
    '  const onRef = useRef(on);',
    '  onRef.current = on;',
    '  const ref = useRef<Instance | null>(null);',
    '  const previous = useRef<Record<string, unknown> | null>(null);',
    '  const handle = useRef<ScriptHandle<I, O> | null>(null);',
    '  if (handle.current === null) {',
    '    const outputs: Record<string, unknown> = {};',
    '    for (const name of Object.keys(def.ports.outputs)) {',
    "      if (def.ports.outputs[name] === 'signal') continue;",
    '      Object.defineProperty(outputs, name, { enumerable: true, get: () => ref.current?.outputValues[name] });',
    '    }',
    '    const signals: Record<string, () => void> = {};',
    '    for (const name of Object.keys(def.ports.inputs)) {',
    "      if (def.ports.inputs[name] !== 'signal') continue;",
    '      signals[name] = () => {',
    '        if (ref.current !== null) scheduleSignal(ref.current, name);',
    '      };',
    '    }',
    '    handle.current = { outputs: outputs as Readonly<Partial<O>>, signals };',
    '  }',
    '  const record = inputs as Record<string, unknown>;',
    '  // Mount: the node is created — the code runs, the inputs it was given are delivered (each marks',
    '  // itself changed, as the replayed queue does), then setup, then the run. Unmount: destroy.',
    '  useEffect(() => {',
    '    const inst = instantiate(def as ScriptDefinition<unknown, unknown>, () => publish(), (name) => onRef.current[name as keyof O]?.());',
    '    ref.current = inst;',
    '    for (const name of Object.keys(record)) {',
    '      inst.inputValues[name] = record[name];',
    '      inst.changedInputs[name] = true;',
    '    }',
    '    previous.current = { ...record };',
    '    callSetup(inst);',
    '    callRun(inst);',
    '    return () => {',
    '      inst.killed = true;',
    '      callDestroy(inst);',
    '      ref.current = null;',
    '      previous.current = null;',
    '    };',
    '    // eslint-disable-next-line react-hooks/exhaustive-deps -- once, like the node\'s own creation',
    '  }, []);',
    '  // Every commit after: deliver what changed, then run once with those names (`userInputSetter` + `scheduleRun`).',
    '  useEffect(() => {',
    '    const inst = ref.current;',
    '    const before = previous.current;',
    '    if (inst === null || before === null) return;',
    '    let any = false;',
    '    for (const name of Object.keys(record)) {',
    '      if (before[name] === record[name] && name in before) continue;',
    '      inst.inputValues[name] = record[name];',
    '      inst.changedInputs[name] = true;',
    '      any = true;',
    '    }',
    '    previous.current = { ...record };',
    '    if (any) callRun(inst);',
    '  });',
    '  return handle.current;',
    '}',
    ''
  ].join('\n');
}
