/**
 * EXP-011 §64 — `Server-Sent Events` (`net.noodl.SSE`), Tier 3.11's first transport: `src/lib/sse.ts`, the node's
 * connection machine transcribed from `noodl-runtime/src/nodes/std-library/agent/sse.ts`, `sse-connection.ts` and
 * `stream-parsers.ts`. One hook, `useServerSentEvents(source, options, listeners)`: the two Actions are verbs on the
 * handle, the four Events and the outcome trio are listeners, every Status and Data output a live getter — the
 * streaming trio's shape (§58), so a `Text` feeding a `Text Accumulator`'s Chunk with `On Message` pulsing its Add
 * is the streaming-LLM page. The module imports `./streaming` (describeError, tryParseJson, StreamSource) and
 * `./errors` (the Failure outcome raises `sse/connect-failed`), so it earns both.
 *
 * Kept as a quoted line array like the other libs: the specs pin lines of it, and mutation arms anchor on them.
 */

/** Where the module lands in the exported app. */
export const SSE_LIB_PATH = 'src/lib/sse.ts';

export function sseLibSource(): string {
  return [
    '//',
    '// Server-Sent Events, transcribed from the interpreter it has to agree with:',
    '// noodl-runtime/src/nodes/std-library/agent/sse.ts (the node), sse-connection.ts (the connection, the two transports,',
    '// the backoff and the dedupe window) and stream-parsers.ts (the SSE frame parser, parseJsonOrText, textForPath).',
    '//',
    '// useServerSentEvents(source, options, listeners): one connection per mount — `connect()` / `disconnect()` are the two',
    '// Actions, the four Events and the outcome trio are the listeners, every Status and Data output is a live getter on the',
    '// handle. The options are the node\'s inputs, read live: a URL or Auto Connect change re-runs the runtime\'s',
    '// scheduleAutoConnect; the rest are read when the next connection opens, as the runtime reads `_internal` in doConnect.',
    '//',
    '',
    'import { useEffect, useReducer, useRef } from \'react\';',
    '',
    'import { raiseAppError } from \'./errors\';',
    'import { describeError, tryParseJson, type StreamSource } from \'./streaming\';',
    '',
    '// ============================================================================',
    '// stream-parsers.ts — the SSE frame parser, JSON-or-text, the text path',
    '// ============================================================================',
    '',
    'export interface SseFrame {',
    '  event: string;',
    '  data: string;',
    '  id: string;',
    '  retry?: number;',
    '}',
    '',
    'export interface SseParseResult {',
    '  frames: SseFrame[];',
    '  rest: string;',
    '}',
    '',
    '/** The WHATWG event-stream grammar over a buffer: complete frames out, the incomplete tail back. */',
    'export function parseSseChunk(buffer: string): SseParseResult {',
    '  const frames: SseFrame[] = [];',
    '  let i = buffer.charCodeAt(0) === 0xfeff ? 1 : 0;',
    '  let consumed = i;',
    '  let eventType = \'\';',
    '  let data: string | null = null;',
    '  let id = \'\';',
    '  let retry: number | undefined;',
    '  const dispatch = () => {',
    '    if (data === null) {',
    '      eventType = \'\';',
    '      retry = undefined;',
    '      return;',
    '    }',
    '    frames.push({',
    '      event: eventType || \'message\',',
    '      data: data.endsWith(\'\\n\') ? data.slice(0, -1) : data,',
    '      id,',
    '      ...(retry !== undefined ? { retry } : {})',
    '    });',
    '    eventType = \'\';',
    '    data = null;',
    '    retry = undefined;',
    '  };',
    '  while (i < buffer.length) {',
    '    let lineEnd = -1;',
    '    let nextStart = -1;',
    '    for (let j = i; j < buffer.length; j++) {',
    '      const c = buffer.charCodeAt(j);',
    '      if (c === 10 /* \\n */) {',
    '        lineEnd = j;',
    '        nextStart = j + 1;',
    '        break;',
    '      }',
    '      if (c === 13 /* \\r */) {',
    '        if (j + 1 >= buffer.length) {',
    '          return { frames, rest: buffer.slice(consumed) };',
    '        }',
    '        lineEnd = j;',
    '        nextStart = buffer.charCodeAt(j + 1) === 10 ? j + 2 : j + 1;',
    '        break;',
    '      }',
    '    }',
    '    if (lineEnd === -1) break; // Incomplete line.',
    '    const line = buffer.slice(i, lineEnd);',
    '    i = nextStart;',
    '    if (line.length === 0) {',
    '      dispatch();',
    '      consumed = i;',
    '      continue;',
    '    }',
    '    if (line.charCodeAt(0) === 58 /* : */) continue; // Comment / keep-alive.',
    '    const colon = line.indexOf(\':\');',
    '    const field = colon === -1 ? line : line.slice(0, colon);',
    '    let value = colon === -1 ? \'\' : line.slice(colon + 1);',
    '    if (value.charCodeAt(0) === 32 /* space */) value = value.slice(1);',
    '    if (field === \'event\') {',
    '      eventType = value;',
    '    } else if (field === \'data\') {',
    '      data = data === null ? value + \'\\n\' : data + value + \'\\n\';',
    '    } else if (field === \'id\') {',
    '      if (value.indexOf(\'\\u0000\') === -1) id = value;',
    '    } else if (field === \'retry\') {',
    '      if (/^\\d+$/.test(value)) retry = parseInt(value, 10);',
    '    }',
    '  }',
    '  return { frames, rest: buffer.slice(consumed) };',
    '}',
    '',
    '/** The Data output: parsed when the payload could be JSON and parses, the text itself otherwise. */',
    'export function parseJsonOrText(text: string): unknown {',
    '  const trimmed = text.trim();',
    '  if (trimmed === \'\') return text;',
    '  const first = trimmed.charCodeAt(0);',
    '  const couldBeJson =',
    '    first === 123 /* { */ ||',
    '    first === 91 /* [ */ ||',
    '    first === 34 /* " */ ||',
    '    first === 45 /* - */ ||',
    '    (first >= 48 && first <= 57) /* 0-9 */ ||',
    '    trimmed === \'true\' ||',
    '    trimmed === \'false\' ||',
    '    trimmed === \'null\';',
    '  if (!couldBeJson) return text;',
    '  const outcome = tryParseJson(trimmed);',
    '  return outcome.ok ? outcome.value : text;',
    '}',
    '',
    'export function splitPath(path: string): string[] {',
    '  if (!path) return [];',
    '  return path',
    '    .replace(/\\[(\\d+)\\]/g, \'.$1\')',
    '    .split(\'.\')',
    '    .map((segment) => segment.trim())',
    '    .filter((segment) => segment !== \'\');',
    '}',
    '',
    'export function valueAtPath(root: unknown, path: string): unknown {',
    '  const segments = splitPath(path);',
    '  let current: unknown = root;',
    '  for (const segment of segments) {',
    '    if (current === null || typeof current !== \'object\') return undefined;',
    '    if (segment === \'__proto__\' || segment === \'constructor\' || segment === \'prototype\') return undefined;',
    '    current = (current as Record<string, unknown>)[segment];',
    '  }',
    '  return current;',
    '}',
    '',
    '/** The Text output — always a string: Raw with no path, the field at the path when it is a string/number/boolean, blank otherwise. */',
    'export function textForPath(raw: string, parsed: unknown, path: string): string {',
    '  if (!path) return raw;',
    '  const value = valueAtPath(parsed, path);',
    '  const kind = typeof value;',
    '  if (kind === \'string\') return value as string;',
    '  if (kind === \'number\' || kind === \'boolean\') return String(value);',
    '  return \'\';',
    '}',
    '',
    '// ============================================================================',
    '// sse-connection.ts — the connection, verbatim',
    '// ============================================================================',
    '',
    'export type SseConnectionState = \'idle\' | \'connecting\' | \'open\' | \'reconnecting\' | \'closed\' | \'error\';',
    'export type SseDeliverySemantics = \'at-most-once\' | \'at-least-once\' | \'at-least-once-deduped\';',
    'export type SseTransportKind = \'eventsource\' | \'fetch\';',
    'export type SseTransportPreference = \'auto\' | SseTransportKind;',
    '',
    'export const RECONNECT_BASE_DELAY = 1000;',
    'export const RECONNECT_MAX_DELAY = 30000;',
    'export const DEFAULT_DEDUPE_WINDOW = 512;',
    '',
    '/** Exponential backoff with a ceiling: base · 2^attempt, never above max; beyond 30 attempts the ceiling. */',
    'export function backoffDelay(attempt: number, base: number, max: number): number {',
    '  const b = base > 0 ? base : RECONNECT_BASE_DELAY;',
    '  const m = max > 0 ? max : RECONNECT_MAX_DELAY;',
    '  const n = attempt > 0 ? attempt : 0;',
    '  if (n > 30) return m;',
    '  return Math.min(m, b * Math.pow(2, n));',
    '}',
    '',
    '/** The dedupe window — the last N event ids, in arrival order. */',
    'export class RecentIds {',
    '  private readonly _limit: number;',
    '  private readonly _order: string[] = [];',
    '  private readonly _set = new Set<string>();',
    '  constructor(limit?: number) {',
    '    this._limit = limit && limit > 0 ? limit : DEFAULT_DEDUPE_WINDOW;',
    '  }',
    '  has(id: string): boolean {',
    '    return this._set.has(id);',
    '  }',
    '  add(id: string): boolean {',
    '    if (this._set.has(id)) return false;',
    '    this._set.add(id);',
    '    this._order.push(id);',
    '    if (this._order.length > this._limit) {',
    '      const evicted = this._order.shift() as string;',
    '      this._set.delete(evicted);',
    '    }',
    '    return true;',
    '  }',
    '  get size(): number {',
    '    return this._set.size;',
    '  }',
    '  clear(): void {',
    '    this._order.length = 0;',
    '    this._set.clear();',
    '  }',
    '}',
    '',
    'export interface SseTransportCallbacks {',
    '  onOpen(): void;',
    '  onFrame(frame: SseFrame): void;',
    '  onFailure(message: string, fatal: boolean): void;',
    '  onEnd(): void;',
    '  onSelfRetry(): void;',
    '}',
    '',
    'export interface SseTransport {',
    '  open(): void;',
    '  close(): void;',
    '}',
    '',
    'export interface SseMessageEventLike {',
    '  data?: unknown;',
    '  lastEventId?: unknown;',
    '}',
    '',
    'export interface EventSourceLike {',
    '  readyState?: number;',
    '  onopen: ((...args: unknown[]) => void) | null;',
    '  onmessage: ((ev: SseMessageEventLike) => void) | null;',
    '  onerror: ((...args: unknown[]) => void) | null;',
    '  addEventListener(type: string, listener: (ev: SseMessageEventLike) => void): void;',
    '  close(): void;',
    '}',
    '',
    'export type EventSourceConstructorLike = new (url: string, init?: { withCredentials?: boolean }) => EventSourceLike;',
    '',
    'export interface StreamReadResultLike {',
    '  value?: unknown;',
    '  done?: boolean;',
    '}',
    '',
    'export interface StreamReaderLike {',
    '  read(): Promise<StreamReadResultLike>;',
    '  cancel?(): unknown;',
    '}',
    '',
    'export interface StreamBodyLike {',
    '  getReader?(): StreamReaderLike;',
    '  [Symbol.asyncIterator]?(): AsyncIterator<unknown>;',
    '}',
    '',
    'export interface StreamResponseLike {',
    '  ok?: boolean;',
    '  status?: number;',
    '  body?: StreamBodyLike | null;',
    '}',
    '',
    'export interface SseRequestInit {',
    '  method: string;',
    '  headers: Record<string, string>;',
    '  credentials: \'include\' | \'same-origin\';',
    '  body?: unknown;',
    '  signal?: unknown;',
    '}',
    '',
    'export type FetchLike = (url: string, init?: SseRequestInit) => Promise<StreamResponseLike>;',
    '',
    'export interface AbortControllerLike {',
    '  signal: unknown;',
    '  abort(): void;',
    '}',
    '',
    'export type AbortControllerConstructorLike = new () => AbortControllerLike;',
    '',
    '/** The environment seams the runtime keeps for its own tests — the browser\'s globals when absent. */',
    'export interface SseTransportEnv {',
    '  EventSourceImpl?: EventSourceConstructorLike | null;',
    '  fetchImpl?: FetchLike | null;',
    '  AbortControllerImpl?: AbortControllerConstructorLike | null;',
    '  setTimeoutImpl?(handler: () => void, timeout: number): unknown;',
    '  clearTimeoutImpl?(handle: unknown): void;',
    '  nowImpl?(): number;',
    '}',
    '',
    '/** The browser\'s EventSource: no headers, no body, the browser\'s own retry (reported as a self-retry). */',
    'export class EventSourceTransport implements SseTransport {',
    '  private readonly _url: string;',
    '  private readonly _withCredentials: boolean;',
    '  private readonly _eventTypes: string[];',
    '  private readonly _EventSource: EventSourceConstructorLike | null;',
    '  private readonly _cb: SseTransportCallbacks;',
    '  private _es: EventSourceLike | null = null;',
    '  private _closed = false;',
    '  private _everOpen = false;',
    '  constructor(',
    '    options: {',
    '      url: string;',
    '      withCredentials?: boolean;',
    '      eventTypes?: string[];',
    '      EventSourceImpl?: EventSourceConstructorLike | null;',
    '    },',
    '    callbacks: SseTransportCallbacks',
    '  ) {',
    '    this._url = options.url;',
    '    this._withCredentials = !!options.withCredentials;',
    '    this._eventTypes = options.eventTypes || [];',
    '    this._EventSource =',
    '      \'EventSourceImpl\' in options',
    '        ? (options.EventSourceImpl ?? null)',
    '        : typeof EventSource !== \'undefined\'',
    '          ? (EventSource as unknown as EventSourceConstructorLike)',
    '          : null;',
    '    this._cb = callbacks;',
    '  }',
    '  open(): void {',
    '    if (this._closed) return;',
    '    if (!this._EventSource) {',
    '      this._cb.onFailure(\'EventSource is not available in this environment\', true);',
    '      return;',
    '    }',
    '    let es: EventSourceLike;',
    '    try {',
    '      es = new this._EventSource(this._url, { withCredentials: this._withCredentials });',
    '    } catch (e) {',
    '      this._cb.onFailure(\'Could not open EventSource for \' + this._url + \': \' + describeError(e), true);',
    '      return;',
    '    }',
    '    this._es = es;',
    '    es.onopen = () => {',
    '      if (this._closed) return;',
    '      this._everOpen = true;',
    '      this._cb.onOpen();',
    '    };',
    '    es.onmessage = (ev: SseMessageEventLike) => {',
    '      if (this._closed) return;',
    '      this._cb.onFrame({ event: \'message\', data: ev && ev.data != null ? String(ev.data) : \'\', id: idOf(ev) });',
    '    };',
    '    for (const type of this._eventTypes) {',
    '      if (!type || type === \'message\') continue;',
    '      es.addEventListener(type, (ev: SseMessageEventLike) => {',
    '        if (this._closed) return;',
    '        this._cb.onFrame({ event: type, data: ev && ev.data != null ? String(ev.data) : \'\', id: idOf(ev) });',
    '      });',
    '    }',
    '    es.onerror = () => {',
    '      if (this._closed) return;',
    '      if (es.readyState === 2) {',
    '        this._cb.onFailure(',
    '          this._everOpen',
    '            ? \'The event stream closed and the browser stopped retrying\'',
    '            : \'Could not open the event stream (check the URL, CORS, and that the response is text/event-stream)\',',
    '          false',
    '        );',
    '        return;',
    '      }',
    '      this._cb.onSelfRetry();',
    '    };',
    '  }',
    '  close(): void {',
    '    this._closed = true;',
    '    const es = this._es;',
    '    if (!es) return;',
    '    this._es = null;',
    '    es.onopen = null;',
    '    es.onmessage = null;',
    '    es.onerror = null;',
    '    try {',
    '      es.close();',
    '    } catch (e) {',
    '      // closing twice is not an error',
    '    }',
    '  }',
    '}',
    '',
    'function idOf(ev: SseMessageEventLike): string {',
    '  const id = ev && ev.lastEventId;',
    '  return typeof id === \'string\' ? id : \'\';',
    '}',
    '',
    '/** fetch + a streaming body: headers, a method and a body; the frames parsed here; Last-Event-ID carried on a reconnect. */',
    'export class FetchStreamTransport implements SseTransport {',
    '  private readonly _url: string;',
    '  private readonly _method: string;',
    '  private readonly _headers: Record<string, string>;',
    '  private readonly _body: unknown;',
    '  private readonly _withCredentials: boolean;',
    '  private readonly _lastEventId: string;',
    '  private readonly _fetch: FetchLike | null;',
    '  private readonly _AbortController: AbortControllerConstructorLike | null;',
    '  private readonly _cb: SseTransportCallbacks;',
    '  private _controller: AbortControllerLike | null = null;',
    '  private _reader: StreamReaderLike | null = null;',
    '  private _closed = false;',
    '  constructor(',
    '    options: {',
    '      url: string;',
    '      method?: string;',
    '      headers?: Record<string, string>;',
    '      body?: unknown;',
    '      withCredentials?: boolean;',
    '      lastEventId?: string;',
    '      fetchImpl?: FetchLike | null;',
    '      AbortControllerImpl?: AbortControllerConstructorLike | null;',
    '    },',
    '    callbacks: SseTransportCallbacks',
    '  ) {',
    '    this._url = options.url;',
    '    this._method = (options.method || \'GET\').toUpperCase();',
    '    this._headers = options.headers || {};',
    '    this._body = options.body;',
    '    this._withCredentials = !!options.withCredentials;',
    '    this._lastEventId = options.lastEventId || \'\';',
    '    this._fetch =',
    '      \'fetchImpl\' in options',
    '        ? (options.fetchImpl ?? null)',
    '        : typeof fetch !== \'undefined\'',
    '          ? (fetch as unknown as FetchLike)',
    '          : null;',
    '    this._AbortController =',
    '      \'AbortControllerImpl\' in options',
    '        ? (options.AbortControllerImpl ?? null)',
    '        : typeof AbortController !== \'undefined\'',
    '          ? (AbortController as unknown as AbortControllerConstructorLike)',
    '          : null;',
    '    this._cb = callbacks;',
    '  }',
    '  open(): void {',
    '    if (this._closed) return;',
    '    if (!this._fetch) {',
    '      this._cb.onFailure(\'fetch is not available in this environment\', true);',
    '      return;',
    '    }',
    '    const headers: Record<string, string> = { Accept: \'text/event-stream\', \'Cache-Control\': \'no-store\' };',
    '    for (const key in this._headers) {',
    '      if (this._headers[key] !== undefined && this._headers[key] !== null) {',
    '        headers[key] = String(this._headers[key]);',
    '      }',
    '    }',
    '    if (this._lastEventId) headers[\'Last-Event-ID\'] = this._lastEventId;',
    '    const init: SseRequestInit = {',
    '      method: this._method,',
    '      headers,',
    '      credentials: this._withCredentials ? \'include\' : \'same-origin\'',
    '    };',
    '    if (this._body !== undefined && this._body !== null && this._method !== \'GET\' && this._method !== \'HEAD\') {',
    '      if (typeof this._body === \'string\') {',
    '        init.body = this._body;',
    '      } else {',
    '        init.body = JSON.stringify(this._body);',
    '        if (!hasHeaderNamed(headers, \'content-type\')) headers[\'Content-Type\'] = \'application/json\';',
    '      }',
    '    }',
    '    if (this._AbortController) {',
    '      try {',
    '        this._controller = new this._AbortController();',
    '        init.signal = this._controller.signal;',
    '      } catch (e) {',
    '        this._controller = null;',
    '      }',
    '    }',
    '    let promise: Promise<StreamResponseLike>;',
    '    try {',
    '      const fetchImpl = this._fetch;',
    '      promise = fetchImpl(this._url, init);',
    '    } catch (e) {',
    '      this._cb.onFailure(\'Could not start the request: \' + describeError(e), true);',
    '      return;',
    '    }',
    '    Promise.resolve(promise)',
    '      .then((res) => this._onResponse(res))',
    '      .catch((e) => {',
    '        if (this._closed || isAbort(e)) return;',
    '        this._cb.onFailure(\'Stream request failed: \' + describeError(e), false);',
    '      });',
    '  }',
    '  private async _onResponse(res: StreamResponseLike | null | undefined): Promise<void> {',
    '    if (this._closed) return;',
    '    if (!res) {',
    '      this._cb.onFailure(\'The stream request returned no response\', false);',
    '      return;',
    '    }',
    '    if (res.ok === false || (typeof res.status === \'number\' && (res.status < 200 || res.status >= 300))) {',
    '      const status = res.status;',
    '      const fatal = typeof status === \'number\' && status >= 400 && status < 500 && status !== 408 && status !== 429;',
    '      this._cb.onFailure(\'The stream endpoint returned HTTP \' + status, fatal);',
    '      return;',
    '    }',
    '    this._cb.onOpen();',
    '    const body = res.body;',
    '    if (!body) {',
    '      this._cb.onFailure(\'The response has no readable body; this environment cannot stream fetch responses\', true);',
    '      return;',
    '    }',
    '    let buffer = \'\';',
    '    const decoder = typeof TextDecoder !== \'undefined\' ? new TextDecoder(\'utf-8\') : null;',
    '    const consume = (chunk: unknown) => {',
    '      const text =',
    '        typeof chunk === \'string\' ? chunk : decoder && chunk ? decoder.decode(chunk as Uint8Array, { stream: true }) : \'\';',
    '      if (!text) return;',
    '      buffer += text;',
    '      const { frames, rest } = parseSseChunk(buffer);',
    '      buffer = rest;',
    '      for (const frame of frames) {',
    '        if (this._closed) return;',
    '        this._cb.onFrame(frame);',
    '      }',
    '    };',
    '    try {',
    '      if (typeof body.getReader === \'function\') {',
    '        const reader = body.getReader();',
    '        this._reader = reader;',
    '        for (;;) {',
    '          const step = await reader.read();',
    '          if (this._closed) return;',
    '          if (step && step.done) break;',
    '          consume(step && step.value);',
    '        }',
    '      } else if (typeof body[Symbol.asyncIterator] === \'function\') {',
    '        for await (const chunk of body as AsyncIterable<unknown>) {',
    '          if (this._closed) return;',
    '          consume(chunk);',
    '        }',
    '      } else {',
    '        this._cb.onFailure(\'The response body is neither a reader nor async-iterable\', true);',
    '        return;',
    '      }',
    '    } catch (e) {',
    '      if (this._closed || isAbort(e)) return;',
    '      this._cb.onFailure(\'The event stream was interrupted: \' + describeError(e), false);',
    '      return;',
    '    }',
    '    if (this._closed) return;',
    '    if (buffer.trim() !== \'\') {',
    '      const { frames } = parseSseChunk(buffer + \'\\n\\n\');',
    '      for (const frame of frames) {',
    '        if (this._closed) return;',
    '        this._cb.onFrame(frame);',
    '      }',
    '    }',
    '    this._cb.onEnd();',
    '  }',
    '  close(): void {',
    '    this._closed = true;',
    '    const controller = this._controller;',
    '    this._controller = null;',
    '    if (controller) {',
    '      try {',
    '        controller.abort();',
    '      } catch (e) {',
    '        // an aborted controller aborts quietly',
    '      }',
    '    }',
    '    const reader = this._reader;',
    '    this._reader = null;',
    '    if (reader && typeof reader.cancel === \'function\') {',
    '      try {',
    '        const p = reader.cancel() as { catch?: (onRejected: () => void) => unknown } | undefined;',
    '        if (p && typeof p.catch === \'function\') p.catch(() => {});',
    '      } catch (e) {',
    '        // a cancelled reader cancels quietly',
    '      }',
    '    }',
    '  }',
    '}',
    '',
    'function hasHeaderNamed(headers: Record<string, string>, name: string): boolean {',
    '  const lower = name.toLowerCase();',
    '  for (const key in headers) if (key.toLowerCase() === lower) return true;',
    '  return false;',
    '}',
    '',
    'function isAbort(e: unknown): boolean {',
    '  const name = e && (e as { name?: string }).name;',
    '  return name === \'AbortError\';',
    '}',
    '',
    'export interface SseConnectionOptions extends SseTransportEnv {',
    '  url: string;',
    '  transport?: SseTransportPreference;',
    '  method?: string;',
    '  headers?: Record<string, string>;',
    '  body?: unknown;',
    '  withCredentials?: boolean;',
    '  eventTypes?: string[];',
    '  autoReconnect?: boolean;',
    '  reconnectOnStreamEnd?: boolean;',
    '  reconnectDelay?: number;',
    '  maxReconnectDelay?: number;',
    '  maxRetries?: number;',
    '  dedupeById?: boolean;',
    '  dedupeWindow?: number;',
    '  onState?: (state: SseConnectionState) => void;',
    '  onFrame?: (frame: SseFrame) => void;',
    '  onError?: (message: string) => void;',
    '  onDuplicate?: (frame: SseFrame) => void;',
    '}',
    '',
    '/** One stream: a transport, the retry state machine, the dedupe window, the counters the Status outputs read. */',
    'export class SseConnection {',
    '  private readonly _options: SseConnectionOptions;',
    '  private readonly _setTimeout: (fn: () => void, ms: number) => unknown;',
    '  private readonly _clearTimeout: (handle: unknown) => void;',
    '  private readonly _now: () => number;',
    '  private readonly _recentIds: RecentIds;',
    '  private _transport: SseTransport | null = null;',
    '  private _reconnectTimer: unknown = null;',
    '  private _disposed = false;',
    '  state: SseConnectionState = \'idle\';',
    '  retryCount = 0;',
    '  lastError = \'\';',
    '  lastEventId = \'\';',
    '  lastEventType = \'\';',
    '  messageCount = 0;',
    '  duplicatesSuppressed = 0;',
    '  lastMessageTime = 0;',
    '  serverRetryMs: number | undefined;',
    '  private _sawEventIds = false;',
    '  constructor(options: SseConnectionOptions) {',
    '    this._options = options;',
    '    this._setTimeout = options.setTimeoutImpl || ((fn, ms) => setTimeout(fn, ms));',
    '    this._clearTimeout = options.clearTimeoutImpl || ((h) => clearTimeout(h as never));',
    '    this._now = options.nowImpl || (() => Date.now());',
    '    this._recentIds = new RecentIds(options.dedupeWindow);',
    '  }',
    '  get transportKind(): SseTransportKind {',
    '    return resolveTransport(this._options);',
    '  }',
    '  get connected(): boolean {',
    '    return this.state === \'open\';',
    '  }',
    '  get deliverySemantics(): SseDeliverySemantics {',
    '    if (!this._sawEventIds) return \'at-most-once\';',
    '    return this._options.dedupeById === false ? \'at-least-once\' : \'at-least-once-deduped\';',
    '  }',
    '  hasPendingTimer(): boolean {',
    '    return this._reconnectTimer !== null;',
    '  }',
    '  connect(): void {',
    '    if (this._disposed) return;',
    '    this._clearReconnectTimer();',
    '    this._closeTransport();',
    '    const url = this._options.url;',
    '    if (!url) {',
    '      this._fail(\'No URL was set on the stream\', true);',
    '      return;',
    '    }',
    '    this.retryCount = 0;',
    '    this.lastError = \'\';',
    '    this._setState(\'connecting\');',
    '    this._openTransport();',
    '  }',
    '  disconnect(): boolean {',
    '    if (this._disposed) return false;',
    '    this._clearReconnectTimer();',
    '    const wasActive = this._transport !== null || this.state === \'connecting\' || this.state === \'reconnecting\';',
    '    this._closeTransport();',
    '    if (wasActive || this.state !== \'closed\') this._setState(\'closed\');',
    '    return wasActive;',
    '  }',
    '  dispose(): void {',
    '    this._disposed = true;',
    '    this._clearReconnectTimer();',
    '    this._closeTransport();',
    '    this._recentIds.clear();',
    '  }',
    '  get disposed(): boolean {',
    '    return this._disposed;',
    '  }',
    '  private _openTransport(): void {',
    '    const kind = resolveTransport(this._options);',
    '    const callbacks: SseTransportCallbacks = {',
    '      onOpen: () => this._onOpen(),',
    '      onFrame: (frame) => this._onFrame(frame),',
    '      onFailure: (message, fatal) => this._fail(message, fatal),',
    '      onEnd: () => this._onEnd(),',
    '      onSelfRetry: () => this._onSelfRetry()',
    '    };',
    '    if (kind === \'eventsource\') {',
    '      this._transport = new EventSourceTransport(',
    '        {',
    '          url: this._options.url,',
    '          withCredentials: this._options.withCredentials,',
    '          eventTypes: this._options.eventTypes,',
    '          ...(\'EventSourceImpl\' in this._options ? { EventSourceImpl: this._options.EventSourceImpl } : {})',
    '        },',
    '        callbacks',
    '      );',
    '    } else {',
    '      this._transport = new FetchStreamTransport(',
    '        {',
    '          url: this._options.url,',
    '          method: this._options.method,',
    '          headers: this._options.headers,',
    '          body: this._options.body,',
    '          withCredentials: this._options.withCredentials,',
    '          lastEventId: this.lastEventId,',
    '          ...(\'fetchImpl\' in this._options ? { fetchImpl: this._options.fetchImpl } : {}),',
    '          ...(\'AbortControllerImpl\' in this._options',
    '            ? { AbortControllerImpl: this._options.AbortControllerImpl }',
    '            : {})',
    '        },',
    '        callbacks',
    '      );',
    '    }',
    '    this._transport.open();',
    '  }',
    '  private _closeTransport(): void {',
    '    const transport = this._transport;',
    '    this._transport = null;',
    '    if (transport) transport.close();',
    '  }',
    '  private _clearReconnectTimer(): void {',
    '    if (this._reconnectTimer !== null) {',
    '      this._clearTimeout(this._reconnectTimer);',
    '      this._reconnectTimer = null;',
    '    }',
    '  }',
    '  private _setState(state: SseConnectionState): void {',
    '    if (this.state === state) return;',
    '    this.state = state;',
    '    if (!this._disposed && this._options.onState) this._options.onState(state);',
    '  }',
    '  private _onOpen(): void {',
    '    if (this._disposed) return;',
    '    this.retryCount = 0;',
    '    this.lastError = \'\';',
    '    this._setState(\'open\');',
    '  }',
    '  private _onFrame(frame: SseFrame): void {',
    '    if (this._disposed) return;',
    '    if (frame.retry !== undefined) this.serverRetryMs = frame.retry;',
    '    if (frame.id) {',
    '      this._sawEventIds = true;',
    '      this.lastEventId = frame.id;',
    '      if (this._options.dedupeById !== false && !this._recentIds.add(frame.id)) {',
    '        this.duplicatesSuppressed++;',
    '        if (this._options.onDuplicate) this._options.onDuplicate(frame);',
    '        return;',
    '      }',
    '    }',
    '    this.messageCount++;',
    '    this.lastEventType = frame.event;',
    '    this.lastMessageTime = this._now();',
    '    if (this._options.onFrame) this._options.onFrame(frame);',
    '  }',
    '  private _onEnd(): void {',
    '    if (this._disposed) return;',
    '    this._closeTransport();',
    '    if (this._options.reconnectOnStreamEnd) {',
    '      this._scheduleReconnect();',
    '      return;',
    '    }',
    '    this._setState(\'closed\');',
    '  }',
    '  private _onSelfRetry(): void {',
    '    if (this._disposed) return;',
    '    this.retryCount++;',
    '    const max = this._options.maxRetries || 0;',
    '    if (max > 0 && this.retryCount > max) {',
    '      this._closeTransport();',
    '      this._fail(\'Gave up after \' + max + \' reconnection attempts\', true);',
    '      return;',
    '    }',
    '    this._report(\'The event stream dropped; the browser is reconnecting\');',
    '    this._setState(\'reconnecting\');',
    '  }',
    '  private _fail(message: string, fatal: boolean): void {',
    '    if (this._disposed) return;',
    '    this._report(message);',
    '    if (fatal) {',
    '      this._closeTransport();',
    '      this._setState(\'error\');',
    '      return;',
    '    }',
    '    if (this._options.autoReconnect === false) {',
    '      this._closeTransport();',
    '      this._setState(\'error\');',
    '      return;',
    '    }',
    '    const max = this._options.maxRetries || 0;',
    '    if (max > 0 && this.retryCount >= max) {',
    '      this._closeTransport();',
    '      this.lastError = message + \' (gave up after \' + max + \' attempts)\';',
    '      if (this._options.onError) this._options.onError(this.lastError);',
    '      this._setState(\'error\');',
    '      return;',
    '    }',
    '    this._closeTransport();',
    '    this.retryCount++;',
    '    this._scheduleReconnect();',
    '  }',
    '  private _scheduleReconnect(): void {',
    '    this._clearReconnectTimer();',
    '    const base = this.serverRetryMs !== undefined ? this.serverRetryMs : (this._options.reconnectDelay as number);',
    '    const delay = backoffDelay(this.retryCount - 1 > 0 ? this.retryCount - 1 : 0, base, this._options.maxReconnectDelay as number);',
    '    this._setState(\'reconnecting\');',
    '    this._reconnectTimer = this._setTimeout(() => {',
    '      this._reconnectTimer = null;',
    '      if (this._disposed) return;',
    '      this._openTransport();',
    '    }, delay);',
    '  }',
    '  private _report(message: string): void {',
    '    this.lastError = message;',
    '    if (!this._disposed && this._options.onError) this._options.onError(message);',
    '  }',
    '}',
    '',
    '/** Auto prefers fetch (headers, a body, the frames parsed here) and falls back to EventSource. */',
    'export function resolveTransport(options: {',
    '  transport?: SseTransportPreference;',
    '  method?: string;',
    '  headers?: Record<string, string>;',
    '  body?: unknown;',
    '  fetchImpl?: FetchLike | null;',
    '  EventSourceImpl?: EventSourceConstructorLike | null;',
    '}): SseTransportKind {',
    '  if (options.transport === \'eventsource\') return \'eventsource\';',
    '  if (options.transport === \'fetch\') return \'fetch\';',
    '  const haveFetch = \'fetchImpl\' in options ? !!options.fetchImpl : typeof fetch !== \'undefined\';',
    '  if (haveFetch) return \'fetch\';',
    '  const haveEventSource = \'EventSourceImpl\' in options ? !!options.EventSourceImpl : typeof EventSource !== \'undefined\';',
    '  if (haveEventSource) return \'eventsource\';',
    '  return \'fetch\';',
    '}',
    '',
    '// ============================================================================',
    '// sse.ts — the node',
    '// ============================================================================',
    '',
    '/** The outcome a Connect reports (`sse/connect-failed`, the node\'s one code). */',
    'export const SSE_ERROR_CONNECT_FAILED = \'sse/connect-failed\';',
    '',
    '/**',
    ' * The node\'s inputs, typed as the ports take them — a wire delivers whatever it delivers, and each is coerced here',
    ' * exactly as the runtime setter coerces it. A key that is absent keeps initialize()\'s value; a key present with',
    ' * `undefined` is a wire that delivered nothing, which the setters read as their empty case.',
    ' */',
    'export interface ServerSentEventsOptions {',
    '  /** URL: `\'\'` when null/undefined, else `String(value)`; a change while connected reconnects to the new one. */',
    '  url?: unknown;',
    '  /** Transport: \'auto\' | \'fetch\' | \'eventsource\' — anything falsy is \'auto\'. */',
    '  transport?: unknown;',
    '  /** Method: anything falsy is \'GET\'. */',
    '  method?: unknown;',
    '  /** Headers: an object, else none. */',
    '  headers?: unknown;',
    '  /** Body: stored raw. */',
    '  body?: unknown;',
    '  /** With Credentials: `!!value`. */',
    '  withCredentials?: unknown;',
    '  /** Event Types: a comma-separated string; anything falsy is \'\'. */',
    '  eventTypes?: unknown;',
    '  /** Text Path: `\'\'` when null/undefined, else `String(value)`. */',
    '  textPath?: unknown;',
    '  /** Auto Connect: `!!value`. */',
    '  autoConnect?: unknown;',
    '  /** Auto Reconnect: `!!value`; initialize() says true. */',
    '  autoReconnect?: unknown;',
    '  /** Reconnect On Stream End: `!!value`. */',
    '  reconnectOnStreamEnd?: unknown;',
    '  /** Reconnect Delay (ms): `Number(value) > 0 ? Number(value) : 1000`. */',
    '  reconnectDelay?: unknown;',
    '  /** Max Reconnect Delay (ms): `Number(value) > 0 ? Number(value) : 30000`. */',
    '  maxReconnectDelay?: unknown;',
    '  /** Max Retries: `Number(value) > 0 ? Number(value) : 0`. */',
    '  maxRetries?: unknown;',
    '  /** Dedupe By Id: `!!value`; initialize() says true. */',
    '  dedupeById?: unknown;',
    '}',
    '',
    '/** The four Events and the outcome trio (+ Completed), called after the outputs are written — a chain reads this frame\'s values. */',
    'export interface ServerSentEventsListeners {',
    '  /** On Open — the stream has been established. */',
    '  onOpen?: () => void;',
    '  /** On Message — once per event, after Data, Raw and Text already hold it. */',
    '  onMessage?: () => void;',
    '  /** On Error — the stream failed or dropped, whether or not a retry follows. */',
    '  onError?: () => void;',
    '  /** On Close — the stream has stopped for good, cleanly or having given up. */',
    '  onClose?: () => void;',
    '  /** Done — a Connect whose stream opened, or a Disconnect that stopped one. */',
    '  done?: () => void;',
    '  /** Completed — after every Connect or Disconnect, whatever the outcome. */',
    '  completed?: () => void;',
    '  /** Unchanged — a Disconnect with nothing running, or a Connect a later Connect or Disconnect superseded before it opened. */',
    '  unchanged?: () => void;',
    '  /** Failure — the stream could not be opened, or gave up retrying; Last Error carries the reason. */',
    '  failure?: () => void;',
    '}',
    '',
    '/** What a Server-Sent Events node hands the page. */',
    'export interface ServerSentEventsHandle {',
    '  /** Connect — opens the stream, replacing any connection already open and resetting the retry count. */',
    '  connect(): void;',
    '  /** Disconnect — closes the stream and stops retrying. */',
    '  disconnect(): void;',
    '  /** Connection State: idle, connecting, open, reconnecting, closed or error. */',
    '  readonly connectionState: string;',
    '  /** Connected: true only while the stream is open. */',
    '  readonly connected: boolean;',
    '  /** Last Error. */',
    '  readonly lastError: string;',
    '  /** Retry Count. */',
    '  readonly retryCount: number;',
    '  /** Data: the payload parsed as JSON when it is JSON, the text when it is not; undefined before the first event. */',
    '  readonly data: unknown;',
    '  /** Raw. */',
    '  readonly raw: string;',
    '  /** Text: Raw with no Text Path, the field at the path when one is set, blank when it does not resolve. */',
    '  readonly text: string;',
    '  /** Event Type: the event name the server sent, or message. */',
    '  readonly eventType: string;',
    '  /** Last Event Id. */',
    '  readonly lastEventId: string;',
    '  /** Message Count. */',
    '  readonly messageCount: number;',
    '  /** Last Message Time: ms since the epoch, 0 before the first event. */',
    '  readonly lastMessageTime: number;',
    '  /** Duplicates Suppressed. */',
    '  readonly duplicatesSuppressed: number;',
    '  /** Delivery Semantics: at-most-once, at-least-once or at-least-once-deduped. */',
    '  readonly deliverySemantics: string;',
    '}',
    '',
    '/** Node.beginOutcome()\'s token: one report, then spent. */',
    'interface OutcomeToken {',
    '  reported: boolean;',
    '}',
    '',
    '/** The node\'s `_internal`, as initialize() fills it. */',
    'interface SseInternal {',
    '  url: string;',
    '  transport: SseTransportPreference;',
    '  method: string;',
    '  headers: Record<string, string> | null;',
    '  body: unknown;',
    '  withCredentials: boolean;',
    '  eventTypes: string;',
    '  textPath: string;',
    '  autoConnect: boolean;',
    '  autoReconnect: boolean;',
    '  reconnectOnStreamEnd: boolean;',
    '  reconnectDelay: number;',
    '  maxReconnectDelay: number;',
    '  maxRetries: number;',
    '  dedupeById: boolean;',
    '  connection: SseConnection | null;',
    '  connectedUrl?: string;',
    '  connectionState: SseConnectionState;',
    '  data: unknown;',
    '  raw: string;',
    '  eventType: string;',
    '  pendingConnect: OutcomeToken | null;',
    '}',
    '',
    '/** EXP-011 §66.5: node.ts sendValue drops an undefined before it crosses a wire (`if (value === undefined) return;`), so a setter never sees one — an option passed as undefined (a Variable nothing has written) is NOT a delivery: the internal keeps what it holds. */',
    'function has(options: object, key: string): boolean {',
    '  return Object.prototype.hasOwnProperty.call(options, key) && (options as Record<string, unknown>)[key] !== undefined;',
    '}',
    '',
    '/** initialize(). */',
    'function createInternal(): SseInternal {',
    '  return {',
    '    url: \'\',',
    '    transport: \'auto\',',
    '    method: \'GET\',',
    '    headers: null,',
    '    body: undefined,',
    '    withCredentials: false,',
    '    eventTypes: \'\',',
    '    textPath: \'\',',
    '    autoConnect: false,',
    '    autoReconnect: true,',
    '    reconnectOnStreamEnd: false,',
    '    reconnectDelay: 1000,',
    '    maxReconnectDelay: 30000,',
    '    maxRetries: 0,',
    '    dedupeById: true,',
    '    connection: null,',
    '    connectionState: \'idle\',',
    '    data: undefined,',
    '    raw: \'\',',
    '    eventType: \'\',',
    '    pendingConnect: null',
    '  };',
    '}',
    '',
    '/** The setters, keyed on presence — each coerces exactly as the runtime\'s `set` does. */',
    'function applyOptions(internal: SseInternal, options: ServerSentEventsOptions): void {',
    '  if (has(options, \'url\')) internal.url = options.url === undefined || options.url === null ? \'\' : String(options.url);',
    '  if (has(options, \'transport\')) internal.transport = (options.transport as SseTransportPreference) || \'auto\';',
    '  if (has(options, \'method\')) internal.method = (options.method as string) || \'GET\';',
    '  if (has(options, \'headers\')) {',
    '    internal.headers = options.headers && typeof options.headers === \'object\' ? (options.headers as Record<string, string>) : null;',
    '  }',
    '  if (has(options, \'body\')) internal.body = options.body;',
    '  if (has(options, \'withCredentials\')) internal.withCredentials = !!options.withCredentials;',
    '  if (has(options, \'eventTypes\')) internal.eventTypes = (options.eventTypes as string) || \'\';',
    '  if (has(options, \'textPath\')) internal.textPath = options.textPath === undefined || options.textPath === null ? \'\' : String(options.textPath);',
    '  if (has(options, \'autoConnect\')) internal.autoConnect = !!options.autoConnect;',
    '  if (has(options, \'autoReconnect\')) internal.autoReconnect = !!options.autoReconnect;',
    '  if (has(options, \'reconnectOnStreamEnd\')) internal.reconnectOnStreamEnd = !!options.reconnectOnStreamEnd;',
    '  if (has(options, \'reconnectDelay\')) internal.reconnectDelay = Number(options.reconnectDelay) > 0 ? Number(options.reconnectDelay) : 1000;',
    '  if (has(options, \'maxReconnectDelay\')) internal.maxReconnectDelay = Number(options.maxReconnectDelay) > 0 ? Number(options.maxReconnectDelay) : 30000;',
    '  if (has(options, \'maxRetries\')) internal.maxRetries = Number(options.maxRetries) > 0 ? Number(options.maxRetries) : 0;',
    '  if (has(options, \'dedupeById\')) internal.dedupeById = !!options.dedupeById;',
    '}',
    '',
    '/** Everything the node kept on `this`, in one ref. */',
    'interface SseState {',
    '  source: StreamSource;',
    '  internal: SseInternal;',
    '  env: SseTransportEnv;',
    '  dead: boolean;',
    '  latest: { options: ServerSentEventsOptions; listeners: ServerSentEventsListeners };',
    '  rerender: () => void;',
    '}',
    '',
    '/** Node.reportOutcome: on a Failure the raise, then the outcome\'s pulse, then Completed. Unchanged never raises. */',
    'function reportOutcome(s: SseState, token: OutcomeToken, outcome: \'done\' | \'unchanged\' | \'failure\', failure?: { code: string; message: string }): void {',
    '  if (token.reported) return;',
    '  token.reported = true;',
    '  if (outcome === \'failure\' && failure !== undefined) {',
    '    raiseAppError({ code: failure.code, message: failure.message, nodeId: s.source.nodeId, nodeType: \'net.noodl.SSE\', componentName: s.source.componentName });',
    '  }',
    '  s.latest.listeners[outcome]?.();',
    '  s.latest.listeners.completed?.();',
    '}',
    '',
    '/** settleConnect: the pending Connect\'s token takes this outcome, once. */',
    'function settleConnect(s: SseState, outcome: \'done\' | \'unchanged\' | \'failure\', code?: string, message?: string): void {',
    '  const token = s.internal.pendingConnect;',
    '  if (!token) return;',
    '  s.internal.pendingConnect = null;',
    '  reportOutcome(s, token, outcome, outcome === \'failure\' ? { code: code as string, message: message as string } : undefined);',
    '}',
    '',
    'function teardownConnection(s: SseState): void {',
    '  const connection = s.internal.connection;',
    '  s.internal.connection = null;',
    '  if (connection) connection.dispose();',
    '}',
    '',
    '/** handleState: the Status outputs move, then On Open / On Close, then the pending Connect settles. */',
    'function handleState(s: SseState, state: SseConnectionState): void {',
    '  const internal = s.internal;',
    '  internal.connectionState = state;',
    '  s.rerender();',
    '  if (state === \'open\') s.latest.listeners.onOpen?.();',
    '  if (state === \'closed\' || state === \'error\') s.latest.listeners.onClose?.();',
    '  if (state === \'open\') settleConnect(s, \'done\');',
    '  if (state === \'error\') {',
    '    const conn = internal.connection;',
    '    settleConnect(s, \'failure\', SSE_ERROR_CONNECT_FAILED, (conn && conn.lastError) || \'The stream could not be opened\');',
    '  }',
    '}',
    '',
    '/** handleFrame: Raw, Data, Event Type written (Text derives), then On Message. */',
    'function handleFrame(s: SseState, frame: SseFrame): void {',
    '  const internal = s.internal;',
    '  internal.raw = frame.data;',
    '  internal.data = parseJsonOrText(frame.data);',
    '  internal.eventType = frame.event;',
    '  s.rerender();',
    '  s.latest.listeners.onMessage?.();',
    '}',
    '',
    '/** handleError: Last Error / Retry Count / Duplicates Suppressed move, then On Error. */',
    'function handleError(s: SseState): void {',
    '  s.rerender();',
    '  s.latest.listeners.onError?.();',
    '}',
    '',
    '/** doConnect: settle any earlier Connect as Unchanged, tear the connection down, open a new one on the current inputs. */',
    'function doConnect(s: SseState, outcome?: OutcomeToken): void {',
    '  const internal = s.internal;',
    '  settleConnect(s, \'unchanged\');',
    '  internal.pendingConnect = outcome || null;',
    '  teardownConnection(s);',
    '  internal.connectedUrl = internal.url;',
    '  const options: SseConnectionOptions = {',
    '    url: internal.url,',
    '    transport: internal.transport,',
    '    method: internal.method,',
    '    headers: internal.headers || undefined,',
    '    body: internal.body,',
    '    withCredentials: internal.withCredentials,',
    '    eventTypes: internal.eventTypes',
    '      ? internal.eventTypes',
    '          .split(\',\')',
    '          .map((part) => part.trim())',
    '          .filter(Boolean)',
    '      : [],',
    '    autoReconnect: internal.autoReconnect,',
    '    reconnectOnStreamEnd: internal.reconnectOnStreamEnd,',
    '    reconnectDelay: internal.reconnectDelay,',
    '    maxReconnectDelay: internal.maxReconnectDelay,',
    '    maxRetries: internal.maxRetries,',
    '    dedupeById: internal.dedupeById,',
    '    onState: (state) => handleState(s, state),',
    '    onFrame: (frame) => handleFrame(s, frame),',
    '    onError: () => handleError(s),',
    '    ...s.env',
    '  };',
    '  const connection = new SseConnection(options);',
    '  internal.connection = connection;',
    '  connection.connect();',
    '}',
    '',
    'function doDisconnect(s: SseState): boolean {',
    '  const connection = s.internal.connection;',
    '  return connection ? connection.disconnect() : false;',
    '}',
    '',
    '/**',
    ' * scheduleAutoConnect\'s body, run after the inputs have updated: a live connection on a changed URL is superseded',
    ' * (Unchanged) and reopened when Auto Connect says so; no connection and Auto Connect + a URL opens one.',
    ' */',
    'function autoConnect(s: SseState): void {',
    '  const internal = s.internal;',
    '  const live = internal.connection && !internal.connection.disposed ? internal.connection : null;',
    '  if (live) {',
    '    if (internal.connectedUrl === internal.url) return;',
    '    settleConnect(s, \'unchanged\');',
    '    teardownConnection(s);',
    '    if (internal.autoConnect && internal.url) doConnect(s);',
    '    return;',
    '  }',
    '  if (!internal.autoConnect || !internal.url) return;',
    '  doConnect(s);',
    '}',
    '',
    '/**',
    ' * A Server-Sent Events node. `env` is the runtime\'s own test seam (a fetch, an EventSource, a clock, timers) — the',
    ' * emitted page never passes it.',
    ' */',
    'export function useServerSentEvents(',
    '  source: StreamSource,',
    '  options: ServerSentEventsOptions = {},',
    '  on: ServerSentEventsListeners = {},',
    '  env: SseTransportEnv = {}',
    '): ServerSentEventsHandle {',
    '  const [, publish] = useReducer((n: number) => n + 1, 0);',
    '  const stateRef = useRef<SseState | null>(null);',
    '  const handleRef = useRef<ServerSentEventsHandle | null>(null);',
    '  if (stateRef.current === null || handleRef.current === null) {',
    '    const s: SseState = {',
    '      source,',
    '      internal: createInternal(),',
    '      env,',
    '      dead: false,',
    '      latest: { options, listeners: on },',
    '      rerender: () => {',
    '        if (!s.dead) publish();',
    '      }',
    '    };',
    '    stateRef.current = s;',
    '    const internal = s.internal;',
    '    handleRef.current = {',
    '      connect() {',
    '        applyOptions(internal, s.latest.options);',
    '        doConnect(s, { reported: false });',
    '      },',
    '      disconnect() {',
    '        applyOptions(internal, s.latest.options);',
    '        const token: OutcomeToken = { reported: false };',
    '        settleConnect(s, \'unchanged\');',
    '        reportOutcome(s, token, doDisconnect(s) ? \'done\' : \'unchanged\');',
    '      },',
    '      get connectionState() {',
    '        return internal.connectionState;',
    '      },',
    '      get connected() {',
    '        return internal.connectionState === \'open\';',
    '      },',
    '      get lastError() {',
    '        return internal.connection ? internal.connection.lastError : \'\';',
    '      },',
    '      get retryCount() {',
    '        return internal.connection ? internal.connection.retryCount : 0;',
    '      },',
    '      get data() {',
    '        return internal.data;',
    '      },',
    '      get raw() {',
    '        return internal.raw;',
    '      },',
    '      get text() {',
    '        return textForPath(internal.raw, internal.data, internal.textPath);',
    '      },',
    '      get eventType() {',
    '        return internal.eventType;',
    '      },',
    '      get lastEventId() {',
    '        return internal.connection ? internal.connection.lastEventId : \'\';',
    '      },',
    '      get messageCount() {',
    '        return internal.connection ? internal.connection.messageCount : 0;',
    '      },',
    '      get lastMessageTime() {',
    '        return internal.connection ? internal.connection.lastMessageTime : 0;',
    '      },',
    '      get duplicatesSuppressed() {',
    '        return internal.connection ? internal.connection.duplicatesSuppressed : 0;',
    '      },',
    '      get deliverySemantics() {',
    '        return internal.connection ? internal.connection.deliverySemantics : \'at-most-once\';',
    '      }',
    '    };',
    '  }',
    '  const s = stateRef.current;',
    '  s.latest = { options, listeners: on };',
    '',
    '  const scheduled = useRef<{ url: unknown; autoConnect: unknown } | null>(null);',
    '  // _onNodeDeleted: the connection torn down, the pending Connect forgotten. StrictMode runs the mount twice in',
    '  // development; the cleanup between tears the first connection down and the second mount\'s pass reopens it.',
    '  useEffect(() => {',
    '    s.dead = false;',
    '    scheduled.current = null;',
    '    return () => {',
    '      s.dead = true;',
    '      teardownConnection(s);',
    '      s.internal.pendingConnect = null;',
    '    };',
    '    // eslint-disable-next-line react-hooks/exhaustive-deps -- the state object is created once',
    '  }, []);',
    '',
    '  // The setters run on every render (a wired input delivers on change); the URL and Auto Connect setters schedule',
    '  // the auto-connect pass, which runs once after the inputs have updated — here, after the render that changed them.',
    '  useEffect(() => {',
    '    applyOptions(s.internal, s.latest.options);',
    '    const prev = scheduled.current;',
    '    // The APPLIED values, not the raw options — an undefined on a later render ran no setter (§66.5).',
    '    const next = { url: s.internal.url, autoConnect: s.internal.autoConnect };',
    '    scheduled.current = next;',
    '    if (prev === null || prev.url !== next.url || prev.autoConnect !== next.autoConnect) autoConnect(s);',
    '  });',
    '',
    '  return handleRef.current;',
    '}'
  ].join('\n');
}
