/**
 * `src/lib/streaming.ts` — the streaming trio's host, emitted into the app (EXP-011 §58).
 *
 * {@link ./runTasksLib.ts}'s shape, one module over: a transcription of the runtime the three nodes have to
 * agree with, shipped only when a component keeps a `JSON Stream Parser`, a `Stream Buffer` or a `Text
 * Accumulator`. It transcribes `noodl-runtime/src/nodes/std-library/agent/stream-parsers.ts` (the pure cores —
 * `splitDelimited`, `scanJsonValues` with its string / escape / depth tracking and its waiting scalar,
 * `tryParseJson`, `truncateHead`, `utf8ByteLength`) and the three node files (`json-stream-parser.ts`,
 * `stream-buffer.ts`, `text-accumulator.ts`) as pure functions over a state object that return the ORDERED event
 * list the runtime would issue — every value-level signal, every outcome (`done` / `unchanged` / `failure`, then
 * `completed`, the raise before the `failure` pulse as `Node.reportOutcome` orders it), and the buffer's timer
 * instructions — so every boundary case is gradable under node, and three hooks that deliver those events.
 *
 * The data port is delivered with the pulse (`parse(chunk)`, `add(data)`: the setter, then the action); the config
 * ports are read off an options object every render (a present key goes through the setter's coercion, an
 * absent one keeps `initialize()`'s value). The value outputs are live getters over the state. The raises carry
 * the node's own provenance (`Node.raiseRuntimeError`'s three fields) through `./errors`.
 *
 * What differs, recorded in the module's own header: the setters run at the pulse rather than at delivery; a
 * wired `Data` counts as arrived; `flagOutputDirty` collapses into one re-render per invocation.
 */

export const STREAMING_LIB_PATH = 'src/lib/streaming.ts';

export function streamingLibSource(): string {
  return [
    '//',
    '// The streaming trio, hosted. Transcribed from the runtime they have to agree with:',
    '// noodl-runtime/src/nodes/std-library/agent/stream-parsers.ts (the pure cores: splitDelimited, scanJsonValues,',
    '// tryParseJson, truncateHead, utf8ByteLength), json-stream-parser.ts, stream-buffer.ts and text-accumulator.ts',
    '// (the three state machines, their value outputs, their signals and their outcomes — Done / Unchanged / Failure,',
    '// then Completed, as Node.reportOutcome orders them: on a Failure the raise first, then the pulse).',
    '//',
    '// Each machine is a set of pure functions over a plain state object that return the ORDERED list of events the',
    '// runtime would issue — every signal, every raise, and for the buffer the timer it would arm or stop — so the',
    '// behaviour is gradable without React. The hooks keep one state per node in a ref, deliver the events (a signal',
    "// to its listener, a raise to the app's error channel with the node's own provenance, the timer to setTimeout)",
    "// and re-render the host once per invocation. The handle's value outputs are live getters over the state, so a",
    "// chain fired by a signal reads what the runtime's getter answers at that moment.",
    '//',
    "// The data input (Chunk / Data) is delivered with the pulse: parse(chunk) / add(data) run the port's setter, then",
    '// the action; a call with no argument means the port was never fed, and the setter never ran.',
    "// Config inputs are read off the options object every render: a key that is present goes through the port's",
    "// setter (its coercion), a key that is absent keeps the node's initialize() value — a declared default never runs",
    '// its setter.',
    '//',
    '// Recorded divergences: the setters run at the pulse with the value the render or the chain holds, not at the',
    "// moment a wire delivers it — so the accumulator's refused-chunk Failure fires at the Add that carries it; a wired",
    '// Data counts as arrived whether or not its source has published; flagOutputDirty collapses into one re-render per',
    '// invocation.',
    '//',
    '',
    "import { useEffect, useReducer, useRef } from 'react';",
    '',
    "import { raiseAppError } from './errors';",
    '',
    '// ============================================================================',
    '// The pure cores — stream-parsers.ts',
    '// ============================================================================',
    '',
    'export interface DelimitedResult {',
    '  messages: string[];',
    '  rest: string;',
    '}',
    '',
    '/** Splits `buffer` on `delimiter`, keeping the trailing incomplete piece in `rest`. An empty delimiter never splits. */',
    'export function splitDelimited(buffer: string, delimiter: string): DelimitedResult {',
    '  if (!delimiter) return { messages: [], rest: buffer };',
    '  const parts = buffer.split(delimiter);',
    '  const rest = parts.pop() as string;',
    '  return { messages: parts, rest };',
    '}',
    '',
    'export interface JsonScanResult {',
    '  /** Complete top-level values, in order. */',
    '  values: unknown[];',
    "  /** The unparsed tail — an incomplete value, or ''. */",
    '  rest: string;',
    '  /** One entry per value that scanned as complete but failed JSON.parse. */',
    '  errors: string[];',
    '}',
    '',
    'export interface JsonScanOptions {',
    '  /** Treat top-level `[`, `]` and `,` as framing rather than data. Default true. */',
    '  arrayFraming?: boolean;',
    '}',
    '',
    '/** Extracts every complete top-level JSON value from `buffer`; an unterminated value waits in `rest`. */',
    'export function scanJsonValues(buffer: string, options?: JsonScanOptions): JsonScanResult {',
    '  const arrayFraming = options?.arrayFraming !== false;',
    '  const values: unknown[] = [];',
    '  const errors: string[] = [];',
    '',
    '  let i = 0;',
    '  while (i < buffer.length) {',
    '    while (i < buffer.length) {',
    '      const c = buffer[i];',
    "      if (c === ' ' || c === '\\t' || c === '\\n' || c === '\\r') i++;",
    "      else if (arrayFraming && (c === ',' || c === '[' || c === ']')) i++;",
    '      else break;',
    '    }',
    "    if (i >= buffer.length) return { values, rest: '', errors };",
    '',
    '    const end = scanOneValue(buffer, i);',
    '    if (end === -1) return { values, rest: buffer.slice(i), errors };',
    '',
    '    const slice = buffer.slice(i, end);',
    '    try {',
    '      values.push(JSON.parse(slice));',
    '    } catch (e) {',
    "      errors.push('Could not parse JSON value: ' + describeError(e));",
    '    }',
    '    i = end;',
    '  }',
    '',
    "  return { values, rest: '', errors };",
    '}',
    '',
    '/** The index just past the JSON value starting at `start`, or -1 if it is not yet complete. */',
    'function scanOneValue(buffer: string, start: number): number {',
    '  const first = buffer[start];',
    '',
    "  if (first === '{' || first === '[') {",
    '    let depth = 0;',
    '    let inString = false;',
    '    let escaped = false;',
    '    for (let j = start; j < buffer.length; j++) {',
    '      const c = buffer[j];',
    '      if (inString) {',
    '        if (escaped) escaped = false;',
    "        else if (c === '\\\\') escaped = true;",
    "        else if (c === '\"') inString = false;",
    '        continue;',
    '      }',
    "      if (c === '\"') inString = true;",
    "      else if (c === '{' || c === '[') depth++;",
    "      else if (c === '}' || c === ']') {",
    '        depth--;',
    '        if (depth === 0) return j + 1;',
    '      }',
    '    }',
    '    return -1;',
    '  }',
    '',
    "  if (first === '\"') {",
    '    let escaped = false;',
    '    for (let j = start + 1; j < buffer.length; j++) {',
    '      const c = buffer[j];',
    '      if (escaped) escaped = false;',
    "      else if (c === '\\\\') escaped = true;",
    "      else if (c === '\"') return j + 1;",
    '    }',
    '    return -1;',
    '  }',
    '',
    '  // A scalar is only complete once something that cannot belong to it has arrived: `12` might still become `123`.',
    '  for (let j = start; j < buffer.length; j++) {',
    '    const c = buffer[j];',
    "    if (c === ' ' || c === '\\t' || c === '\\n' || c === '\\r' || c === ',' || c === '}' || c === ']') {",
    '      return j;',
    '    }',
    '  }',
    '  return -1;',
    '}',
    '',
    'export interface JsonParseOutcome {',
    '  ok: boolean;',
    '  value?: unknown;',
    '  error?: string;',
    '}',
    '',
    '/** JSON.parse that reports rather than throws. */',
    'export function tryParseJson(text: string): JsonParseOutcome {',
    '  try {',
    '    return { ok: true, value: JSON.parse(text) };',
    '  } catch (e) {',
    '    return { ok: false, error: describeError(e) };',
    '  }',
    '}',
    '',
    "/** UTF-8 byte length of `text`, computed (a lone surrogate counts as U+FFFD's three bytes). */",
    'export function utf8ByteLength(text: string): number {',
    '  let bytes = 0;',
    '  for (let i = 0; i < text.length; i++) {',
    '    const code = text.charCodeAt(i);',
    '    if (code < 0x80) bytes += 1;',
    '    else if (code < 0x800) bytes += 2;',
    '    else if (code >= 0xd800 && code <= 0xdbff) {',
    '      const next = text.charCodeAt(i + 1);',
    '      if (next >= 0xdc00 && next <= 0xdfff) {',
    '        bytes += 4;',
    '        i++;',
    '      } else {',
    '        bytes += 3;',
    '      }',
    '    } else bytes += 3;',
    '  }',
    '  return bytes;',
    '}',
    '',
    '/** Caps `text` at `maxLength` characters by dropping from the FRONT — streams are newest-interesting. */',
    'export function truncateHead(text: string, maxLength: number): { text: string; dropped: number } {',
    '  if (!(maxLength > 0) || text.length <= maxLength) return { text, dropped: 0 };',
    '  return { text: text.slice(text.length - maxLength), dropped: text.length - maxLength };',
    '}',
    '',
    '/** Human-readable message from an unknown thrown value. */',
    'export function describeError(e: unknown): string {',
    '  if (e instanceof Error) return e.message;',
    "  if (typeof e === 'string') return e;",
    '  try {',
    '    return String(e);',
    '  } catch {',
    "    return 'Unknown error';",
    '  }',
    '}',
    '',
    '// ============================================================================',
    "// The events a machine issues, in the runtime's order",
    '// ============================================================================',
    '',
    'export type StreamEvent =',
    "  | { kind: 'signal'; name: string }",
    "  | { kind: 'raise'; code: string; message: string }",
    "  | { kind: 'arm-timer' }",
    "  | { kind: 'stop-timer' };",
    '',
    "/** Node.reportOutcome: on a Failure the raise (unless a more precise raise already went out), then the outcome's pulse, then Completed. Unchanged never raises. */",
    'function reportOutcome(',
    '  events: StreamEvent[],',
    "  outcome: 'done' | 'unchanged' | 'failure',",
    '  failure?: { code: string; message: string; raise?: boolean }',
    '): void {',
    "  if (outcome === 'failure' && failure !== undefined && failure.raise !== false) {",
    "    events.push({ kind: 'raise', code: failure.code, message: failure.message });",
    '  }',
    "  events.push({ kind: 'signal', name: outcome });",
    "  events.push({ kind: 'signal', name: 'completed' });",
    '}',
    '',
    '/** Which node this is — the provenance every raise carries (Node.raiseRuntimeError fills the same three in). */',
    'export interface StreamSource {',
    "  /** The authored label, or the node's display name. */",
    '  label: string;',
    "  /** The node's graph id. */",
    '  nodeId: string;',
    "  /** The component it sits in — '/Pages/Home'. */",
    '  componentName: string;',
    '}',
    '',
    "/** A setter's number coercion: `Number(value) > 0 ? Number(value) : 0`. */",
    'function positiveOrZero(value: unknown): number {',
    '  return Number(value) > 0 ? Number(value) : 0;',
    '}',
    '',
    '/** `Max Size` / `Max Messages`: `Number(value) >= 0 ? Number(value) : 0`. */',
    'function nonNegativeOrZero(value: unknown): number {',
    '  return Number(value) >= 0 ? Number(value) : 0;',
    '}',
    '',
    '/** EXP-011 §66.5: node.ts sendValue drops an undefined before it crosses a wire (`if (value === undefined) return;`), so a setter never sees one — an option passed as undefined (a Variable nothing has written) is NOT a delivery: the internal keeps what it holds. */',
    'function has(options: object, key: string): boolean {',
    '  return Object.prototype.hasOwnProperty.call(options, key) && (options as Record<string, unknown>)[key] !== undefined;',
    '}',
    '',
    '// ============================================================================',
    '// JSON Stream Parser — json-stream-parser.ts',
    '// ============================================================================',
    '',
    "export type JsonStreamFormat = 'ndjson' | 'stream' | 'single';",
    '',
    'export interface ParserState {',
    '  pendingChunk: string;',
    '  buffer: string;',
    '  format: JsonStreamFormat;',
    '  maxLength: number;',
    '  parsed: unknown;',
    '  values: unknown[];',
    '  totalValues: number;',
    '  error: string;',
    '  errorCount: number;',
    '  isComplete: boolean;',
    '}',
    '',
    'export interface JsonStreamParserOptions {',
    "  /** 'ndjson' (one per line) | 'stream' (any complete values) | 'single' (one document). Unset: ndjson. */",
    '  format?: unknown;',
    '  /** Cap on unparsed text held while a value completes; 0 disables. Unset: 1048576. */',
    '  maxLength?: unknown;',
    '}',
    '',
    "const PARSE_ERROR_CODE = 'json-stream-parser/parse-failed';",
    '',
    '/** initialize(). */',
    'export function createParserState(): ParserState {',
    '  return {',
    "    pendingChunk: '',",
    "    buffer: '',",
    "    format: 'ndjson',",
    '    maxLength: 1024 * 1024,',
    '    parsed: undefined,',
    '    values: [],',
    '    totalValues: 0,',
    "    error: '',",
    '    errorCount: 0,',
    '    isComplete: false',
    '  };',
    '}',
    '',
    '/** The config setters, for the keys present. */',
    'export function applyParserOptions(state: ParserState, options: JsonStreamParserOptions): void {',
    "  if (has(options, 'format')) state.format = (options.format as JsonStreamFormat) || 'ndjson';",
    "  if (has(options, 'maxLength')) state.maxLength = positiveOrZero(options.maxLength);",
    '}',
    '',
    '/** The Chunk setter: undefined / null clear it, anything else is String(value). */',
    'export function parserSetChunk(state: ParserState, value: unknown): void {',
    "  state.pendingChunk = value === undefined || value === null ? '' : String(value);",
    '}',
    '',
    'function parserReportError(state: ParserState, message: string): void {',
    '  state.error = message;',
    '  state.errorCount++;',
    '}',
    '',
    '/** Parse: appends the pending chunk and emits every value that is now complete. */',
    'export function parserParse(state: ParserState): StreamEvent[] {',
    '  const events: StreamEvent[] = [];',
    '  const chunk = state.pendingChunk;',
    "  if (chunk !== '') state.buffer += chunk;",
    "  if (state.buffer === '') {",
    "    reportOutcome(events, 'unchanged');",
    '    return events;',
    '  }',
    '',
    '  if (state.maxLength > 0 && state.buffer.length > state.maxLength) {',
    '    // Dropping the buffer loudly beats accumulating a runaway one silently. Is Complete is not touched here.',
    "    state.buffer = '';",
    "    parserReportError(state, 'Gave up on ' + state.maxLength + '+ characters of unparsed text; check the Format setting');",
    "    reportOutcome(events, 'failure', { code: PARSE_ERROR_CODE, message: state.error });",
    '    return events;',
    '  }',
    '',
    '  const values: unknown[] = [];',
    '  const errors: string[] = [];',
    '',
    "  if (state.format === 'ndjson') {",
    "    const split = splitDelimited(state.buffer, '\\n');",
    '    state.buffer = split.rest;',
    '    for (const line of split.messages) {',
    '      const trimmed = line.trim();',
    "      if (trimmed === '') continue;",
    '      const outcome = tryParseJson(trimmed);',
    '      if (outcome.ok) values.push(outcome.value);',
    "      else errors.push('Line did not parse as JSON: ' + outcome.error);",
    '    }',
    "  } else if (state.format === 'single') {",
    '    const scan = scanJsonValues(state.buffer, { arrayFraming: false });',
    '    if (scan.values.length > 0) {',
    '      values.push(scan.values[0]);',
    '      state.buffer = scan.rest;',
    '    }',
    '    for (const e of scan.errors) errors.push(e);',
    '  } else {',
    '    const scan = scanJsonValues(state.buffer, { arrayFraming: true });',
    '    state.buffer = scan.rest;',
    '    for (const v of scan.values) values.push(v);',
    '    for (const e of scan.errors) errors.push(e);',
    '  }',
    '',
    '  state.isComplete = state.buffer.length === 0;',
    '',
    '  if (values.length > 0) {',
    '    state.values = values;',
    '    state.parsed = values[values.length - 1];',
    '    state.totalValues += values.length;',
    '  }',
    '',
    '  const errorsBefore = state.errorCount;',
    '  for (const message of errors) parserReportError(state, message);',
    '',
    '  // Success reports "this Parse yielded values": a chunk that merely advanced an incomplete value stays quiet.',
    "  if (values.length > 0) events.push({ kind: 'signal', name: 'success' });",
    '',
    "  if (state.errorCount > errorsBefore) reportOutcome(events, 'failure', { code: PARSE_ERROR_CODE, message: state.error });",
    "  else reportOutcome(events, 'done');",
    '  return events;',
    '}',
    '',
    '/** Clear: discards the pending text, the parsed values and the error counter. */',
    'export function parserClear(state: ParserState): StreamEvent[] {',
    '  const events: StreamEvent[] = [];',
    "  const hadSomething = state.buffer !== '' || state.values.length > 0 || state.errorCount > 0 || state.totalValues > 0;",
    "  state.buffer = '';",
    '  state.values = [];',
    '  state.parsed = undefined;',
    "  state.error = '';",
    '  state.errorCount = 0;',
    '  state.totalValues = 0;',
    '  state.isComplete = false;',
    "  events.push({ kind: 'signal', name: 'cleared' });",
    "  reportOutcome(events, hadSomething ? 'done' : 'unchanged');",
    '  return events;',
    '}',
    '',
    '// ============================================================================',
    '// Stream Buffer — stream-buffer.ts',
    '// ============================================================================',
    '',
    'export interface BufferState {',
    '  pendingData: unknown;',
    '  hasPendingData: boolean;',
    '  buffer: unknown[];',
    '  flushedData: unknown[];',
    '  flushCount: number;',
    '  droppedItems: number;',
    '  flushSize: number;',
    '  flushInterval: number;',
    '  maxSize: number;',
    '  /** Why the last Add was refused; undefined until one is. */',
    '  lastError: string | undefined;',
    '}',
    '',
    'export interface StreamBufferOptions {',
    '  /** Flush once this many items are buffered; 0 disables. Unset: 0. */',
    '  flushSize?: unknown;',
    '  /** Flush this often (ms) while items are buffered; 0 disables. Unset: 0. */',
    '  flushInterval?: unknown;',
    '  /** Hard cap on buffered items, oldest dropped; 0 means no cap. Unset: 10000. */',
    '  maxSize?: unknown;',
    '}',
    '',
    "const NO_DATA_CODE = 'stream-buffer/no-data';",
    '',
    '/** initialize(). */',
    'export function createBufferState(): BufferState {',
    '  return {',
    '    pendingData: undefined,',
    '    hasPendingData: false,',
    '    buffer: [],',
    '    flushedData: [],',
    '    flushCount: 0,',
    '    droppedItems: 0,',
    '    flushSize: 0,',
    '    flushInterval: 0,',
    '    maxSize: 10000,',
    '    lastError: undefined',
    '  };',
    '}',
    '',
    '/** The config setters, for the keys present; a changed interval re-arms (stop, then arm iff something is buffered). */',
    'export function applyBufferOptions(state: BufferState, options: StreamBufferOptions): StreamEvent[] {',
    '  const events: StreamEvent[] = [];',
    "  if (has(options, 'flushSize')) state.flushSize = positiveOrZero(options.flushSize);",
    "  if (has(options, 'flushInterval')) {",
    '    const next = positiveOrZero(options.flushInterval);',
    '    if (next !== state.flushInterval) {',
    '      state.flushInterval = next;',
    "      events.push({ kind: 'stop-timer' });",
    "      if (state.buffer.length > 0) events.push({ kind: 'arm-timer' });",
    '    }',
    '  }',
    "  if (has(options, 'maxSize')) state.maxSize = nonNegativeOrZero(options.maxSize);",
    '  return events;',
    '}',
    '',
    '/** The Data setter: the value is retained, and its arrival is remembered for good. */',
    'export function bufferSetData(state: BufferState, value: unknown): void {',
    '  state.pendingData = value;',
    '  state.hasPendingData = true;',
    '}',
    '',
    '/** Add: buffers the current Data, flushing straight away if that reaches Flush Size. */',
    'export function bufferAdd(state: BufferState): StreamEvent[] {',
    '  const events: StreamEvent[] = [];',
    '  if (!state.hasPendingData) {',
    "    const message = 'Nothing to add — no value has arrived on the Data input';",
    '    state.lastError = message;',
    "    reportOutcome(events, 'failure', { code: NO_DATA_CODE, message });",
    '    return events;',
    '  }',
    '',
    '  state.buffer.push(state.pendingData);',
    '',
    '  if (state.maxSize > 0 && state.buffer.length > state.maxSize) {',
    '    const dropped = state.buffer.length - state.maxSize;',
    '    state.buffer.splice(0, dropped);',
    '    state.droppedItems += dropped;',
    "    events.push({ kind: 'signal', name: 'overflowed' });",
    '  }',
    '',
    '  if (state.flushSize > 0 && state.buffer.length >= state.flushSize) {',
    '    // One invocation: the Add that filled the buffer owns the flush it triggered.',
    '    for (const e of bufferFlush(state, true)) events.push(e);',
    '    return events;',
    '  }',
    "  events.push({ kind: 'arm-timer' });",
    "  reportOutcome(events, 'done');",
    '  return events;',
    '}',
    '',
    "/** Flush. `owned` is whether a pulse owns this invocation; the interval timer's own flush owns none, so it reports no outcome. */",
    'export function bufferFlush(state: BufferState, owned: boolean): StreamEvent[] {',
    '  const events: StreamEvent[] = [];',
    "  events.push({ kind: 'stop-timer' });",
    '  if (state.buffer.length === 0) {',
    '    // A timed flush with nothing to send is exactly what an idle buffer should do.',
    "    if (owned) reportOutcome(events, 'unchanged');",
    '    return events;',
    '  }',
    '',
    '  // A fresh array: handing out the live buffer would let a downstream node see it mutate under it on the next Add.',
    '  state.flushedData = state.buffer;',
    '  state.buffer = [];',
    '  state.flushCount++;',
    '',
    "  events.push({ kind: 'signal', name: 'flushed' });",
    "  if (owned) reportOutcome(events, 'done');",
    '  return events;',
    '}',
    '',
    '/** Clear: discards the buffer and resets both counters without flushing. */',
    'export function bufferClear(state: BufferState): StreamEvent[] {',
    '  const events: StreamEvent[] = [];',
    "  events.push({ kind: 'stop-timer' });",
    '  // Read before the reset, not after.',
    '  const hadSomethingToClear =',
    '    state.buffer.length > 0 || state.flushedData.length > 0 || state.droppedItems > 0 || state.flushCount > 0;',
    '  state.buffer = [];',
    '  state.flushedData = [];',
    '  state.droppedItems = 0;',
    '  state.flushCount = 0;',
    '',
    "  events.push({ kind: 'signal', name: 'cleared' });",
    "  reportOutcome(events, hadSomethingToClear ? 'done' : 'unchanged');",
    '  return events;',
    '}',
    '',
    '// ============================================================================',
    '// Text Accumulator — text-accumulator.ts',
    '// ============================================================================',
    '',
    'export interface AccumulatorState {',
    '  pendingChunk: string;',
    '  buffer: string;',
    '  messages: string[];',
    '  lastMessage: string;',
    '  delimiter: string;',
    '  maxLength: number;',
    '  maxMessages: number;',
    '  droppedCharacters: number;',
    '  droppedMessages: number;',
    '  error: string;',
    '}',
    '',
    'export interface TextAccumulatorOptions {',
    "  /** Message boundary; empty accumulates everything. Unset: '\\n'. */",
    '  delimiter?: unknown;',
    '  /** Cap on the pending buffer in characters, oldest dropped. Unset: 1048576. */',
    '  maxLength?: unknown;',
    '  /** Cap on retained complete messages, oldest dropped; 0 keeps them all. Unset: 1000. */',
    '  maxMessages?: unknown;',
    '}',
    '',
    "const CHUNK_ERROR_CODE = 'text-accumulator/chunk-not-text';",
    '',
    '/** Names what arrived, in the words of the port that should have been wired instead. */',
    'export function describeBadChunk(value: unknown): string {',
    '  const shape = Array.isArray(value)',
    "    ? 'an array'",
    '    : value instanceof Date',
    "      ? 'a Date'",
    "      : typeof value === 'object'",
    "        ? 'an object'",
    "        : 'a ' + typeof value;",
    '  return (',
    "    'Chunk must be text, but ' + shape + ' arrived, so nothing was appended. ' +",
    "    \"A stream's Data output is JSON-parsed and is an object for a payload like \" +",
    "    '{\"delta\":\"Hi\"} — wire the stream\\'s Text output instead (set its Text Path for a JSON ' +",
    "    'payload), or a Function node that picks the string field out of Data.'",
    '  );',
    '}',
    '',
    '/** initialize(). */',
    'export function createAccumulatorState(): AccumulatorState {',
    '  return {',
    "    pendingChunk: '',",
    "    buffer: '',",
    '    messages: [],',
    "    lastMessage: '',",
    "    delimiter: '\\n',",
    '    maxLength: 1024 * 1024,',
    '    maxMessages: 1000,',
    '    droppedCharacters: 0,',
    '    droppedMessages: 0,',
    "    error: ''",
    '  };',
    '}',
    '',
    '/** The config setters, for the keys present. */',
    'export function applyAccumulatorOptions(state: AccumulatorState, options: TextAccumulatorOptions): void {',
    "  if (has(options, 'delimiter')) {",
    "    state.delimiter = options.delimiter === undefined || options.delimiter === null ? '' : String(options.delimiter);",
    '  }',
    "  if (has(options, 'maxLength')) state.maxLength = positiveOrZero(options.maxLength);",
    "  if (has(options, 'maxMessages')) state.maxMessages = nonNegativeOrZero(options.maxMessages);",
    '}',
    '',
    '/** reportChunkError with no token: the message once per distinct mis-wiring, the Failure pulse, then the raise. */',
    'function accumulatorReportChunkError(state: AccumulatorState, message: string, events: StreamEvent[]): void {',
    '  const isRepeat = state.error === message;',
    '  if (!isRepeat) state.error = message;',
    '  if (isRepeat) return;',
    "  events.push({ kind: 'signal', name: 'failure' });",
    "  events.push({ kind: 'raise', code: CHUNK_ERROR_CODE, message });",
    '}',
    '',
    '/** The Chunk setter: text and the primitives that read as text are accepted; anything else is refused and named. */',
    'export function accumulatorSetChunk(state: AccumulatorState, value: unknown): StreamEvent[] {',
    '  const events: StreamEvent[] = [];',
    '  const kind = typeof value;',
    '',
    '  if (value === undefined || value === null) {',
    "    state.pendingChunk = '';",
    "  } else if (kind === 'string') {",
    '    state.pendingChunk = value as string;',
    "  } else if (kind === 'number' || kind === 'boolean' || kind === 'bigint') {",
    '    state.pendingChunk = String(value);',
    '  } else {',
    "    state.pendingChunk = '';",
    '    accumulatorReportChunkError(state, describeBadChunk(value), events);',
    '    return events;',
    '  }',
    '',
    "  state.error = '';",
    '  return events;',
    '}',
    '',
    '/** Add: appends the current Chunk, which is retained between pulses. */',
    'export function accumulatorAdd(state: AccumulatorState): StreamEvent[] {',
    '  const events: StreamEvent[] = [];',
    '  const chunk = state.pendingChunk;',
    "  if (chunk === '') {",
    "    // An empty chunk is a no-op, not an error: a stream's keep-alive frames are empty. Also the path after a refused chunk.",
    "    reportOutcome(events, 'unchanged');",
    '    return events;',
    '  }',
    '',
    '  state.buffer += chunk;',
    '',
    '  const capped = truncateHead(state.buffer, state.maxLength);',
    '  state.buffer = capped.text;',
    '  if (capped.dropped > 0) {',
    '    state.droppedCharacters += capped.dropped;',
    "    events.push({ kind: 'signal', name: 'overflowed' });",
    '  }',
    '',
    '  const split = splitDelimited(state.buffer, state.delimiter);',
    '  state.buffer = split.rest;',
    '',
    '  if (split.messages.length > 0) {',
    '    state.messages = state.messages.concat(split.messages);',
    '    state.lastMessage = split.messages[split.messages.length - 1];',
    '',
    '    const max = state.maxMessages;',
    '    if (max > 0 && state.messages.length > max) {',
    '      const dropped = state.messages.length - max;',
    '      state.messages = state.messages.slice(dropped);',
    '      state.droppedMessages += dropped;',
    "      events.push({ kind: 'signal', name: 'overflowed' });",
    '    }',
    '  }',
    '',
    '  // Message Received fires once per Add that completed at least one message, not once per message.',
    "  if (split.messages.length > 0) events.push({ kind: 'signal', name: 'messageReceived' });",
    "  events.push({ kind: 'signal', name: 'changed' });",
    '',
    "  reportOutcome(events, 'done');",
    '  return events;',
    '}',
    '',
    '/** Clear: empties the buffer, the messages and both dropped counts. */',
    'export function accumulatorClear(state: AccumulatorState): StreamEvent[] {',
    '  const events: StreamEvent[] = [];',
    '  // Read before the reset, not after.',
    '  const hadSomethingToClear =',
    '    state.buffer.length > 0 ||',
    '    state.messages.length > 0 ||',
    '    state.droppedCharacters > 0 ||',
    '    state.droppedMessages > 0 ||',
    '    !!state.error;',
    "  state.buffer = '';",
    '  state.messages = [];',
    "  state.lastMessage = '';",
    '  state.droppedCharacters = 0;',
    '  state.droppedMessages = 0;',
    "  state.error = '';",
    '',
    "  events.push({ kind: 'signal', name: 'cleared' });",
    "  reportOutcome(events, hadSomethingToClear ? 'done' : 'unchanged');",
    '  return events;',
    '}',
    '',
    '// ============================================================================',
    '// The hooks',
    '// ============================================================================',
    '',
    'type Listeners = Partial<Record<string, () => void>>;',
    '',
    'interface Host {',
    '  dead: boolean;',
    '  timer: ReturnType<typeof setTimeout> | null;',
    '}',
    '',
    "/** Delivers one invocation's events in order: a signal to its listener, a raise to the channel, the timer instructions to the host. */",
    'function deliver(',
    '  events: StreamEvent[],',
    '  host: Host,',
    '  on: { current: Listeners },',
    '  source: StreamSource,',
    '  nodeType: string,',
    '  armTimer: () => void',
    '): void {',
    '  for (const event of events) {',
    "    if (event.kind === 'signal') on.current[event.name]?.();",
    "    else if (event.kind === 'raise') {",
    '      raiseAppError({ code: event.code, message: event.message, nodeId: source.nodeId, nodeType, componentName: source.componentName });',
    "    } else if (event.kind === 'arm-timer') armTimer();",
    '    else if (host.timer !== null) {',
    '      clearTimeout(host.timer);',
    '      host.timer = null;',
    '    }',
    '  }',
    '}',
    '',
    'export interface JsonStreamParserListeners {',
    '  success?: () => void;',
    '  cleared?: () => void;',
    '  done?: () => void;',
    '  unchanged?: () => void;',
    '  failure?: () => void;',
    '  completed?: () => void;',
    '}',
    '',
    'export interface JsonStreamParserHandle {',
    '  /** Parse — with the Chunk the pulse carries, or with nothing when the port was never fed. */',
    '  parse(chunk?: unknown): void;',
    '  clear(): void;',
    '  readonly parsed: unknown;',
    '  readonly values: unknown[];',
    '  readonly valueCount: number;',
    '  readonly pendingCharacters: number;',
    '  readonly isComplete: boolean;',
    '  readonly error: string;',
    '  readonly errorCount: number;',
    '}',
    '',
    'export function useJsonStreamParser(',
    '  source: StreamSource,',
    '  options: JsonStreamParserOptions = {},',
    '  on: JsonStreamParserListeners = {}',
    '): JsonStreamParserHandle {',
    '  const [, publish] = useReducer((n: number) => n + 1, 0);',
    '  const onRef = useRef<Listeners>(on as Listeners);',
    '  onRef.current = on as Listeners;',
    '  const optionsRef = useRef(options);',
    '  optionsRef.current = options;',
    '  const inst = useRef<{ state: ParserState; host: Host } | null>(null);',
    '  const handle = useRef<JsonStreamParserHandle | null>(null);',
    '  if (inst.current === null || handle.current === null) {',
    '    const self = { state: createParserState(), host: { dead: false, timer: null } as Host };',
    '    inst.current = self;',
    '    const run = (events: StreamEvent[]) => {',
    "      deliver(events, self.host, onRef, source, 'net.noodl.JSONStreamParser', () => {});",
    '      if (!self.host.dead) publish();',
    '    };',
    '    handle.current = {',
    '      parse(...args: [unknown?]) {',
    '        applyParserOptions(self.state, optionsRef.current);',
    '        if (args.length > 0) parserSetChunk(self.state, args[0]);',
    '        run(parserParse(self.state));',
    '      },',
    '      clear() {',
    '        applyParserOptions(self.state, optionsRef.current);',
    '        run(parserClear(self.state));',
    '      },',
    '      get parsed() {',
    '        return self.state.parsed;',
    '      },',
    '      get values() {',
    '        return self.state.values;',
    '      },',
    '      get valueCount() {',
    '        return self.state.totalValues;',
    '      },',
    '      get pendingCharacters() {',
    '        return self.state.buffer.length;',
    '      },',
    '      get isComplete() {',
    '        return self.state.isComplete;',
    '      },',
    '      get error() {',
    '        return self.state.error;',
    '      },',
    '      get errorCount() {',
    '        return self.state.errorCount;',
    '      }',
    '    };',
    '  }',
    '  // The config setters run as the values arrive — after every render.',
    '  useEffect(() => {',
    '    applyParserOptions(inst.current!.state, optionsRef.current);',
    '  });',
    '  useEffect(() => {',
    '    const host = inst.current!.host;',
    '    host.dead = false;',
    '    return () => {',
    '      host.dead = true;',
    '    };',
    '  }, []);',
    '  return handle.current;',
    '}',
    '',
    'export interface StreamBufferListeners {',
    '  flushed?: () => void;',
    '  overflowed?: () => void;',
    '  cleared?: () => void;',
    '  done?: () => void;',
    '  unchanged?: () => void;',
    '  failure?: () => void;',
    '  completed?: () => void;',
    '}',
    '',
    'export interface StreamBufferHandle {',
    '  /** Add — with the Data the pulse carries, or with nothing when the port was never fed (a Failure, as the runtime reports it). */',
    '  add(data?: unknown): void;',
    '  flush(): void;',
    '  clear(): void;',
    '  readonly buffer: unknown[];',
    '  readonly bufferSize: number;',
    '  readonly flushedData: unknown[];',
    '  readonly flushCount: number;',
    '  readonly droppedItems: number;',
    '  readonly error: string | undefined;',
    '}',
    '',
    'export function useStreamBuffer(',
    '  source: StreamSource,',
    '  options: StreamBufferOptions = {},',
    '  on: StreamBufferListeners = {}',
    '): StreamBufferHandle {',
    '  const [, publish] = useReducer((n: number) => n + 1, 0);',
    '  const onRef = useRef<Listeners>(on as Listeners);',
    '  onRef.current = on as Listeners;',
    '  const optionsRef = useRef(options);',
    '  optionsRef.current = options;',
    '  const inst = useRef<{ state: BufferState; host: Host; sync: () => void } | null>(null);',
    '  const handle = useRef<StreamBufferHandle | null>(null);',
    '  if (inst.current === null || handle.current === null) {',
    '    const state = createBufferState();',
    '    const host: Host = { dead: false, timer: null };',
    "    // armTimer: only with an interval, only when no timer is running; the timer's flush owns no token.",
    '    const armTimer = () => {',
    '      if (state.flushInterval <= 0) return;',
    '      if (host.timer !== null) return;',
    '      host.timer = setTimeout(() => {',
    '        host.timer = null;',
    '        run(bufferFlush(state, false));',
    '      }, state.flushInterval);',
    '    };',
    '    const run = (events: StreamEvent[]) => {',
    "      deliver(events, host, onRef, source, 'net.noodl.StreamBuffer', armTimer);",
    '      if (!host.dead) publish();',
    '    };',
    '    const sync = () => {',
    '      const events = applyBufferOptions(state, optionsRef.current);',
    "      if (events.length > 0) deliver(events, host, onRef, source, 'net.noodl.StreamBuffer', armTimer);",
    '    };',
    '    inst.current = { state, host, sync };',
    '    handle.current = {',
    '      add(...args: [unknown?]) {',
    '        sync();',
    '        if (args.length > 0) bufferSetData(state, args[0]);',
    '        run(bufferAdd(state));',
    '      },',
    '      flush() {',
    '        sync();',
    '        run(bufferFlush(state, true));',
    '      },',
    '      clear() {',
    '        sync();',
    '        run(bufferClear(state));',
    '      },',
    '      get buffer() {',
    '        return state.buffer;',
    '      },',
    '      get bufferSize() {',
    '        return state.buffer.length;',
    '      },',
    '      get flushedData() {',
    '        return state.flushedData;',
    '      },',
    '      get flushCount() {',
    '        return state.flushCount;',
    '      },',
    '      get droppedItems() {',
    '        return state.droppedItems;',
    '      },',
    '      get error() {',
    '        return state.lastError;',
    '      }',
    '    };',
    '  }',
    '  // The config setters run as the values arrive — after every render; a changed interval re-arms here.',
    '  useEffect(() => {',
    '    inst.current!.sync();',
    '  });',
    '  // Unmount: _onNodeDeleted — the timer stopped, the buffer and the last batch dropped.',
    '  useEffect(() => {',
    '    const self = inst.current!;',
    '    self.host.dead = false;',
    '    return () => {',
    '      self.host.dead = true;',
    '      if (self.host.timer !== null) {',
    '        clearTimeout(self.host.timer);',
    '        self.host.timer = null;',
    '      }',
    '      self.state.buffer = [];',
    '      self.state.flushedData = [];',
    '    };',
    '  }, []);',
    '  return handle.current;',
    '}',
    '',
    'export interface TextAccumulatorListeners {',
    '  messageReceived?: () => void;',
    '  changed?: () => void;',
    '  cleared?: () => void;',
    '  overflowed?: () => void;',
    '  done?: () => void;',
    '  unchanged?: () => void;',
    '  failure?: () => void;',
    '  completed?: () => void;',
    '}',
    '',
    'export interface TextAccumulatorHandle {',
    '  /** Add — with the Chunk the pulse carries (the setter refuses a non-text one, by name), or with nothing when the port was never fed. */',
    '  add(chunk?: unknown): void;',
    '  clear(): void;',
    '  readonly accumulated: string;',
    '  readonly messages: string[];',
    '  readonly lastMessage: string;',
    '  readonly messageCount: number;',
    '  readonly characterCount: number;',
    '  readonly byteCount: number;',
    '  readonly droppedCharacters: number;',
    '  readonly droppedMessages: number;',
    '  readonly error: string;',
    '}',
    '',
    'export function useTextAccumulator(',
    '  source: StreamSource,',
    '  options: TextAccumulatorOptions = {},',
    '  on: TextAccumulatorListeners = {}',
    '): TextAccumulatorHandle {',
    '  const [, publish] = useReducer((n: number) => n + 1, 0);',
    '  const onRef = useRef<Listeners>(on as Listeners);',
    '  onRef.current = on as Listeners;',
    '  const optionsRef = useRef(options);',
    '  optionsRef.current = options;',
    '  const inst = useRef<{ state: AccumulatorState; host: Host } | null>(null);',
    '  const handle = useRef<TextAccumulatorHandle | null>(null);',
    '  if (inst.current === null || handle.current === null) {',
    '    const self = { state: createAccumulatorState(), host: { dead: false, timer: null } as Host };',
    '    inst.current = self;',
    '    const run = (events: StreamEvent[]) => {',
    "      deliver(events, self.host, onRef, source, 'net.noodl.TextAccumulator', () => {});",
    '      if (!self.host.dead) publish();',
    '    };',
    '    handle.current = {',
    '      add(...args: [unknown?]) {',
    '        applyAccumulatorOptions(self.state, optionsRef.current);',
    "        // The setter's own announcement (a refused chunk) goes out before the Add's outcome, as delivery precedes the pulse.",
    '        const events = args.length > 0 ? accumulatorSetChunk(self.state, args[0]) : [];',
    '        for (const e of accumulatorAdd(self.state)) events.push(e);',
    '        run(events);',
    '      },',
    '      clear() {',
    '        applyAccumulatorOptions(self.state, optionsRef.current);',
    '        run(accumulatorClear(self.state));',
    '      },',
    '      get accumulated() {',
    '        return self.state.buffer;',
    '      },',
    '      get messages() {',
    '        return self.state.messages;',
    '      },',
    '      get lastMessage() {',
    '        return self.state.lastMessage;',
    '      },',
    '      get messageCount() {',
    '        return self.state.messages.length;',
    '      },',
    '      get characterCount() {',
    '        return self.state.buffer.length;',
    '      },',
    '      get byteCount() {',
    '        return utf8ByteLength(self.state.buffer);',
    '      },',
    '      get droppedCharacters() {',
    '        return self.state.droppedCharacters;',
    '      },',
    '      get droppedMessages() {',
    '        return self.state.droppedMessages;',
    '      },',
    '      get error() {',
    '        return self.state.error;',
    '      }',
    '    };',
    '  }',
    '  useEffect(() => {',
    '    applyAccumulatorOptions(inst.current!.state, optionsRef.current);',
    '  });',
    '  useEffect(() => {',
    '    const host = inst.current!.host;',
    '    host.dead = false;',
    '    return () => {',
    '      host.dead = true;',
    '    };',
    '  }, []);',
    '  return handle.current;',
    '}'
  ].join('\n');
}
