/**
 * EXP-011 §65 — `WebSocket` (`net.noodl.WebSocket`), Tier 3.11's second transport: `src/lib/websocket.ts`, the node's
 * connection machine transcribed from `noodl-runtime/src/nodes/std-library/agent/websocket.ts` and
 * `websocket-connection.ts`. One hook, `useWebSocket(source, options, listeners)`: the three Actions are verbs on the
 * handle (`send` carries the Message, read at the pulse), the six Events and the outcome trio are listeners, every Status
 * and Data output a live getter — the streaming table's shape (§58, §64). The module imports `./errors` (a Failure
 * outcome raises under the node's own codes: websocket/connect-failed, the four Send refusals), and nothing from
 * `./streaming` — its source type is its own, so a socket alone does not ship the trio's module.
 *
 * Kept as a quoted line array like the other libs: the specs pin lines of it, and mutation arms anchor on them.
 * Generated from a plain source (websocket-lib-source.ts + gen-wslib.py, session 89's scratchpad) — regenerate, never
 * hand-edit the array.
 */

/** Where the module lands in the exported app. */
export const WEBSOCKET_LIB_PATH = 'src/lib/websocket.ts';

export function websocketLibSource(): string {
  return [
    '//',
    '// WebSocket, transcribed from the interpreter it has to agree with:',
    '// noodl-runtime/src/nodes/std-library/agent/websocket.ts (the node: the ports, the input-change policy, the outcome',
    '// tokens) and websocket-connection.ts (the connection: reconnection and backoff, the heartbeat, the send queue, teardown).',
    '//',
    '// useWebSocket(source, options, listeners): one connection per mount — `connect()` / `disconnect()` / `send(message)` are',
    '// the three Actions, the six Events and the outcome trio are the listeners, every Status and Data output is a live getter',
    '// on the handle. The options are the node\'s inputs, read live: URL, Protocols and Auto Connect schedule the runtime\'s',
    '// rebuild (a changed identity drops the connection and reopens it where the app still wants one); the tuning inputs are',
    '// pushed onto the live connection in place through applyConfig / configure, as the runtime\'s setters push them.',
    '//',
    '',
    'import { useEffect, useReducer, useRef } from \'react\';',
    '',
    'import { raiseAppError } from \'./errors\';',
    '',
    '// ============================================================================',
    '// websocket-connection.ts — the connection state machine, verbatim',
    '// ============================================================================',
    '',
    '/** Connection state, as the node publishes it on the `connectionState` output. */',
    'export type WebSocketConnectionState = \'idle\' | \'connecting\' | \'open\' | \'reconnecting\' | \'closed\' | \'error\';',
    '',
    '/** What happens to a `send` that arrives while the socket is not open. */',
    'export type SendWhenDisconnected = \'queue\' | \'drop\' | \'error\';',
    '',
    '/** How the outgoing payload is turned into a frame. */',
    'export type MessageEncoding = \'auto\' | \'text\' | \'binary\';',
    '',
    '/** The `close` event, as much of it as this class reads. */',
    'export interface WebSocketCloseEventLike {',
    '  code?: number;',
    '  reason?: string;',
    '  wasClean?: boolean;',
    '}',
    '',
    '/** The `message` event, as much of it as this class reads. */',
    'export interface WebSocketMessageEventLike {',
    '  data: unknown;',
    '}',
    '',
    '/** The structural shape of a WebSocket, declared here rather than taken from the DOM lib. */',
    'export interface WebSocketLike {',
    '  binaryType?: string;',
    '  readyState?: number;',
    '  bufferedAmount?: number;',
    '  onopen: ((event?: unknown) => void) | null;',
    '  onmessage: ((event: WebSocketMessageEventLike) => void) | null;',
    '  onerror: ((event?: unknown) => void) | null;',
    '  onclose: ((event?: WebSocketCloseEventLike) => void) | null;',
    '  send(data: unknown): void;',
    '  close(code?: number, reason?: string): void;',
    '}',
    '',
    'export type WebSocketConstructorLike = new (url: string, protocols?: string | string[]) => WebSocketLike;',
    '',
    '/** What one `send()` did with its value — the four states, named (the node turns them into Done / Unchanged / Failure). */',
    'export type WebSocketSendResult =',
    '  /** Handed to the socket. */',
    '  | { kind: \'sent\' }',
    '  /** Held in order until the socket reopens. Still owed, so still a `Done` to the graph. */',
    '  | { kind: \'queued\' }',
    '  /** Discarded by the `drop` policy, and counted. The author asked for this. */',
    '  | { kind: \'dropped\' }',
    '  /** Refused. `code` is the code the node reports it under. */',
    '  | { kind: \'failed\'; code: string; message: string };',
    '',
    '/** Codes for {@link WebSocketSendResult}, so the node and this class cannot spell them apart. */',
    'export const WS_ERROR_NOTHING_TO_SEND = \'websocket/nothing-to-send\';',
    'export const WS_ERROR_NOT_CONNECTED = \'websocket/not-connected\';',
    'export const WS_ERROR_QUEUE_FULL = \'websocket/queue-full\';',
    'export const WS_ERROR_ENCODE_FAILED = \'websocket/encode-failed\';',
    'export const WS_ERROR_SEND_FAILED = \'websocket/send-failed\';',
    '',
    '/** Tuning knobs. Every one of them maps to an input port on the node. */',
    'export interface WebSocketConnectionConfig {',
    '  url?: string;',
    '  protocols?: string[];',
    '  autoReconnect?: boolean;',
    '  reconnectDelay?: number;',
    '  maxReconnectDelay?: number;',
    '  /** Attempts allowed per outage. Negative means unlimited; `0` means none. */',
    '  maxRetries?: number;',
    '  jitter?: boolean;',
    '  /** `0` (the default) disables the heartbeat entirely. */',
    '  heartbeatInterval?: number;',
    '  heartbeatMessage?: string;',
    '  /** Empty disables both latency measurement and dead-connection detection. */',
    '  heartbeatReply?: string;',
    '  sendWhenDisconnected?: SendWhenDisconnected;',
    '  /** `0` or negative means unlimited, which is not recommended. */',
    '  maxQueueSize?: number;',
    '  messageEncoding?: MessageEncoding;',
    '}',
    '',
    '/** What the connection tells its owner about. */',
    'export interface WebSocketConnectionCallbacks {',
    '  /** Any observable status field changed. Coarse on purpose: the node re-renders every status output. */',
    '  onStatus?(): void;',
    '  /** The socket opened. `isReconnect` is false only for the very first open. */',
    '  onOpen?(isReconnect: boolean): void;',
    '  onMessage?(value: unknown, raw: string, isBinary: boolean): void;',
    '  /** Something went wrong. `lastError` already carries the same text. */',
    '  onError?(message: string): void;',
    '  onClose?(code: number, reason: string, willReconnect: boolean): void;',
    '  /** A message was handed to the socket. Not fired for heartbeats. */',
    '  onSent?(value: unknown): void;',
    '}',
    '',
    '/** The seams the runtime keeps for its own tests — the browser\'s globals when absent. */',
    'export interface WebSocketConnectionSeams {',
    '  /** Explicit key wins even when null, so a host can say "there is no WebSocket here" despite a global one existing. */',
    '  WebSocketImpl?: WebSocketConstructorLike | null;',
    '  setTimeoutImpl?(handler: () => void, timeout: number): unknown;',
    '  clearTimeoutImpl?(handle: unknown): void;',
    '  nowImpl?(): number;',
    '  randomImpl?(): number;',
    '}',
    '',
    'export type WebSocketConnectionOptions = WebSocketConnectionConfig & WebSocketConnectionCallbacks & WebSocketConnectionSeams;',
    '',
    'export const DEFAULT_RECONNECT_DELAY = 1000;',
    'export const DEFAULT_MAX_RECONNECT_DELAY = 30000;',
    'export const DEFAULT_MAX_RETRIES = 10;',
    'export const DEFAULT_MAX_QUEUE_SIZE = 100;',
    '',
    '/** Code reported when the socket died without a close frame (or errored). */',
    'const CLOSE_CODE_ABNORMAL = 1006;',
    '',
    '/**',
    ' * Close codes where reconnecting cannot possibly help: the client and server disagree about the protocol, the payload',
    ' * or the policy, so the next attempt fails identically. Not in the list: 1000/1001 (see the graceful-goodbye branch),',
    ' * 1006 (the ordinary network drop), 1011/1012/1013 (server-side trouble) and the 4000–4999 application range.',
    ' */',
    'const FATAL_CLOSE_CODES = [1002, 1003, 1007, 1008, 1009, 1010, 1015];',
    '',
    '/** Whether an unsolicited close should be retried — anything the client did not ask for, except the codes where retrying is futile. */',
    'export function isFatalCloseCode(code: number): boolean {',
    '  return FATAL_CLOSE_CODES.indexOf(code) !== -1;',
    '}',
    '',
    '/**',
    ' * Backoff delay for attempt `attempt` (0-based): `base * 2^attempt`, capped at `max`, then — with jitter on — scaled',
    ' * into [50%, 100%] of that (equal jitter: a fleet does not return in lockstep, and never sooner than half the backoff).',
    ' */',
    'export function nextReconnectDelay(attempt: number, base: number, max: number, jitter: boolean, random: () => number): number {',
    '  const safeBase = base > 0 ? base : DEFAULT_RECONNECT_DELAY;',
    '  const safeMax = max > 0 ? max : DEFAULT_MAX_RECONNECT_DELAY;',
    '  // 2^attempt overflows to Infinity well before attempt 1024; clamp the exponent so the arithmetic stays finite.',
    '  const exponent = Math.min(attempt, 30);',
    '  const raw = Math.min(safeMax, safeBase * Math.pow(2, exponent));',
    '  if (!jitter) return Math.round(raw);',
    '  return Math.round(raw * (0.5 + 0.5 * random()));',
    '}',
    '',
    '/** True for values a WebSocket can send as a binary frame unchanged. */',
    'function isBinaryPayload(value: unknown): boolean {',
    '  if (value === null || value === undefined) return false;',
    '  if (typeof ArrayBuffer !== \'undefined\') {',
    '    if (value instanceof ArrayBuffer) return true;',
    '    if (ArrayBuffer.isView(value)) return true;',
    '  }',
    '  if (typeof Blob !== \'undefined\' && value instanceof Blob) return true;',
    '  return false;',
    '}',
    '',
    '/** Text form of an outgoing value: strings pass through, objects become JSON. */',
    'function toText(value: unknown): string {',
    '  if (typeof value === \'string\') return value;',
    '  if (typeof value === \'object\') return JSON.stringify(value);',
    '  return String(value);',
    '}',
    '',
    '/** Parse a received text frame if it is JSON, otherwise hand back the string (`null`, `12`, `true` arrive as those values). */',
    'function parseIncoming(text: string): unknown {',
    '  try {',
    '    return JSON.parse(text);',
    '  } catch (e) {',
    '    return text;',
    '  }',
    '}',
    '',
    '/**',
    ' * One WebSocket connection, with its reconnection, heartbeat and send-queue policy.',
    ' *',
    ' *   idle ──connect()──▶ connecting ──open──▶ open',
    ' *                           │                 │',
    ' *                    (open fails)      (socket down, unsolicited)',
    ' *                           ▼                 ▼',
    ' *                     reconnecting ◀──────────┘   (autoReconnect, retryable, retries not exhausted)',
    ' *                     ┌─────┴─────┐',
    ' *                  open           error          (fatal code, retries spent, or autoReconnect off)',
    ' *',
    ' *   any state ──disconnect()──▶ closed',
    ' *',
    ' * `reconnecting` spans the whole outage — from the loss, across the backoff wait and every attempt, until one succeeds.',
    ' */',
    'export class WebSocketConnection {',
    '  // ── observable status; the node\'s output getters read these ────────────────',
    '  state: WebSocketConnectionState = \'idle\';',
    '  connected = false;',
    '  /** Attempts made during the current outage. Reset on open and on connect(). */',
    '  retryCount = 0;',
    '  lastError = \'\';',
    '  queueSize = 0;',
    '  /** Messages discarded rather than sent, since the node was created. */',
    '  droppedCount = 0;',
    '  /** Last measured heartbeat round-trip, in ms. `0` until measured. */',
    '  latency = 0;',
    '  closeCode = 0;',
    '  closeReason = \'\';',
    '',
    '  private _config: Required<WebSocketConnectionConfig>;',
    '  private _callbacks: WebSocketConnectionCallbacks;',
    '',
    '  private _WebSocket: WebSocketConstructorLike | null;',
    '  private _setTimeout: (handler: () => void, timeout: number) => unknown;',
    '  private _clearTimeout: (handle: unknown) => void;',
    '  private _now: () => number;',
    '  private _random: () => number;',
    '',
    '  private _socket: WebSocketLike | null = null;',
    '  private _reconnectTimer: unknown = null;',
    '  private _heartbeatTimer: unknown = null;',
    '  /** Set while a heartbeat is awaiting its reply; `0` when nothing is pending. */',
    '  private _pendingPingAt = 0;',
    '  private _queue: unknown[] = [];',
    '  private _disposed = false;',
    '  /** True between `disconnect()` and the resulting teardown. */',
    '  private _intentionalClose = false;',
    '  /** False until the first successful open; drives `isReconnect`. */',
    '  private _hasEverOpened = false;',
    '',
    '  constructor(options: WebSocketConnectionOptions = {}) {',
    '    this._config = {',
    '      url: options.url || \'\',',
    '      protocols: options.protocols || [],',
    '      autoReconnect: options.autoReconnect !== false,',
    '      reconnectDelay: options.reconnectDelay !== undefined ? options.reconnectDelay : DEFAULT_RECONNECT_DELAY,',
    '      maxReconnectDelay: options.maxReconnectDelay !== undefined ? options.maxReconnectDelay : DEFAULT_MAX_RECONNECT_DELAY,',
    '      maxRetries: options.maxRetries !== undefined ? options.maxRetries : DEFAULT_MAX_RETRIES,',
    '      jitter: options.jitter !== false,',
    '      heartbeatInterval: options.heartbeatInterval || 0,',
    '      heartbeatMessage: options.heartbeatMessage !== undefined ? options.heartbeatMessage : \'ping\',',
    '      heartbeatReply: options.heartbeatReply !== undefined ? options.heartbeatReply : \'pong\',',
    '      sendWhenDisconnected: options.sendWhenDisconnected || \'queue\',',
    '      maxQueueSize: options.maxQueueSize !== undefined ? options.maxQueueSize : DEFAULT_MAX_QUEUE_SIZE,',
    '      messageEncoding: options.messageEncoding || \'auto\'',
    '    };',
    '',
    '    this._callbacks = {',
    '      onStatus: options.onStatus,',
    '      onOpen: options.onOpen,',
    '      onMessage: options.onMessage,',
    '      onError: options.onError,',
    '      onClose: options.onClose,',
    '      onSent: options.onSent',
    '    };',
    '',
    '    this._WebSocket =',
    '      \'WebSocketImpl\' in options',
    '        ? (options.WebSocketImpl ?? null)',
    '        : typeof WebSocket !== \'undefined\'',
    '          ? (WebSocket as unknown as WebSocketConstructorLike)',
    '          : null;',
    '    this._setTimeout = options.setTimeoutImpl || ((fn, ms) => setTimeout(fn, ms));',
    '    this._clearTimeout = options.clearTimeoutImpl || ((handle) => clearTimeout(handle as never));',
    '    this._now = options.nowImpl || (() => Date.now());',
    '    this._random = options.randomImpl || (() => Math.random());',
    '  }',
    '',
    '  // ── configuration ─────────────────────────────────────────────────────────',
    '',
    '  /** Update tuning parameters on a live connection — `url` and `protocols` are the node\'s to rebuild for, not this method\'s. */',
    '  configure(config: WebSocketConnectionConfig): void {',
    '    const previousHeartbeat = this._config.heartbeatInterval;',
    '    Object.keys(config).forEach((key) => {',
    '      const value = (config as Record<string, unknown>)[key];',
    '      if (value !== undefined) (this._config as Record<string, unknown>)[key] = value;',
    '    });',
    '',
    '    // A new heartbeat interval takes effect immediately rather than after the current one elapses.',
    '    if (this._config.heartbeatInterval !== previousHeartbeat && this.state === \'open\') {',
    '      this._startHeartbeat();',
    '    }',
    '  }',
    '',
    '  getConfig(): Readonly<WebSocketConnectionConfig> {',
    '    return this._config;',
    '  }',
    '',
    '  // ── lifecycle ─────────────────────────────────────────────────────────────',
    '',
    '  /**',
    '   * Open (or reopen) the connection. An app-initiated connect is a fresh intent (the retry counter and the state reset);',
    '   * a retry stays in `reconnecting` and keeps counting. Connecting while already open replaces the socket — the old one',
    '   * is torn down without an `onClose`, because the app asked for the replacement.',
    '   */',
    '  connect(isRetry = false): void {',
    '    if (this._disposed) return;',
    '',
    '    this._clearReconnectTimer();',
    '    this._stopHeartbeat();',
    '    this._teardownSocket();',
    '    this._intentionalClose = false;',
    '',
    '    if (!isRetry) {',
    '      this.retryCount = 0;',
    '    }',
    '',
    '    if (!this._WebSocket) {',
    '      this._fail(\'WebSocket is not available in this environment\');',
    '      return;',
    '    }',
    '',
    '    const url = (this._config.url || \'\').trim();',
    '    if (!url) {',
    '      this._fail(\'URL is required to connect\');',
    '      return;',
    '    }',
    '    if (!/^wss?:\\/\\//i.test(url)) {',
    '      this._fail(\'URL must start with ws:// or wss:// — got: \' + url);',
    '      return;',
    '    }',
    '',
    '    this.state = isRetry ? \'reconnecting\' : \'connecting\';',
    '    this.connected = false;',
    '    this.closeCode = 0;',
    '    this.closeReason = \'\';',
    '    this._emitStatus();',
    '',
    '    const protocols = this._config.protocols && this._config.protocols.length ? this._config.protocols : undefined;',
    '',
    '    let socket: WebSocketLike;',
    '    try {',
    '      socket = new this._WebSocket(url, protocols);',
    '    } catch (e) {',
    '      // A constructor throw is a permanent problem with the url or the subprotocol list — retrying is futile.',
    '      this._fail(\'Could not open WebSocket: \' + this._describe(e));',
    '      return;',
    '    }',
    '',
    '    this._socket = socket;',
    '',
    '    // ArrayBuffer is far more useful to a graph than the spec\'s default Blob, which cannot be read synchronously.',
    '    try {',
    '      if (\'binaryType\' in socket) socket.binaryType = \'arraybuffer\';',
    '    } catch (e) {',
    '      // Read-only or unsupported; received binary just arrives in whatever form the implementation prefers.',
    '    }',
    '',
    '    socket.onopen = () => this._handleOpen(socket);',
    '    socket.onmessage = (event) => this._handleMessage(socket, event);',
    '    // Browsers fire error-then-close; some hosts fire only error when the connection never establishes. Both funnel',
    '    // into one once-per-socket handler so neither host duplicates nor skips the reconnect decision.',
    '    socket.onerror = () => this._handleSocketError(socket);',
    '    socket.onclose = (event) => this._handleSocketDown(socket, event);',
    '  }',
    '',
    '  /**',
    '   * Close the connection at the app\'s request. Cancels any pending reconnect; teardown is done inline rather than',
    '   * waiting for the `close` event, so `closed` is reached deterministically even if the socket never fires one.',
    '   *',
    '   * @returns whether there was anything to close — the difference between the node reporting `Done` and `Unchanged`.',
    '   */',
    '  disconnect(): boolean {',
    '    if (this._disposed) return false;',
    '',
    '    this._clearReconnectTimer();',
    '    this._stopHeartbeat();',
    '',
    '    // A live socket, or a backoff wait we are cancelling. Excludes `idle`/`closed`/`error`, so disconnecting twice',
    '    // does not emit On Close twice.',
    '    const hadSomethingToClose =',
    '      this._socket !== null || this.state === \'connecting\' || this.state === \'reconnecting\' || this.state === \'open\';',
    '    this._intentionalClose = true;',
    '    this._teardownSocket(1000, \'Client disconnect\');',
    '',
    '    this.connected = false;',
    '    this.retryCount = 0;',
    '    this.closeCode = 1000;',
    '    this.closeReason = \'Client disconnect\';',
    '',
    '    if (!hadSomethingToClose) {',
    '      // Never connected and not trying to: nothing happened, so say nothing.',
    '      this.state = \'closed\';',
    '      this._emitStatus();',
    '      return false;',
    '    }',
    '',
    '    this.state = \'closed\';',
    '    this._emitStatus();',
    '    this._invoke(() => this._callbacks.onClose && this._callbacks.onClose(1000, \'Client disconnect\', false));',
    '    return true;',
    '  }',
    '',
    '  /** Release everything (unmount, navigation, the node deleted). Fires no callbacks: the node is gone. */',
    '  dispose(): void {',
    '    if (this._disposed) return;',
    '    this._disposed = true;',
    '',
    '    this._clearReconnectTimer();',
    '    this._stopHeartbeat();',
    '    this._teardownSocket(1000, \'Node deleted\');',
    '',
    '    // Anything still queued is never going to be sent; count it so the number is right if something reads it.',
    '    this.droppedCount += this._queue.length;',
    '    this._queue = [];',
    '    this.queueSize = 0;',
    '    this.connected = false;',
    '    this.state = \'closed\';',
    '  }',
    '',
    '  get isDisposed(): boolean {',
    '    return this._disposed;',
    '  }',
    '',
    '  // ── sending ───────────────────────────────────────────────────────────────',
    '',
    '  /**',
    '   * Send `value`, or apply the send-while-disconnected policy. Everything that did not reach a socket is either in the',
    '   * queue (`queueSize`) or counted as lost (`droppedCount`) — and the *reason* is what the node turns into an outcome.',
    '   */',
    '  send(value: unknown): WebSocketSendResult {',
    '    if (this._disposed) return { kind: \'dropped\' };',
    '',
    '    if (value === undefined || value === null) {',
    '      // Almost always a wiring mistake. Say so rather than returning silently.',
    '      const message = \'Nothing to send: the Message input is empty\';',
    '      this._reportError(message);',
    '      return { kind: \'failed\', code: WS_ERROR_NOTHING_TO_SEND, message };',
    '    }',
    '',
    '    if (this.state !== \'open\' || !this._socket) {',
    '      switch (this._config.sendWhenDisconnected) {',
    '        case \'drop\':',
    '          // The requested behaviour, so not an error — but still counted.',
    '          this.droppedCount++;',
    '          this._emitStatus();',
    '          return { kind: \'dropped\' };',
    '',
    '        case \'error\': {',
    '          this.droppedCount++;',
    '          const message = \'Cannot send: the connection is not open (state: \' + this.state + \')\';',
    '          this._reportError(message);',
    '          return { kind: \'failed\', code: WS_ERROR_NOT_CONNECTED, message };',
    '        }',
    '',
    '        case \'queue\':',
    '        default: {',
    '          const limit = this._config.maxQueueSize;',
    '          if (limit > 0 && this._queue.length >= limit) {',
    '            // Refuse the newest rather than evicting the oldest: the queue stays an ordered prefix of what the app said.',
    '            this.droppedCount++;',
    '            const message = \'Send queue is full (\' + limit + \' messages); this message was dropped\';',
    '            this._reportError(message);',
    '            return { kind: \'failed\', code: WS_ERROR_QUEUE_FULL, message };',
    '          }',
    '          this._queue.push(value);',
    '          this.queueSize = this._queue.length;',
    '          this._emitStatus();',
    '          return { kind: \'queued\' };',
    '        }',
    '      }',
    '    }',
    '',
    '    return this._sendNow(value, true);',
    '  }',
    '',
    '  /** Hand a value straight to the socket. Assumes the socket is open. */',
    '  private _sendNow(value: unknown, notify: boolean): WebSocketSendResult {',
    '    let frame: unknown;',
    '    try {',
    '      frame = this._encode(value);',
    '    } catch (e) {',
    '      this.droppedCount++;',
    '      const message = \'Could not encode the message: \' + this._describe(e);',
    '      this._reportError(message);',
    '      return { kind: \'failed\', code: WS_ERROR_ENCODE_FAILED, message };',
    '    }',
    '',
    '    try {',
    '      (this._socket as WebSocketLike).send(frame);',
    '    } catch (e) {',
    '      // Usually InvalidStateError from a socket that has just closed. The close handler deals with the connection.',
    '      this.droppedCount++;',
    '      const message = \'Send failed: \' + this._describe(e);',
    '      this._reportError(message);',
    '      return { kind: \'failed\', code: WS_ERROR_SEND_FAILED, message };',
    '    }',
    '',
    '    if (notify) {',
    '      this._invoke(() => this._callbacks.onSent && this._callbacks.onSent(value));',
    '    }',
    '    return { kind: \'sent\' };',
    '  }',
    '',
    '  private _encode(value: unknown): unknown {',
    '    // Something already binary is sent as-is whatever the encoding says — re-encoding an ArrayBuffer as text would corrupt it.',
    '    if (isBinaryPayload(value)) return value;',
    '',
    '    if (this._config.messageEncoding === \'binary\') {',
    '      if (typeof TextEncoder === \'undefined\') {',
    '        throw new Error(\'binary encoding needs TextEncoder, which this environment does not provide\');',
    '      }',
    '      return new TextEncoder().encode(toText(value));',
    '    }',
    '',
    '    return toText(value);',
    '  }',
    '',
    '  /** Drain the queue into a freshly opened socket, in order; a failing send goes back to the front (still owed). */',
    '  private _flushQueue(): void {',
    '    if (this._queue.length === 0) return;',
    '',
    '    while (this._queue.length > 0 && this.state === \'open\' && this._socket) {',
    '      const value = this._queue.shift();',
    '      if (this._sendNow(value, true).kind !== \'sent\') {',
    '        this._queue.unshift(value);',
    '        break;',
    '      }',
    '    }',
    '',
    '    this.queueSize = this._queue.length;',
    '    this._emitStatus();',
    '  }',
    '',
    '  /** Queue contents, for assertions. Not used by the node. */',
    '  peekQueue(): unknown[] {',
    '    return this._queue.slice();',
    '  }',
    '',
    '  // ── socket event handling ─────────────────────────────────────────────────',
    '',
    '  private _handleOpen(socket: WebSocketLike): void {',
    '    if (this._disposed || socket !== this._socket) return;',
    '',
    '    const isReconnect = this._hasEverOpened;',
    '    this._hasEverOpened = true;',
    '',
    '    this.state = \'open\';',
    '    this.connected = true;',
    '    this.retryCount = 0;',
    '    this.lastError = \'\';',
    '    this.closeCode = 0;',
    '    this.closeReason = \'\';',
    '    this._emitStatus();',
    '',
    '    this._invoke(() => this._callbacks.onOpen && this._callbacks.onOpen(isReconnect));',
    '',
    '    this._startHeartbeat();',
    '    // After onOpen, so an app that authenticates in its open handler has sent its credentials before the backlog.',
    '    this._flushQueue();',
    '  }',
    '',
    '  private _handleMessage(socket: WebSocketLike, event: WebSocketMessageEventLike): void {',
    '    if (this._disposed || socket !== this._socket) return;',
    '',
    '    const data = event && event.data;',
    '    const isBinary = typeof data !== \'string\';',
    '',
    '    if (!isBinary) {',
    '      const text = data as string;',
    '      // Only filter when the heartbeat is actually running: with it off, a server whose protocol happens to use the',
    '      // word "pong" must still see it delivered.',
    '      const reply = this._config.heartbeatInterval > 0 ? this._config.heartbeatReply : \'\';',
    '      if (reply && text === reply) {',
    '        // A heartbeat reply is transport bookkeeping: it updates latency and is swallowed rather than emitted.',
    '        if (this._pendingPingAt) {',
    '          this.latency = Math.max(0, this._now() - this._pendingPingAt);',
    '          this._pendingPingAt = 0;',
    '          this._emitStatus();',
    '        }',
    '        return;',
    '      }',
    '',
    '      this._invoke(() => this._callbacks.onMessage && this._callbacks.onMessage(parseIncoming(text), text, false));',
    '      return;',
    '    }',
    '',
    '    this._invoke(() => this._callbacks.onMessage && this._callbacks.onMessage(data, \'\', true));',
    '  }',
    '',
    '  private _handleSocketError(socket: WebSocketLike): void {',
    '    if (socket !== this._socket) return;',
    '',
    '    // The browser event carries no detail by design, so the message says what we can actually know.',
    '    const message = this._hasEverOpened ? \'WebSocket connection error\' : \'Could not connect to \' + (this._config.url || \'(no url)\');',
    '',
    '    if (!this._disposed) {',
    '      this.lastError = message;',
    '      this._invoke(() => this._callbacks.onError && this._callbacks.onError(message));',
    '    }',
    '',
    '    this._handleSocketDown(socket, { code: CLOSE_CODE_ABNORMAL, reason: message, wasClean: false });',
    '  }',
    '',
    '  /** The one place a socket\'s death is processed, whichever event announced it. Guarded per socket. */',
    '  private _handleSocketDown(socket: WebSocketLike, event?: WebSocketCloseEventLike): void {',
    '    if (!socket) return;',
    '    const tagged = socket as WebSocketLike & { __nodegxDownHandled?: boolean };',
    '    if (tagged.__nodegxDownHandled) return;',
    '    tagged.__nodegxDownHandled = true;',
    '',
    '    this._detach(socket);',
    '    try {',
    '      socket.close();',
    '    } catch (e) {',
    '      // Already closed, or never finished connecting.',
    '    }',
    '',
    '    // A socket we have already replaced or torn down has nothing to say about the current connection.',
    '    if (socket !== this._socket) return;',
    '    this._socket = null;',
    '',
    '    this._stopHeartbeat();',
    '    if (this._disposed) return;',
    '',
    '    const code = event && typeof event.code === \'number\' ? event.code : CLOSE_CODE_ABNORMAL;',
    '    const reason = (event && event.reason) || \'\';',
    '',
    '    this.connected = false;',
    '    this.closeCode = code;',
    '    this.closeReason = reason;',
    '',
    '    if (this._intentionalClose) {',
    '      // disconnect() owns the state transition and the onClose signal.',
    '      return;',
    '    }',
    '',
    '    const willReconnect = this._shouldReconnect(code);',
    '',
    '    if (willReconnect) {',
    '      const delay = nextReconnectDelay(this.retryCount, this._config.reconnectDelay, this._config.maxReconnectDelay, this._config.jitter, this._random);',
    '      this.retryCount++;',
    '      this.state = \'reconnecting\';',
    '      this.lastError = this._describeClose(code, reason) + \'; reconnecting in \' + delay + \'ms\';',
    '      this._emitStatus();',
    '      this._invoke(() => this._callbacks.onClose && this._callbacks.onClose(code, reason, true));',
    '',
    '      this._reconnectTimer = this._setTimeout(() => {',
    '        this._reconnectTimer = null;',
    '        this.connect(true);',
    '      }, delay);',
    '      return;',
    '    }',
    '',
    '    // Not reconnecting. A server saying a clean goodbye with reconnection switched off is `closed`, everything else is',
    '    // `error` — and must be loud, because a connection that quietly stopped working is the failure this node exists to prevent.',
    '    const wasGracefulGoodbye = code === 1000 || code === 1001;',
    '    if (wasGracefulGoodbye && !this._config.autoReconnect) {',
    '      this.state = \'closed\';',
    '      this._emitStatus();',
    '      this._invoke(() => this._callbacks.onClose && this._callbacks.onClose(code, reason, false));',
    '      return;',
    '    }',
    '',
    '    this.state = \'error\';',
    '    const why = isFatalCloseCode(code)',
    '      ? this._describeClose(code, reason) + \'; this will not be retried\'',
    '      : !this._config.autoReconnect',
    '        ? this._describeClose(code, reason) + \'; Auto Reconnect is off\'',
    '        : this._describeClose(code, reason) + \'; gave up after \' + this.retryCount + \' reconnect attempts\';',
    '    this.lastError = why;',
    '    this._emitStatus();',
    '    this._invoke(() => this._callbacks.onError && this._callbacks.onError(why));',
    '    this._invoke(() => this._callbacks.onClose && this._callbacks.onClose(code, reason, false));',
    '  }',
    '',
    '  private _shouldReconnect(code: number): boolean {',
    '    if (!this._config.autoReconnect) return false;',
    '    if (isFatalCloseCode(code)) return false;',
    '    const max = this._config.maxRetries;',
    '    if (max < 0) return true;',
    '    return this.retryCount < max;',
    '  }',
    '',
    '  // ── heartbeat ─────────────────────────────────────────────────────────────',
    '',
    '  /** Start (or restart) the heartbeat — a self-rescheduling timeout, so one timer primitive serves. */',
    '  private _startHeartbeat(): void {',
    '    this._stopHeartbeat();',
    '    this._pendingPingAt = 0;',
    '',
    '    const interval = this._config.heartbeatInterval;',
    '    if (!interval || interval <= 0) return;',
    '',
    '    this._heartbeatTimer = this._setTimeout(() => this._onHeartbeat(), interval);',
    '  }',
    '',
    '  private _onHeartbeat(): void {',
    '    this._heartbeatTimer = null;',
    '    if (this._disposed || this.state !== \'open\' || !this._socket) return;',
    '',
    '    const reply = this._config.heartbeatReply;',
    '',
    '    // Dead-connection detection: the previous heartbeat is still unanswered a whole interval later, so the socket is',
    '    // open in name only. Only possible when a reply marker is configured.',
    '    if (reply && this._pendingPingAt) {',
    '      const waited = this._now() - this._pendingPingAt;',
    '      this._pendingPingAt = 0;',
    '      const message = \'Heartbeat went unanswered for \' + waited + \'ms; treating the connection as dead\';',
    '      this.lastError = message;',
    '      this._invoke(() => this._callbacks.onError && this._callbacks.onError(message));',
    '      // Runs the ordinary unsolicited-close path, so backoff and retry limits apply exactly as they do to a real drop.',
    '      this._handleSocketDown(this._socket, { code: CLOSE_CODE_ABNORMAL, reason: message, wasClean: false });',
    '      return;',
    '    }',
    '',
    '    const message = this._config.heartbeatMessage;',
    '    if (message) {',
    '      // notify: false — a heartbeat is not an application message and must not fire On Message Sent.',
    '      if (this._sendNow(message, false).kind === \'sent\' && reply) {',
    '        this._pendingPingAt = this._now();',
    '      }',
    '    }',
    '',
    '    if (this.state === \'open\' && this._socket) {',
    '      this._heartbeatTimer = this._setTimeout(() => this._onHeartbeat(), this._config.heartbeatInterval);',
    '    }',
    '  }',
    '',
    '  private _stopHeartbeat(): void {',
    '    if (this._heartbeatTimer !== null) {',
    '      this._clearTimeout(this._heartbeatTimer);',
    '      this._heartbeatTimer = null;',
    '    }',
    '    this._pendingPingAt = 0;',
    '  }',
    '',
    '  // ── plumbing ──────────────────────────────────────────────────────────────',
    '',
    '  private _clearReconnectTimer(): void {',
    '    if (this._reconnectTimer !== null) {',
    '      this._clearTimeout(this._reconnectTimer);',
    '      this._reconnectTimer = null;',
    '    }',
    '  }',
    '',
    '  /** Detach handlers so a dying socket cannot call back into a live object. */',
    '  private _detach(socket: WebSocketLike): void {',
    '    socket.onopen = null;',
    '    socket.onmessage = null;',
    '    socket.onerror = null;',
    '    socket.onclose = null;',
    '  }',
    '',
    '  private _teardownSocket(code?: number, reason?: string): void {',
    '    const socket = this._socket;',
    '    if (!socket) return;',
    '    this._socket = null;',
    '    this._detach(socket);',
    '    try {',
    '      if (code !== undefined) socket.close(code, reason);',
    '      else socket.close();',
    '    } catch (e) {',
    '      // Already closed, or never opened.',
    '    }',
    '  }',
    '',
    '  /** A connect attempt that cannot proceed: terminal, loud, and not retried. */',
    '  private _fail(message: string): void {',
    '    this.state = \'error\';',
    '    this.connected = false;',
    '    this.lastError = message;',
    '    this._emitStatus();',
    '    this._invoke(() => this._callbacks.onError && this._callbacks.onError(message));',
    '  }',
    '',
    '  private _reportError(message: string): void {',
    '    this.lastError = message;',
    '    this._emitStatus();',
    '    this._invoke(() => this._callbacks.onError && this._callbacks.onError(message));',
    '  }',
    '',
    '  private _emitStatus(): void {',
    '    this._invoke(() => this._callbacks.onStatus && this._callbacks.onStatus());',
    '  }',
    '',
    '  /** Run an owner callback without letting it break the state machine. */',
    '  private _invoke(fn: () => void): void {',
    '    try {',
    '      fn();',
    '    } catch (e) {',
    '      console.error(\'[WebSocket] Error in a graph callback:\', e);',
    '    }',
    '  }',
    '',
    '  private _describe(e: unknown): string {',
    '    if (e && typeof (e as Error).message === \'string\') return (e as Error).message;',
    '    return String(e);',
    '  }',
    '',
    '  private _describeClose(code: number, reason: string): string {',
    '    const base = code === CLOSE_CODE_ABNORMAL ? \'Connection lost (no close frame)\' : \'Connection closed (\' + code + \')\';',
    '    return reason ? base + \': \' + reason : base;',
    '  }',
    '}',
    '',
    '// ============================================================================',
    '// websocket.ts — the node',
    '// ============================================================================',
    '',
    '/** The failure this node reports when a `Connect` cannot open, or gives up trying. */',
    'export const WS_ERROR_CONNECT_FAILED = \'websocket/connect-failed\';',
    '',
    '/** Where the node sits — the provenance every raise carries. */',
    'export interface WebSocketSource {',
    '  /** The authored label, or the node\'s display name. */',
    '  label: string;',
    '  /** The node\'s graph id. */',
    '  nodeId: string;',
    '  /** The component it sits in — \'/Pages/Home\'. */',
    '  componentName: string;',
    '}',
    '',
    '/**',
    ' * The node\'s inputs, typed as the ports take them — a wire delivers whatever it delivers, and each is coerced here',
    ' * exactly as the runtime setter coerces it. A key that is absent keeps initialize()\'s value; a key present with',
    ' * `undefined` is a wire that delivered nothing, which the setters read as their empty case.',
    ' */',
    'export interface WebSocketOptions {',
    '  /** URL: a string, else `\'\'`; a change rebuilds the connection (reconnecting to the new one where the app wanted one). */',
    '  url?: unknown;',
    '  /** Auto Connect: `!!value`; initialize() says true — a URL with nothing else authored connects at mount. */',
    '  autoConnect?: unknown;',
    '  /** Protocols: `"json, chat.v1"` → `[\'json\', \'chat.v1\']`; a change rebuilds the connection. */',
    '  protocols?: unknown;',
    '  /** Auto Reconnect: `!!value`; the connection\'s default is true. */',
    '  autoReconnect?: unknown;',
    '  /** Reconnect Delay (ms): `Number(value)`. */',
    '  reconnectDelay?: unknown;',
    '  /** Max Reconnect Delay (ms): `Number(value)`. */',
    '  maxReconnectDelay?: unknown;',
    '  /** Max Retries: `Number(value)`; 0 disables retrying, negative means unlimited. */',
    '  maxRetries?: unknown;',
    '  /** Backoff Jitter: `!!value`; the connection\'s default is true. */',
    '  jitter?: unknown;',
    '  /** Heartbeat Interval (ms): `Number(value)`; 0 (the default) disables it. */',
    '  heartbeatInterval?: unknown;',
    '  /** Heartbeat Message: a string, else `\'\'`. */',
    '  heartbeatMessage?: unknown;',
    '  /** Heartbeat Reply: a string, else `\'\'`. */',
    '  heartbeatReply?: unknown;',
    '  /** Message Type: \'auto\' | \'text\' | \'binary\' — anything falsy is \'auto\'. */',
    '  messageType?: unknown;',
    '  /** When Disconnected: \'queue\' | \'drop\' | \'error\' — anything falsy is \'queue\'. */',
    '  whenDisconnected?: unknown;',
    '  /** Max Queue Size: `Number(value)`; 0 or less is unlimited. */',
    '  maxQueueSize?: unknown;',
    '}',
    '',
    '/** The six Events and the outcome trio (+ Completed), called after the outputs are written — a chain reads this frame\'s values. */',
    'export interface WebSocketListeners {',
    '  /** On Open — every time the socket opens, including after a reconnect. */',
    '  onOpen?: () => void;',
    '  /** On Message — once per message, after Received already holds it; heartbeat replies are not messages. */',
    '  onMessage?: () => void;',
    '  /** On Message Sent — a message handed to the socket, including a queued one flushed on reopen; not for heartbeats. */',
    '  onMessageSent?: () => void;',
    '  /** On Error — a failed connect, a refused send, a dead heartbeat, or a give-up. */',
    '  onError?: () => void;',
    '  /** On Close — whenever the socket goes down, whether or not a reconnect follows. */',
    '  onClose?: () => void;',
    '  /** On Reconnect — every open after the first; the cue to re-fetch rather than assume continuity. */',
    '  onReconnect?: () => void;',
    '  /** Done — a Connect whose socket opened, a Send accepted for delivery (sent or queued), or a Disconnect that closed something. */',
    '  done?: () => void;',
    '  /** Completed — after every Connect, Disconnect or Send, whatever the outcome. */',
    '  completed?: () => void;',
    '  /** Unchanged — a Disconnect with nothing open, a Send discarded by the Drop policy, or a Connect superseded before it opened. */',
    '  unchanged?: () => void;',
    '  /** Failure — no URL, a URL that is not ws:// or wss://, a connection that gave up, or a refused Send; Last Error carries the reason. */',
    '  failure?: () => void;',
    '}',
    '',
    '/** What a WebSocket node hands the page. */',
    'export interface WebSocketHandle {',
    '  /** Connect — opens the socket, replacing one already open without reporting a close. */',
    '  connect(): void;',
    '  /** Disconnect — closes the socket and cancels any pending reconnect. */',
    '  disconnect(): void;',
    '  /** Send — hands the Message to the socket, or applies the When Disconnected policy. */',
    '  send(message?: unknown): void;',
    '  /** Connection State: idle, connecting, open, reconnecting, closed or error. */',
    '  readonly connectionState: string;',
    '  /** Connected: true only while the socket is open. */',
    '  readonly connected: boolean;',
    '  /** Retry Count: attempts made during the current outage; back to zero once the socket opens. */',
    '  readonly retryCount: number;',
    '  /** Last Error. */',
    '  readonly lastError: string;',
    '  /** Queue Size: messages held because the socket was not open when Send ran. */',
    '  readonly queueSize: number;',
    '  /** Dropped: messages that will never be sent. */',
    '  readonly droppedCount: number;',
    '  /** Latency (ms): the last heartbeat\'s round trip; 0 until one has been measured. */',
    '  readonly latency: number;',
    '  /** Close Code: from the last close, or 1006 when the socket died without one. */',
    '  readonly closeCode: number;',
    '  /** Close Reason. */',
    '  readonly closeReason: string;',
    '  /** Received: the last message, parsed as JSON when it is JSON and the text when it is not; undefined before the first. */',
    '  readonly received: unknown;',
    '  /** Received Raw: the last text message exactly as it arrived; blank for a binary frame. */',
    '  readonly receivedRaw: string;',
    '  /** Received Is Binary. */',
    '  readonly receivedIsBinary: boolean;',
    '}',
    '',
    '/** Node.beginOutcome()\'s token: one report, then spent. */',
    'interface OutcomeToken {',
    '  reported: boolean;',
    '}',
    '',
    '/** The node\'s `_internal`, as initialize() fills it. */',
    'interface WebSocketInternal {',
    '  /** Built lazily so a node that never connects never allocates one. */',
    '  connection: WebSocketConnection | null;',
    '  /** Current input values, and the seed for the next connection. */',
    '  config: WebSocketConnectionConfig;',
    '  /** True when `autoConnect` should open the socket as soon as a url exists. */',
    '  autoConnect: boolean;',
    '  /** The `Connect` invocation still waiting for its handshake, if there is one. Rebuild and auto-connect mint none. */',
    '  pendingConnect: OutcomeToken | null;',
    '  received: unknown;',
    '  receivedRaw: string;',
    '  receivedIsBinary: boolean;',
    '}',
    '',
    '/** initialize(). */',
    'function createInternal(): WebSocketInternal {',
    '  return {',
    '    connection: null,',
    '    autoConnect: true,',
    '    pendingConnect: null,',
    '    received: undefined,',
    '    receivedRaw: \'\',',
    '    receivedIsBinary: false,',
    '    config: {',
    '      url: \'\',',
    '      protocols: [],',
    '      autoReconnect: true,',
    '      reconnectDelay: DEFAULT_RECONNECT_DELAY,',
    '      maxReconnectDelay: DEFAULT_MAX_RECONNECT_DELAY,',
    '      maxRetries: DEFAULT_MAX_RETRIES,',
    '      jitter: true,',
    '      heartbeatInterval: 0,',
    '      heartbeatMessage: \'ping\',',
    '      heartbeatReply: \'pong\',',
    '      sendWhenDisconnected: \'queue\',',
    '      maxQueueSize: DEFAULT_MAX_QUEUE_SIZE,',
    '      messageEncoding: \'auto\'',
    '    }',
    '  };',
    '}',
    '',
    '/** Whether a live connection is pointed somewhere other than where the inputs now say. Only `url` and `protocols` count. */',
    'export function identityChanged(built: WebSocketConnectionConfig, wanted: WebSocketConnectionConfig): boolean {',
    '  if ((built.url || \'\') !== (wanted.url || \'\')) return true;',
    '  const a = built.protocols || [];',
    '  const b = wanted.protocols || [];',
    '  return a.length !== b.length || a.some((protocol, index) => protocol !== b[index]);',
    '}',
    '',
    '/** `"json, chat.v1"` → `[\'json\', \'chat.v1\']`. */',
    'export function parseProtocols(value: unknown): string[] {',
    '  if (typeof value !== \'string\' || value.trim() === \'\') return [];',
    '  return value',
    '    .split(\',\')',
    '    .map((p) => p.trim())',
    '    .filter((p) => p.length > 0);',
    '}',
    '',
    'function has(options: object, key: string): boolean {',
    '  return Object.prototype.hasOwnProperty.call(options, key);',
    '}',
    '',
    '/** Everything the node kept on `this`, in one ref. */',
    'interface WsState {',
    '  source: WebSocketSource;',
    '  internal: WebSocketInternal;',
    '  env: WebSocketConnectionSeams;',
    '  dead: boolean;',
    '  latest: { options: WebSocketOptions; listeners: WebSocketListeners };',
    '  rerender: () => void;',
    '}',
    '',
    '/** Node.reportOutcome: on a Failure the raise, then the outcome\'s pulse, then Completed. Unchanged never raises. */',
    'function reportOutcome(s: WsState, token: OutcomeToken, outcome: \'done\' | \'unchanged\' | \'failure\', failure?: { code: string; message: string }): void {',
    '  if (token.reported) return;',
    '  token.reported = true;',
    '  if (outcome === \'failure\' && failure !== undefined) {',
    '    raiseAppError({ code: failure.code, message: failure.message, nodeId: s.source.nodeId, nodeType: \'net.noodl.WebSocket\', componentName: s.source.componentName });',
    '  }',
    '  s.latest.listeners[outcome]?.();',
    '  s.latest.listeners.completed?.();',
    '}',
    '',
    '/**',
    ' * settleConnect: end the `Connect` invocation still waiting, if there is one — the one place the pending token is read,',
    ' * called from the socket opening, the connection reaching `error`, a later `Connect`, and a `Disconnect`; a no-op when',
    ' * nothing is pending, which is what keeps the auto-connect and rebuild paths silent.',
    ' */',
    'function settleConnect(s: WsState, outcome: \'done\' | \'unchanged\' | \'failure\', code?: string, message?: string): void {',
    '  const token = s.internal.pendingConnect;',
    '  if (!token) return;',
    '  s.internal.pendingConnect = null;',
    '  reportOutcome(s, token, outcome, outcome === \'failure\' ? { code: code as string, message: message as string } : undefined);',
    '}',
    '',
    '/** getConnection: the live connection, built on first use from the current inputs (and again after a dispose). */',
    'function getConnection(s: WsState): WebSocketConnection {',
    '  const internal = s.internal;',
    '  if (internal.connection && !internal.connection.isDisposed) return internal.connection;',
    '',
    '  const connection = new WebSocketConnection({',
    '    ...internal.config,',
    '    onStatus: () => {',
    '      s.rerender();',
    '      // `error` is the connection\'s one terminal failure state — `_fail` for a connect that cannot even start, and the',
    '      // give-up branch of `_handleSocketDown`. `onError` is NOT the discriminator: it also fires for a transient drop.',
    '      if (connection.state === \'error\') {',
    '        settleConnect(s, \'failure\', WS_ERROR_CONNECT_FAILED, connection.lastError || \'The connection could not be opened\');',
    '      }',
    '    },',
    '    onOpen: (isReconnect: boolean) => {',
    '      s.latest.listeners.onOpen?.();',
    '      // RFC 6455 has no resume, so this is the app\'s cue to re-fetch rather than assume the stream was continuous.',
    '      if (isReconnect) s.latest.listeners.onReconnect?.();',
    '      // Last, after the lifecycle signal and the status values it is about. A first attempt that dropped and a retry',
    '      // that then opened is one `Done`, not a `Failure` followed by a `Done`: the token rides the whole outage.',
    '      settleConnect(s, \'done\');',
    '    },',
    '    onMessage: (value: unknown, raw: string, isBinary: boolean) => {',
    '      internal.received = value;',
    '      internal.receivedRaw = raw;',
    '      internal.receivedIsBinary = isBinary;',
    '      s.rerender();',
    '      s.latest.listeners.onMessage?.();',
    '    },',
    '    onError: () => {',
    '      s.latest.listeners.onError?.();',
    '    },',
    '    onClose: () => {',
    '      s.latest.listeners.onClose?.();',
    '    },',
    '    onSent: () => {',
    '      s.latest.listeners.onMessageSent?.();',
    '    },',
    '    ...s.env',
    '  });',
    '',
    '  internal.connection = connection;',
    '  return connection;',
    '}',
    '',
    '/** applyConfig: push tuning values onto the live connection without disturbing it. */',
    'function applyConfig(s: WsState, config: WebSocketConnectionConfig): void {',
    '  const internal = s.internal;',
    '  Object.keys(config).forEach((key) => {',
    '    const value = (config as Record<string, unknown>)[key];',
    '    if (value !== undefined) (internal.config as Record<string, unknown>)[key] = value;',
    '  });',
    '  if (internal.connection && !internal.connection.isDisposed) {',
    '    internal.connection.configure(config);',
    '  }',
    '}',
    '',
    '/**',
    ' * rebuild: the connection\'s identity (`url`, `protocols`) or `autoConnect` changed. Nothing identifying changed ⇒ nothing',
    ' * (a queued message, a connection in progress, are not thrown away). An existing connection is dropped rather than',
    ' * re-pointed (its counters describe a particular session) and reopened where the app still wants one.',
    ' */',
    'function rebuild(s: WsState): void {',
    '  const internal = s.internal;',
    '  const existing = internal.connection && !internal.connection.isDisposed ? internal.connection : null;',
    '',
    '  if (existing && !identityChanged(existing.getConfig(), internal.config)) {',
    '    return;',
    '  }',
    '',
    '  if (existing) {',
    '    // The app had asked to be connected, so it still wants to be — to the new endpoint.',
    '    const wasActive = existing.state === \'connecting\' || existing.state === \'open\' || existing.state === \'reconnecting\';',
    '',
    '    existing.dispose();',
    '    internal.connection = null;',
    '    // A `Connect` still shaking hands against the OLD endpoint will never open it: superseded, not failed; the reconnect',
    '    // below is the rebuild\'s, not the author\'s, and mints no token of its own.',
    '    settleConnect(s, \'unchanged\');',
    '    s.rerender();',
    '',
    '    if (internal.config.url && (internal.autoConnect || wasActive)) {',
    '      getConnection(s).connect();',
    '    }',
    '    return;',
    '  }',
    '',
    '  // Nothing built yet. Auto-connect with no url is not an error, just an unconfigured node — it stays idle until a url',
    '  // arrives. An explicit Connect signal with no url IS an error, and says so.',
    '  if (internal.autoConnect && internal.config.url) {',
    '    getConnection(s).connect();',
    '  }',
    '}',
    '',
    '/** The setters, keyed on presence — each coerces exactly as the runtime\'s `set` does; the tuning ones through applyConfig. */',
    'function applyOptions(s: WsState, options: WebSocketOptions): void {',
    '  const internal = s.internal;',
    '  if (has(options, \'url\')) internal.config.url = typeof options.url === \'string\' ? options.url : \'\';',
    '  if (has(options, \'autoConnect\')) internal.autoConnect = !!options.autoConnect;',
    '  if (has(options, \'protocols\')) internal.config.protocols = parseProtocols(options.protocols);',
    '  const tuning: WebSocketConnectionConfig = {};',
    '  if (has(options, \'autoReconnect\')) tuning.autoReconnect = !!options.autoReconnect;',
    '  if (has(options, \'reconnectDelay\')) tuning.reconnectDelay = Number(options.reconnectDelay);',
    '  if (has(options, \'maxReconnectDelay\')) tuning.maxReconnectDelay = Number(options.maxReconnectDelay);',
    '  if (has(options, \'maxRetries\')) tuning.maxRetries = Number(options.maxRetries);',
    '  if (has(options, \'jitter\')) tuning.jitter = !!options.jitter;',
    '  if (has(options, \'heartbeatInterval\')) tuning.heartbeatInterval = Number(options.heartbeatInterval);',
    '  if (has(options, \'heartbeatMessage\')) tuning.heartbeatMessage = typeof options.heartbeatMessage === \'string\' ? options.heartbeatMessage : \'\';',
    '  if (has(options, \'heartbeatReply\')) tuning.heartbeatReply = typeof options.heartbeatReply === \'string\' ? options.heartbeatReply : \'\';',
    '  if (has(options, \'messageType\')) tuning.messageEncoding = (options.messageType as MessageEncoding) || \'auto\';',
    '  if (has(options, \'whenDisconnected\')) tuning.sendWhenDisconnected = (options.whenDisconnected as SendWhenDisconnected) || \'queue\';',
    '  if (has(options, \'maxQueueSize\')) tuning.maxQueueSize = Number(options.maxQueueSize);',
    '  applyConfig(s, tuning);',
    '}',
    '',
    '/** _onNodeDeleted: no socket, no reconnect timer, no heartbeat timer — and a pending Connect reports nothing (nowhere to report to). */',
    'function teardown(s: WsState): void {',
    '  const internal = s.internal;',
    '  if (internal.connection) {',
    '    internal.connection.dispose();',
    '    internal.connection = null;',
    '  }',
    '  internal.pendingConnect = null;',
    '}',
    '',
    '/**',
    ' * A WebSocket node. `env` is the runtime\'s own test seam (a WebSocket constructor, timers, a clock, a random) — the',
    ' * emitted page never passes it.',
    ' */',
    'export function useWebSocket(source: WebSocketSource, options: WebSocketOptions = {}, on: WebSocketListeners = {}, env: WebSocketConnectionSeams = {}): WebSocketHandle {',
    '  const [, publish] = useReducer((n: number) => n + 1, 0);',
    '  const stateRef = useRef<WsState | null>(null);',
    '  const handleRef = useRef<WebSocketHandle | null>(null);',
    '  if (stateRef.current === null || handleRef.current === null) {',
    '    const s: WsState = {',
    '      source,',
    '      internal: createInternal(),',
    '      env,',
    '      dead: false,',
    '      latest: { options, listeners: on },',
    '      rerender: () => {',
    '        if (!s.dead) publish();',
    '      }',
    '    };',
    '    stateRef.current = s;',
    '    const internal = s.internal;',
    '    handleRef.current = {',
    '      connect() {',
    '        applyOptions(s, s.latest.options);',
    '        // The token is minted here — at the port — and nowhere else, so the auto-connect and rebuild paths stay silent.',
    '        // A `Connect` fired while an earlier one is still shaking hands supersedes it.',
    '        settleConnect(s, \'unchanged\');',
    '        internal.pendingConnect = { reported: false };',
    '        getConnection(s).connect();',
    '      },',
    '      disconnect() {',
    '        applyOptions(s, s.latest.options);',
    '        const outcome: OutcomeToken = { reported: false };',
    '        const connection = internal.connection;',
    '        // A `Connect` still in flight is being cancelled, not failed. It is a separate invocation with its own token, so both report.',
    '        settleConnect(s, \'unchanged\');',
    '        // A Disconnect with nothing open is `Unchanged`, and a Disconnect cannot fail.',
    '        const closedSomething = connection ? connection.disconnect() : false;',
    '        reportOutcome(s, outcome, closedSomething ? \'done\' : \'unchanged\');',
    '      },',
    '      send(message?: unknown) {',
    '        applyOptions(s, s.latest.options);',
    '        const outcome: OutcomeToken = { reported: false };',
    '        // `send` sets Last Error and Dropped and fires On Error before it returns, so every value the outcome is about is already written.',
    '        const result = getConnection(s).send(message);',
    '        if (result.kind === \'failed\') {',
    '          reportOutcome(s, outcome, \'failure\', { code: result.code, message: result.message });',
    '          return;',
    '        }',
    '        // A queued message is `Done` (owed to the wire), a dropped one is `Unchanged` (the author said "throw it away").',
    '        reportOutcome(s, outcome, result.kind === \'dropped\' ? \'unchanged\' : \'done\');',
    '      },',
    '      get connectionState() {',
    '        return internal.connection ? internal.connection.state : \'idle\';',
    '      },',
    '      get connected() {',
    '        return internal.connection ? internal.connection.connected : false;',
    '      },',
    '      get retryCount() {',
    '        return internal.connection ? internal.connection.retryCount : 0;',
    '      },',
    '      get lastError() {',
    '        return internal.connection ? internal.connection.lastError : \'\';',
    '      },',
    '      get queueSize() {',
    '        return internal.connection ? internal.connection.queueSize : 0;',
    '      },',
    '      get droppedCount() {',
    '        return internal.connection ? internal.connection.droppedCount : 0;',
    '      },',
    '      get latency() {',
    '        return internal.connection ? internal.connection.latency : 0;',
    '      },',
    '      get closeCode() {',
    '        return internal.connection ? internal.connection.closeCode : 0;',
    '      },',
    '      get closeReason() {',
    '        return internal.connection ? internal.connection.closeReason : \'\';',
    '      },',
    '      get received() {',
    '        return internal.received;',
    '      },',
    '      get receivedRaw() {',
    '        return internal.receivedRaw;',
    '      },',
    '      get receivedIsBinary() {',
    '        return internal.receivedIsBinary;',
    '      }',
    '    };',
    '  }',
    '  const s = stateRef.current;',
    '  s.latest = { options, listeners: on };',
    '',
    '  const scheduled = useRef<{ url: unknown; protocols: unknown; autoConnect: unknown } | null>(null);',
    '  // _onNodeDeleted: the connection disposed, the pending Connect forgotten. StrictMode runs the mount twice in',
    '  // development; the cleanup between tears the first connection down and the second mount\'s rebuild reopens it.',
    '  useEffect(() => {',
    '    s.dead = false;',
    '    scheduled.current = null;',
    '    return () => {',
    '      s.dead = true;',
    '      teardown(s);',
    '    };',
    '    // eslint-disable-next-line react-hooks/exhaustive-deps -- the state object is created once',
    '  }, []);',
    '',
    '  // The setters run on every render (a wired input delivers on change): the tuning ones are applied in place; the URL,',
    '  // Protocols and Auto Connect setters schedule the rebuild, which runs once after the inputs have updated — here, after',
    '  // the render that changed them (and once at mount, as the first delivery does).',
    '  useEffect(() => {',
    '    applyOptions(s, s.latest.options);',
    '    const prev = scheduled.current;',
    '    const next = { url: s.latest.options.url, protocols: s.latest.options.protocols, autoConnect: s.latest.options.autoConnect };',
    '    scheduled.current = next;',
    '    if (prev === null || prev.url !== next.url || prev.protocols !== next.protocols || prev.autoConnect !== next.autoConnect) rebuild(s);',
    '  });',
    '',
    '  return handleRef.current;',
    '}'
  ].join('\n');
}
