/**
 * NAT-008 AC3 — the twelve badge marks, as geometry this window already holds.
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * 🔴 **A MASK, NOT AN `<img>`, AND THE PLATFORM'S OWN COMMENT SAYS WHY.** `/u/[handle]` draws a
 * badge as `WebkitMaskImage: url(/badges/...)` on a span that carries the colour, because the
 * twelve files **contain no colour at all** — an SVG loaded through `<img>` is its own document
 * and inherits none, so the same file rendered as an image is twelve black marks in dark theme
 * and twelve invisible ones in light. Copying the markup and not the mechanism is the exact
 * failure this criterion names.
 *
 * 🔴 **AND THE FILES ARE HERE RATHER THAN FETCHED, WHICH IS THIS TASK'S OWN DECISION.** The
 * platform serves them from `public/badges/`, so the copy-the-web answer is a mask URL pointing
 * at `community.nodegx.io`. This window is `nodeIntegration: true, contextIsolation: false`; a
 * remote request for a *decoration* is a fingerprinting surface, a mixed-content surface and a
 * thing that fails with the network — and NAT-013 would then have to explain why a profile read
 * from cache draws twelve holes. The task's trap says the editor's answer about remote images is
 * decided here rather than inherited, so: **this editor makes no remote image request at all.**
 * The same ruling retires `avatarUrl` — see `peopleview.avatarInitial`.
 *
 * ⚠️ **THE DRIFT THIS BUYS, AND THE SHAPE THAT CONTAINS IT.** Twelve marks in two repositories
 * is two copies, and this one cannot see the other. What stops it becoming a *wrong* drawing is
 * that the lookup is keyed on `family` + `tier` — both of which the API sends — and a key with no
 * mark here returns `null`, which draws the platform's own **no-artwork branch**: the badge's
 * title and tier, no broken square. So a thirteenth badge added on the platform arrives here as a
 * badge with no picture, never as somebody else's picture.
 *
 * ⚠️ Generated from `nodegx-community/public/badges/*.svg` (themselves generated by that repo's
 * `scripts/draw-badges.mjs` from four family marks and one tier rule) on 2026-08-20. They are
 * data URIs rather than files because a `mask-image` needs a URL and this module has to work
 * unchanged in webpack, in Storybook and in a jest run with no bundler.
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * @module noodl-core-ui/components/community/badgeMarks
 */

/**
 * `family-tier` → a `url(...)` value ready for `mask-image`.
 *
 * ⚠️ Lower-cased keys, because the wire's spelling is the database's and this lookup should not
 * be the place a capitalisation change becomes a missing picture.
 */
const MARKS: Record<string, string> = {
  'building-bronze':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Ebuilding · bronze%3C/title%3E%3Cpath d=%22M9.42 10.58 L13.02 14.18 L14.58 12.62 L10.98 9.02 Z%22/%3E%3Crect x=%223%22 y=%222.6%22 width=%227.6%22 height=%227.6%22 rx=%222%22/%3E%3Crect x=%2213.4%22 y=%229.8%22 width=%227.6%22 height=%227.6%22 rx=%222%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3C/svg%3E")',
  'building-gold':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Ebuilding · gold%3C/title%3E%3Cpath d=%22M9.42 10.58 L13.02 14.18 L14.58 12.62 L10.98 9.02 Z%22/%3E%3Crect x=%223%22 y=%222.6%22 width=%227.6%22 height=%227.6%22 rx=%222%22/%3E%3Crect x=%2213.4%22 y=%229.8%22 width=%227.6%22 height=%227.6%22 rx=%222%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22/%3E%3C/svg%3E")',
  'building-silver':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Ebuilding · silver%3C/title%3E%3Cpath d=%22M9.42 10.58 L13.02 14.18 L14.58 12.62 L10.98 9.02 Z%22/%3E%3Crect x=%223%22 y=%222.6%22 width=%227.6%22 height=%227.6%22 rx=%222%22/%3E%3Crect x=%2213.4%22 y=%229.8%22 width=%227.6%22 height=%227.6%22 rx=%222%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3C/svg%3E")',
  'community-bronze':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Ecommunity · bronze%3C/title%3E%3Cpath d=%22M11.24 4.76 L4.84 15.76 L6.36 16.64 L12.76 5.64 Z%22/%3E%3Cpath d=%22M11.24 5.64 L17.64 16.64 L19.16 15.76 L12.76 4.76 Z%22/%3E%3Cpath d=%22M5.6 17.08 L18.4 17.08 L18.4 15.32 L5.6 15.32 Z%22/%3E%3Ccircle cx=%2212%22 cy=%225.2%22 r=%222.9%22/%3E%3Ccircle cx=%225.6%22 cy=%2216.2%22 r=%222.9%22/%3E%3Ccircle cx=%2218.4%22 cy=%2216.2%22 r=%222.9%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3C/svg%3E")',
  'community-gold':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Ecommunity · gold%3C/title%3E%3Cpath d=%22M11.24 4.76 L4.84 15.76 L6.36 16.64 L12.76 5.64 Z%22/%3E%3Cpath d=%22M11.24 5.64 L17.64 16.64 L19.16 15.76 L12.76 4.76 Z%22/%3E%3Cpath d=%22M5.6 17.08 L18.4 17.08 L18.4 15.32 L5.6 15.32 Z%22/%3E%3Ccircle cx=%2212%22 cy=%225.2%22 r=%222.9%22/%3E%3Ccircle cx=%225.6%22 cy=%2216.2%22 r=%222.9%22/%3E%3Ccircle cx=%2218.4%22 cy=%2216.2%22 r=%222.9%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22/%3E%3C/svg%3E")',
  'community-silver':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Ecommunity · silver%3C/title%3E%3Cpath d=%22M11.24 4.76 L4.84 15.76 L6.36 16.64 L12.76 5.64 Z%22/%3E%3Cpath d=%22M11.24 5.64 L17.64 16.64 L19.16 15.76 L12.76 4.76 Z%22/%3E%3Cpath d=%22M5.6 17.08 L18.4 17.08 L18.4 15.32 L5.6 15.32 Z%22/%3E%3Ccircle cx=%2212%22 cy=%225.2%22 r=%222.9%22/%3E%3Ccircle cx=%225.6%22 cy=%2216.2%22 r=%222.9%22/%3E%3Ccircle cx=%2218.4%22 cy=%2216.2%22 r=%222.9%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3C/svg%3E")',
  'contributing-bronze':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Econtributing · bronze%3C/title%3E%3Cpath d=%22M12 2.6 L17 8.6 L13.2 8.6 L13.2 13.4 L10.8 13.4 L10.8 8.6 L7 8.6 Z%22/%3E%3Cpath d=%22M3.6 11 L6 11 L6 15.1 L18 15.1 L18 11 L20.4 11 L20.4 15.5 C20.4 16.6 19.5 17.5 18.4 17.5 L5.6 17.5 C4.5 17.5 3.6 16.6 3.6 15.5 Z%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3C/svg%3E")',
  'contributing-gold':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Econtributing · gold%3C/title%3E%3Cpath d=%22M12 2.6 L17 8.6 L13.2 8.6 L13.2 13.4 L10.8 13.4 L10.8 8.6 L7 8.6 Z%22/%3E%3Cpath d=%22M3.6 11 L6 11 L6 15.1 L18 15.1 L18 11 L20.4 11 L20.4 15.5 C20.4 16.6 19.5 17.5 18.4 17.5 L5.6 17.5 C4.5 17.5 3.6 16.6 3.6 15.5 Z%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22/%3E%3C/svg%3E")',
  'contributing-silver':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Econtributing · silver%3C/title%3E%3Cpath d=%22M12 2.6 L17 8.6 L13.2 8.6 L13.2 13.4 L10.8 13.4 L10.8 8.6 L7 8.6 Z%22/%3E%3Cpath d=%22M3.6 11 L6 11 L6 15.1 L18 15.1 L18 11 L20.4 11 L20.4 15.5 C20.4 16.6 19.5 17.5 18.4 17.5 L5.6 17.5 C4.5 17.5 3.6 16.6 3.6 15.5 Z%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3C/svg%3E")',
  'learning-bronze':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Elearning · bronze%3C/title%3E%3Cpath d=%22M3 5.4 C5.4 4.3 8.4 4.3 10.8 5.6 L10.8 16.4 C8.4 15.1 5.4 15.1 3 16.2 Z%22/%3E%3Cpath d=%22M21 5.4 C18.6 4.3 15.6 4.3 13.2 5.6 L13.2 16.4 C15.6 15.1 18.6 15.1 21 16.2 Z%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3C/svg%3E")',
  'learning-gold':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Elearning · gold%3C/title%3E%3Cpath d=%22M3 5.4 C5.4 4.3 8.4 4.3 10.8 5.6 L10.8 16.4 C8.4 15.1 5.4 15.1 3 16.2 Z%22/%3E%3Cpath d=%22M21 5.4 C18.6 4.3 15.6 4.3 13.2 5.6 L13.2 16.4 C15.6 15.1 18.6 15.1 21 16.2 Z%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22/%3E%3C/svg%3E")',
  'learning-silver':
    'url("data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 width=%2224%22 height=%2224%22 fill-rule=%22evenodd%22%3E%3Ctitle%3Elearning · silver%3C/title%3E%3Cpath d=%22M3 5.4 C5.4 4.3 8.4 4.3 10.8 5.6 L10.8 16.4 C8.4 15.1 5.4 15.1 3 16.2 Z%22/%3E%3Cpath d=%22M21 5.4 C18.6 4.3 15.6 4.3 13.2 5.6 L13.2 16.4 C15.6 15.1 18.6 15.1 21 16.2 Z%22/%3E%3Ccircle cx=%228.8%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2212%22 cy=%2220.6%22 r=%221.35%22/%3E%3Ccircle cx=%2215.2%22 cy=%2220.6%22 r=%221.35%22 opacity=%22.3%22/%3E%3C/svg%3E")',
};

/**
 * The mark for a badge, or `null` when this editor has no drawing for it.
 *
 * 🔴 `null` is a real answer and callers must draw the no-artwork branch for it — see the module
 * note. Returning a placeholder mark would make an unknown badge look like a known one.
 */
export function badgeMark(family: string, tier: string): string | null {
  return MARKS[`${family}-${tier}`.toLowerCase().trim()] ?? null;
}

/** Exported for the spec that asserts the set is the platform's twelve and not eleven. */
export function badgeMarkKeys(): string[] {
  return Object.keys(MARKS).sort();
}
