/**
 * BLD-008 — what the interview on disk refuses to believe, and what it resumes.
 *
 * `.nodegx/review/interview.json` holds the one thing in this panel that cannot
 * be regenerated by running something again: paragraphs a person typed about
 * their own project. So the interesting assertions are about a file that is
 * *wrong* — hand-edited, half-written by a crash, copied in with a project
 * folder — because those are the files that actually occur, and every one of
 * them must cost this interview and never the panel.
 *
 * The resume rule is graded here too. It compares against the **specs**, which
 * are free, rather than against a fresh interview turn, which is billed: a
 * resume that pays for the questions again to discover it already had the
 * answers is not a resume.
 */

import { interviewQuestions } from '../../src/editor/src/models/AiAssistant/review/interviewQuestions';
import {
  INTERVIEW_FILE_VERSION,
  parseInterviewFile,
  serialiseInterview
} from '../../src/editor/src/models/AiAssistant/review/InterviewSidecar';
import {
  interviewFrom,
  recordAnswer,
  recordSkip,
  resumableInterview,
  type InterviewQuestion,
  type InterviewState
} from '../../src/editor/src/models/AiAssistant/review/interviewState';

function fromSpecs(): InterviewState {
  return interviewFrom(
    interviewQuestions().map(
      (spec): InterviewQuestion => ({
        id: spec.id,
        docKind: spec.docKind,
        heading: spec.heading,
        question: spec.question,
        why: 'Because.',
        guess: 'A guess.'
      })
    )
  );
}

describe('the round trip', () => {
  it('keeps the questions and the answers', () => {
    let state = fromSpecs();
    state = recordAnswer(state, 'brief:who-uses-it', 'Shoppers, not staff.');
    state = recordSkip(state, 'architecture:decisions');

    const parsed = parseInterviewFile(serialiseInterview(state, 'project-1', '2026-08-09T00:00:00.000Z'), 'project-1');
    expect(parsed?.questions.length).toBe(state.questions.length);
    expect(parsed?.answers['brief:who-uses-it']).toEqual({ status: 'answered', text: 'Shoppers, not staff.' });
    expect(parsed?.answers['architecture:decisions']).toEqual({ status: 'skipped' });
  });

  it('keeps a proposed document and the decision on it', () => {
    const state: InterviewState = {
      ...fromSpecs(),
      proposedDoc: { path: 'docs/uk-vat.md', title: 'UK VAT', purpose: 'Rates.', inject: 'always', why: 'Thrice.' },
      proposalAccepted: true
    };
    const parsed = parseInterviewFile(serialiseInterview(state, undefined, 'now'));
    expect(parsed?.proposedDoc?.path).toBe('docs/uk-vat.md');
    expect(parsed?.proposedDoc?.inject).toBe('always');
    expect(parsed?.proposalAccepted).toBe(true);
  });
});

describe('a file that is wrong costs this interview, never the panel', () => {
  it('returns nothing for text that is not JSON', () => {
    expect(parseInterviewFile('{half a file')).toBe(undefined);
  });

  it('returns nothing for a version it cannot read', () => {
    const text = serialiseInterview(fromSpecs(), 'p', 'now').replace(
      `"version": ${INTERVIEW_FILE_VERSION}`,
      '"version": 99'
    );
    expect(parseInterviewFile(text)).toBe(undefined);
  });

  it('⚠️ refuses a file that belongs to another project', () => {
    // `.nodegx/` travels with a copied folder, so this is not hypothetical: it
    // is what happens when somebody duplicates a project to try something.
    const text = serialiseInterview(fromSpecs(), 'project-1', 'now');
    expect(parseInterviewFile(text, 'project-2')).toBe(undefined);
    expect(parseInterviewFile(text, 'project-1')).not.toBe(undefined);
  });

  it('drops a question that is missing its id, and keeps the rest', () => {
    const state = fromSpecs();
    const raw = JSON.parse(serialiseInterview(state, undefined, 'now'));
    delete raw.interview.questions[0].id;
    const parsed = parseInterviewFile(JSON.stringify(raw));
    expect(parsed?.questions.length).toBe(state.questions.length - 1);
  });

  it('⚠️ degrades a corrupt answer to unanswered rather than dropping its question', () => {
    // The two ways to fail differ: asking again costs one question, while
    // dropping it silently produces a document heading nobody was asked about
    // and no TODO saying so.
    const raw = JSON.parse(serialiseInterview(recordAnswer(fromSpecs(), 'brief:who-uses-it', 'x'), undefined, 'now'));
    raw.interview.answers['brief:who-uses-it'] = { status: 'answered' }; // no text
    const parsed = parseInterviewFile(JSON.stringify(raw));
    expect(parsed?.questions.some((q) => q.id === 'brief:who-uses-it')).toBe(true);
    expect(parsed?.answers['brief:who-uses-it']).toBe(undefined);
  });

  it('refuses a proposed document whose path escapes docs/', () => {
    const raw = JSON.parse(serialiseInterview(fromSpecs(), undefined, 'now'));
    raw.interview.proposedDoc = { path: '../evil.md', title: 't', purpose: 'p', inject: 'pull', why: 'w' };
    expect(parseInterviewFile(JSON.stringify(raw))?.proposedDoc).toBe(undefined);
  });
});

describe('resuming', () => {
  it('resumes when the questions still match the templates', () => {
    const saved = recordAnswer(fromSpecs(), 'brief:who-uses-it', 'Shoppers.');
    expect(resumableInterview(saved, interviewQuestions())).toBe(saved);
  });

  it('⚠️ refuses when a template gained or lost a heading', () => {
    // Every stored answer would still land on an id that exists, so the mismatch
    // is invisible at the point of use — the interview would simply describe
    // documents that are no longer the ones about to be drafted.
    const saved = fromSpecs();
    expect(resumableInterview(saved, interviewQuestions().slice(1))).toBe(undefined);
    expect(
      resumableInterview({ ...saved, questions: saved.questions.slice().reverse() }, interviewQuestions())
    ).toBe(undefined);
  });
});
