/**
 * AIX-010 — `review_project`: the retrofit's material, for an external agent.
 *
 * The editor's review is a three-turn LLM job. This is not that. Here the
 * *caller* is the agent, so the server's job is to hand it exactly what the
 * editor's own drafting turn is handed — the assembled, budgeted project
 * context and an honest account of what was left out — and then get out of the
 * way. The agent drafts, and writes back through AIX-009's `write_project_doc`,
 * which is already the one doc write path.
 *
 * It returns context, not prose, and — the part worth being careful about — the
 * per-document guidance it returns is **generated by the editor's own prompt
 * module**, not restated here. Two copies of "never describe the graph" is two
 * copies that drift, and the whole AIX-009…012 group rests on that line holding.
 * `reviewSystemPrompt(kind)` is imported and called; if the editor's anti-goals
 * change, this tool's guidance changes with them in the same commit.
 *
 * Read-only. Registered unconditionally, like the other read tools.
 */

import * as fs from 'fs';
import * as path from 'path';

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';

import type {
  CoverageRead,
  CoverageSkipped,
  CoverageSource,
  ExplainGraph,
  GraphComponent,
  PageMap,
  ProjectReviewSources,
  RankedComponent,
  ReviewDocKind
} from '../editor-deps';
import {
  assembleProjectReview,
  graphComponentFromFiles,
  KNOWN_DOCS,
  renderCoverageForPrompt,
  renderProjectReviewContext,
  REVIEW_DOC_ORDER,
  REVIEW_DOC_PATHS,
  reviewSystemPrompt,
  summariseCoverage
} from '../editor-deps';
import type { ProjectStore } from '../project/ProjectStore';
import { guarded, jsonResult } from './util';

export interface ReviewProjectResponse {
  summary: string;
  /** The assembled reference material — what the editor's drafting turn reads. */
  context: string;
  coverage: {
    text: string;
    componentsTotal: number;
    nodesTotal: number;
    read: CoverageRead[];
    notRead: CoverageSkipped[];
    sources: CoverageSource[];
    charsUsed: number;
    charsBudget: number;
  };
  pageMap: PageMap;
  ranking: RankedComponent[];
  documents: Array<{
    kind: ReviewDocKind;
    path: string;
    exists: boolean;
    purpose?: string;
    guidance: string;
  }>;
  next: string;
}

/**
 * Every component in the project, adapted to the shape the assembler reads.
 *
 * Built from the store rather than from a live editor, which is the same seam
 * `explain/graph` opens for the serialised-project adapter — the assembler
 * cannot tell the difference, and that is what lets one implementation serve
 * both the editor and this tool.
 */
function buildGraph(store: ProjectStore): ExplainGraph {
  const components: GraphComponent[] = [];
  for (const row of store.listComponents()) {
    try {
      const stored = store.readComponent(row.path);
      components.push(graphComponentFromFiles(stored.legacyName, stored.files));
    } catch {
      // A component the registry lists but whose files will not read is a
      // corrupt project, not a reason to refuse the whole review. It shows up
      // as a component the review did not see.
      continue;
    }
  }
  return { components };
}

export function registerReviewTools(server: McpServer, store: ProjectStore): void {
  server.registerTool(
    'review_project',
    {
      title: 'Review project for docs retrofit',
      description:
        'Assemble everything needed to draft this project\'s docs/ set (BRIEF, ARCHITECTURE, CONVENTIONS) for a ' +
        'project that has none: the component interfaces, the page map, the data model, the node vocabulary, and ' +
        'the full graphs of the highest-signal components under a budget. Returns CONTEXT, not prose — you write ' +
        'the documents and save them with write_project_doc. Read the coverage: it tells you which components ' +
        'were not read, and anything you would say about those must be a "> TODO:" line for the human, not a ' +
        'confident claim.',
      inputSchema: {
        maxComponentReads: z
          .number()
          .int()
          .min(1)
          .max(40)
          .optional()
          .describe('How many components to read in full. Default 8.'),
        maxChars: z
          .number()
          .int()
          .min(10_000)
          .max(600_000)
          .optional()
          .describe('Total context character budget. Default 160000.')
      }
    },
    guarded((args: { maxComponentReads?: number; maxChars?: number }) => {
      const project = store.readProjectFile();
      const routes = store.readRoutes();

      const sources: ProjectReviewSources = {
        projectName: project?.name,
        declaredRoutes: routes?.routes,
        rootComponent: project?.settings?.rootComponent,
        // The three docs as they stand, so a re-run proposes an edit rather
        // than a replacement — the "our docs have drifted" path.
        docs: {
          ...readDoc(store, 'conventions'),
          ...readDoc(store, 'brief'),
          ...readDoc(store, 'architecture')
        }
        // No backend summary: reading a live schema needs a running backend and
        // credentials this server does not hold. It is reported as absent, which
        // the prompt turns into "do not assert anything about the data model",
        // rather than silently as "there is no data model".
      };

      const budget = {
        ...(args.maxComponentReads !== undefined ? { maxComponentReads: args.maxComponentReads } : {}),
        ...(args.maxChars !== undefined ? { maxChars: args.maxChars } : {})
      };

      const context = assembleProjectReview(buildGraph(store), sources, { budget });

      const payload: ReviewProjectResponse = {
        summary: summariseCoverage(context.coverage),
        context: renderProjectReviewContext(context),
        coverage: {
          text: renderCoverageForPrompt(context.coverage),
          componentsTotal: context.coverage.componentsTotal,
          nodesTotal: context.coverage.nodesTotal,
          read: context.coverage.read,
          notRead: context.coverage.notRead,
          sources: context.coverage.sources,
          charsUsed: context.coverage.charsUsed,
          charsBudget: context.coverage.charsBudget
        },
        pageMap: context.pageMap,
        ranking: context.ranking,
        documents: REVIEW_DOC_ORDER.map((kind) => ({
          kind,
          path: REVIEW_DOC_PATHS[kind],
          exists: sources.docs?.[kind] !== undefined,
          purpose: KNOWN_DOCS.find((d) => d.kind === kind)?.purpose,
          // The editor's own instructions for this document, verbatim.
          guidance: reviewSystemPrompt(kind)
        })),
        next:
          'Draft each document from the context above and save it with write_project_doc. Mark every inference ' +
          'with a "> TODO:" line. Never describe the graph: no node inventories, no connection lists, no port ' +
          'names — the editor narrates any component live on demand, and a prose copy rots on the next edit.'
      };

      return jsonResult(payload);
    })
  );
}

/**
 * One existing doc body, or nothing. A missing file is an absent field, never an
 * empty string — the assembler distinguishes "no BRIEF.md" from "an empty one".
 *
 * The paths are the module's own constants, so there is no caller-supplied
 * component to contain; `write_project_doc` remains the only path that takes one
 * and it does its own `assertInsideDocs`.
 */
function readDoc(store: ProjectStore, kind: ReviewDocKind): Record<string, string> {
  const abs = path.join(store.projectDir, REVIEW_DOC_PATHS[kind]);
  try {
    return fs.existsSync(abs) ? { [kind]: fs.readFileSync(abs, 'utf8') } : {};
  } catch {
    return {};
  }
}
